namespace eval ::sth::hlapiGen:: {

}

set ::sth::hlapiGen::hlapiGenTable {
    ::sth::hlapiGen::
    {hlapi_gen
        {class                              tableName                                       cfgFunc                                cfgConvertFunc               ctrlFunc                             ctrlConvertFunc           resultFunc                               resultConvertFunc      priority     multiDevCheckFunc}
        {igmprouterconfig                   ::sth::igmp::igmpQuerierTable                   emulation_igmp_querier_config           basic                       emulation_igmp_querier_control          port_list               emulation_igmp_querier_info             port_list               130         basic}
        {igmphostconfig                     ::sth::igmp::igmpTable                          emulation_igmp_config                   igmpconfig                  emulation_igmp_control                  port_list               emulation_igmp_info                     port                    240         igmp}
        {ipv4group                          ::sth::multicast_group::multicast_groupTable    emulation_multicast_group_config        basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {ipv6group                          ::sth::multicast_group::multicast_groupTable    emulation_multicast_group_config        basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {ipv4networkblock                   ::sth::multicast_group::multicast_groupTable    emulation_multicast_source_config       basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {igmpgroupmembership                ::sth::igmp::igmpTable                          emulation_igmp_group_config             basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {bgprouterconfig                    ::sth::Bgp::bgpTable                            emulation_bgp_config                    bgpconfig                   emulation_bgp_control                   handle_list             emulation_bgp_info                      handle                  130         bgp }
        {bgpipv4routeconfig                 ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                route                   130         _none_}
        {bgpipv6routeconfig                 ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                route                   130         _none_}
        {bgpflowspecconfig                  ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {bgpsrtepolicyconfig                ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysglistattribute       ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype1          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype2          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype3          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype4          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype5          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype6          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype7          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {bgpsrtepolicysegmenttype8          ::sth::Bgp::bgpTable                            emulation_bgp_route_config              basic                       _none_                                  _none_                  emulation_bgp_route_info                _none_                  130         _none_}
        {dhcpv4blockconfig                  ::sth::Dhcp::dhcpTable                          emulation_dhcp_group_config             dhcpv4                      emulation_dhcp_control                  dhcp                    emulation_dhcp_stats                    dhcp                    225         _none_}
        {dhcpv4portconfig                   ::sth::Dhcp::dhcpTable                          emulation_dhcp_config                   unused                       _none_                                 _none_                  _none_                                  _none_                  225         _none_}
        {dhcpv6portconfig                   ::sth::Dhcpv6::dhcpv6Table                      emulation_dhcpv6_config                 unused                       _none_                                 _none_                  _none_                                  _none_                  225         _none_}
        {dhcpv6blockconfig                  ::sth::Dhcpv6::dhcpv6Table                      emulation_dhcpv6_group_config           dhcpv6                      emulation_dhcp_control                  dhcp                    emulation_dhcp_stats                    dhcp                    225         _none_}
        {dhcpv6pdblockconfig                ::sth::Dhcpv6::dhcpv6Table                      emulation_dhcpv6pd_group_config         dhcpv6pd                    emulation_dhcp_control                  dhcp                    emulation_dhcp_stats                    dhcp                    225         _none_}
        {dhcpv4serverconfig                 ::sth::DhcpServer::dhcpServerTable              emulation_dhcp_server_config            dhcpserverv4                emulation_dhcp_server_control           dhcpserver              emulation_dhcp_server_stats             dhcpserver              220         _none_}
        {dhcpv4serverpoolconfig             ::sth::DhcpServer::dhcpServerTable              emulation_dhcp_server_relay_agent_config    unused                   _none_                                 _none_                  _none_                                  _none_                  220         _none_}
        {dhcpv6serverconfig                 ::sth::Dhcpv6Server::dhcpv6ServerTable          emulation_dhcpv6_server_config          dhcpserverv6                emulation_dhcp_server_control           dhcpserver              emulation_dhcp_server_stats             dhcpserver              220         _none_}
        {greif                              ::sth::Gre::greTable                            emulation_gre_config                    greconfig                   _none_                                 _none_                   _none_                                  _none_                  330         _none_}
        {pppoeclientblockconfig             ::sth::Pppox::pppoxTable                        pppox_config                            pppoxclientconfig           pppox_control                           handle_list             pppox_stats                             handle                  105         pppoeclient}
        {pppoeserverblockconfig             ::sth::PppoxServer::pppoxServerTable            pppox_server_config                     pppoxserverconfig           pppox_server_control                    handle_list             pppox_server_stats                      handle                  100         _none_}
        {pppprotocolconfig                  ::sth::ppp::pppTable                            ppp_config                              pppconfig                   ppp_config                              ppp                     ppp_stats                               port                    100         _none_}
        {ospfv2routerconfig                 ::sth::ospf::ospfTable                          emulation_ospfv2_config                 ospf                        emulation_ospf_control                  ospf                    emulation_ospfv2_info                   ospf                    130         ospf }
        {ospfv3routerconfig                 ::sth::ospf::ospfTable                          emulation_ospfv3_config                 ospf                        emulation_ospf_control                  ospf                    emulation_ospfv3_info                   ospf                    130         ospf }
        {bfdrouterconfig                    ::sth::bfd::bfdTable                            emulation_bfd_config                    bfdconfig                   emulation_bfd_control                   handle_list             emulation_bfd_info                      handle                  145         basic}
        {isisrouterconfig                   ::sth::IsIs::isisTable                          emulation_isis_config                   isisconfig                  emulation_isis_control                  handle                  emulation_isis_info                     handle                  130         isis }
        {isislspconfig                      ::sth::IsIs::isisTable                          emulation_isis_topology_route_config    basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {mldhostconfig                      ::Mld::mldTable                                 emulation_mld_config                    mld                         emulation_mld_control                   handle                  emulation_mld_info                      handle                  130         basic}
        {ldprouterconfig                    ::sth::Ldp::LdpTable                            emulation_ldp_config                    ldpconfig                   emulation_ldp_control                   handle_list             emulation_ldp_info                      handle                  140         ldp }
        {ipv4prefixlsp                      ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {Ipv4IngressPrefixLsp               ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {Ipv6PrefixLsp                      ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {Ipv6IngressPrefixLsp               ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {VcLsp                              ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {GeneralizedPwidLsp                 ::sth::Ldp::LdpTable                            emulation_ldp_route_config              basic                       _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {PseudoWireSwitchingPointTlv        ::sth::Ldp::LdpTable                            emulation_lsp_switching_point_tlvs_config   basic                   _none_                                  _none_                  _none_                                  _none_                  140         _none_}
        {rsvprouterconfig                   ::sth::Rsvp::rsvpTable                          emulation_rsvp_config                   rsvpconfig                  emulation_rsvp_control                  handle_list             emulation_rsvp_info                     handle                  130         rsvp }
        {rsvptunnelparams                   ::sth::Rsvp::rsvpTable                          emulation_rsvp_tunnel_config            basic                       emulation_rsvpte_tunnel_control         rsvp_tunnel             emulation_rsvp_tunnel_info              handle                  135         _none_}
        {rsvpcustomobject                   ::sth::Rsvp::rsvpTable                          emulation_rsvp_custom_object_config     basic                       _none_                                  _none_                  _none_                                  _none_                  120         _none_}

        {vrfproviderlink                    ::sth::Mplsvpn::MplsvpnTable                    emulation_mpls_l2_3vpn_pe_config        mpls_vpn_pe                 _none_                                  _none_                  _none_                                  _none_                  350         _none_  }
        {vpnsiteinfovplsldp                 ::sth::Mplsvpn::MplsvpnTable                    emulation_mpls_l2vpn_site_config        mpls_vpn_site               _none_                                  _none_                  _none_                                  _none_                  360         vpn_site}
        {vpnsiteinfovplsldp_other           ::sth::Vpls::VplsTable                          emulation_vpls_site_config              vpls_site                   _none_                                  _none_                  _none_                                  _none_                  360         vpn_site}
        {vpnsiteinfovplsbgp                 ::sth::Mplsvpn::MplsvpnTable                    emulation_mpls_l2vpn_site_config        mpls_vpn_site               _none_                                  _none_                  _none_                                  _none_                  360         vpn_site}
        {vpnsiteinforfc2547                 ::sth::Mplsvpn::MplsvpnTable                    emulation_mpls_l3vpn_site_config        mpls_vpn_site               _none_                                  _none_                  _none_                                  _none_                  360         vpn_site}
        {ldprouterconfig_pe                 ::sth::Vpls::VplsTable                          emulation_l2vpn_pe_config               vpls_pe                     emulation_ldp_control                   handle_list             emulation_ldp_info                      handle                  350         _none_}

        {eoamnodeconfig                     ::sth::Eoam::EoamTable                          emulation_oam_config_msg                eoam                        emulation_oam_control                   handle                  emulation_oam_info                      eoam                    120         eoam}
        {ancpaccessnodeconfig               ::sth::Ancp::ancpTable                          emulation_ancp_config                   ancpconfig                  emulation_ancp_control                  ancp                    emulation_ancp_stats                    handle                  310         ancp}
        {lacpportconfig                     ::sth::Lacp::lacpTable                          emulation_lacp_config                   lacp                        emulation_lacp_control                  lacp                    emulation_lacp_info                     port                    120         _none_}
        {lag                                ::sth::Lacp::lacpTable                          emulation_lag_config                    lag                         emulation_lacp_control                  lacp                    emulation_lacp_info                     port                    120         _none_}
        {linkoamrouterconfig                ::sth::LinkOam::LinkOamTable                    emulation_efm_config                    efm                         emulation_efm_control                   lacp                    emulation_efm_stat                      port                    120         _none_}
        {ieee1588v2clockconfig              ::sth::Ptp::PtpTable                            emulation_ptp_config                    ptp                         emulation_ptp_control                   ptp                     emulation_ptp_stats                     handle                  130         ptp}
        {pimrouterconfig                    ::sth::pimTable                                 emulation_pim_config                    pimconfig                   emulation_pim_control                   port                    emulation_pim_info                      handle                  130         basic}
        {pimv4groupblk                      ::sth::pimTable                                 emulation_pim_group_config              pim_group                   _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {pimv6groupblk                      ::sth::pimTable                                 emulation_pim_group_config              pim_group                   _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {pimv4joinsrc                       ::sth::multicast_group::multicast_groupTable    emulation_multicast_source_config       basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {pimv6joinsrc                       ::sth::multicast_group::multicast_groupTable    emulation_multicast_source_config       basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {pimv4prunesrc                      ::sth::multicast_group::multicast_groupTable    emulation_multicast_source_config       basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {pimv6prunesrc                      ::sth::multicast_group::multicast_groupTable    emulation_multicast_source_config       basic                       _none_                                  _none_                  _none_                                  _none_                  130         _none_}
        {lldpnodeconfig                     ::sth::Lldp::lldpTable                          emulation_lldp_config                   lldpconfig                  emulation_lldp_control                   handle_list            emulation_lldp_info                     handle                  120         basic}
        {fcoehostconfig                     ::sth::fcoe::fcoeTable                          fcoe_config                             fcoe                        fcoe_control                            handle_list             fcoe_stats                              handle                  120         basic}
        {riprouterconfig                    ::sth::rip::ripTable                            emulation_rip_config                    ripconfig                   emulation_rip_control                   port                    emulation_rip_info                      handle                  130         rip}
        {ripv4routeparams                   ::sth::rip::ripTable                            emulation_rip_route_config              basic                        _none_                                 _none_                  _none_                                  _none_                  130         basic}
        {ripngrouteparams                   ::sth::rip::ripTable                            emulation_rip_route_config              basic                        _none_                                 _none_                  _none_                                  _none_                  130         basic}
        {l2tpv3blockconfig                  ::sth::l2tpv3::l2tpv3Table                      l2tpv3_config                           l2tpv3                      l2tpv3_control                          handle                  l2tpv3_stats                            handle                  120         _none_}

        {pppol2tpv2clientblockconfig        ::sth::l2tp::l2tpTable                          l2tp_config                             l2tp                        l2tp_control                            handle                  l2tp_stats                              handle                  120         _none_}
        {pppol2tpv2serverblockconfig        ::sth::l2tp::l2tpTable                          l2tp_config                             l2tp                        l2tp_control                            handle                  l2tp_stats                              handle                  120         _none_}
        {dot1xsupplicantblockconfig         ::sth::Dot1x::Dot1xTable                        emulation_dot1x_config                  dot1x                       emulation_dot1x_control                 dot1x                   emulation_dot1x_stats                   handle                  120         _none_}

        {sipuaprotocolconfig                ::sth::sip::sipTable                            emulation_sip_config                    sip                         emulation_sip_control                   handle                  emulation_sip_stats                     handle                  120         _none_ }
        {bridgeportconfig                   ::sth::Stp::stpTable                            emulation_stp_config                    stp                         emulation_stp_control                   handle                  emulation_stp_stats                     handle                  120         basic}
        {saadeviceconfig                    ::sth::Ipv6AutoConfig::ipv6AutoConfigTable      emulation_ipv6_autoconfig               ipv6autoconfig              emulation_ipv6_autoconfig_control       port                    emulation_ipv6_autoconfig_stats         port                    120         _none_}
        {rfc3918config                      ::sth::Rfctest::rfctestTable                    test_rfc3918_config                     rfc3918                     test_rfc3918_control                    rfc                     test_rfc3918_info                       rfc                     200         _none_}
        {rfc2544backtobackframesconfig      ::sth::Rfctest::rfctestTable                    test_rfc2544_config                     rfc                         test_rfc2544_control                    rfc                     test_rfc2544_info                       rfc                     200         _none_}
        {rfc2544framelossconfig             ::sth::Rfctest::rfctestTable                    test_rfc2544_config                     rfc                         _none_                                  rfc                     _none_                                  rfc                     200         _none_}
        {rfc2544latencyconfig               ::sth::Rfctest::rfctestTable                    test_rfc2544_config                     rfc                         _none_                                  rfc                     _none_                                  rfc                     200         _none_}
        {rfc2544throughputconfig            ::sth::Rfctest::rfctestTable                    test_rfc2544_config                     rfc                         _none_                                  rfc                     _none_                                  rfc                     200         _none_}
        {rfc2544latencyprofile              ::sth::Rfctest::rfctestTable                    rfc2544_asymmetric_profile              basic                       _none_                                 _none_                  _none_                                 _none_                   200         _none_}
        {rfc2544throughputprofile           ::sth::Rfctest::rfctestTable                    rfc2544_asymmetric_profile              basic                       _none_                                 _none_                  _none_                                 _none_                   200         _none_}
        {rfc2544framelossprofile            ::sth::Rfctest::rfctestTable                    rfc2544_asymmetric_profile              basic                       _none_                                 _none_                  _none_                                 _none_                   200         _none_}
        {httpclientprotocolconfig           ::sth::http::httpTable                          emulation_http_config                   httpconfigclient            emulation_http_control                  httpmodehandleclient    emulation_http_stats                    httpmodehandleclient    420         _none_}
        {httpserverprotocolconfig           ::sth::http::httpTable                          emulation_http_config                   httpconfigserver            emulation_http_control                  httpmodehandleserver    emulation_http_stats                    httpmodehandleserver    400         _none_}
        {httpserverprotocolprofile          ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {httpclientprotocolprofile          ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {clientloadprofile                  ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {clientloadphase                    ::sth::http::httpTable                          emulation_http_phase_config             basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {httpserverresponseconfig           ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                   _none_                 370         _none_}
        {serverprofile                      ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {clientprofile                      ::sth::http::httpTable                          emulation_http_profile_config           basic                           _none_                             _none_                   _none_                                  _none_                  370         _none_}
        {emulateddevice                     ::sth::device::deviceTable                      emulation_device_config                 deviceconfig                    _none_                             _none_                   _none_                                  _none_                  390         _none_}
        {host                               ::sth::device::deviceTable                      emulation_device_config                 deviceconfig                    _none_                             _none_                   _none_                                  _none_                  390         _none_}
        {pcepprotocolconfig                 ::sth::pcep::pcepTable                          emulation_pcep_config                   stak                        emulation_pcep_control                  port_list               _none_                                  _none_                  430         _none_}
        {twampclientconfig                  ::sth::twamp::twampTable                        emulation_twamp_config                  twampclientconfig           emulation_twamp_control                 handle                  emulation_twamp_stats                   port_list               420         _none_}
        {twampserverconfig                  ::sth::twamp::twampTable                        emulation_twamp_config                  twampserverconfig           emulation_twamp_control                 handle                  emulation_twamp_stats                   port_list               420         _none_}
        {twamptestsession                   ::sth::twamp::twampTable                        emulation_twamp_session_config          basic                           _none_                             _none_                   _none_                                  _none_                  420         _none_}
        {iptvstbblockconfig                 ::sth::iptv::iptvTable                          emulation_iptv_config                   iptvconfig                  emulation_iptv_control                 iptv                     emulation_iptv_stats                    port_list               410         _none_}
        {iptvchannelblock                   ::sth::iptv::iptvTable                          emulation_iptv_channel_block_config     basic                           _none_                             _none_                   _none_                                  _none_                  405         _none_}
        {iptvviewingprofileconfig           ::sth::iptv::iptvTable                          emulation_iptv_viewing_behavior_profile_config basic                    _none_                             _none_                   _none_                                  _none_                  406         _none_}
        {iptvviewedchannels                 ::sth::iptv::iptvTable                          emulation_iptv_channel_viewing_profile_config basic                     _none_                             _none_                   _none_                                  _none_                  406         _none_}
        {vqdevicechannelblock               ::sth::Vqa::vqaTable                            emulation_vqa_host_config               vqahost                     emulation_vqa_control                   handle                     emulation_vqa_stats                     port_list               250         _none_}
        {vqprobechannelblock                ::sth::Vqa::vqaTable                            emulation_vqa_config                    vqaprobe                    emulation_vqa_control                   port_list                     emulation_vqa_stats                     port_list               250         _none_}
        {vqanalyzer                         ::sth::Vqa::vqaTable                            emulation_vqa_port_config               vqaport                         _none_                              _none_                     _none_                                 _none_               250         _none_}
        {vqanalyzeroptions                  ::sth::Vqa::vqaTable                            emulation_vqa_global_config             vqaglobal                       _none_                              _none_                     _none_                                 _none_               250         _none_}
        {videoserverprotocolconfig          ::sth::video::videoTable                        emulation_video_config                  video                       emulation_video_control                 port_list                   emulation_video_stats               port_list               240         _none_}
        {videoclientprotocolconfig          ::sth::video::videoTable                        emulation_video_config                  video                       emulation_video_control                 port_list                   emulation_video_stats               port_list               241         _none_}
        {videoserverstream                  ::sth::video::videoTable                        emulation_video_server_streams_config   basic                           _none_                              _none_                     _none_                                 _none_               241         _none_}
        {realismoptions                     ::sth::Session::sessionTable                    system_settings                         realism                           _none_                              _none_                     _none_                                 _none_               500         _none_}
        {capturefilter                      ::sth::packetCapture::PacketCaptureTable        packet_config_pattern                   capturefilter                   _none_                              _none_                     _none_                                 _none_               500         _none_}
    }
}


# the iptv will be enabled on the igmp or mld, so the priority should be lower than the igmp or mld

#in collum multiDevCheckFunc, will define one function to check if multiple device can be configured in one hltapi function with the count and
#step info set in it.
#the input of this function is :class name and the objects of this class.
#the output of this function is: 1) the objects which will trigger on hltapi function, 2) the return vlaue of the object which will not used to
#trigger hltapi function. 3) the multiple related args will also be returned
#
