# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_id', models.IntegerField()),
                ('suite_path', models.CharField(max_length=100)),
                ('submitted_time', models.DateField()),
                ('scheduled_time', models.DateField()),
                ('completed_time', models.DateField()),
            ],
        ),
    ]
