# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceBlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name=b'Build no.')),
                ('input1_block_size', models.CharField(choices=[(0, b'4K'), (1, b'8K'), (2, b'16K')], max_length=10, verbose_name=b'Block size')),
                ('input2_mode', models.CharField(choices=[(0, b'Read'), (1, b'Read-Write')], max_length=20, verbose_name=b'R/W Mode')),
                ('output1_iops', models.IntegerField(verbose_name=b'IOPS')),
                ('output2_bw', models.IntegerField(verbose_name=b'Band-width')),
                ('output3_latency', models.IntegerField(verbose_name=b'Latency')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIkv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name=b'Build no.')),
                ('input1_put_value_size', models.IntegerField(choices=[(0, b'4K'), (1, b'8K')], verbose_name=b'PUT Value size')),
                ('output1_put_per_seccond', models.IntegerField(verbose_name=b'PUTs per second')),
            ],
        ),
    ]
