# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0002_auto_20170911_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSuiteExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_suite_execution_id', models.IntegerField(default=10, unique=True)),
            ],
        ),
    ]
