# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0003_lastsuiteexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiteexecution',
            name='completed_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suiteexecution',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suiteexecution',
            name='submitted_time',
            field=models.DateTimeField(),
        ),
    ]
