# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0007_testcaseexecution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suiteexecution',
            old_name='suite_id',
            new_name='execution_id',
        ),
    ]
