# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0011_auto_20171020_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseexecution',
            name='script_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
