# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0016_suiteexecution_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jqls', models.TextField(default=b'[]')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='catalogsuite',
            name='test_cases',
            field=models.ManyToManyField(to='fun_test.CatalogTestCase'),
        ),
    ]
