# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0023_metricchart_children_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTestPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name=b'Datetime')),
                ('input_app', models.CharField(default=b'unit_tests', max_length=20)),
                ('num_passed', models.IntegerField(verbose_name=b'Passed')),
                ('num_failed', models.IntegerField(verbose_name=b'Failed')),
                ('num_disabled', models.IntegerField(verbose_name=b'Disabled')),
                ('hardware_version', models.CharField(default=b'', max_length=50, verbose_name=b'Hardware version')),
                ('software_date', models.CharField(default=b'', max_length=50, verbose_name=b'Software date')),
                ('git_commit', models.CharField(default=b'', max_length=100, verbose_name=b'Git commit')),
                ('branch_funsdk', models.CharField(default=b'', max_length=100, verbose_name=b'Branch FunSDK')),
            ],
        ),
    ]
