# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-13 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0029_auto_20180511_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Datetime')),
                ('input_ndata_min', models.IntegerField(default=8, verbose_name=b'ndata min')),
                ('input_ndata_max', models.IntegerField(default=8, verbose_name=b'ndata min')),
                ('input_nparity_min', models.IntegerField(default=4, verbose_name=b'nparity min')),
                ('input_stridelen_min', models.IntegerField(default=4096, verbose_name=b'strideline min')),
                ('input_stridelen_max', models.IntegerField(default=4096, verbose_name=b'strideline max')),
                ('output_encode_latency_min', models.IntegerField(verbose_name=b'Encode Latency min')),
                ('output_encode_latency_max', models.IntegerField(verbose_name=b'Encode Latency max')),
                ('output_encode_latency_avg', models.IntegerField(verbose_name=b'Encode Latency avg')),
                ('output_encode_throughput_min', models.IntegerField(verbose_name=b'Encode Throughput min')),
                ('output_encode_throughput_max', models.IntegerField(verbose_name=b'Encode Throughput max')),
                ('output_encode_throughput_avg', models.IntegerField(verbose_name=b'Encode Throughput avg')),
                ('output_recovery_latency_min', models.IntegerField(verbose_name=b'Recovery Latency min')),
                ('output_recovery_latency_max', models.IntegerField(verbose_name=b'Recovery Latency max')),
                ('output_recovery_latency_avg', models.IntegerField(verbose_name=b'Recovery Latency avg')),
                ('output_recovery_throughput_min', models.IntegerField(verbose_name=b'Recovery Throughput min')),
                ('output_recovery_throughput_max', models.IntegerField(verbose_name=b'Recovery Throughput max')),
                ('output_recovery_throughput_avg', models.IntegerField(verbose_name=b'Recovery Throughput avg')),
            ],
        ),
    ]
