# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0031_auto_20180514_1056'),
        ('fun_test', '0031_auto_20180514_1059'),
    ]

    operations = [
    ]
