# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0033_auto_20171223_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsuiteexecution',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
