# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0037_bcopyflooddmaperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcopyflooddmaperformance',
            name='input_n',
            field=models.IntegerField(choices=[(0, b'1'), (1, b'2'), (2, b'4'), (3, b'8'), (4, b'16'), (5, b'32'), (6, b'64')], default=0, verbose_name=b'N'),
        ),
    ]
