# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0044_modules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
