# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0046_auto_20180626_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_FILTER_TYPE_DEFLATE_Bandwidth',
            new_name='output_FILTER_TYPE_DEFLATE_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_FILTER_TYPE_INFLATE_Bandwidth',
            new_name='output_FILTER_TYPE_INFLATE_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth',
            new_name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth',
            new_name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_VOL_TYPE_BLK_EC_read_Bandwidth',
            new_name='output_VOL_TYPE_BLK_EC_read_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_VOL_TYPE_BLK_EC_write_Bandwidth',
            new_name='output_VOL_TYPE_BLK_EC_write_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_VOL_TYPE_BLK_LSV_read_Bandwidth',
            new_name='output_VOL_TYPE_BLK_LSV_read_Bandwidth_total',
        ),
        migrations.RenameField(
            model_name='voltestperformance',
            old_name='output_VOL_TYPE_BLK_LSV_write_Bandwidth',
            new_name='output_VOL_TYPE_BLK_LSV_write_Bandwidth_total',
        ),
    ]
