# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0047_auto_20180626_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_FILTER_TYPE_DEFLATE_Bandwidth avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_FILTER_TYPE_INFLATE_Bandwidth avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_VOL_TYPE_BLK_EC_read_Bandwidth avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_VOL_TYPE_BLK_EC_write_Bandwidth_avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_Bandwidth_avg'),
        ),
        migrations.AddField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_Bandwidth_avg',
            field=models.IntegerField(default=0, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_Bandwidth_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_FILTER_TYPE_DEFLATE_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_FILTER_TYPE_INFLATE_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_VOL_TYPE_BLK_EC_read_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_VOL_TYPE_BLK_EC_write_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_VOL_TYPE_BLK_LSV_read_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_Bandwidth_total',
            field=models.IntegerField(verbose_name=b'output_VOL_TYPE_BLK_LSV_write_Bandwidth_total'),
        ),
    ]
