# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-08 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0050_auto_20180706_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecperformance',
            name='status',
            field=models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status'),
        ),
    ]
