# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0051_ecperformance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecvolperformance',
            name='status',
            field=models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='ecvolperformance',
            name='output_ecvol_ec_stats_iops',
            field=models.IntegerField(default=-1, verbose_name=b'IOPS'),
        ),
        migrations.AlterField(
            model_name='ecvolperformance',
            name='output_ecvol_ec_stats_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'Latency avg'),
        ),
        migrations.AlterField(
            model_name='ecvolperformance',
            name='output_ecvol_ec_stats_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'Latency max'),
        ),
        migrations.AlterField(
            model_name='ecvolperformance',
            name='output_ecvol_ec_stats_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_iops',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_deflate_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Deflate: BW total'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_iops',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_inflate_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Inflate: BW total '),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_iops',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_decrypt_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Dec: Total BW'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_iops',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_filter_type_xts_encrypt_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'Enc: BW total'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_iops',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_read_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'LSV read: BW total'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_avg_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: BW avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_iops',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: IOPS'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_latency_ns_avg',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: Latency avg'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_latency_ns_max',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: Latency max'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_latency_ns_min',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: Latency min'),
        ),
        migrations.AlterField(
            model_name='lsvzipcryptoperformance',
            name='output_lsv_write_total_op_bw_mbps',
            field=models.IntegerField(default=-1, verbose_name=b'LSV write: BW total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_Bandwidth avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_DEFLATE_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_DEFLATE_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_Bandwidth avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_INFLATE_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_INFLATE_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_DECRYPT_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_DECRYPT_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_FILTER_TYPE_XTS_ENCRYPT_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_FILTER_TYPE_XTS_ENCRYPT_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_read_Bandwidth total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_read_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_read_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_read_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_read_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_read_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_write_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_write_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_write_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_write_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_EC_write_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_EC_write_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_Bandwidth_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_read_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_read_latency_min'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_Bandwidth_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_Bandwidth_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_Bandwidth_total',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_Bandwidth_total'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_IOPS',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_IOPS'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_latency_avg',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_latency_avg'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_latency_max',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_latency_max'),
        ),
        migrations.AlterField(
            model_name='voltestperformance',
            name='output_VOL_TYPE_BLK_LSV_write_latency_min',
            field=models.IntegerField(default=-1, verbose_name=b'output_VOL_TYPE_BLK_LSV_write_latency_min'),
        ),
    ]
