# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0053_modelmapping_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmapping',
            name='model_name',
            field=models.TextField(default=b'Performance1', unique=True),
        ),
    ]
