# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0056_metricchart_status_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocspeedperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bcopyflooddmaperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bcopyperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecvolperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutransitperformance',
            name='interpolation_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wulatencyallocstack',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wulatencyungated',
            name='interpolation_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
