# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0091_metricchartstatus_num_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricchartstatus',
            name='num_leaves',
        ),
    ]
