# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0092_remove_metricchartstatus_num_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricchart',
            name='num_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
