# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0098_auto_20181012_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricchart',
            name='copied_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricchart',
            name='copied_score_disposition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metricchart',
            name='last_good_score',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='metricchart',
            name='penultimate_good_score',
            field=models.FloatField(default=-1),
        ),
    ]
