# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-24 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0102_teramarkpkeecdh25519performance_teramarkpkeecdh256performance_teramarkpkersaperformance'),
        ('fun_test', '0102_storagecontroller'),
    ]

    operations = [
    ]
