# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0105_auto_20181026_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeraMarkCryptoPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_app', models.CharField(choices=[(0, b'crypto_test_perf')], default=b'crypto_test_perf', max_length=30)),
                ('input_algorithm', models.CharField(choices=[(0, b'AES_ECB'), (1, b'AES_GCM'), (2, b'AES_CBC'), (3, b'AES_XTS')], default=b'', max_length=30)),
                ('input_operation', models.CharField(choices=[(0, b'Encryption'), (1, b'Decryption')], default=b'', max_length=30)),
                ('input_pkt_size', models.IntegerField(choices=[(0, b'16'), (1, b'256'), (2, b'512'), (3, b'1024'), (4, b'4096'), (5, b'8192'), (6, b'16000')], default=-1, verbose_name=b'bytes')),
                ('output_ops_per_sec', models.IntegerField(default=-1, verbose_name=b'ops per sec')),
                ('output_throughput', models.IntegerField(default=-1, verbose_name=b'Mbps')),
                ('output_latency_min', models.IntegerField(default=-1, verbose_name=b'ns')),
                ('output_latency_avg', models.IntegerField(default=-1, verbose_name=b'ns')),
                ('output_latency_max', models.IntegerField(default=-1, verbose_name=b'ns')),
            ],
        ),
    ]
