# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0106_teramarkcryptoperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegresssionScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_path', models.TextField(unique=True)),
            ],
        ),
    ]
