# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-09 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0109_merge_20181108_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=b'SCHEDULER_STATE_UNKNOWN', max_length=30)),
                ('last_start_time', models.DateTimeField()),
                ('last_restart_request_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='metricchartstatus',
            name='build_status',
            field=models.CharField(default=b'UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='metricchartstatus',
            name='jenkins_job_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='metricchartstatus',
            name='suite_execution_id',
            field=models.IntegerField(default=-1),
        ),
    ]
