# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0116_auto_20181114_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricchart',
            name='owner_info',
            field=models.TextField(default=b'UNKNOWN'),
        ),
        migrations.AlterField(
            model_name='regresssionscripts',
            name='module',
            field=models.TextField(default=b"['storage']"),
        ),
    ]
