# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0122_auto_20181121_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricchart',
            name='jira_info',
            field=models.TextField(default=b''),
        ),
    ]
