# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-29 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0127_teramarkzipdeflateperformance_teramarkziplzmaperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeraMarkDfaPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_graph_index', models.IntegerField(choices=[(0, b'0')], default=-1)),
                ('output_processed', models.IntegerField(default=-1, verbose_name=b'Bytes')),
                ('output_matches', models.IntegerField(default=-1, verbose_name=b'Bytes')),
                ('output_latency', models.IntegerField(default=-1, verbose_name=b'ns')),
                ('output_bandwidth', models.IntegerField(default=-1, verbose_name=b'Gbps')),
            ],
        ),
        migrations.AlterField(
            model_name='regresssionscripts',
            name='modules',
            field=models.TextField(default=b'["storage"]'),
        ),
    ]
