# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0144_suitecontainerexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitecontainerexecution',
            name='suite_path',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='suiteexecution',
            name='suite_container_execution_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='suitecontainerexecution',
            name='version',
            field=models.TextField(default=-1),
        ),
    ]
