# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-31 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0149_auto_20190124_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseexecution',
            name='inputs',
            field=models.TextField(default=b'{}'),
        ),
    ]
