# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-08 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0167_auto_20190306_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricchart',
            name='base_line_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 1, 0, 0), verbose_name=b'base_line_date'),
        ),
    ]
