# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-25 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0174_lasttriageflowid_lasttriageid_triage_triageflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1FlowTestPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_app', models.CharField(choices=[(0, b'hw_hsu_test')], default=b'hw_hsu_test', max_length=30)),
                ('input_iterations', models.IntegerField(default=-1)),
                ('output_time', models.IntegerField(default=-1, verbose_name=b'seconds')),
                ('output_time_unit', models.TextField(default=b'secs')),
            ],
        ),
    ]
