# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-26 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0175_suiteexecution_bootup_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suiteexecution',
            old_name='bootup_done',
            new_name='build_done',
        ),
    ]
