# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-20 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0191_auto_20190417_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
