# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0193_junipercryptotunnelperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjobidmap',
            name='lsf_job_id',
            field=models.TextField(default=b''),
        ),
    ]
