# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-17 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0211_auto_20190517_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniperIpsecDecryptionMultiTunnelPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_test', models.TextField(default=b'ipsec_tunnel_throughput')),
                ('input_num_tunnels', models.IntegerField(default=-1)),
                ('input_algorithm', models.TextField(default=b'')),
                ('input_operation', models.TextField(default=b'')),
                ('input_key_size', models.IntegerField(default=-1)),
                ('input_src_memory', models.TextField(default=b'BM')),
                ('input_dst_memory', models.TextField(default=b'BM')),
                ('input_pkt_size', models.FloatField(default=-1, verbose_name=b'pkt size B')),
                ('output_packets_per_sec', models.FloatField(default=-1, verbose_name=b'packets per sec')),
                ('output_throughput', models.FloatField(default=-1, verbose_name=b'Gbps')),
                ('output_packets_per_sec_unit', models.TextField(default=b'Mpps')),
                ('output_throughput_unit', models.TextField(default=b'Gbps')),
                ('input_platform', models.TextField(default=b'F1')),
            ],
        ),
        migrations.CreateModel(
            name='JuniperIpsecDecryptionSingleTunnelPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_test', models.TextField(default=b'ipsec_tunnel_throughput')),
                ('input_num_tunnels', models.IntegerField(default=-1)),
                ('input_algorithm', models.TextField(default=b'')),
                ('input_operation', models.TextField(default=b'')),
                ('input_key_size', models.IntegerField(default=-1)),
                ('input_src_memory', models.TextField(default=b'BM')),
                ('input_dst_memory', models.TextField(default=b'BM')),
                ('input_pkt_size', models.FloatField(default=-1, verbose_name=b'pkt size B')),
                ('output_packets_per_sec', models.FloatField(default=-1, verbose_name=b'packets per sec')),
                ('output_throughput', models.FloatField(default=-1, verbose_name=b'Gbps')),
                ('output_packets_per_sec_unit', models.TextField(default=b'Mpps')),
                ('output_throughput_unit', models.TextField(default=b'Gbps')),
                ('input_platform', models.TextField(default=b'F1')),
            ],
        ),
        migrations.CreateModel(
            name='JuniperIpsecEncryptionMultiTunnelPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_test', models.TextField(default=b'ipsec_tunnel_throughput')),
                ('input_num_tunnels', models.IntegerField(default=-1)),
                ('input_algorithm', models.TextField(default=b'')),
                ('input_operation', models.TextField(default=b'')),
                ('input_key_size', models.IntegerField(default=-1)),
                ('input_src_memory', models.TextField(default=b'BM')),
                ('input_dst_memory', models.TextField(default=b'BM')),
                ('input_pkt_size', models.FloatField(default=-1, verbose_name=b'pkt size B')),
                ('output_packets_per_sec', models.FloatField(default=-1, verbose_name=b'packets per sec')),
                ('output_throughput', models.FloatField(default=-1, verbose_name=b'Gbps')),
                ('output_packets_per_sec_unit', models.TextField(default=b'Mpps')),
                ('output_throughput_unit', models.TextField(default=b'Gbps')),
                ('input_platform', models.TextField(default=b'F1')),
            ],
        ),
        migrations.CreateModel(
            name='JuniperIpsecEncryptionSingleTunnelPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_test', models.TextField(default=b'ipsec_tunnel_throughput')),
                ('input_num_tunnels', models.IntegerField(default=-1)),
                ('input_algorithm', models.TextField(default=b'')),
                ('input_operation', models.TextField(default=b'')),
                ('input_key_size', models.IntegerField(default=-1)),
                ('input_src_memory', models.TextField(default=b'BM')),
                ('input_dst_memory', models.TextField(default=b'BM')),
                ('input_pkt_size', models.FloatField(default=-1, verbose_name=b'pkt size B')),
                ('output_packets_per_sec', models.FloatField(default=-1, verbose_name=b'packets per sec')),
                ('output_throughput', models.FloatField(default=-1, verbose_name=b'Gbps')),
                ('output_packets_per_sec_unit', models.TextField(default=b'Mpps')),
                ('output_throughput_unit', models.TextField(default=b'Gbps')),
                ('input_platform', models.TextField(default=b'F1')),
            ],
        ),
    ]
