# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-19 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0212_juniperipsecdecryptionmultitunnelperformance_juniperipsecdecryptionsingletunnelperformance_juniperip'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjobidmap',
            name='build_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
