# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-20 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0214_jenkinsjobidmap_suite_execution_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daemon',
            fields=[
                ('funmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fun_test.FunModel')),
                ('name', models.TextField(unique=True)),
                ('daemon_id', models.IntegerField()),
                ('heart_beat_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=('fun_test.funmodel',),
        ),
        migrations.AddField(
            model_name='triage3trial',
            name='result',
            field=models.TextField(default=b'UNKNOWN'),
        ),
    ]
