# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0219_testcaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinfo',
            name='steps',
            field=models.TextField(default=b''),
        ),
    ]
