# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-01 04:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0223_auto_20190531_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('funmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fun_test.FunModel')),
                ('name', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('job_ids', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('manual_lock_user', models.TextField(default=None, null=True)),
            ],
            bases=('fun_test.funmodel',),
        ),
        migrations.AddField(
            model_name='suiteexecution',
            name='assets_used',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='suiteexecution',
            name='started_time',
            field=models.DateTimeField(null=True),
        ),
    ]
