# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-15 03:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0228_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsRunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=b'', unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
