# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-02 23:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0232_alibabaperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.TextField(default=b'REGULAR')),
                ('title', models.TextField(default=b'')),
                ('fun_chart_type', models.TextField(default=b'line')),
                ('x_axis_title', models.TextField(default=b'')),
                ('y_axis_title', models.TextField(default=b'')),
                ('series_filters', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('chart_id', models.IntegerField(default=-1, unique=True)),
                ('x_scale', models.TextField(default=b'')),
                ('y_scale', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='LastChartId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='metricchart',
            name='companion_charts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), default=[], size=None),
        ),
        migrations.AddField(
            model_name='metricchart',
            name='creator',
            field=models.TextField(default=b'team-regression@fungible.com'),
        ),
    ]
