# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0234_alibabardmaperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='announcement',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
