# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-22 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0241_auto_20190718_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('directive', models.IntegerField(default=-1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='announcement_level',
            field=models.IntegerField(default=1),
        ),
    ]
