# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-26 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0243_inspurdatareconstructionperformance_inspursinglediskfailureperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjobidmap',
            name='completion_date',
        ),
    ]
