# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-11 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0250_auto_20190811_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage3',
            name='blob',
        ),
    ]
