# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-04 00:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0262_suite_tyoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricchart',
            name='workspace_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='metricchart',
            name='internal_chart_name',
            field=models.TextField(default=b'UNKNOWN'),
        ),
    ]
