# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-31 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0272_auto_20191030_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvmefcpperformance',
            name='input_volumes',
            field=models.IntegerField(default=-1, verbose_name=b'Volumes'),
        ),
    ]
