# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-01 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0274_auto_20191031_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoFastPathPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_allowed', models.BooleanField(default=False)),
                ('interpolated', models.BooleanField(default=False)),
                ('status', models.CharField(default=b'PASSED', max_length=30, verbose_name=b'Status')),
                ('input_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Date')),
                ('input_app', models.CharField(default=b'crypto_fast_path', max_length=30)),
                ('input_algorithm', models.CharField(default=b'', max_length=30)),
                ('input_operation', models.CharField(default=b'', max_length=30)),
                ('input_pkt_size', models.IntegerField(default=-1, verbose_name=b'bytes')),
                ('input_key_size', models.IntegerField(default=-1, verbose_name=b'Key Size')),
                ('output_ops_per_sec', models.IntegerField(default=-1, verbose_name=b'ops per sec')),
                ('output_throughput', models.FloatField(default=-1, verbose_name=b'Throughput')),
                ('output_latency_min', models.IntegerField(default=-1, verbose_name=b'Latency min')),
                ('output_latency_avg', models.IntegerField(default=-1, verbose_name=b'Latency avg')),
                ('output_latency_max', models.IntegerField(default=-1, verbose_name=b'Latency max')),
                ('output_ops_per_sec_unit', models.TextField(default=b'ops')),
                ('output_throughput_unit', models.TextField(default=b'Gbps')),
                ('output_latency_min_unit', models.TextField(default=b'nsecs')),
                ('output_latency_avg_unit', models.TextField(default=b'nsecs')),
                ('output_latency_max_unit', models.TextField(default=b'nsecs')),
                ('input_platform', models.TextField(default=b'F1')),
            ],
        ),
    ]
