# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-08 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0277_funondemandtotaltimeperformance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetricsdag',
            old_name='f1_metrics_dag',
            new_name='metrics_dag',
        ),
        migrations.RemoveField(
            model_name='performancemetricsdag',
            name='s1_metrics_dag',
        ),
    ]
