# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0282_auto_20191121_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiteexecution',
            name='max_run_time',
            field=models.IntegerField(default=604800),
        ),
    ]
