# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-01-04 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0301_auto_20200103_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='health_check_message',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='testbed',
            name='health_check_message',
            field=models.TextField(default=b''),
        ),
    ]
