# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0310_dataplaneoperationsperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='pooled',
            field=models.BooleanField(default=False),
        ),
    ]
