# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-26 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_test', '0312_testbed_pooled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplaneoperationsperformance',
            name='input_real_f1',
            field=models.BooleanField(default=False),
        ),
    ]
