#! /usr/bin/python
#
#  dpc_cli
#
#  Created by rushikesh.pendse@fungible.com on 2018-05-29
#
#  Copyright 2018 Fungible Inc. All rights reserved.
#

import sys
from dpcsh_interactive_client.cmd_controller import CmdController

INTRO = """
    Interactive Client over DPC 
    Features :-
    1. Set/Get configs 
    2. Clear Stats
    3. Peek various Stats in iterations at certain time interval. Shows difference in counters in tabular format. 
       Also user can grep specific counters by using regex
    4. Capture stats to a file. You can provide a filename or it will create a file and print it on console once 
       command is executed successfully.
    
    For "help" or "-h" for available commands/sub-commands
    
    System log level set to 3 by default. If you want to change it then run set system params syslog <level> 
"""


def main():
    try:
        ip_address = raw_input("Enter DPC server IP (Default 10.1.21.120): ")
        tcp_port_num = raw_input("Enter Port num on which DPC is listening (Default 40221): ")
        if not ip_address:
            ip_address = "10.1.21.120"
        if not tcp_port_num:
            tcp_port_num = 40221

        cmd_controller_obj = CmdController(target_ip=ip_address, target_port=int(tcp_port_num), verbose=False)
        cmd_controller_obj.cmdloop(intro=INTRO)
    except Exception as ex:
        print ex
        sys.exit(1)


if __name__ == '__main__':
    main()




