apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-fungible-csi-sp-c35530-pvc-raw4
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 500Gi
