apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example4
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  csi:
    driver: csi-storage.fungible.com
    volumeAttributes:
      type: raw
    volumeHandle: 23cd41b9205b43e8
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Block

