namespace eval ::sth::6pe6vpe:: {
}

set ::sth::6pe6vpe::6pe6vpeTable {
    ::sth::6pe6vpe::
    {    emulation_6pe_6vpe_provider_port_config
        {hname                                     stcobj                      stcattr               type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                             constants}
        {port_handle                               _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {handle                                    _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {mode                                      _none_                      _none_                {CHOICES create delete}     0             _none_         _none_      true           _none_                            true             _none_          _none_                           _none_}
        {dut_interface_ipv4_addr                   Vpn6PeGenCorePortParams     DutIpv4Addr           IPV4                        1             192.85.1.1     _none_      true           _none_                            false            _none_          { create coreport_config }       _none_}
        {dut_interface_ipv4_addr_step              Vpn6PeGenCorePortParams     DutIpv4AddrStep       IPV4                        2             0.0.1.0        _none_      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {dut_interface_ipv4_prefix_length          Vpn6PeGenCorePortParams     Ipv4PrefixLength      NUMERIC                     1             24             0-32        true           _none_                            false            _none_          { create coreport_config }       _none_}
        {sub_interface_enable                      Vpn6PeGenCorePortParams     SubIfEnable           {CHOICES true false}        1             false          _none_      true           _none_                            false            _none_          { create coreport_config }       _none_}
        {sub_interface_count                       Vpn6PeGenCorePortParams     SubIfCount            NUMERIC                     2             1              1-4095      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {vlan_id                                   Vpn6PeGenCorePortParams     VlanId                NUMERIC                     2             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {vlan_id_step                              Vpn6PeGenCorePortParams     VlanIdStep            NUMERIC                     0             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
    }
    {    emulation_6pe_6vpe_cust_port_config
        {hname                                     stcobj                       stcattr              type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                            constants}
        {port_handle                               _none_                       _none_               ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                          _none_}
        {handle                                    _none_                       _none_               ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                          _none_}
        {mode                                      _none_                       _none_               {CHOICES create delete}     0             _none_         _none_      true           _none_                            true             _none_          _none_                          _none_}
        {dut_interface_ipv6_addr                   Vpn6PeGenCustPortParams      DutIpv6Addr          IPV6                        1             ::             _none_      true           _none_                            false            _none_          { create custport_config }      _none_}
        {dut_interface_ipv6_addr_step              Vpn6PeGenCustPortParams      DutIpv6AddrStep      IPV6                        2             0:0:0:1::      _none_      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {dut_interface_ipv6_prefix_length          Vpn6PeGenCustPortParams      Ipv6PrefixLength     NUMERIC                     1             64             0-128       true           _none_                            false            _none_          { create custport_config }      _none_}
        {sub_interface_enable                      Vpn6PeGenCustPortParams      SubIfEnable          {CHOICES true false}        1             false          _none_      true           _none_                            false            _none_          { create custport_config }      _none_}
        {sub_interface_count                       Vpn6PeGenCustPortParams      SubIfCount           NUMERIC                     2             1              1-4095      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {vlan_id                                   Vpn6PeGenCustPortParams      VlanId               NUMERIC                     2             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {vlan_id_step                              Vpn6PeGenCustPortParams      VlanIdStep           NUMERIC                     0             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
    }
    {    emulation_6pe_6vpe_config
        {hname                                            stcobj                          stcattr                                           type                                                  priority             default                 range                 supported        dependency            mandatory       procfunc                  mode                                         constants}
        {handle                                           _none_                          _none_                                            ANY                                                   2                    _none_                  _none_                true             _none_                false           _none_                    _none_                                       _none_}
        {mode                                             _none_                          _none_                                            {CHOICES create delete}                               0                    _none_                  _none_                true             _none_                true            _none_                    _none_                                       _none_}
        {dut_router_id                                    Vpn6PeGenParams                 DutLoopbackIpAddr                                 IPV4                                                  2                    "10.0.0.1"              _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {dut_as                                           Vpn6PeGenParams                 DutAs                                             NUMERIC                                               2                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {dut_4byte_as_enable                              Vpn6PeGenParams                 Enable4ByteDutAs                                  {CHOICES true false}                                  2                    0                       _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {dut_4byte_as                                     Vpn6PeGenParams                 DutAs4Byte                                        ANY                                                   3                    "1:1"                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {use_provider_ports                               Vpn6PeGenParams                 UseCorePortsEnable                                {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {use_cust_ports                                   Vpn6PeGenParams                 UseCustPortsEnable                                {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {igp_protocol                                     Vpn6PeGenParams                 CoreIgpProtocol                                   {CHOICES ospf isis rip none}                          2                    ospf                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {mpls_protocol                                    Vpn6PeGenParams                 CoreMplsProtocol                                  {CHOICES none ldp rsvp ospf isis}                     2                    ldp                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                       _none_}
        {igp_ospf_area_id                                 VpnIgpOspfv2SessionParams       AreaId                                            IPV4                                                  3                    "0.0.0.0"               _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_network_type                            VpnIgpOspfv2SessionParams       NetworkType                                       {CHOICES native broadcast p2p}                        3                    native                  _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                {native "NATIVE" broadcast "BROADCAST" p2p "P2P"}}
        {igp_ospf_router_priority                         VpnIgpOspfv2SessionParams       RouterPriority                                    NUMERIC                                               3                    0                       0-255                 true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_interface_cost                          VpnIgpOspfv2SessionParams       IfCost                                            NUMERIC                                               3                    1                       1-65535               true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_options                                 VpnIgpOspfv2SessionParams       Options                                           HEX                                                   3                    0x02                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_auth_mode                               Ospfv2AuthenticationParams      Authentication                                    {CHOICES none simple md5}                             3                    none                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   {none "NONE" simple "SIMPLE" md5 "MD5"}}
        {igp_ospf_auth_password                           Ospfv2AuthenticationParams      Password                                          ANY                                                   4                    "spirent"               _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   _none_}
        {igp_ospf_auth_md5_key                            Ospfv2AuthenticationParams      Md5KeyId                                          NUMERIC                                               4                    1                       0-255                 true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   _none_}
        {igp_ospf_graceful_restart_enable                 VpnIgpOspfv2SessionParams       EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_graceful_restart_type                   VpnIgpOspfv2SessionParams       GracefulRestartType                               {CHOICES none rfc_standard ll_signalling}             3                    none                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                {none "NONE" rfc_standard "RFCSTANDARD" ll_signalling "LLSIGNALLING"}}
        {igp_ospf_bfd_enable                              VpnIgpOspfv2SessionParams       EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_isis_level                                   VpnIgpIsisSessionParams         Level                                             {CHOICES level1 level2 level1_and_2}                  3                    level2                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 {level1 "LEVEL1" level2 "LEVEL2" level1_and_2 "LEVEL1_AND_2"}}
        {igp_isis_network_type                            VpnIgpIsisSessionParams         NetworkType                                       {CHOICES broadcast p2p}                               3                    broadcast               _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 {broadcast "BROADCAST" p2p "P2P"}}
        {igp_isis_router_priority                         VpnIgpIsisSessionParams         RouterPriority                                    NUMERIC                                               3                    0                       0-127                 true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area1                                   VpnIgpIsisSessionParams         Area1                                             ANY                                                   3                    000001                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area2                                   VpnIgpIsisSessionParams         Area2                                             ANY                                                   3                    _none_                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area3                                   VpnIgpIsisSessionParams         Area3                                             ANY                                                   3                    _none_                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_circuit_id                              VpnIgpIsisSessionParams         CircuitId                                         ANY                                                   3                    1                       0-255                 true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_auth_mode                               IsisAuthenticationParams        Authentication                                    {CHOICES none simple md5}                             3                    none                    _none_                true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   {none "NONE" simple "SIMPLE" md5 "MD5"}}
        {igp_isis_auth_password                           IsisAuthenticationParams        Password                                          ANY                                                   4                    "spirent"               _none_                true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   _none_}
        {igp_isis_auth_md5_key                            IsisAuthenticationParams        Md5KeyId                                          NUMERIC                                               4                    1                       0-255                 true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   _none_}
        {igp_isis_metric_mode                             VpnIgpIsisSessionParams         MetricMode                                        {CHOICES narrow wide narrow_and_wide}                 3                    narrow_and_wide         _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                {narrow "NARROW" wide "WIDE" narrow_and_wide "NARROW_AND_WIDE"}}
        {igp_isis_l1_metric                               VpnIgpIsisSessionParams         L1Metric                                          NUMERIC                                               3                    1                       1-63                  true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l1_wide_metric                          VpnIgpIsisSessionParams         L1WideMetric                                      NUMERIC                                               3                    1                       0-16777215            true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l2_metric                               VpnIgpIsisSessionParams         L2Metric                                          NUMERIC                                               3                    1                       1-63                  true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l2_wide_metric                          VpnIgpIsisSessionParams         L2WideMetric                                      NUMERIC                                               3                    1                       0-16777215            true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_graceful_restart_enable                 VpnIgpIsisSessionParams         EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_hello_padding                           VpnIgpIsisSessionParams         HelloPadding                                      {CHOICES true false}                                  3                    1                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_bfd_enable                              VpnIgpIsisSessionParams         EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {mpls_rsvp_bandwidth_per_link                     Vpn6PeGenParams                 CorePRsvpBandwidthPerLink                         NUMERIC                                               4                    100000                  1-2147483647          true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {mpls_rsvp_bandwidth_per_tunnel                   Vpn6PeGenParams                 CorePRsvpBandwidthPerTunnel                       NUMERIC                                               4                    0                       0-2147483647          true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {mpls_rsvp_egress_label                           VpnMplsRsvpSessionParams        EgressLabel                                       {CHOICES next_available implicit_null explicit_null}  3                    next_available          _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                {next_available "RSVP_EGRESS_NEXTAVAILABLE" implicit_null "RSVP_EGRESS_IMPLICIT_NULL" explicit_null "RSVP_EGRESS_EXPLICIT_NULL"}}
        {mpls_rsvp_transit                                VpnMplsRsvpSessionParams        Transit                                           {CHOICES  accept_all accept_configured}               3                    accept_configured       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                {accept_all "RSVP_TRANSIT_ACCEPT_ALL" accept_configured "RSVP_TRANSIT_ACCEPT_CONFIGURED"}}
        {mpls_rsvp_min_label                              VpnMplsRsvpSessionParams        LabelMin                                          NUMERIC                                               3                    16                      1-65535               true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_max_label                              VpnMplsRsvpSessionParams        LabelMax                                          NUMERIC                                               3                    65535                   1-65535               true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_graceful_restart_enable                VpnMplsRsvpSessionParams        EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_recover_time                           VpnMplsRsvpSessionParams        RecoveryTime                                      NUMERIC                                               3                    0                       0-4294967295          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_restart_time                           VpnMplsRsvpSessionParams        RestartTime                                       NUMERIC                                               3                    3000                    0-4294967295          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_bfd_enable                             VpnMplsRsvpSessionParams        EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_request_conf                           VpnMplsRsvpSessionParams        EnableResvRequestConfirmation                     {CHOICES true false}                                  3                    false                   _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_hello_interval                         VpnMplsRsvpSessionParams        HelloInterval                                     NUMERIC                                               3                    1000                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_} 
        {mpls_rsvp_bundle_interval                        VpnMplsRsvpSessionParams        RefreshReductionBundleInterval                    ALPHANUM                                              3                    null                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_summary_refresh_interval               VpnMplsRsvpSessionParams        RefreshReductionSummaryRefreshInterval            ALPHANUM                                              3                    null                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_inter_packet_delay                     VpnMplsRsvpSessionParams        InterPktDelay                                     NUMERIC                                               3                    30                      0-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_refresh_interval                       VpnMplsRsvpSessionParams        RefreshInterval                                   NUMERIC                                               3                    30000                   1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_refresh_delivery                       VpnMplsRsvpSessionParams        EnableReliableDelivery                            {CHOICES true false}                                  3                    false                   _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_interval                       VpnMplsRsvpSessionParams        RetransmitInterval                                NUMERIC                                               3                    500                     1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_limit                          VpnMplsRsvpSessionParams        RetransmitLimit                                   NUMERIC                                               3                    3                       0-10                  true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_delta                          VpnMplsRsvpSessionParams        RetransmitDelta                                   NUMERIC                                               3                    1                       0-3                   true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_hello_enable                           VpnMplsRsvpSessionParams        EnableHello                                       {CHOICES true false}                                  3                    1                       0-3                   true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_ldp_hello_type                              VpnMplsLdpSessionParams         HelloType                                         {CHOICES direct targeted}                             3                    direct                  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {direct "LDP_DIRECTED_HELLO" targeted "LDP_TARGETED_HELLO"}}
        {mpls_ldp_transport_mode                          VpnMplsLdpSessionParams         TransportTlvMode                                  {CHOICES none tester_ip router_id}                    3                    tester_ip               _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {none "TRANSPORT_TLV_MODE_NONE" tester_ip "TRANSPORT_TLV_MODE_TESTER_IP" router_id "TRANSPORT_TLV_MODE_ROUTER_ID"}}
        {mpls_ldp_hello_interval                          VpnMplsLdpSessionParams         HelloInterval                                     NUMERIC                                               3                    5                       1-21845               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_keepalive_interval                      VpnMplsLdpSessionParams         KeepAliveInterval                                 NUMERIC                                               3                    60                      1-21845               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_egress_label                            VpnMplsLdpSessionParams         EgressLabel                                       {CHOICES next_available implicit_null explicit_null}  3                    next_available          _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {next_available "LDP_EGRESS_NEXTAVAILABLE" implicit_null "LDP_EGRESS_IMPLICIT_NULL" explicit_null "LDP_EGRESS_EXPLICIT_NULL"}}
        {mpls_ldp_min_label                               VpnMplsLdpSessionParams         LabelMin                                          NUMERIC                                               3                    16                      1-65535               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_graceful_restart_enable                 VpnMplsLdpSessionParams         EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_recover_time                            VpnMplsLdpSessionParams         RecoveryTime                                      NUMERIC                                               3                    140                     0-4294967295          true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_reconnect_time                          VpnMplsLdpSessionParams         ReconnectTime                                     NUMERIC                                               3                    60                      0-4294967295          true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_bfd_enable                              VpnMplsLdpSessionParams         EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_label_adv_mode                          VpnMplsLdpSessionParams         LabelAdvertisementMode                            {CHOICES downstream_unsolicited downstream_on_demand} 3                    downstream_unsolicited  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_auth_mode                               LdpAuthenticationParams         Authentication                                    {CHOICES none md5}                                    3                    "none"                  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpauth_config}                    _none_}
        {mpls_ldp_auth_password                           LdpAuthenticationParams         Password                                          ANY                                                   4                    "spirent"               _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpauth_config}                    _none_}
        {mpls_ospf_sr_algorithms                          VpnIgpOspfv2SessionParams       SrAlgorithmTlvAlgorithms                          ANY                                                   3                    0                       _none_                true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_sid_base                               VpnIgpOspfv2SessionParams       SidLabelRangeTlvSidBase                           NUMERIC                                               3                    100                     0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_sid_range                              VpnIgpOspfv2SessionParams       SidLabelRangeTlvSidRange                          NUMERIC                                               3                    100                     0-65535               true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_node_sid_index                         VpnIgpOspfv2SessionParams       PrefixSidSubTlvIndex                              NUMERIC                                               3                    0                       0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_node_sid_index_step                    VpnIgpOspfv2SessionParams       PrefixSidSubTlvIndexStep                          NUMERIC                                               3                    1                       0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_isis_sr_algorithm                           VpnIgpIsisSessionParams         SrAlgorithms                                      ANY                                                   3                    0                       _none_                true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_sid_base                               VpnIgpIsisSessionParams         SrCapSidBase                                      NUMERIC                                               3                    100                     0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_sid_range                              VpnIgpIsisSessionParams         SrCapSidRange                                     NUMERIC                                               3                    100                     0-65535               true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_node_sid_index                         VpnIgpIsisSessionParams         SrNodeSidIndex                                    NUMERIC                                               3                    0                       0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_node_sid_index_step                    VpnIgpIsisSessionParams         SrNodeSidIndexStep                                NUMERIC                                               3                    1                       0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {p_router_enable                                  Vpn6PeGenParams                 CorePEnable                                       {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {p_router_num_per_subif                           Vpn6PeGenParams                 CorePPerSubIf                                     NUMERIC                                               3                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {p_router_topology_type                           Vpn6PeGenParams                 CorePTopologyType                                 {CHOICES tree grid}                                   3                    tree                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {tree "TREE" grid "GRID"}}
        {p_router_id_start                                Vpn6PeGenParams                 CorePLoopbackIpAddr                               IPV4                                                  3                    "192.0.1.1"             _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {p_router_id_step                                 Vpn6PeGenParams                 CorePLoopbackIpAddrStep                           IPV4                                                  3                    "0.0.1.0"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {p_router_ipv4_addr                               Vpn6PeGenParams                 CorePIfIpAddr                                     IPV4                                                  3                    "1.0.0.1"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {p_router_ipv4_prefix_len                         Vpn6PeGenParams                 CorePIfPrefixLength                               NUMERIC                                               3                    24                      1-30                  true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {pe_router_num_per_subif                          Vpn6PeGenParams                 CorePePerSubIf                                    NUMERIC                                               3                    1                       1-10000               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {pe_router_id_start                               Vpn6PeGenParams                 CorePeLoopbackIpAddr                              IPV4                                                  3                    "10.0.0.2"              _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {pe_router_id_step                                Vpn6PeGenParams                 CorePeLoopbackIpAddrStep                          IPV4                                                  3                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {vpn_6vpe_enable                                  Vpn6PeGenParams                 Vpn6VpeEnable                                     {CHOICES true false}                                  2                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_enable                       Vpn6PeGenParams                 CoreRouteReflectorEnable                          {CHOICES true false}                                  2                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_per_subif                    Vpn6PeGenParams                 CoreRouteReflectorPerSubIf                        NUMERIC                                               4                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_per_pe                       Vpn6PeGenParams                 CoreRouteReflectorPerPe                           NUMERIC                                               4                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_id_start                     Vpn6PeGenParams                 CoreRouteReflectorLoopbackIpAddr                  IPV4                                                  4                    "7.7.7.7"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_id_step                      Vpn6PeGenParams                 CoreRouteReflectorLoopbackIpAddrStep              IPV4                                                  4                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_cluster_id                   Vpn6PeGenParams                 CoreRouteReflectorClusterId                       IPV4                                                  4                    "0.0.0.0"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_cluster_id_step              Vpn6PeGenParams                 CoreRouteReflectorClusterIdStep                   IPV4                                                  4                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_ids                          Vpn6PeGenParams                 CoreRouteReflectorIds                             IPV4                                                  4                    "0.0.0.0"               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {bgp_route_reflector_mode                         Vpn6PeGenParams                 CoreRouteReflectorMode                            {CHOICES stc_as_rr dut_as_rr}                         3                    stc_as_rr               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {stc_as_rr "STC_AS_RR" dut_as_rr "DUT_AS_RR"}}
        {bgp_bfd_enable                                   Vpn6PeGenParams                 CoreEnableBfdForBgp                               {CHOICES true false}                                  3                    0                       _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {vrf_count                                        Vpn6PeGenParams                 VpnCount                                          NUMERIC                                               3                    10                      1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {vrf_rd_assignment                                Vpn6PeGenParams                 VpnRouteDistinguisherAssignment                   {CHOICES use_rt manual}                               3                    use_rt                  _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {use_rt "USE_RT" manual "MANUAL"}}
        {vrf_route_target_start                           Vpn6PeGenParams                 VpnRouteTarget                                    ANY                                                   3                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {vrf_route_target_step                            Vpn6PeGenParams                 VpnRouteTargetStep                                ANY                                                   3                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_vrf_assignment                           Vpn6PeGenParams                 CustCeVpnAssignment                               {CHOICES round_robin sequential}                      3                    round_robin             _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {round_robin "ROUND_ROBIN" sequential "SEQUENTIAL"}}
        {cust_ce_routing_protocol                         Vpn6PeGenParams                 CustCeRoutingProtocol                             {CHOICES bgp ospf rip isis mixed}                    3                    bgp                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {bgp "BGP" ospf "OSPF" rip "RIP" isis "ISIS" static_route "STATIC_ROUTES" mixed "MIXED"}}
        {cust_ce_bgp_percent                              Vpn6PeGenParams                 CustCeBgpPercent                                  NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_rip_percent                              Vpn6PeGenParams                 CustCeRipPercent                                  NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_ospf_percent                             Vpn6PeGenParams                 CustCeOspfPercent                                 NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_isis_percent                             Vpn6PeGenParams                 CustCeIsisPercent                                 NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_as                                   Vpn6PeGenParams                 CustCeBgpAs                                       NUMERIC                                               5                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_as_step_per_ce_enable                Vpn6PeGenParams                 CustCeBgpAsStepPerCeEnable                        {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_as_step_per_ce                       Vpn6PeGenParams                 CustCeBgpAsStepPerCe                              NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_as_step_per_vrf_enable               Vpn6PeGenParams                 CustCeBgpAsStepPerVpnEnable                       {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_as_step_per_vrf                      Vpn6PeGenParams                 CustCeBgpAsStepPerVpn                             NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as_enable                      Vpn6PeGenParams                 CustCeBgp4ByteAsEnable                            {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as                             Vpn6PeGenParams                 CustCeBgp4ByteAs                                  ANY                                                   6                    1:1                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_ce_enable          Vpn6PeGenParams                 CustCeBgp4ByteAsStepPerCeEnable                   {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_ce                 Vpn6PeGenParams                 CustCeBgp4ByteAsStepPerCe                         NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_vrf_enable         Vpn6PeGenParams                 CustCeBgp4ByteAsStepPerVpnEnable                  {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_vrf                Vpn6PeGenParams                 CustCeBgp4ByteAsStepPerVpn                        NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {customer_ce_static_route_percent                 Vpn6PeGenParams                 CustCeStaticRoutePercent                          NUMERIC                                               6                    0                       0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_rd_start                                    Vpn6PeGenParams                 CustRouteDistinguisher                            ANY                                                   5                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_rd_step_per_vrf_enable                      Vpn6PeGenParams                 CustRouteDistinguisherStepPerVpnEnable            {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_rd_step_per_vrf                             Vpn6PeGenParams                 CustRouteDistinguisherStepPerVpn                  ANY                                                   6                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_rd_step_per_ce_enable                       Vpn6PeGenParams                 CustRouteDistinguisherStepPerCeEnable             {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_rd_step_per_ce                              Vpn6PeGenParams                 CustRouteDistinguisherStepPerCe                   ANY                                                   6                    0:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_pe_vrf_assignment                       Vpn6PeGenParams                 ProviderPeVpnAssignment                           {CHOICES vpn_per_pe pe_per_vpn}                       5                    vpn_per_pe              _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {vpn_per_pe "VPNS_PER_PE" pe_per_vpn "PES_PER_VPN"}}
        {provider_pe_vrf_count                            Vpn6PeGenParams                 ProviderPeLspCount                                NUMERIC                                               6                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_pe_vrf_all_assign                       Vpn6PeGenParams                 CorePeVpnAll                                      {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as_enable                        Vpn6PeGenParams                 CoreCeBgpAsEnable                                 {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as                               Vpn6PeGenParams                 CoreCeBgpAs                                       NUMERIC                                               6                    1                       1-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as_step_per_ce_enable            Vpn6PeGenParams                 CoreCeBgpAsStepPerCeEnable                        {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as_step_per_ce                   Vpn6PeGenParams                 CoreCeBgpAsStepPerCe                              NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as_step_per_vrf_enable           Vpn6PeGenParams                 CoreCeBgpAsStepPerVpnEnable                       {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_as_step_per_vrf                  Vpn6PeGenParams                 CoreCeBgpAsStepPerVpn                             NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as_enable                  Vpn6PeGenParams                 CoreCeBgp4ByteAsEnable                            {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as                         Vpn6PeGenParams                 CoreCeBgp4ByteAs                                  ANY                                                   6                    1:1                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_ce_enable      Vpn6PeGenParams                 CoreCeBgp4ByteAsStepPerCeEnable                   {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_ce             Vpn6PeGenParams                 CoreCeBgp4ByteAsStepPerCe                         NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_vrf_enable     Vpn6PeGenParams                 CoreCeBgp4ByteAsStepPerVpnEnable                  {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_vrf            Vpn6PeGenParams                 CoreCeBgp4ByteAsStepPerVpn                        NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_rd_start                                Vpn6PeGenParams                 CoreRouteDistinguisher                            ANY                                                   5                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_rd_step_per_vrf_enable                  Vpn6PeGenParams                 CoreRouteDistinguisherStepPerVpnEnable            {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_rd_step_per_vrf                         Vpn6PeGenParams                 CoreRouteDistinguisherStepPerVpn                  ANY                                                   6                    1:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_rd_step_per_ce_enable                   Vpn6PeGenParams                 CoreRouteDistinguisherStepPerCeEnable             {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_rd_step_per_ce                          Vpn6PeGenParams                 CoreRouteDistinguisherStepPerCe                   ANY                                                   6                    0:0                     _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ipv6_vpn_route_start                        Vpn6PeGenParams                 VpnCustRouteStart                                 IPV6                                                  7                    2000::                  _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ipv6_vpn_route_overlap                      Vpn6PeGenParams                 VpnCustRouteOverlap                               {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ipv6_vpn_route_prefix_len                   Vpn6PeGenParams                 VpnCustRoutePrefixLength                          NUMERIC                                               7                    64                      1-128                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ipv6_vpn_route_step                         Vpn6PeGenParams                 VpnCustRouteStep                                  NUMERIC                                               7                    1                       0-4294967295          true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {cust_ipv6_ce_route_type                          Vpn6PeGenParams                 CustCeRouteType                                   {CHOICES internal external}                           7                    internal                _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {internal "INTERNAL" external "EXTERNAL"}}
        {cust_route_count_per_ce                          Vpn6PeGenParams                 CustRoutesPerCe                                   NUMERIC                                               7                     1                      1-2147483647          true             _none_                false           _none_                    {create vpn6pe_config }                    _none_}
        {provider_ipv6_vpn_route_start                    Vpn6PeGenParams                 VpnCoreRouteStart                                 IPV6                                                  7                    2001::                  _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ipv6_vpn_route_overlap                  Vpn6PeGenParams                 VpnCoreRouteOverlap                               {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ipv6_vpn_route_prefix_len               Vpn6PeGenParams                 VpnCoreRoutePrefixLength                          NUMERIC                                               7                    64                      1-128                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_ipv6_vpn_route_step                     Vpn6PeGenParams                 VpnCoreRouteStep                                  NUMERIC                                               7                    1                       0-4294967295          true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {provider_route_count_per_ce                      Vpn6PeGenParams                  CoreRoutesPerCe                                  NUMERIC                                               7                    1                       1-2147483647          true             _none_                false           _none_                    {create vpn6pe_config }                    _none_}
        {vrf_route_mpls_label_type                        Vpn6PeGenParams                 VpnRouteMplsLabelType                             {CHOICES label_per_site label_per_route}              7                    label_per_site          _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {label_per_site "SITE" label_per_route "ROUTE"}}
        {vrf_route_mpls_label_start                       Vpn6PeGenParams                 VpnRouteMplsLabelStart                            NUMERIC                                               7                    16                      1-1048575             true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {traffic_flow_direction                           Vpn6PeGenParams                 TrafficFlow                                       {CHOICES cust_to_core core_to_cust bidirectional fully_meshed none }  7    bidirectional           _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {cust_to_core "customer_to_core" core_to_cust "core_to_customer" bidirectional "bidirectional" fully_meshed "fully_meshed"}}
        {traffic_pattern                                  Vpn6PeGenParams                 TrafficPattern                                    {CHOICES one_to_one one_to_many}                      8                    one_to_many             _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {one_to_one "ONE_TO_ONE" one_to_many "ONE_TO_MANY"}}
        {traffic_stream_group_method                      Vpn6PeGenParams                 StreamBlockGroupMethod                            {CHOICES aggregate vpn}                               7                    aggregate               _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     {aggregate "AGGREGATE" vpn "VPN"}}
        {traffic_use_single_stream_per_endpoint_pair      Vpn6PeGenParams                 StreamBlockUseSingleStreamNumberPerEndpointPair   {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {traffic_load_percent_provider                    Vpn6PeGenParams                 TrafficLoadPercentFromCorePorts                   NUMERIC                                               7                    10                      0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
        {traffic_load_percent_cust                        Vpn6PeGenParams                 TrafficLoadPercentFromCustomerPorts               NUMERIC                                               7                    10                      0-100                 true             _none_                false           _none_                    {create vpn6pe_config}                     _none_}
     }
    {    emulation_6pe_6vpe_control
        {hname                        stcobj     stcattr           type                      priority          default        range       supported        dependency       mandatory    procfunc       mode       constants}
        {handle                       _none_     _none_            ANY                       2                _none_          _none_      true             _none_           false        _none_         _none_        _none_}
        {port_handle                  _none_     _none_            ANY                       2                _none_          _none_      true             _none_           false        _none_         _none_        _none_}
        {action                       _none_     _none_            {CHOICES start stop}      0                _none_          _none_      true             _none_           true         _none_         _none_        _none_}
    }
    {    emulation_6pe_6vpe_info 
        {hname                       stcobj       stcattr          type                                                  priority        default         range           supported     dependency        mandatory    procfunc        mode               constants}
        {port_handle                 _none_       _none_           ANY                                                   2               _none_          _none_          true          _none_            false        _none_          _none_             _none_}
        {handle                      _none_       _none_           ANY                                                   2               _none_          _none_          true          _none_            false        _none_          _none_             _none_}
        {mode                        _none_       _none_           {CHOICES rsvp|ldp|isis|ospfv2|ospfv3|bgp|rip|bfd|summary} 0           _none_          _none_          true          _none_            true         _none_          _none_             _none_}
    }
}