# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Ancp:: {
}

set ::sth::Ancp::ancpTable {
    ::sth::Ancp::
    {   emulation_ancp_config
        {hname                          stcobj              stcattr                 type                                                                    priority        default         range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {mode                           _none_              _none_                  {CHOICES create enable modify disable enable_all disable_all delete}        0           _none_          _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {port_handle                    _none_              _none_                  ALPHANUM                                                                    2           _none_          _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {handle                         _none_              _none_                  ALPHANUM                                                                    1           _none_          _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {device_count                   Emulateddevice      count                   NUMERIC                                                                     17          1               _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        {session_count                  _none_              _none_                  NUMERIC                                                                     17          1               _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        {encap_type                     _none_              _none_      {CHOICES ETHERNETII LLC_SNAP VC_MUX ATM_LLC_SNAP_ETHERNETII ATM_VC_MUX_ETHERNETII}      0           ETHERNETII      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {vlan_id                        VlanIf_Outer        VlanId                  NUMERIC                                                                     77          _none_          1-4095           TRUE        _none_                  FALSE       _none_                                               _none_                                                                                                         _none_}
        {vlan_id_count                  VlanIf_Outer        VlanId.count            NUMERIC                                                                     77          _none_          1-4095           TRUE        _none_                  FALSE       _none_                                               _none_                                                                                                         _none_}
        {vlan_id_repeat                 VlanIf_Outer        _none_                  NUMERIC                                                                     78          _none_          2-4095           TRUE         _none_                 FALSE    {creat ""}                                              _none_    _none_}
        {vlan_id_step                   VlanIf_Outer        VlanId.step             NUMERIC                                                                     78          _none_          2-4095           TRUE         _none_                 FALSE    {creat ""}                                              _none_    _none_}
        {vlan_id_inner                  VlanIf              VlanId                  NUMERIC                                                                     77          _none_          1-4095           TRUE        _none_                  FALSE       _none_                                               _none_                                                                                                         _none_}
        {vlan_id_count_inner            VlanIf              VlanId.count            NUMERIC                                                                     77          _none_          1-4095           TRUE        _none_                  FALSE       _none_                                               _none_                                                                                                         _none_}
        {vlan_id_repeat_inner           VlanIf              _none_                  NUMERIC                                                                     78          _none_          2-4095           TRUE         _none_                 FALSE    {creat ""}                                              _none_    _none_}
        {vlan_id_step_inner             VlanIf              VlanId.step             NUMERIC                                                                     78          _none_          2-4095           TRUE         _none_                 FALSE    {creat ""}                                              _none_    _none_}
        {local_mac_addr                 EthIIIf             SourceMac               ANY                                                                         27       00:10:94:00:00:01  _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}    
        {local_mac_step                 EthIIIf             SourceMac.step          ANY                                                                         27       00:00:00:00:00:01  _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}       
        {local_mac_repeat               EthIIIf             _none_                  ANY                                                                         27          _none_          _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}       
        {remote_mac_addr                _none_              _none_                  ANY                                                                         27          _none_          _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}    
        {remote_mac_step                _none_              _none_                  ANY                                                                         27          _none_          _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}       
        {remote_mac_repeat              _none_              _none_                  ANY                                                                         27          _none_          _none_           TRUE         _none_                 FALSE    {creat "" }    _none_    _none_}    
        {intf_ip_addr                   Ipv4If              Address                 IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {intf_ip_repeat                 Ipv4If              _none_                 NUMERIC                                                                     85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {intf_ip_step                   Ipv4If              Address.step            IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {intf_ip_prefix_len             Ipv4If              prefixLength             NUMERIC                                                                    17          24              _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {intf_ip_prefix                 _none_              _none_                  NUMERIC                                                                     17          _none_          _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        {gateway_ip_addr                Ipv4If              Gateway                 IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {gateway_ip_repeat              _none_              _none_                  NUMERIC                                                                     85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {gateway_ip_step                Ipv4If              Gateway.step            IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {gateway_ip_prefix_len          _none_              _none_                  NUMERIC                                                                     17          24              _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {gateway_ip_prefix              _none_              _none_                  NUMERIC                                                                     17          _none_          _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_} 
        {sut_ip_addr                    Ipv4NetworkBlock    StartIpList             IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {sut_ip_repeat                  Ipv4NetworkBlock    _none_                  NUMERIC                                                                     85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {sut_ip_step                    Ipv4NetworkBlock    StartIpList.step        IPV4                                                                        85          _none_          _none_          true        _none_                  false       processEmulation_bgp_configIp                       {enable configIpInterface modify configIpInterface}                                                             _none_}
        {sut_ip_prefix_len              Ipv4NetworkBlock    PrefixLength            NUMERIC                                                                     17          24              _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {sut_ip_prefix                  Ipv4NetworkBlock    _none_                  NUMERIC                                                                     17          _none_          _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        
        {ancp_standard          AncpAccessNodeConfig     AncpVersion                {CHOICES ietf-ancp-protocol2  gsmp-l2control-config2 rfc_6320}              0           _none_          _none_          true        _none_                 false        _none_                                              _none_                                                                                                          {ietf-ancp-protocol2 ANCP_DRAFT_02 gsmp-l2control-config2 L2CP_DRAFT_00 rfc_6320 RFC_6320}}
        
        {keep_alive             AncpAccessNodeConfig     AncpKeepAliveTimeout           NUMERIC                                                                 17          _none_          _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        {topology_discovery     AncpAccessNodeConfig     EnableDynamicTopologyDiscovery {CHOICES 0 1}                                                           0           _none_          _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {bulk_transaction       AncpAccessNodeConfig     EnableBulkTransaction          {CHOICES  0 1}                                                          0           _none_          _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {tcp_port               AncpAccessNodeConfig     TcpPort                        NUMERIC                                                                 0           _none_          _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {partition_type         AncpAccessNodeConfig     PartitionType                  {CHOICES NO_PARTITION FIXED_PARTITION_REQUEST FIXED_PARTITION_ASSIGNED} 0           NO_PARTITION    _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {partition_flag         AncpAccessNodeConfig     PartitionFlag                  {CHOICES NEW_ADJACENCY RECOVERED_ADJACENCY}                             0           NEW_ADJACENCY   _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {partition_id           AncpAccessNodeConfig     PartitionId                    NUMERIC                                                                 0           0               _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {code                   AncpAccessNodeConfig     Code                           NUMERIC                                                                 0           0               0-4095          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {vci                            Aal5If              vci                         NUMERIC                                                                 50          _none_          0-65535         true        _none_                  false          _none_                                           _none_                                       _none_}
        {vci_step                       Aal5If              VciStep                     NUMERIC                                                                 51          _none_          0-65535         true        _none_                  false          _none_                                           _none_                                       _none_}
        {vci_count                      _none_              _none_                      NUMERIC                                                                 54          _none_          1-65536         true        _none_                  false          _none_                                           _none_                                       _none_}
        {vpi                            Aal5If              vpi                         NUMERIC                                                                 52          _none_          0-255           true        _none_                  false          _none_                                           _none_                                       _none_}
        {vpi_step                       Aal5If              VpiStep                     NUMERIC                                                                 53          _none_          0-255           true        _none_                  false          _none_                                           _none_                                       _none_}
        {vpi_count                      _none_              _none_                      NUMERIC                                                                 55          _none_          1-256           true        _none_                  false          _none_                                           _none_                                       _none_}
        {pvc_incr_mode                  _none_              _none_                      {CHOICES vci vpi both}                                                  56          _none_          _none_          true        _none_                  false          _none_                                           _none_                                      _none_}
    }
    
    {   emulation_ancp_subscriber_lines_config
        {hname                              stcobj              stcattr             type                                                                    priority    default     range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {mode                               _none_              _none_              {CHOICES create enable modify disable enable_all disable_all delete}    0           _none_      _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {ancp_client_handle                 _none_              _none_              ALPHANUM                                                                2           _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {handle                             _none_              _none_              ALPHANUM                                                                1           _none_      _none_          true        mode                    true       _none_                                              _none_                                                                                                          _none_}
        {subscriber_lines_per_access_node   _none_              _none_              NUMERIC                                                                 17          1           _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {subscriber_protocol                _none_              _none_              {CHOICES ppp|dhcp }                                                     17          _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        {session_count                      _none_              _none_              NUMERIC                                                                 17          1           _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}         
        
        {circuit_id                         AncpTlvConfig       _none_              ANY                                                                     1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {remote_id                          AncpTlvConfig       _none_              ANY                                                                     1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {remote_id_suffix                   AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {remote_id_suffix_step              AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {remote_id_suffix_repeat            AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {circuit_id_suffix                  AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {circuit_id_suffix_step             AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {circuit_id_suffix_repeat           AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {tlv_service_vlan_id                AncpTlvConfig       _none_              ANY                                                                     1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {tlv_service_vlan_id_wildcard       AncpTlvConfig       _none_             {CHOICES 0 | 1}                                                          1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {tlv_customer_vlan_id               AncpTlvConfig       _none_              ANY                                                                     1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {tlv_customer_vlan_id_wildcard      AncpTlvConfig       _none_             {CHOICES 0 | 1}                                                          1           _none_       _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
       
        {vlan_allocation_model              AncpTlvConfig       _none_             {CHOICES 1_1| N_1}                                                       1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {enable_c_vlan                      AncpTlvConfig       _none_             {CHOICES 0 | 1}                                                          1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}        
        
        {customer_vlan_id                   AncpTlvConfig       _none_              NUMERIC                                                                 1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {customer_vlan_id_step              AncpTlvConfig       _none_              NUMERIC                                                                 1             1         _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {customer_vlan_id_repeat            AncpTlvConfig       _none_              NUMERIC                                                                 1             1         _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
          
        {include_encap                      _none_              _none_              {CHOICES 0 1}                                                           0           _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {data_link                          AncpTlvConfig       _none_             {CHOICES ethernet atm_aal5}                                              1           _none_      _none_          false       {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {encap1                             AncpTlvConfig       _none_             {CHOICES na untagged_ethernet single_tagged_ethernet}                    1           _none_      _none_          false       {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {encap2                             AncpTlvConfig       _none_  {CHOICES na  pppoa_llc pppoa_null ipoa_llc ipoa_null aal5_llc_w_fcs aal5_llc_wo_fcs aal5_null_w_fcs aal5_null_wo_fcs}   1   _none_  _none_  false {mode modify} false       _none_                                              _none_                                                                                                          _none_}
        
        {dsl_type                           AncpTlvConfig       _none_             {CHOICES adsl1 adsl2 adsl2_plus vdsl1 vdsl2 sdsl unknown}                1           _none_      _none_          false       {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        
        {actual_rate_upstream               AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {actual_rate_upstream_step          AncpTlvConfig       _none_               NUMERIC                                                                1           0           _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {actual_rate_upstream_repeat        AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        
        {upstream_min_rate                  AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {upstream_max_rate                  AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {upstream_attainable_rate           AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {upstream_min_low_power_rate        AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {upstream_max_interleaving_delay    AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {upstream_act_interleaving_delay    AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        
        {actual_rate_downstream             AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {actual_rate_downstream_step        AncpTlvConfig       _none_               NUMERIC                                                                1           0           _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {actual_rate_downstream_repeat      AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        
        {downstream_min_rate                AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {downstream_max_rate                AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {downstream_attainable_rate         AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {downstream_min_low_power_rate      AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {downstream_max_interleaving_delay  AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
        {downstream_act_interleaving_delay  AncpTlvConfig       _none_               NUMERIC                                                                1           _none_      _none_          true        {mode modify}           false       _none_                                              _none_                                                                                                          _none_}
                                                          
        
        
        
    }
    
    {   emulation_ancp_control
        {hname                          stcobj              stcattr                 type                                                                        priority    default     range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {ancp_handle                    _none_              _none_                  ALPHANUM                                                                    15          _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {ancp_subscriber                _none_              _none_                  ALPHANUM                                                                    15          _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {action_control                 _none_              _none_                  {CHOICES start stop}                                                        20          _none_      _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}       
        {action                         _none_              _none_                  {CHOICES initiate send connect flap flap_start flap_stop}                                                        20          _none_      _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {flap_count                     _none_              _none_                  NUMERIC                                                                    15          _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {subscriber_line_up_time        _none_              _none_                  NUMERIC                                                                    15          _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        {subscriber_line_down_time      _none_              _none_                  NUMERIC                                                                    15          _none_      _none_          true        _none_                  false        _none_                                              _none_                                                                                                          _none_}
        
    }
    {   emulation_ancp_stats
        {hname                          stcobj              stcattr                 type                 priority    default       range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {handle                         _none_              _none_                  ALPHANUM                15       _none_        _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {reset                           _none_              _none_                 {CHOICES 0 1}           20          _none_      _none_          true        _none_                 false        _none_                                              _none_                                                                                                          _none_}
        {rx_adj_syn_pkts               AncpAccessNodeResults    RxSynCount        ANY                       20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {rx_adj_syn_ack_pkts           AncpAccessNodeResults    RxKeepAliveCount        ANY                 20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {rx_adj_ack_pkts               AncpAccessNodeResults    RxAckCount             ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {rx_adj_rst_ack_pkts           AncpAccessNodeResults    RxRstackCount             ANY               20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}             
        {tx_adj_syn_pkts               AncpAccessNodeResults    TxSynCount                ANY               20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {tx_adj_syn_ack_pkts           AncpAccessNodeResults    TxSynackCount             ANY               20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {tx_adj_ack_pkts               AncpAccessNodeResults    TxAckCount                ANY               20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_} 
        {tx_adj_rst_ack_pkts           AncpAccessNodeResults   TxRstackCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}             
        {tx_port_up_count              AncpAccessNodeResults   TxPortUpCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {tx_port_down_count            AncpAccessNodeResults   TxPortDownCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {rx_management_count           AncpAccessNodeResults   RxManagementCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {tx_keepalive_count            AncpAccessNodeResults   TxKeepAliveCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {rx_keepalive_count            AncpAccessNodeResults   RxKeepAliveCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {keepalive_timeout_count       AncpAccessNodeResults   KeepAliveTimeoutCount           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {subscribers_up                AncpAccessNodeResults   SubscribersUp           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}
        {subscribers_down              AncpAccessNodeResults   SubscribersDown           ANY                  20          _none_      _none_          true        _none_                  false       _none_                                              {stats ""}                                                                                                      _none_}    
    }
    
   
}
