

namespace eval ::sth::bfd {
    set bfdTable {
        ::sth::bfd::
        {emulation_bfd_config
            {hname                              stcobj                     stcattr                                   type                                        priority       default         range         supported       dependency                                          mandatory       procfunc                                               mode                                                                         constants}
            {mode                               _none_                      _none_                           {CHOICES create modify enable disable delete}           10          create          _none_          true           _none_                                              true           _none_                                               _none_                                                                         _none_}
            {port_handle                        _none_                      _none_                           ANY                                                     20          _none_          _none_          true           {mandatory {mode create}}                           false          _none_                                               _none_                                                                         _none_}
            {handle                             _none_                      _none_                           ANY                                                     40          _none_          _none_          true           {mandatory {mode modify enable disable delete}}     false          _none_                                               _none_                                                                         _none_}
            {count                              Emulateddevice              count                            NUMERIC                                                 30          1               _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {ip_version                         _none_                      _none_                           {CHOICES IPv4 IPv6}                                     50          IPv4            _none_          true           _none_                                              false          processEmulation_bfd_configIpVersion                 {create configBfdRouter modify configBfdRouter}                                _none_}
            {intf_ip_addr                       Ipv4If                      Address                          IPV4                                                    60          _none_          _none_          true           _none_                                              false          processEmulation_bfd_configIp                        {create configIpInterface modify configIpInterface}                            _none_}
            {intf_ip_addr_step                  Ipv4If                      AddrStep                         IPV4                                                    70          _none_          _none_          true           _none_                                              false          _none_                                               {create configIpInterface modify configIpInterface}                            _none_}
            {intf_ipv6_addr                     Ipv6If                      Address                          IPV6                                                    80          _none_          _none_          true           _none_                                              false          processEmulation_bfd_configIp                        {create configIpInterface modify configIpInterface}                            _none_}
            {intf_ipv6_addr_step                Ipv6If                      AddrStep                         IPV6                                                    90          _none_          _none_          true           _none_                                              false          _none_                                               {create configIpInterface modify configIpInterface}                            _none_}
            {remote_ip_addr                     Ipv4NetworkBlock            StartIpList                      IPV4                                                    100         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configRemoteAddr                {create configIpNetworkBlock modify configIpNetworkBlock}                      _none_}
            {remote_ip_addr_step                Ipv4NetworkBlock            AddrIncrement                    IPV4                                                    110         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configRemoteAddrStep            {create configIpNetworkBlock modify configIpNetworkBlock}                      _none_}
            {remote_ipv6_addr                   Ipv6NetworkBlock            StartIpList                      IPV6                                                    120         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configRemoteAddr                {create configIpNetworkBlock modify configIpNetworkBlock}                      _none_}
            {remote_ipv6_addr_step              Ipv6NetworkBlock            AddrIncrement                    IPV6                                                    130         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configRemoteAddrStep            {create configIpNetworkBlock modify configIpNetworkBlock}                      _none_}
            {local_mac_addr                     EthIIIf                     SourceMac                        ANY                                                     140         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configMacAddr                   {create configEthIIIntf modify configEthIIIntf}                                _none_}
            {local_mac_addr_step                EthIIIf                     SrcMacStep                       ANY                                                     150         _none_          _none_          true           _none_                                              false          _none_                                               {create configEthIIIntf modify configEthIIIntf}                                _none_}
            {vlan_id1                           VlanIf                      VlanId                           NUMERIC                                                 160         _none_          0-4096          true           _none_                                              false          processEmulation_bfd_configVlanId                    {create configVlanIfInner modify configVlanIfInner}                            _none_}
            {vlan_id_mode1                      VlanIf                      VlanId.mode                      {CHOICES fixed increment}                               170         _none_          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {vlan_id_step1                      VlanIf                      IdStep                           NUMERIC                                                 180         _none_          0-4096          true           _none_                                              false          _none_                                               {create configVlanIfInner modify configVlanIfInner}                            _none_}
            {vlan_ether_type1                   VlanIf                      Tpid                             {CHOICES vlan_tag_0x8100 vlan_tag_0x88a8 vlan_tag_0x9100}  190      vlan_tag_0x8100 _none_          true           _none_                                              false          processEmulation_bfd_configvlanType                  {create configVlanIfInner modify configVlanIfInner}                            _none_}             
            {vlan_id2                           VlanIf_Outer                VlanId                           NUMERIC                                                 340         _none_          0-4096          true           _none_                                              false          processEmulation_bfd_configVlanId                    {create configVlanIfOuter modify configVlanIfOuter}                            _none_}
            {vlan_id_mode2                      VlanIf_Outer                VlanId.mode                      {CHOICES fixed increment}                               350         _none_          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {vlan_id_step2                      VlanIf_Outer                IdStep                           NUMERIC                                                 360         _none_          0-4096          true           _none_                                              false          _none_                                               {create configVlanIfOuter modify configVlanIfOuter}                            _none_}
            {vlan_ether_type2                   VlanIf_Outer                Tpid                             {CHOICES vlan_tag_0x8100 vlan_tag_0x88a8 vlan_tag_0x9100}  190      vlan_tag_0x8100 _none_          true           _none)                                              false          processEmulation_bfd_configvlanType                  {create configVlanIfOuter modify configVlanIfOuter}                            _none_}
            {vci                                Aal5If                      vci                              NUMERIC                                                 200         _none_          0-65535         true           _none_                                              false          processEmulation_bfd_configVci                       {create configAtmIf modify configAtmIf}                                        _none_}
            {vci_step                           Aal5If                      vci.step                         NUMERIC                                                 210         _none_          0-65535         true           _none_                                              false          _none_                                                _none_                                                                        _none_}
            {vpi                                Aal5If                      vpi                              NUMERIC                                                 220         _none_          0-255           true           _none_                                              false          processEmulation_bfd_configVpi                       {create configAtmIf modify configAtmIf}                                        _none_}
            {vpi_step                           Aal5If                      vpi.step                         NUMERIC                                                 230         _none_          0-255           true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {gateway_ip_addr                    Ipv4If                      Gateway                          IPV4                                                    240         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configGateWay                   {create configIpInterface modify configIpInterface}                            _none_}
            {gateway_ip_addr_step               Ipv4If                      GatewayStep                      IPV4                                                    250         _none_          _none_          true           _none_                                              false          _none_                                               {create configIpInterface modify configIpInterface}                            _none_}
            {gateway_ipv6_addr                  Ipv6If                      Gateway                          IPV6                                                    260         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configGateWay                   {create configIpInterface modify configIpInterface}                            _none_}
            {gateway_ipv6_addr_step             Ipv6If                      GatewayStep                      IPV6                                                    270         _none_          _none_          true           _none_                                              false          _none_                                               {create configIpInterface modify configIpInterface}                            _none_}
            {session_discriminator    {IPv4 BfdIpv4ControlPlaneIndependentSession IPv6 BfdIpv6ControlPlaneIndependentSession}  
                                                                            MyDiscriminator                  NUMERIC                                                 280         _none_          _none_          true           _none_                                              false          processEmulation_bfd_configSessionDiscriminator      {create configBFDCpiSession modify configBFDCpiSession}                        _none_}
            {session_discriminator_step  {IPv4 BfdIpv4ControlPlaneIndependentSession IPv6 BfdIpv6ControlPlaneIndependentSession}    
                                                                            MyDiscriminatorIncrement         NUMERIC                                                 290         _none_          _none_          true           _none_                                              false          _none_                                               {create configBFDCpiSession modify configBFDCpiSession}                        _none_}
            {detect_multiplier                  BfdRouterConfig             DetectMultiplier                 NUMERIC                                                 310         2               2-100           true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {echo_rx_interval                   BfdRouterConfig             EchoRxInterval                   NUMERIC                                                 320         0               0-10000         true           {mode create modify}                                false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {active_mode                        BfdRouterConfig             RouterRole                       {CHOICES active passive}                                330         active          _none_          true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {control_interval                   _none_                      _none_                           NUMERIC                                                 999         0               _none_          false          {mode create modify}                                false          _none_                                               _none_                                                                         _none_}
            {hop_mode                           _none_                      _none_                           {CHOICES single multi}                                  999         _none_          _none_          false          _none_                                              false          _none_                                               _none_                                                                         _none_}
            {pkts_per_control_interval          _none_                      _none_                           NUMERIC                                                 999         _none_          _none_          false          _none_                                              false          _none_                                               _none_                                                                         _none_}
            {reset                              _none_                      _none_                           ANY                                                     999         _none_          _none_          false          {mode create}                                       false          _none_                                               _none_                                                                         _none_}
            {encap_type                         _none_                      _none_                          {CHOICES ETHERNETII SAP SNAP LLC_SNAP VC/MUX_IP}         999         _none_          _none_          false          _none_                                              false          _none_                                               _none_                                                                         _none_}
            {remote_mac_addr                    _none_                      _none_                          ANY                                                      999         _none_          _none_          false          _none_                                              false          _none_                                               _none_                                                                         _none_}
            {remote_mac_addr_step               _none_                      _none_                          ANY                                                      999         _none_          _none_          false          _none_                                              false          _none_                                               _none_                                                                         _none_}
            {dlci                               _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {remote_discriminator               _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {remote_discriminator_step          _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {control_plane_independent          _none_                      _none_                          {CHOICES 0 1}                                             999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {echo_bit                           _none_                      _none_                          {CHOICES 0 1}                                             999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {echo_timeout                       _none_                      _none_                          NUMERIC                                                   999         _none_         0-10000          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {echo_tx_interval                   _none_                      _none_                          NUMERIC                                                   999         _none_         0-10000          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {flap_tx_interval                   _none_                      _none_                          NUMERIC                                                   999         0               _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {performance_mode                   _none_                      _none_                         {CHOICES scaling small manual}                             999         _none_          _none_          false         _none_                                              false          _none_                                               _none_                                                                         _none_}
            {interval_time_unit                BfdRouterConfig             IntervalTimeUnit                {CHOICES msec usec}                                      330         msec            _none_          true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {scale_mode                        BfdRouterConfig             ScaleMode                       {CHOICES normal gen_tx_no_results gen_tx_rx_results}     330         normal          _none_          true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {use_partial_block_state           BfdRouterConfig             UsePartialBlockState            {CHOICES 0 1}                                            330         0               _none_          true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {rx_interval                       BfdRouterConfig             RxInterval                       NUMERIC                                                 310         50              _none_           true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {tx_interval                       BfdRouterConfig             TxInterval                       NUMERIC                                                 310         50              _none_           true           _none_                                              false          _none_                                               {create configBfdRouter modify configBfdRouter}                                _none_}
            {bfd_cc_channel_type               BfdGlobalConfig             BfdCcChannelType                 ANY                                                 310         34              _none_           true           _none_                                              false          _none_                                               _none_                                _none_}
            {bfd_cv_channel_type               BfdGlobalConfig             BfdCvChannelType                 ANY                                                 310         35              _none_           true           _none_                                              false          _none_                                               _none_                                _none_}
            {router_id                         Router                      RouterId                        IPV4                                                    60          192.0.0.1        _none_          true           _none_                                              false          _none_                                               {create configRouter modify configRouter}                            _none_}
            {router_id_step                    Router                      RouterIdStep	                   IPV4                                                    70          0.0.0.1        _none_          true           _none_                                              false          _none_                                               {create configRouter modify configRouter}                            _none_}
            {ipv6_router_id                    Router                      Ipv6RouterId                    IPV6                                                    80          2000::1          _none_          true           _none_                                              false          _none_                                               {create configRouter modify configRouter}                            _none_}
            {ipv6_router_id_step               Router                      Ipv6RouterIdStep                IPV6                                                    90          0000::1          _none_          true           _none_                                              false          _none_                                               {create configRouter modify configRouter}                            _none_}
           
        }
        {emulation_bfd_control
            {hname                              stcobj                     stcattr                         type                                                 priority      default         range       supported                       dependency                         mandatory                   procfunc                                         mode                                                                            constants}
            {handle                             _none_                      _none_                         ANY                                                        10          _none_          _none_          true                            _none_                           false                      _none_                                          _none_                                                                          _none_}
            {mode                               _none_                      _none_  {CHOICES start stop flap stop_pdus resume_pdus admin_up admin_down enable_demand disable_demand initiate_poll}              20          _none_          _none_          true                            _none_                           true                       _none_                                          _none_                                                                          _none_}
            {port_handle                        _none_                      _none_                         ANY                                                        30          _none_          _none_          true                            _none_                           false                      _none_                                          _none_                                                                          _none_}
            {flap_count                         _none_                      _none_                         NUMERIC                                                    40          5               _none_          true                          {mode flap}                        false                      _none_                                          _none_                                                                          _none_}
            {flap_interval                      _none_                      _none_                         NUMERIC                                                    50          _none_          _none_          true                          {mode flap}                        false                      _none_                                          _none_                                                                          _none_}
        }
        {emulation_bfd_info
            {hname                              stcobj                      stcattr                            type                                                 priority      default         range       supported                       dependency                          mandatory                 procfunc                                          mode                                                                            constants}
            {handle                             _none_                      _none_                          ANY                                                       10          _none_          _none_          true                            _none_                            false                     _none_                                          _none_                                                                          _none_}
            {mode                               _none_                      _none_                          {CHOICES aggregate_stats learned_info clear_stats bfd_stats mpls_stats}        20          _none_          _none_          true                            _none_                            true                      _none_                                          _none_                                                                          _none_}
            {port_handle                        _none_                      _none_                          ANY                                                       30          _none_          _none_          true                            _none_                            false                     _none_                                          _none_                                                                          _none_}
            {flap_count                         BfdRouterResults            FlapCount                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {rx_count                           BfdRouterResults            RxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {timeout_count                      BfdRouterResults            TimeoutCount                    NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {tx_count                           BfdRouterResults            txCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {packet_rx                          BfdRouterResults            RxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {packet_dr                          _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {poll_rx                            _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {final_rx                           _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {echo_rx                            _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {avg_intr_arriv                     _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {min_intr_arriv {IPv4 BfdIpv4SessionResults IPv6 BfdIpv6SessionResults}  RxDesiredMinRxInterval   NUMERIC                                                 60          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {max_intr_arriv                     _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {packet_tx                          BfdRouterResults            TxCount                         NUMERIC                                                   40          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {poll_tx                            _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {final_tx                           _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {echo_tx                            _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {avg_intr_dept                      _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {min_intr_dept                      _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {max_intr_dept                      _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {to_down_state                      BfdRouterConfig             SessionsDownCount               NUMERIC                                                   70          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {to_admin_down_state                _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {to_init_state                      _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {to_up_state                        BfdRouterConfig             SessionsUpCount                 NUMERIC                                                   80          _none_          _none_          true                            _none_                            false                     _none_                                      {learned_info ""}                                                                   _none_}
            {routers_configured                 _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {routers_running                    _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {control_pkts_tx                    _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {control_pkts_tx                    _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {echo_self_pkts_rx                  _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {echo_self_pkts_tx                  _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {echo_dut_pkts_tx                   _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {echo_dut_pkts_rx                   _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {sessions_configured                _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {sessions_auto_created              _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {sessions_configured_up             _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
            {sessions_auto_created_up           _none_                      _none_                          NUMERIC                                                   999         _none_          _none_          false                           _none_                            false                     _none_                                     {aggregate_stats ""}                                                                 _none_}
        }
        
        {emulation_bfd_info_bfd_stats
            {hname                              stcobj                      stcattr                            type                                                 priority      default         range       supported                       dependency                          mandatory                 procfunc                                       mode                                                                 constants}
            {flap_count                         BfdRouterResults            FlapCount                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_count                           BfdRouterResults            RxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {timeout_count                      BfdRouterResults            TimeoutCount                    NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_count                           BfdRouterResults            TxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {session_up_count                   BfdRouterConfig             SessionsUpCount                 NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {session_down_count                 BfdRouterConfig             SessionsDownCount               NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
        }
        {emulation_bfd_info_mpls_stats
            {hname                              stcobj                      stcattr                          type                                                 priority      default         range       supported                       dependency                          mandatory                 procfunc                                       mode                                                                 constants}
            {bfd_control_bits                   BfdMplsSessionResults       BfdControlBits                  NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {bfd_diagnostic_code                BfdMplsSessionResults       BfdDiagnosticCode               NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {bfd_session_state                  BfdMplsSessionResults       BfdSessionState                 NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {fec_info                           BfdMplsSessionResults       FecInfo                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {flap_count                         BfdMplsSessionResults       FlapCount                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {last_bfd_diagnostic_error_rx       BfdMplsSessionResults       LastBfdDiagnosticErrorRx        NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {my_discriminator                   BfdMplsSessionResults       MyDiscriminator                 NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_avg_rate                        BfdMplsSessionResults       RxAvgRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_count                           BfdMplsSessionResults       RxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_desired_min_rx_interval         BfdMplsSessionResults       RxDesiredMinRxInterval          NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_max_rate                        BfdMplsSessionResults       RxMaxRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_min_rate                        BfdMplsSessionResults       RxMinRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {rx_req_min_echo_rx_interval        BfdMplsSessionResults       RxReqMinEchoRxInterval          NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {timeout_count                      BfdMplsSessionResults       TimeoutCount                    NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_avg_rate                        BfdMplsSessionResults       TxAvgRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_count                           BfdMplsSessionResults       TxCount                         NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_interval                        BfdMplsSessionResults       TxInterval                      NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_max_rate                        BfdMplsSessionResults       TxMaxRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {tx_min_rate                        BfdMplsSessionResults       TxMinRate                       NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
            {your_discriminator                 BfdMplsSessionResults       YourDiscriminator               NUMERIC                                                   50          _none_          _none_          true                            _none_                            false                     _none_                                      _none_                                                                   _none_}
        }
        {emulation_bfd_session_config
            {hname                              stcobj                     stcattr                                   type                                        priority       default         range         supported       dependency                                          mandatory       procfunc                                               mode                                                                         constants}
            {mode                               _none_                      _none_                           {CHOICES create modify delete}                          10          create          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {ipv4_handle                        _none_                      _none_                           ANY                                                     40          _none_          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {ipv6_handle                        _none_                      _none_                           ANY                                                     40          _none_          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {bfd_handle                         _none_                      _none_                           ANY                                                     40          _none_          _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {ip_version                         _none_                      _none_                           {CHOICES IPv4 IPv6 IPv46}                               50          IPv4            _none_          true           _none_                                              false          _none_                                               _none_                                                                         _none_}
            {ipv4_enable_my_discriminator       BfdIpv4ControlPlaneIndependentSession  EnableMyDiscriminator {CHOICES 0 1}                                           60          0               _none_          true           _none_                                              false          _none_                                               {create configBfdsession modify configBfdsession}                              _none_}
            {ipv4_my_discriminator              BfdIpv4ControlPlaneIndependentSession  MyDiscriminator        ANY                                                    70          1               _none_          true           _none_                                              false          _none_                                               {create configBfdsession modify configBfdsession}                              _none_}
            {ipv4_my_discriminator_incr         BfdIpv4ControlPlaneIndependentSession  MyDiscriminatorIncrement ANY                                                  80          1               _none_          true           _none_                                              false          _none_                                               {create configBfdsession modify configBfdsession}                              _none_}
            {ipv4_addr_incr                     Ipv4NetworkBlock            AddrIncrement                      ANY                                                   90          1               _none_          true           _none_                                              false          _none_                                               {create configIpNetworkBlock4 modify configIpNetworkBlock4}                      _none_}
            {ipv4_network_count                 Ipv4NetworkBlock            NetworkCount                       ANY                                                   100         24              0-32            true           _none_                                              false          _none_                                               {create configIpNetworkBlock4 modify configIpNetworkBlock4}                      _none_}
            {ipv4_prefix_length                 Ipv4NetworkBlock            PrefixLength                       ANY                                                   110         192.0.1.0       _none_          true           _none_                                              false          _none_                                               {create configIpNetworkBlock4 modify configIpNetworkBlock4}                      _none_}
            {ipv4_start_ip_list                 Ipv4NetworkBlock            StartIpList                        ANY                                                   110         _none_          _none_          true           _none_                                              false          _none_                                               {create configIpNetworkBlock4 modify configIpNetworkBlock4}                      _none_}
            {ipv6_enable_my_discriminator       BfdIpv6ControlPlaneIndependentSession  EnableMyDiscriminator   {CHOICES 0 1}                                         330         0               _none_          true           _none_                                              false          _none_                                               {create configBfdsession6 modify configBfdsession6}                            _none_}
            {ipv6_my_discriminator              BfdIpv6ControlPlaneIndependentSession  MyDiscriminator         ANY                                                   330         1               _none_          true           _none_                                              false          _none_                                               {create configBfdsession6 modify configBfdsession6}                            _none_}
            {ipv6_my_discriminator_incr         BfdIpv6ControlPlaneIndependentSession  MyDiscriminatorIncrement ANY                                                  310         1               _none_           true           _none_                                             false          _none_                                              {create configBfdsession6 modify configBfdsession6}                            _none_}
            {ipv6_addr_incr                     Ipv6NetworkBlock             AddrIncrement                     ANY                                                   310         1               _none_           true           _none_                                             false          _none_                                              {create configIpNetworkBlock6 modify configIpNetworkBlock6}                    _none_}
            {ipv6_network_count                 Ipv6NetworkBlock             NetworkCount                      ANY                                                   310         1               0-128           true           _none_                                              false          _none_                                               {create configIpNetworkBlock6 modify configIpNetworkBlock6}                    _none_}
            {ipv6_prefix_length                 Ipv6NetworkBlock             PrefixLength                      ANY                                                   310         64              _none_           true           _none_                                             false          _none_                                              {create configIpNetworkBlock6 modify configIpNetworkBlock6}                    _none_}            
            {ipv6_start_ip_list                 Ipv6NetworkBlock             StartIpList                       ANY                                                   310         2000::1         _none_           true           _none_                                             false          _none_                                              {create configIpNetworkBlock6 modify configIpNetworkBlock6}                    _none_}            
       
        }
        
        
    }
}
