namespace eval ::sth::convergence:: {
}

set ::sth::convergence::convergenceTable {
 ::sth::convergence::
 { emulation_convergence_config
    {hname                                  stcobj              stcattr                       type                                                  priority        default         range           supported       dependency                  mandatory       procfunc                mode                                   constants}
    {handle                                 _none_              _none_                      ALPHANUM                                                    1           _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {mode                                   _none_              _none_                      {CHOICES create modify delete}                              1           _none_          _none_              true        _none_                      true            _none_                  _none_                                  _none_}
    {convergence_proto                  ConvergenceConfig       TestType                    {CHOICES bfd ospfv2 ospfv3 isis bgp}                        10          _none_          _none_              true        _none_                      true           _none_  {create configconvergence modify configconvergence}     {bfd BfdConvergence ospfv2 OSPFv2Convergence ospfv3 OSPFv3Convergence isis ISISConvergence bgp BGPConvergence}}
    {load_test                          ConvergenceConfig       LoadTest                    {CHOICES true false}                                        10          false           _none_              true        _none_                      false           _none_  {create configconvergence modify configconvergence}     _none_}
    {stream_convergence_threshold       ConvergenceConfig       StreamConvergenceThreshold  NUMERIC                                                     10          10              0-4294967295        true        _none_                      false           _none_  {create configconvergence modify configconvergence}     _none_}
    {selected_stream_block              ConvergencePathConfig   StreamHandle                ALPHANUM                                                    20          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {primary_router                         _none_              _none_                      ALPHANUM                                                    20          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {backup_router                          _none_              _none_                      ALPHANUM                                                    20          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}    
 }
 { emulation_convergence_control
    {hname                                  stcobj              stcattr                       type                                                  priority        default         range           supported       dependency                  mandatory       procfunc                mode                                   constants}
    {handle                                 _none_              _none_                      ALPHANUM                                                    1           _none_          _none_              true        _none_                      true            _none_                  _none_                                  _none_}
    {mode                                   _none_              _none_                      {CHOICES setup collector reset}                             1           _none_          _none_              true        _none_                      true            _none_                  _none_                                  _none_}
    {test_type                              _none_              _none_                      {CHOICES convergence load reversion}                        10          convergence     _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {mismatch_warning                       _none_              _none_                      {CHOICES true false}                                        10          true            _none_              true        {mode collector}            false           _none_                  _none_                                  _none_}
    {timeout                                _none_              _none_                      NUMERIC                                                     10          _none_          10-600              true        _none_                      false           _none_                  _none_                                  _none_}
 }
 { emulation_convergence_info
    {hname                                  stcobj              stcattr                       type                                                  priority        default         range           supported       dependency                  mandatory       procfunc                mode                                   constants}
    {handle                                 _none_              _none_                      ALPHANUM                                                    1           _none_          _none_              true        _none_                      true            _none_                  _none_                                  _none_}
    {mode                                   _none_              _none_                      {CHOICES stats}                                             1           _none_          _none_              true        _none_                      true            _none_                  _none_                                  _none_}
    {avg_convergence_time               EventConfigResult       AvgConvergenceTime          _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {avg_reversion_convergence_time     EventConfigResult       AvgReversionConvergenceTime _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {converged_streams                  EventConfigResult       ConvergedStreams            _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {convergence_time                   EventConfigResult       ConvergenceTime             _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {expected_streams                   EventConfigResult       ExpectedStreams             _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {first_event_timestamp              EventConfigResult       FirstEventTimestamp         _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {first_event_timestamp_reversion    EventConfigResult       FirstEventTimestampInReversion                      _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {packet_timestamp_first_stream      EventConfigResult       FirstPacketTimestampOnFirstStream                   _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {traffic_timestamp_first_stream_reversion   EventConfigResult   FirstPacketTimestampOnFirstStreamInReversion    _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {packet_timestamp_last_stream       EventConfigResult       FirstPacketTimestampOnLastStream                    _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {traffic_timestamp_last_stream_reversion    EventConfigResult   FirstPacketTimestampOnLastStreamInReversion     _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {last_event_timestamp               EventConfigResult       LastEventTimestamp          _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {last_event_timestamp_reversion     EventConfigResult       LastEventTimestampInReversion                       _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {max_convergence_time               EventConfigResult       MaxConvergenceTime          _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {max_reversion_convergence_time     EventConfigResult       MaxReversionConvergenceTime _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {min_convergence_time               EventConfigResult       MinConvergenceTime          _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {min_reversion_convergence_time     EventConfigResult       MinReversionConvergenceTime _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {non_converged_streams              EventConfigResult       NonConvergedStreams         _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {primary_streams                    EventConfigResult       PrimaryStreams              _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {reversion_convergence_time         EventConfigResult       ReversionConvergenceTime    _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {streams_exceeding_threshold        EventConfigResult       StreamsExceedingThresholdCount                      _none_                          _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
    {unexpected_converged_streams       EventConfigResult       UnexpectedConvergedStreams  _none_                                                  _none_          _none_          _none_              true        _none_                      false           _none_                  _none_                                  _none_}
 } 
}
