namespace eval ::sth::device:: {
}
set ::sth::device::deviceTable {
    ::sth::device::
    {emulation_device_config
        {hname                          stcobj                  stcattr                         type                                                priority        default     range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {port_handle                    _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {handle                         _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {mode                           _none_                  _none_                      {CHOICES create modify delete}                          3               _none_      _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {count                          EmulatedDevice          devicecount                           NUMERIC                                       3               1           _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {router_id                      EmulatedDevice          RouterId                        IPV4                                                3               192.0.0.1      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {router_id_step                 EmulatedDevice          RouterIdStep                    IPV4                                                3               0.0.0.1      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {router_id_ipv6                 EmulatedDevice          Ipv6RouterId                          IPV6                                          3               2000::1      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {router_id_ipv6_step            EmulatedDevice          Ipv6RouterIdStep                      IPV6                                          3               0000::1      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {enable_ping_response           EmulatedDevice          EnablePingResponse          {CHOICES 0 1}                                           3               0          _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                          {1 TRUE 0 FALSE}}
        {ip_version                     _none_                  _none_                      {CHOICES ipv4 ipv6 ipv46 none}                          4               ipv4        _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {intf_ip_addr                   Ipv4If                  Address                         IPV4                                                4               192.85.1.3  _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_ip_addr_step              Ipv4If                  AddrStep                        IPV4                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {ip_stack_count                 Ipv4If                  IfCountPerLowerIf               NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {stack_ip_repeat                Ipv4If                  AddrRepeatCount                 NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {stack_ip_recycle_count         Ipv4If                  IfRecycleCount                  NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {gateway_ip_addr                Ipv4If                  Gateway                         IPV4                                                4               192.85.1.1      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {gateway_ip_addr_step           Ipv4If                  GatewayStep                     IPV4                                                4               0.0.0.0      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_prefix_len                Ipv4If                  PrefixLength                    NUMERIC                                             4               24      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {tos                            Ipv4If                  Tos                             NUMERIC                                             4               192      0-255          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {tos_type                        Ipv4If                 TosType                         {CHOICES tos diffserv}                              4               tos      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_ipv6_addr                 Ipv6If                  Address                         IPV6                                                4               2000::2      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {ipv6_stack_count               Ipv6If                  IfCountPerLowerIf               NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {stack_ipv6_repeat              Ipv6If                  AddrRepeatCount                 NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {stack_ipv6_recycle_count       Ipv6If                  IfRecycleCount                  NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {resolve_gateway_mac            Ipv4If                  ResolveGatewayMac             {CHOICES true false}                                  4               true      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   {true TRUE false FALSE}}
        {ipv6_resolve_gateway_mac       Ipv6If                  ResolveGatewayMac             {CHOICES true false}                                  4               true      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   {true TRUE false FALSE}}
        {gateway_mac                    Ipv4If                  GatewayMac                      ANY                                                 4               00:00:01:00:00:01      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {ipv6_gateway_mac               Ipv6If                  GatewayMac                      ANY                                                 4               00:00:01:00:00:01      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {intf_ipv6_addr_step            Ipv6If                  AddrStep                        IPV6                                                4               0000::1      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {intf_ipv6_prefix_len           Ipv6If                  PrefixLength                    NUMERIC                                             4               64      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {gateway_ipv6_addr              Ipv6If                  Gateway                         IPV6                                                4               ::0      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {gateway_ipv6_addr_step         Ipv6If                  GatewayStep                     IPV6                                                4               0000::0000      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {traffic_class                  Ipv6If                  TrafficClass                     NUMERIC                                                4               0      0-255          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {enable_gw_learning             Ipv6If                  EnableGatewayLearning           {CHOICES true false}                                4              false      _none_         true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {link_local_ipv6_addr           Ipv6If_Link_Local       Address                         IPV6                                                14              fe80::1     _none_          true        _none_                  false       _none_                                              {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {link_local_ipv6_addr_step      Ipv6If_Link_Local       AddrStep                        IPV6                                                15              ::1         _none_          true        _none_                  false       _none_                                              {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {link_local_ipv6_prefix_len     Ipv6If_Link_Local       PrefixLength                    NUMERIC                                             16              128         1-128           true        _none_                  false       _none_                                              {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {mac_addr                       EthIIIf                 SourceMac                          ANY                                              4            00:10:94:00:00:02      _none_          true        _none_                  false       _none_                                              {create configEthIIIntf modify configEthIIIntf}                                                                 _none_}
        {mac_addr_step                  EthIIIf                 SrcMacStep                      ANY                                                 4               00:00:00:00:00:01      _none_          true        _none_                  false       _none_                                              {create configEthIIIntf modify configEthIIIntf}                                                                 _none_}
        {use_default_phy_mac            EthIIIf                 UseDefaultPhyMac                {CHOICES true false}                                              4            false      _none_          true        _none_                  false       _none_                                              {create configEthIIIntf modify configEthIIIntf}                                                                 _none_}
        {qinq_incr_mode                 _none_                  _none_                     {CHOICES inner both outer}                               4               inner       _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {encapsulation                  _none_                  _none_                     {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq ethernet_ii_mvlan}  4           ethernet_ii     _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {vlan_id                        VlanIf                  VlanId                          NUMERIC                                             4               100         _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_id_step                   VlanIf                  IdStep                          NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_id_count                  VlanIf                  IfRecycleCount                  NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}        
        {vlan_user_pri                  VlanIf                  Priority                        NUMERIC                                             4               7            0-7             true        _none_                  false       _none_                                             {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_id_repeat_count           VlanIf                  IdRepeatCount                   NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}        
        {vlan_tpid                      VlanIf                  tpid                            NUMERIC                                             4             33024       0-65535          true        _none_                  false       _none_                                                  {create configVlanIfInner modify configVlanIfInner}                                                                   _none_} 
        {vlan_cfi                       VlanIf                  Cfi                             NUMERIC                                             4               0            0-1            true        _none_                  false       _none_                                                  {create configVlanIfInner modify configVlanIfInner}                                                          _none_} 
        {vlan_outer_id                  VlanIf_Outer            VlanId                          NUMERIC                                             4               100         _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_id_step             VlanIf_Outer            IdStep                          NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_id_count            VlanIf_Outer            IfRecycleCount                  NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}        
        {vlan_outer_user_pri            VlanIf_Outer            Priority                        NUMERIC                                             4               7           0-7             true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_id_repeat_count     VlanIf_Outer            IdRepeatCount                   NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}        
        {vlan_outer_tpid                VlanIf_Outer            tpid                            NUMERIC                                             4             33024       0-65535           true        _none_                  false       _none_                                                  {create configVlanIfOuter modify configVlanIfOuter}                                                          _none_} 
        {vlan_outer_cfi                 VlanIf_Outer            Cfi                             NUMERIC                                             4               0            0-1            true        _none_                  false       _none_                                                  {create configVlanIfInner modify configVlanIfInner}                                                          _none_} 
        {vlan_id_list                   VlanIf_List             VlanId                          NUMERIC                                             4               100         _none_          true        _none_                  false       _none_                                              {create configVlanIfMultiple modify configVlanIfMultiple}                                                             _none_}
        {vlan_id_step_list              VlanIf_List             IdStep                          NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfMultiple modify configVlanIfMultiple}                                                             _none_}
        {vlan_id_count_list             VlanIf_List             IfRecycleCount                  NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfMultiple modify configVlanIfMultiple}                                                             _none_}        
        {vlan_user_pri_list             VlanIf_List             Priority                        NUMERIC                                             4               7            0-7             true        _none_                  false       _none_                                             {create configVlanIfMultiple modify configVlanIfMultiple}                                                             _none_}
        {vlan_id_repeat_count_list      VlanIf_List             IdRepeatCount                   NUMERIC                                             4               0           _none_          true        _none_                  false       _none_                                              {create configVlanIfMultiple modify configVlanIfMultiple}                                                             _none_}        
        {vlan_tpid_list                 VlanIf_List             tpid                            NUMERIC                                             4             33024       0-65535          true        _none_                  false       _none_                                                  {create configVlanIfMultiple modify configVlanIfMultiple}                                                                   _none_}
        {vlan_cfi_list                  VlanIf_List             Cfi                             NUMERIC                                             4               0            0-1            true        _none_                  false       _none_                                              {create configVlanIfMultiple modify configVlanIfMultiple}                                                          _none_}
        {expand                     _none_              _none_                  {CHOICES true false}                                       3               1           _none_          true        _none_                  false       _none_                                             _none_     _none_    }
        {block_mode                 _none_              _none_          {CHOICES ONE_HOST_PER_BLOCK ONE_DEVICE_PER_BLOCK ONE_NETWORK_PER_BLOCK MULTIPLE_NETWORKS_PER_BLOCK MULTIPLE_DEVICE_PER_BLOCK}        3          ONE_DEVICE_PER_BLOCK          _none_      true         _none_        false              _none_                                             _none_     _none_    }
    }
}
