# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Dhcpv6:: {
}

set ::sth::Dhcpv6::dhcpv6Table {
 ::sth::Dhcpv6::
 { emulation_dhcpv6_config
    { hname                             stcobj              stcattr                     type                        priority       default     range        supported   dependency                  mandatory   procfunc                         mode                                                                          constants}
    { port_handle                      _none_              _none_                      ALPHANUM                        1           _none_      0-MAX_INT       true        _none_                      false       _none_                        _none_                                                                        _none_}
    { mode                             _none_              _none_                      {CHOICES enable create modify reset}   2    _none_      _none_          true        _none_                      true        _none_                        _none_                                                                        _none_} 
    { handle                           _none_              _none_                      ALPHANUM                        1           _none_      _none_          true        _none_                      false       _none_                        _none_                                                                        _none_}
    { ip_version                       _none_              _none_                      {CHOICES 4 6}                   2           4           _none_          true        _none_                      false       _none_                        _none_                                                                        _none_}
    { dhcp6_reb_max_rt                 Dhcpv6PortConfig    MaxRebindRetryTimeout       NUMERIC                         3           600         1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_reb_timeout                Dhcpv6PortConfig    RebindTimeout               NUMERIC                         3           10          1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_rel_max_rc                 Dhcpv6PortConfig    ReleaseRetryCount           NUMERIC                         3           5           1-32            true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_rel_timeout                Dhcpv6PortConfig    ReleaseTimeout              NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_ren_max_rt                 Dhcpv6PortConfig    MaxRenewRetryTimeout        NUMERIC                         3           600         1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_ren_timeout                Dhcpv6PortConfig    RenewTimeout                NUMERIC                         3           10          1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_req_max_rc                 Dhcpv6PortConfig    RequestRetryCount           NUMERIC                         3           10          1-32            true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_req_max_rt                 Dhcpv6PortConfig    MaxRequestRetryTimeout      NUMERIC                         3           30          1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_req_timeout                Dhcpv6PortConfig    RequestTimeout              NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_sol_max_rc                 Dhcpv6PortConfig    SolicitRetryCount           NUMERIC                         3           10          1-32            true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_sol_max_rt                 Dhcpv6PortConfig    MaxSolicitRetryTimeout      NUMERIC                         3           120         1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_sol_timeout                Dhcpv6PortConfig    SolicitTimeout              NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_outstanding_session_count  Dhcpv6PortConfig    OutstandingSessionCount     NUMERIC                         3           1           1-65535         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_release_rate               Dhcpv6PortConfig    ReleaseRate                 NUMERIC                         3           100         1-1000          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_request_rate               Dhcpv6PortConfig    RequestRate                 NUMERIC                         3           100         1-1000          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_renew_rate                 Dhcpv6PortConfig    RenewRate                   NUMERIC                         3           100         1-1000          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_sequence_type              Dhcpv6PortConfig    SeqType                     {CHOICES PARALLEL SEQUENTIAL}   3           SEQUENTIAL  _none_          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_indef_rel_rt               Dhcpv6PortConfig    IndefReleaseRetry           {CHOICES true false}            3           false       _none_          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_indef_req_rt               Dhcpv6PortConfig    IndefRequestRetry           {CHOICES true false}            3           false       _none_          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_indef_sol_rt               Dhcpv6PortConfig    IndefSolicitRetry           {CHOICES true false}            3           false       _none_          true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_dec_max_rc                 Dhcpv6PortConfig    DeclineRetryCount           NUMERIC                         3           5           1-32            true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_dec_timeout                Dhcpv6PortConfig    DeclineTimeout              NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_inforeq_max_rt             Dhcpv6PortConfig    MaxInfoRequestTimeout       NUMERIC                         3           120         1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_inforeq_timeout            Dhcpv6PortConfig    InfoRequestTimeout          NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_cfm_duration               Dhcpv6PortConfig    MaxConfirmDuration          NUMERIC                         3           10          1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_cfm_max_rt                 Dhcpv6PortConfig    MaxConfirmTimeout           NUMERIC                         3           4           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
    { dhcp6_cfm_timeout                Dhcpv6PortConfig    ConfirmTimeout              NUMERIC                         3           1           1-99999         true        _none_                      false       _none_                        {create configDhcpv6PortConfig modify configDhcpv6PortConfig}                 _none_}
 }                                
 { emulation_dhcpv6_group_config  
    { hname                                  stcobj              stcattr                          type                                                           priority                default                                 range         supported       dependency          mandatory   procfunc                                            mode                                       constants}
    { handle                                 _none_              _none_                           ALPHANUM                                                         1                      _none_                                 _none_          true            _none_              true        _none_                        _none_                                                          _none_}
    { mode                                   _none_              _none_                           {CHOICES enable create modify reset}                             2                      _none_                                 _none_          true            _none_              true        _none_                        _none_                                                          _none_}
    { encap                                  _none_              _none_                           {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}          3                      ethernet_ii                            _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { num_sessions                           EmulatedDevice      DeviceCount                      NUMERIC                                                          4                      _none_                                 _none_          true            _none_              false       _none_                        _none_                                                          _none_} 
    { device_name                            _none_              _none_                           ANY                                                              6                      _none_                                 _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { mac_addr                               EthIIIf             SourceMac                        ANY                                                              6                      00:10:94:00:00:02                      _none_          true            _none_              false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { mac_addr_step                          EthIIIf             SrcMacStep                       ANY                                                              7                      00:00:00:00:00:01                      _none_          true            _none_              false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { local_ipv6_addr                        Ipv6If              Address                          IPV6                                                             4                      2000::2                                _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_addr_step                   Ipv6If              AddrStep                         IPV6                                                             4                       ::1                                  _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_prefix_len                  Ipv6If              PrefixLength                     NUMERIC                                                          4                       64                                   0-128           true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr                      Ipv6If              Gateway                          IPV6                                                             4                       ::0                                 _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr_step                 Ipv6If              GatewayStep                      IPV6                                                             4                       ::                                    _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { qinq_incr_mode                         _none_              _none_                          {CHOICES inner outer both}                                        4                      _none_                                 _none_          true            _none_              false       _none_                         _none_                                                         _none_}
    { vlan_id                                VlanIf              VlanId                           NUMERIC                                                          5                       100                                   0-4095          true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     processConfigCmd_vlanId       {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_id_step                           VlanIf              IdStep                           NUMERIC                                                          5                        1                                    0-4095          true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_id_count                          VlanIf              _none_                           NUMERIC                                                          5                        1                                    1-4096          true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        _none_                                                   _none_}
    { vlan_id_mode                           _none_              _none_                          {CHOICES fixed increment}                                         5                      _none_                                 _none_          true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        _none_                                                   _none_}
    { vlan_user_priority                     VlanIf              Priority                         NUMERIC                                                          5                        0                                    0-7             true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_cfi                               VlanIf              Cfi                             {CHOICES 0 1}                                                     5                        1                                    _none_          true      {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                         {create configVlanIfInner modify configVlanIfInner}      _none_}  
    { vlan_id_outer                          VlanIf_Outer        VlanId                           NUMERIC                                                          5                       100                                   0-4095          true        {{encap ethernet_ii_qinq}}      false                       processConfigCmd_vlanId       {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_id_outer_step                     VlanIf_Outer        IdStep                           NUMERIC                                                          5                        1                                    0-4095          true        {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_id_outer_count                    VlanIf_Outer        _none_                           NUMERIC                                                          5                        1                                    1-4096          true        {{encap ethernet_ii_qinq}}      false                       _none_                        _none_                                                   _none_}
    { vlan_id_outer_mode                     _none_              _none_                          {CHOICES fixed increment}                                         5                      _none_                                 _none_          true        {{encap ethernet_ii_qinq}}      false                       _none_                        _none_                                                   _none_}
    { vlan_outer_user_priority               VlanIf_Outer        Priority                         NUMERIC                                                          5                        0                                    0-7             true        {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_outer_cfi                         VlanIf_Outer        Cfi                             {CHOICES 0 1}                                                     5                        1                                    _none_          true        {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { dhcp_range_ip_type                     _none_              _none_                           {CHOICES 4 6}                                                    2                      4                                      _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { dhcp6_client_mode                      Dhcpv6BlockConfig   Dhcpv6ClientMode                 {CHOICES DHCPPD DHCPV6 DHCPV6ANDPD}                              2                      _none_                                 _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_duid_enterprise_id         Dhcpv6BlockConfig   DuidEnterprise                   NUMERIC                                                          4                      3456                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_duid_vendor_id             Dhcpv6BlockConfig   DuidStart                        NUMERIC                                                          5                      1                                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_duid_vendor_id_increment   Dhcpv6BlockConfig   DuidStep                         NUMERIC                                                          6                      1                                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_duid_type                  Dhcpv6BlockConfig   DuidType                         {CHOICES CUSTOM EN LL LLT}                                       6                      LLT                                    _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_ia_t1                      Dhcpv6BlockConfig   T1Timer                          NUMERIC                                                          5                      302400                                 _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_range_ia_t2                      Dhcpv6BlockConfig   T2Timer                          NUMERIC                                                          6                      483840                                 _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { control_plane_prefix                   Dhcpv6BlockConfig   ControlPlanePrefix               {CHOICES LINKLOCAL ROUTERADVERTISEMENT}                          5                      LINKLOCAL                              _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dst_addr_type                          Dhcpv6BlockConfig   DstAddrType                      {CHOICES ALL_DHCP_RELAY_AGENTS_AND_SERVERS ALL_DHCP_SERVERS}     6                      ALL_DHCP_RELAY_AGENTS_AND_SERVERS      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { duid_value                             Dhcpv6BlockConfig   DuidValue                        NUMERIC                                                          6                      1                                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_ldra                            Dhcpv6BlockConfig   EnableLdra                       {CHOICES true false}                                             5                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_rebind                          Dhcpv6BlockConfig   EnableRebind                     {CHOICES true false}                                             6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_reconfig_accept                 Dhcpv6BlockConfig   EnableReconfigAccept             {CHOICES true false}                                             6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_relay_agent                     Dhcpv6BlockConfig   EnableRelayAgent                 {CHOICES true false}                                             5                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_renew                           Dhcpv6BlockConfig   EnableRenew                      {CHOICES true false}                                             6                      true                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { preferred_lifetime                     Dhcpv6BlockConfig   PreferredLifetime                NUMERIC                                                          6                      604800                                 0-4294967295    true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { prefix_length                          Dhcpv6BlockConfig   PrefixLength                     NUMERIC                                                          5                      0                                      0-64            true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { prefix_start                           Dhcpv6BlockConfig   PrefixStart                      IPV6                                                             6                      none                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { rapid_commit_mode                      Dhcpv6BlockConfig   RapidCommitMode                  {CHOICES DISABLE ENABLE SERVER}                                  6                      DISABLE                                _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { relay_server_ipv6_addr                 Dhcpv6BlockConfig   RelayServerIpv6Addr              IPV6                                                             5                      none                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { relay_server_ipv6_addr_step            Dhcpv6BlockConfig   RelayServerIpv6AddrStep          IPV6                                                             6                      none                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { use_relay_agent_mac_addr_for_dataplane Dhcpv6BlockConfig   UseRelayAgentMacAddrForDataplane {CHOICES true false}                                             6                      true                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { valid_lifetime                         Dhcpv6BlockConfig   ValidLifetime                    NUMERIC                                                          6                      2592000                                 0-4294967295   true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_dad                             Dhcpv6BlockConfig   EnableDad                        {CHOICES true false}                                             6                      true                                   _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dad_timeout                            Dhcpv6BlockConfig   DadTimeout                       NUMERIC                                                          6                      1                                      1-4294967295    true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dad_transmits                          Dhcpv6BlockConfig   DadTransmits                     NUMERIC                                                          6                      1                                      1-4294967295    true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp_realm                             Dhcpv6BlockConfig   DhcpRealm                        ANY                                                              6                      "spirent.com"                          _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { requested_addr_start                   Dhcpv6BlockConfig   RequestedAddrStart               IPV6                                                             6                      ::                                     _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { client_mac_addr                        Dhcpv6BlockConfig   ClientMacAddrStart               ANY                                                              6                      00:10:01:00:00:01                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { client_mac_addr_step                   Dhcpv6BlockConfig   ClientMacAddrStep                ANY                                                              6                      00:00:00:00:00:01                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { client_mac_addr_mask                   Dhcpv6BlockConfig   ClientMacAddrMask                ANY                                                              6                      00:00:00:ff:ff:ff                      _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_auth                            Dhcpv6BlockConfig   EnableAuth                       {CHOICES true false}                                             6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { auth_protocol                          Dhcpv6BlockConfig   AuthProtocol                     {CHOICES DELAYED_AUTH RECONFIG_KEY }                             6                      DELAYED_AUTH                           _none_          true            {{enable_auth true}}  false       _none_                      {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { enable_remote_id                       Dhcpv6BlockConfig   EnableRemoteId                   {CHOICES true false}                                             38                     false                                   _none_       true        _none_                      false       _none_                      {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { remote_id                              Dhcpv6BlockConfig   RemoteId                         ANY                                                              39                      0                                   _none_          true        _none_                      false       processRemoteId             {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { remote_id_suffix                       Dhcpv6BlockConfig   _none_                           NUMERIC                                                          40                      _none_                                   _none_          true        _none_                      false       _none_                                      _none_                                          _none_}
    { remote_id_suffix_step                  Dhcpv6BlockConfig   _none_                           NUMERIC                                                          42                      _none_                                   _none_          true        _none_                      false       _none_                                      _none_                                          _none_}
    { remote_id_suffix_repeat                Dhcpv6BlockConfig   _none_                           NUMERIC                                                          43                      _none_                                   _none_          true        _none_                      false       _none_                                      _none_                                          _none_}    
    { remote_id_suffix_count                 Dhcpv6BlockConfig   _none_                           NUMERIC                                                          41                      _none_                                   _none_          true        _none_                      false       _none_                                      _none_                                          _none_}
    { remote_id_enterprise                   Dhcpv6BlockConfig   RemoteIdEnterprise               NUMERIC                                                          44                      3456                                   _none_          true     _none_                      false       _none_          {create configDhcpv6BlockConfig modify configDhcpv6BlockConfig} _none_}
    { dhcp6_delayed_auth_key_id              Dhcpv6DelayedAuthKey  KeyId                          ANY                                                              7                      1                                      0-4294967295    true            {{auth_protocol DELAYED_AUTH}} false       _none_             {create configDhcpv6DelayedAuthKey modify configDhcpv6DelayedAuthKey} _none_}
    { dhcp6_delayed_auth_key_value           Dhcpv6DelayedAuthKey  KeyValue                       ANY                                                              7                      spirent123                             _none_          true            {{auth_protocol DELAYED_AUTH}} false       _none_             {create configDhcpv6DelayedAuthKey modify configDhcpv6DelayedAuthKey} _none_}
    { option_value                           Dhcpv6MsgOption     OptionType                       ANY                                                              6                      0                                      0-255           true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { option_payload                         Dhcpv6MsgOption     Payload                          ANY                                                              6                      _none_                                 _none_          true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { remove_option                          Dhcpv6MsgOption     Remove                           ANY                                                              6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { enable_wildcards                       Dhcpv6MsgOption     EnableWildcards                  ANY                                                              6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { string_as_hex_value                    Dhcpv6MsgOption     HexValue                         ANY                                                              6                      false                                  _none_          true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { include_in_message                     Dhcpv6MsgOption     MsgTypeList                      ANY                                                              6                      1                                      _none_          true            _none_              false       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}     _none_}
    { ipv6_enable_gateway_learning           Ipv6If              EnableGatewayLearning            _none_                                                           4                      false                                  _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
 }                                                                                                                                                                                                                                                        
 { emulation_dhcpv6pd_group_config        
    { hname                                  stcobj                stcattr                        type                                                         priority    default                               range         supported   dependency                  mandatory                    procfunc                        mode                                                                constants}
    { handle                                 _none_                _none_                         ALPHANUM                                                       1           _none_                              _none_          true        _none_                      true                        _none_                        _none_                                                                  _none_}
    { mode                                   _none_                _none_                         {CHOICES enable create modify reset}                           2           _none_                              _none_          true        _none_                      true                        _none_                        _none_                                                                  _none_}
    { encap                                  _none_                _none_                         {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}        3           ethernet_ii                         _none_          true        _none_                      false                       _none_                        _none_                                                                  _none_}
    { num_sessions                           EmulatedDevice        DeviceCount                     NUMERIC                                                       4           1                                   _none_          true        _none_                      false                       _none_                        _none_                                                                  _none_} 
    { device_name                            _none_                _none_                          ANY                                                           6           _none_                              _none_          true        _none_                      false                       _none_                        _none_                                                                  _none_}
    { mac_addr                               EthIIIf               SourceMac                       ANY                                                           6           00:10:94:00:00:02                   _none_          true        _none_                      false                       _none_                        {create configEthIIIntf modify configEthIIIntf}                         _none_}
    { mac_addr_step                          EthIIIf               SrcMacStep                      ANY                                                           7           00:00:00:00:00:01                   _none_          true        _none_                      false                       _none_                        {create configEthIIIntf modify configEthIIIntf}                         _none_}
    { local_ipv6_addr                        Ipv6If                Address                         IPV6                                                          4           2000::2                             _none_          true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
    { local_ipv6_addr_step                   Ipv6If                AddrStep                        IPV6                                                          4            ::1                               _none_          true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
    { local_ipv6_prefix_len                  Ipv6If                PrefixLength                    NUMERIC                                                       4            64                                0-128           true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
    { gateway_ipv6_addr                      Ipv6If                Gateway                         IPV6                                                          4            ::0                              _none_          true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
    { gateway_ipv6_addr_step                 Ipv6If                GatewayStep                     IPV6                                                          4            ::                                 _none_          true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
    { qinq_incr_mode                         _none_                _none_                          {CHOICES inner outer both}                                    4           _none_                              _none_          true        _none_                      false                       _none_                         _none_                                                                 _none_}
    { vlan_id                                VlanIf                VlanId                           NUMERIC                                                      5            100                                0-4095          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     processConfigCmd_vlanId       {create configVlanIfInner modify configVlanIfInner}                     _none_}
    { vlan_id_step                           VlanIf                IdStep                           NUMERIC                                                      5             1                                 0-4095          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        {create configVlanIfInner modify configVlanIfInner}                     _none_}
    { vlan_id_count                          VlanIf                IfRecycleCount                   NUMERIC                                                      5             1                                 1-4096          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        _none_                                                                  _none_}
    { vlan_id_mode                           _none_                _none_                          {CHOICES fixed increment}                                     5           _none_                              _none_          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        _none_                                                                  _none_}
    { vlan_user_priority                     VlanIf                Priority                         NUMERIC                                                      5             0                                 0-7             true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                        {create configVlanIfInner modify configVlanIfInner}                     _none_}
    { vlan_cfi                               VlanIf                Cfi                             {CHOICES 0 1}                                                 5             1                                 _none_          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false    _none_                         {create configVlanIfInner modify configVlanIfInner}                     _none_}  
    { vlan_id_outer                          VlanIf_Outer          VlanId                           NUMERIC                                                      5            100                                0-4095          true    {{encap ethernet_ii_qinq}}      false                       processConfigCmd_vlanId       {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { vlan_id_outer_step                     VlanIf_Outer          IdStep                           NUMERIC                                                      5             1                                 0-4095          true    {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { vlan_id_outer_count                    VlanIf_Outer          IfRecycleCount                   NUMERIC                                                      5             1                                 1-4096          true    {{encap ethernet_ii_qinq}}      false                       _none_                        _none_                                                                  _none_}
    { vlan_id_outer_mode                     _none_                _none_                          {CHOICES fixed increment}                                     5           _none_                              _none_          true    {{encap ethernet_ii_qinq}}      false                       _none_                        _none_                                                                  _none_}
    { vlan_outer_user_priority               VlanIf_Outer          Priority                         NUMERIC                                                      5             0                                 0-7             true    {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { vlan_outer_cfi                         VlanIf_Outer          Cfi                             {CHOICES 0 1}                                                 5             1                                 _none_          true    {{encap ethernet_ii_qinq}}      false                       _none_                        {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { dhcp6_client_mode                      _none_                _none_                          {CHOICES DHCPPD DHCPV6 DHCPV6ANDPD}                           2           DHCPPD                              _none_          true        _none_                      false                       _none_                        _none_                                                                  _none_}
    { dhcp6_range_duid_enterprise_id         Dhcpv6PDBlockConfig   DuidEnterprise                  NUMERIC                                                       4           3456                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp6_range_duid_vendor_id             Dhcpv6PDBlockConfig   DuidStart                       NUMERIC                                                       5           1                                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp6_range_duid_vendor_id_increment   Dhcpv6PDBlockConfig   DuidStep                        NUMERIC                                                       6           1                                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp6_range_duid_type                  Dhcpv6PDBlockConfig   DuidType                        {CHOICES CUSTOM EN LL LLT}                                    6           LLT                                 _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp6_range_ia_t1                      Dhcpv6PDBlockConfig   T1Timer                         NUMERIC                                                       5           302400                              _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp6_range_ia_t2                      Dhcpv6PDBlockConfig   T2Timer                         NUMERIC                                                       6           483840                              _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dhcp_range_ip_type                     _none_                _none_                          {CHOICES 6 4}                                                 6           6                                   _none_          true        _none_                      false                       _none_                        _none_                                                                  _none_}
    { control_plane_prefix                   Dhcpv6PDBlockConfig   ControlPlanePrefix              {CHOICES LINKLOCAL ROUTERADVERTISEMENT}                       5           LINKLOCAL                           _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { dst_addr_type                          Dhcpv6PDBlockConfig   DstAddrType                     {CHOICES ALL_DHCP_RELAY_AGENTS_AND_SERVERS ALL_DHCP_SERVERS}  6           ALL_DHCP_RELAY_AGENTS_AND_SERVERS   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { duid_value                             Dhcpv6PDBlockConfig   DuidValue                        NUMERIC                                                      6           1                                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { enable_ldra                            Dhcpv6PDBlockConfig   EnableLdra                      {CHOICES true false}                                          5           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { enable_rebind                          Dhcpv6PDBlockConfig   EnableRebind                    {CHOICES true false}                                          6           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { enable_reconfig_accept                 Dhcpv6PDBlockConfig   EnableReconfigAccept            {CHOICES true false}                                          6           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { enable_relay_agent                     Dhcpv6PDBlockConfig   EnableRelayAgent                {CHOICES true false}                                          5           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { enable_renew                           Dhcpv6PDBlockConfig   EnableRenew                     {CHOICES true false}                                          6           true                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { preferred_lifetime                     Dhcpv6PDBlockConfig   PreferredLifetime                NUMERIC                                                      6           604800                              0-4294967295    true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { prefix_length                          Dhcpv6PDBlockConfig   PrefixLength                     NUMERIC                                                      5           0                                   0-64            true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { prefix_start                           Dhcpv6PDBlockConfig   PrefixStart                      IPV6                                                         6           none                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { rapid_commit_mode                      Dhcpv6PDBlockConfig   RapidCommitMode                  {CHOICES DISABLE ENABLE SERVER}                              6           DISABLE                             _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { relay_server_ipv6_addr                 Dhcpv6PDBlockConfig   RelayServerIpv6Addr              IPV6                                                         5           none                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { relay_server_ipv6_addr_step            Dhcpv6PDBlockConfig   RelayServerIpv6AddrStep          IPV6                                                         6           ::                                  _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { use_relay_agent_mac_addr_for_dataplane Dhcpv6PDBlockConfig   UseRelayAgentMacAddrForDataplane {CHOICES true false}                                         6           true                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { valid_lifetime                         Dhcpv6PDBlockConfig   ValidLifetime                    NUMERIC                                                      6           2592000                             0-4294967295    true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { export_addr_to_clients                 _none_                  _none_                        {CHOICES 0 1}                                                 6           _none_                              _none_          true        _none_                      false                       _none_                         _none_                                                                 _none_}
    { client_count                           _none_                  _none_                         NUMERIC                                                      6           _none_                              _none_          true        _none_                      false                       _none_                         _none_                                                                 _none_}
    { client_mac_addr                        Dhcpv6PDBlockConfig   ClientMacAddrStart               ANY                                                          6           00:10:01:00:00:01                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { client_mac_addr_step                   Dhcpv6PDBlockConfig   ClientMacAddrStep                ANY                                                          6           00:00:00:00:00:01                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { client_mac_addr_mask                   Dhcpv6PDBlockConfig   ClientMacAddrMask                ANY                                                          6           00:00:00:ff:ff:ff                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}     _none_}
    { option_value                           Dhcpv6MsgOption       OptionType                       ANY                                                          6           0                                   0-255           true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { option_payload                         Dhcpv6MsgOption       Payload                          ANY                                                          6           _none_                              _none_          true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { remove_option                          Dhcpv6MsgOption       Remove                           ANY                                                          6           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { enable_wildcards                       Dhcpv6MsgOption       EnableWildcards                  ANY                                                          6           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { string_as_hex_value                    Dhcpv6MsgOption       HexValue                         ANY                                                          6           false                               _none_          true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { include_in_message                     Dhcpv6MsgOption       MsgTypeList                      ANY                                                          6           1                                   _none_          true        _none_                      false                       _none_                        {create configDhcpv6MsgOption modify configDhcpv6MsgOption}             _none_}
    { enable_remote_id                       Dhcpv6PDBlockConfig   EnableRemoteId                   {CHOICES true false}                                         38          false                                   _none_      true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}         _none_}
    { remote_id                              Dhcpv6PDBlockConfig   RemoteId                         ANY                                                          39          0                                   _none_          true        _none_                      false                       processRemoteId               {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}         _none_}
    { remote_id_suffix                       Dhcpv6PDBlockConfig   _none_                           NUMERIC                                                      40          _none_                              _none_          true        _none_                      false                       _none_                                      _none_                                                    _none_}
    { remote_id_suffix_step                  Dhcpv6PDBlockConfig   _none_                           NUMERIC                                                      42          _none_                              _none_          true        _none_                      false                       _none_                                      _none_                                                    _none_}
    { remote_id_suffix_repeat                Dhcpv6PDBlockConfig   _none_                           NUMERIC                                                      43          _none_                              _none_          true        _none_                      false                       _none_                                      _none_                                                    _none_}    
    { remote_id_suffix_count                 Dhcpv6PDBlockConfig   _none_                           NUMERIC                                                      41          _none_                              _none_          true        _none_                      false                       _none_                                      _none_                                                    _none_}
    { remote_id_enterprise                   Dhcpv6PDBlockConfig   RemoteIdEnterprise               NUMERIC                                                      44          3456                                _none_          true        _none_                      false                       _none_                        {create configDhcpv6PdBlockConfig modify configDhcpv6PdBlockConfig}         _none_}
    { ipv6_enable_gateway_learning           Ipv6If                EnableGatewayLearning            _none_                                                       4           false                               _none_          true        _none_                      false                       _none_                        {create configIpv6Intf modify configIpv6Intf}                           _none_}
 }                                                                                                                                                                                                                                                                                                                                                                                               
 { emulation_dhcpv6_control
    { hname              stcobj              stcattr    type                         priority      default      range       supported   dependency      mandatory   procfunc    mode        constants}
    { port_handle        _none_             _none_      ALPHANUM                        1           _none_      0-MAX_INT   true        _none_          false       _none_      _none_      _none_}
    { handle             _none_             _none_      ALPHANUM                        2           _none_      _none_      true        _none_          false       _none_      _none_      _none_}
    { action             Dhcpv6PortConfig   _none_      {CHOICES bind release renew rebind abort inforeq}    5           _none_      _none_      true        _none_          true        _none_      _none_      _none_}
    { ip_version         _none_             _none_      {CHOICES 4 6}                   6           4           _none_      true        _none_          false       _none_      _none_      _none_}
    { apply              _none_             _none_      FLAG                            26          _none_      _none_      true        _none_          false       _none_      _none_      {TRUE _none_ FALSE _none_}}
 }
 { emulation_dhcpv6_stats
    { hname                              stcobj                  stcattr             type                            priority    default     range   supported   dependency  mandatory   procfunc             mode                    constants}
    { action                             _none_                  _none_              {CHOICES clear collect }        2           collect     _none_  true        _none_      false       _none_              _none_                    _none_}
    { handle                             _none_                  _none_              ALPHANUM                        25          _none_      _none_  true        _none_      false       _none_              _none_                    _none_}
    { mode                               _none_                  _none_              {CHOICES aggregate session detailed_session}  3 _none_ _none_   true        _none_      false       _none_              _none_                    _none_}
    { port_handle                        _none_                  _none_              ALPHANUM                        26          _none_      _none_  true        _none_      false       _none_              _none_                    _none_}
    { ip_version                         _none_                  _none_              {CHOICES 4 6}                   6           4           _none_  true        _none_      false       _none_              _none_                    _none_}
    { setup_success_rate                 _none_                  BindRate            NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { currently_attempting               _none_                  CurrentAttemptCount NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { currently_bound                    _none_                  CurrentBoundCount   NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { currently_idle                     _none_                  CurrentIdleCount    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { adv_rx_count                       _none_                  RxAdvertiseCount    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { reply_rx_count                     _none_                  RxReplyCount        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { setup_initiated                    _none_                  TotalAttemptCount   NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { setup_success                      _none_                  TotalBoundCount     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { setup_fail                         _none_                  TotalFailedCount    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { release_tx_count                   _none_                  TxReleaseCount      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { request_tx_count                   _none_                  TxRequestCount      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}	
	{ info_request_tx_count              _none_                  TxInfoRequestCount  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { solicits_tx_count                  _none_                  TxSolicitCount      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { avg_setup_time                     _none_                  AvgSetupTime        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { max_setup_time                     _none_                  MaxSetupTime        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { min_setup_time                     _none_                  MinSetupTime        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { success_percent                    _none_                  SuccessPercent      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { avg_rebind_repl_time               _none_                  AvgRebindReplTime   NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { avg_release_repl_time              _none_                  AvgReleaseReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { avg_renew_repl_time                _none_                  AvgRenewReplTime    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { avg_request_repl_time              _none_                  AvgRequestReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { avg_soli_adv_time                  _none_                  AvgSoliAdvTime      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { avg_soli_repl_time                 _none_                  AvgSoliReplTime     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { elapsed_time                       _none_                  ElapsedTime         NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_rebind_repl_time               _none_                  MaxRebindReplTime   NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_release_repl_time              _none_                  MaxReleaseReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_renew_repl_time                _none_                  MaxRenewReplTime    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_request_repl_time              _none_                  MaxRequestReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_soli_adv_time                  _none_                  MaxSoliAdvTime      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { max_soli_repl_time                 _none_                  MaxSoliReplTime     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_rebind_repl_time               _none_                  MinRebindReplTime   NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_release_repl_time              _none_                  MinReleaseReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_renew_repl_time                _none_                  MinRenewReplTime    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_request_repl_time              _none_                  MinRequestReplTime  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_soli_adv_time                  _none_                  MinSoliAdvTime      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { min_soli_repl_time                 _none_                  MinSoliReplTime     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { prefix_count                       _none_                  PrefixCount         NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { rebind_rate                        _none_                  RebindRate          NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { renew_rate                         _none_                  RenewRate           NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { dhcpv6_ipv6_addr                  _none_                   Dhcpv6Ipv6Addr      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_lease_left                 _none_                   Dhcpv6LeaseLeft     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_lease_rx                   _none_                   Dhcpv6LeaseRx       NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_prefix_length              _none_                   Dhcpv6PrefixLength  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_session_state              _none_                   Dhcpv6SessionState  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_status_code                _none_                   Dhcpv6StatusCode    NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { dhcpv6_status_string              _none_                   Dhcpv6StatusString  NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { ipv6_addr                         _none_                   Ipv6Addr            NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { lease_left                        _none_                   LeaseLeft           NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { lease_rx                          _none_                   LeaseRx             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { mac_addr                          _none_                   MacAddr             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_ipv6_addr                      _none_                   PdIpv6Addr          NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_lease_left                     _none_                   PdLeaseLeft         NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_lease_rx                       _none_                   PdLeaseRx           NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_prefix_length                  _none_                   PdPrefixLength      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_session_state                  _none_                   PdSessionState      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_status_code                    _none_                   PdStatusCode        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { pd_status_string                  _none_                   PdStatusString      NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { request_resp_time                 _none_                   RequestRespTime     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { session_index                     _none_                   SessIndex           NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { session_state                     _none_                   SessionState        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { solicit_resp_time                 _none_                   SolicitRespTime     NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { status_code                       _none_                   StatusCode          NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { status_string                     _none_                   StatusString        NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
    { vlan_id                           _none_                   VlanId              NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {detailed_session ""}      _none_}
 }                                                             
}