
namespace eval ::sth::Dhcpv6Server:: {
}

set ::sth::Dhcpv6Server::dhcpv6ServerTable {
 ::sth::Dhcpv6Server::
 { emulation_dhcpv6_server_config
    { hname                                    stcobj                              stcattr                  type                                           priority    default             range         supported   dependency              mandatory   procfunc                          mode                                                        constants}
    { port_handle                              _none_                              _none_                  ALPHANUM                                            1        _none_              _none_          true        _none_                  false       _none_                        _none_                                                          _none_}          
    { mode                                     _none_                              _none_                  {CHOICES enable create modify reset}                       2        create              _none_          true        _none_                  true        _none_                        _none_                                                          _none_}
    { handle                                   _none_                              _none_                  ALPHANUM                                            3        _none_              _none_          true        _none_                  false       _none_                        _none_                                                          _none_}
    { ip_version                               _none_                              _none_                  {CHOICES 4 6}                                       2        4                   _none_          true        _none_                  false       _none_                        _none_                                                          _none_}
    { encapsulation                            _none_                              _none_                  {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq} 3    ethernet_ii         _none_          true        _none_                  false       _none_                        _none_                                                          _none_}
    { count                                    EmulatedDevice              DeviceCount                  NUMERIC                                             4        1                   _none_          true        _none_                  false       _none_                        _none_                                                          _none_}
    { mac_addr                                 EthIIIf                             SourceMac               ANY                                                 6        _none_              _none_          true        _none_                  false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { mac_addr_step                            EthIIIf                             SrcMacStep              ANY                                                 7        _none_              _none_          true        _none_                  false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { local_ipv6_addr                          Ipv6If                              Address                 IPV6                                                4        _none_              _none_          true        _none_                  false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_addr_step                     Ipv6If                              AddrStep                IPV6                                                4        ::1                 _none_          true        _none_                  false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_prefix_len                    Ipv6If                              PrefixLength            NUMERIC                                             4        64                  0-128           true        _none_                  false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr                        Ipv6If                              Gateway                 IPV6                                                4        _none_              _none_          true        _none_                  false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr_step                   Ipv6If                              GatewayStep             IPV6                                                4        ::                  _none_          true        _none_                  false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { qinq_incr_mode                           _none_                              _none_                  {CHOICES inner outer both}                          4        _none_              _none_          true        _none_                  false       _none_                         _none_                                                         _none_}
    { vlan_id                                  VlanIf                              VlanId                  NUMERIC                                             5         100                0-4095          true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     processConfigCmd_vlanId       {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_id_step                             VlanIf                              IdStep                  NUMERIC                                             5          1                 0-4095          true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     _none_                        {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_id_count                            VlanIf                              _none_                  NUMERIC                                             5          1                 1-4096          true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     _none_                        _none_                                                   _none_}
    { vlan_id_mode                             _none_                              _none_                  {CHOICES fixed increment}                           5        _none_              _none_          true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     _none_                        _none_                                                   _none_}
    { vlan_user_priority                       VlanIf                              Priority                NUMERIC                                             5          0                 0-7             true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     _none_                        {create configVlanIfInner modify configVlanIfInner}      _none_}
    { vlan_cfi                                 VlanIf                              Cfi                     {CHOICES 0 1}                                       5          1                 _none_          true      {{encapsulation ethernet_ii_vlan} {encapsulation ethernet_ii_qinq}}  false     _none_                         {create configVlanIfInner modify configVlanIfInner}     _none_}  
    { vlan_id_outer                            VlanIf_Outer                              VlanId                  NUMERIC                                             5         100                0-4095          true        {{encapsulation ethernet_ii_qinq}}                                 false     processConfigCmd_vlanId       {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_id_outer_step                       VlanIf_Outer                              IdStep                  NUMERIC                                             5          1                 0-4095          true        {{encapsulation ethernet_ii_qinq}}                                 false     _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_id_outer_count                      VlanIf_Outer                              _none_                  NUMERIC                                             5          1                 1-4096          true        {{encapsulation ethernet_ii_qinq}}                                 false     _none_                        _none_                                                   _none_}
    { vlan_id_outer_mode                       _none_                              _none_                  {CHOICES fixed increment}                           5        _none_              _none_          true        {{encapsulation ethernet_ii_qinq}}                                 false     _none_                        _none_                                                   _none_}
    { vlan_outer_user_priority                 VlanIf_Outer                              Priority                NUMERIC                                             5          0                 0-7             true        {{encapsulation ethernet_ii_qinq}}                                 false     _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { vlan_outer_cfi                           VlanIf_Outer                              Cfi                     {CHOICES 0 1}                                       5          1                 _none_          true        {{encapsulation ethernet_ii_qinq}}                                 false     _none_                        {create configVlanIfOuter modify configVlanIfOuter}      _none_}
    { dhcp_realm                               Dhcpv6ServerConfig                  DhcpRealm               ANY                                                 10       "spirent.com"       _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { server_emulation_mode                    Dhcpv6ServerConfig                  EmulationMode           {CHOICES DHCPV6 DHCPV6_PD}                          3        DHCPV6_PD           _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { enable_delayed_auth                      Dhcpv6ServerConfig                  EnableDelayedAuth       {CHOICES true false}                                6        false               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { enable_reconfigure_key                   Dhcpv6ServerConfig                  EnableReconfigureKey    {CHOICES true false}                                3        false               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { preferred_lifetime                       Dhcpv6ServerConfig                  PreferredLifetime       NUMERIC                                             3        604800              _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { rebinding_time_percent                   Dhcpv6ServerConfig                  RebindingTimePercent    NUMERIC                                             3        80                  0-200           true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { reconfigure_key                          Dhcpv6ServerConfig                  ReconfigureKey          ALPHANUM                                            10       "spirentcom123456"  _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { reconfigure_key_value_type               Dhcpv6ServerConfig                  ReconfigureKeyValueType {CHOICES ASCII HEX}                                 10       ASCII               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { reneval_time_percent                     Dhcpv6ServerConfig                  RenewalTimePercent      NUMERIC                                             3        50                  0-200           true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { valid_lifetime                           Dhcpv6ServerConfig                  ValidLifetime           NUMERIC                                             3       2592000              _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerConfig modify configDhcpv6ServerConfig}                                 _none_}
    { addr_pool_step_per_server                Dhcpv6ServerDefaultAddrPoolConfig   AddrIncrement           NUMERIC                                             3       1                    _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                   {create configDhcpv6ServerDefaultAddrPoolConfig modify configDhcpv6ServerDefaultAddrPoolConfig}       _none_}
    { addr_pool_host_step                      Dhcpv6ServerDefaultAddrPoolConfig   HostAddrStep            IPV6                                                3       ::1                  _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                   {create configDhcpv6ServerDefaultAddrPoolConfig modify configDhcpv6ServerDefaultAddrPoolConfig}       _none_}
    { addr_pool_addresses_per_server           Dhcpv6ServerDefaultAddrPoolConfig   NetworkCount            NUMERIC                                             3       1                    _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                   {create configDhcpv6ServerDefaultAddrPoolConfig modify configDhcpv6ServerDefaultAddrPoolConfig}       _none_}
    { addr_pool_prefix_length                  Dhcpv6ServerDefaultAddrPoolConfig   PrefixLength            NUMERIC                                             3       64                   0-128           true        {{server_emulation_mode DHCPV6}}                                  false     _none_                   {create configDhcpv6ServerDefaultAddrPoolConfig modify configDhcpv6ServerDefaultAddrPoolConfig}       _none_}
    { addr_pool_start_addr                     Dhcpv6ServerDefaultAddrPoolConfig   StartIpList             IPV6                                                3       2000::1              _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                   {create configDhcpv6ServerDefaultAddrPoolConfig modify configDhcpv6ServerDefaultAddrPoolConfig}       _none_}
    { addr_pool_custom_option_value            Dhcpv6ServerMsgOption               OptionType              ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6AddrPoolCustomOption modify configDhcpv6AddrPoolCustomOption}                     _none_}
    { addr_pool_custom_option_payload          Dhcpv6ServerMsgOption               Payload                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6AddrPoolCustomOption modify configDhcpv6AddrPoolCustomOption}                     _none_}
    { addr_pool_custom_enable_wildcards        Dhcpv6ServerMsgOption               EnableWildcards         ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6AddrPoolCustomOption modify configDhcpv6AddrPoolCustomOption}                     _none_}
    { addr_pool_custom_string_as_hex_value     Dhcpv6ServerMsgOption               HexValue                ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6AddrPoolCustomOption modify configDhcpv6AddrPoolCustomOption}                     _none_}
    { addr_pool_custom_include_in_message      Dhcpv6ServerMsgOption               MsgType                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6AddrPoolCustomOption modify configDhcpv6AddrPoolCustomOption}                     _none_}
    { prefix_pool_step_per_server              Dhcpv6ServerDefaultPrefixPoolConfig ServerPrefixStep        IPV6                                                3       0:0:0:1::            _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerDefaultPrefixPoolConfig modify configDhcpv6ServerDefaultPrefixPoolConfig}   _none_}
    { prefix_pool_per_server                   Dhcpv6ServerDefaultPrefixPoolConfig NetworkCount            NUMERIC                                             3       1                    _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerDefaultPrefixPoolConfig modify configDhcpv6ServerDefaultPrefixPoolConfig}   _none_}
    { prefix_pool_prefix_length                Dhcpv6ServerDefaultPrefixPoolConfig PrefixLength            NUMERIC                                             3       64                   0-128           true        _none_                  false       _none_                        {create configDhcpv6ServerDefaultPrefixPoolConfig modify configDhcpv6ServerDefaultPrefixPoolConfig}   _none_}
    { prefix_pool_step                         Dhcpv6ServerDefaultPrefixPoolConfig AddrIncrement           NUMERIC                                             3       1                    _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerDefaultPrefixPoolConfig modify configDhcpv6ServerDefaultPrefixPoolConfig}   _none_}
    { prefix_pool_start_addr                   Dhcpv6ServerDefaultPrefixPoolConfig StartIpList             IPV6                                                3       2000::1              _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerDefaultPrefixPoolConfig modify configDhcpv6ServerDefaultPrefixPoolConfig}   _none_}
    { prefix_pool_custom_option_value          Dhcpv6ServerMsgOption               OptionType              ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6PrefixPoolCustomOption modify configDhcpv6PrefixPoolCustomOption}                 _none_}
    { prefix_pool_custom_option_payload        Dhcpv6ServerMsgOption               Payload                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6PrefixPoolCustomOption modify configDhcpv6PrefixPoolCustomOption}                 _none_}
    { prefix_pool_custom_enable_wildcards      Dhcpv6ServerMsgOption               EnableWildcards         ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6PrefixPoolCustomOption modify configDhcpv6PrefixPoolCustomOption}                 _none_}
    { prefix_pool_custom_string_as_hex_value   Dhcpv6ServerMsgOption               HexValue                ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6PrefixPoolCustomOption modify configDhcpv6PrefixPoolCustomOption}                 _none_}
    { prefix_pool_custom_include_in_message    Dhcpv6ServerMsgOption               MsgType                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6PrefixPoolCustomOption modify configDhcpv6PrefixPoolCustomOption}                 _none_}
    { dhcp6_delayed_auth_key_id                Dhcpv6DelayedAuthKey                KeyId                   ANY                                                 7       _none_               _none_          true        {{enable_delayed_auth true}}                                      false     _none_                      {create configDhcpv6DelayedAuthKey modify configDhcpv6DelayedAuthKey}                                 _none_}
    { dhcp6_delayed_auth_key_value             Dhcpv6DelayedAuthKey                KeyValue                ANY                                                 7       _none_               _none_          true        {{enable_delayed_auth true}}                                      false     _none_                      {create configDhcpv6DelayedAuthKey modify configDhcpv6DelayedAuthKey}                                 _none_}
    { server_custom_option_value               Dhcpv6ServerMsgOption               OptionType              ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerCustomOption modify configDhcpv6ServerCustomOption}                         _none_}
    { server_custom_option_payload             Dhcpv6ServerMsgOption               Payload                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerCustomOption modify configDhcpv6ServerCustomOption}                         _none_}
    { server_custom_enable_wildcards           Dhcpv6ServerMsgOption               EnableWildcards         ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerCustomOption modify configDhcpv6ServerCustomOption}                         _none_}
    { server_custom_string_as_hex_value        Dhcpv6ServerMsgOption               HexValue                ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerCustomOption modify configDhcpv6ServerCustomOption}                         _none_}
    { server_custom_include_in_message         Dhcpv6ServerMsgOption               MsgType                 ANY                                                 6       _none_               _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerCustomOption modify configDhcpv6ServerCustomOption}                         _none_}
    { add_addr_pool_step_per_server            Dhcpv6ServerAddrPoolConfig          AddrIncrement           NUMERIC                                             3       1                    _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                     {create configDhcpv6ServerAddrPoolConfig modify configDhcpv6ServerAddrPoolConfig}         _none_}
    { add_addr_pool_host_step                  Dhcpv6ServerAddrPoolConfig          HostAddrStep            IPV6                                                3       ::1                  _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                     {create configDhcpv6ServerAddrPoolConfig modify configDhcpv6ServerAddrPoolConfig}         _none_}
    { add_addr_pool_addresses_per_server       Dhcpv6ServerAddrPoolConfig          NetworkCount            NUMERIC                                             3       1                    _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                     {create configDhcpv6ServerAddrPoolConfig modify configDhcpv6ServerAddrPoolConfig}         _none_}
    { add_addr_pool_prefix_length              Dhcpv6ServerAddrPoolConfig          PrefixLength            NUMERIC                                             3       64                   0-128           true        {{server_emulation_mode DHCPV6}}                                  false     _none_                     {create configDhcpv6ServerAddrPoolConfig modify configDhcpv6ServerAddrPoolConfig}         _none_}
    { add_addr_pool_start_addr                 Dhcpv6ServerAddrPoolConfig          StartIpList             IPV6                                                3       2000::1              _none_          true        {{server_emulation_mode DHCPV6}}                                  false     _none_                     {create configDhcpv6ServerAddrPoolConfig modify configDhcpv6ServerAddrPoolConfig}         _none_}
    { add_prefix_pool_step_per_server          Dhcpv6ServerPrefixPoolConfig        ServerPrefixStep        IPV6                                                3       0:0:0:1::            _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerPrefixPoolConfig modify configDhcpv6ServerPrefixPoolConfig}                _none_}
    { add_prefix_pool_per_server               Dhcpv6ServerPrefixPoolConfig        NetworkCount            NUMERIC                                             3       1                    _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerPrefixPoolConfig modify configDhcpv6ServerPrefixPoolConfig}                _none_}
    { add_prefix_pool_prefix_length            Dhcpv6ServerPrefixPoolConfig        PrefixLength            NUMERIC                                             3       64                   0-128           true        _none_                  false       _none_                        {create configDhcpv6ServerPrefixPoolConfig modify configDhcpv6ServerPrefixPoolConfig}                _none_}
    { add_prefix_pool_step                     Dhcpv6ServerPrefixPoolConfig        AddrIncrement           NUMERIC                                             3       1                    _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerPrefixPoolConfig modify configDhcpv6ServerPrefixPoolConfig}                _none_}
    { add_prefix_pool_start_addr               Dhcpv6ServerPrefixPoolConfig        StartIpList             IPV6                                                3       2000::1              _none_          true        _none_                  false       _none_                        {create configDhcpv6ServerPrefixPoolConfig modify configDhcpv6ServerPrefixPoolConfig}                _none_}
 }                                                                                                                                                                                                                                                                                                                                                                               
 { emulation_dhcpv6_server_control
    { hname                                 stcobj                          stcattr           type                                   priority   default          range        supported   dependency          mandatory    procfunc                         mode                                constants}
    { port_handle                           _none_                          _none_          ALPHANUM                                     1       _none_          _none_          true        _none_             false       _none_                         _none_                                _none_}
    { dhcp_handle                           _none_                          _none_          ALPHANUM                                     2       _none_          _none_          true        _none_             false       _none_                         _none_                                _none_}
    { action                                _none_                          _none_          {CHOICES connect renew reset}                3       _none_          _none_          true        _none_             true        _none_                         _none_                                _none_}
    { ip_version                            _none_                          _none_          {CHOICES 4 6}                                2         4             _none_          true        _none_             false       _none_                         _none_                                _none_}
 }
 { emulation_dhcpv6_server_stats
    { hname                                 stcobj                          stcattr                    type                                   priority   default         range         supported   dependency       mandatory      procfunc                        mode                                constants}
    { port_handle                           _none_                          _none_                     ALPHANUM                                     1      _none_         _none_          true        _none_         false       _none_                            _none_                                 _none_}
    { dhcp_handle                           _none_                          _none_                     ALPHANUM                                     2      _none_         _none_          true        _none_         false       _none_                            _none_                                 _none_}
    { action                                _none_                          _none_                     {CHOICES CLEAR COLLECT}                      3      _none_         _none_          true        _none_         true        _none_                            _none_                                 _none_}
    { ip_version                            _none_                          _none_                     {CHOICES 4 6}                                2       4             _none_          true        _none_         false       _none_                            _none_                                 _none_}
    { current_bound_count                   Dhcpv6ServerResults             CurrentBoundCount          NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_confirm_count                      Dhcpv6ServerResults             RxConfirmCount             NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_decline_count                      Dhcpv6ServerResults             RxDeclineCount             NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_info_request_count                 Dhcpv6ServerResults             RxInfoRequestCount         NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_rebind_count                       Dhcpv6ServerResults             RxRebindCount              NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_release_count                      Dhcpv6ServerResults             RxReleaseCount             NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_renew_count                        Dhcpv6ServerResults             RxRenewCount               NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_request_count                      Dhcpv6ServerResults             RxRequestCount             NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { rx_soilicit_count                     Dhcpv6ServerResults             RxSolicitCount             NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { total_bound_count                     Dhcpv6ServerResults             TotalBoundCount            NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { total_expired_count                   Dhcpv6ServerResults             TotalExpiredCount          NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { total_release_count                   Dhcpv6ServerResults             TotalReleasedCount         NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { total_renewed_count                   Dhcpv6ServerResults             TotalRenewedCount          NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { tx_advertise_count                    Dhcpv6ServerResults             TxAdvertiseCount           NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { tx_reconfigure_count                  Dhcpv6ServerResults             TxReconfigureCount         NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { tx_reconfigure_rebind_count           Dhcpv6ServerResults             TxReconfigureRebindCount   NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { tx_reconfigure_renew_count            Dhcpv6ServerResults             TxReconfigureRenewCount    NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
    { tx_reply_count                        Dhcpv6ServerResults             TxReplyCount               NUMERIC                                      5      _none_         _none_          TRUE        _none_         false       _none_                            {aggregate ""}                         _none_}
 }
}
