
namespace eval ::sth::DhcpServer:: {
}

set ::sth::DhcpServer::dhcpServerTable {
 ::sth::DhcpServer::
 { emulation_dhcp_server_config
    { hname                                 stcobj                         stcattr              type                                priority    default         range         supported   dependency              mandatory   procfunc                                                          mode                                                                   constants}
    { port_handle                           _none_                          _none_              ALPHANUM                                1       _none_          _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}          
    { mode                                  _none_                          _none_              {CHOICES enable create modify reset}    2       create          _none_          true        _none_                  true        _none_                                                          _none_                                                                  _none_}
    { handle                                _none_                          _none_              ALPHANUM                                3       _none_          _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { ip_version                            _none_                          _none_              {CHOICES 4 6}                           2        4              _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { count                                 EmulatedDevice              DeviceCount              NUMERIC                                 4       1               1-100000        true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { local_mac                             EthIIIf                         SourceMac           ANY                                     5       _none_          _none_          true        _none_                  false       _none_                                                          {create configEthIIIntf modify configEthIIIntf}                         _none_}
    { remote_mac                            Ipv4If                          GatewayMac          ANY                                     39      _none_          _none_          true        _none_                  false       processEmulation_dhcp_server_config_remoteMac                   {create configIpv4Intf modify configIpv4Intf}                           _none_}               
    { vlan_id                               VlanIf                          VlanId              NUMERIC                                 6       _none_          0-4095          true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       processEmulation_dhcp_server_config_vlanStep           {create configVlanIfInner modify configVlanIfInner}       _none_}
    { vlan_id_mode                          _none_                          _none_              {CHOICES fixed increment}               6       _none_          _none_          true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       _none_                                                 _none_                                                    _none_}
    { vlan_id_step                          VlanIf                          IdStep              NUMERIC                                 6       _none_          0-4095          true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       _none_                                                 _none_                                                    _none_}
    { vlan_id_count                         VlanIf                          _none_              NUMERIC                                 6       _none_          1-4096          true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       processEmulation_dhcp_server_config_vlanIdCount        {create configVlanIfInner modify configVlanIfInner}       _none_}
    { vlan_user_priority                    VlanIf                          Priority            NUMERIC                                 6       _none_          0-7             true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       _none_                                                 {create configVlanIfInner modify configVlanIfInner}       _none_}
    { vlan_ethertype                        VlanIf                          Tpid                {CHOICES 0x8100 0x88A8 0x9100 0x9200}   7       _none_          _none_          true        {{encapsulation ETHERNET_II_VLAN} {encapsulation ETHERNET_II_QINQ}}       false       processEmulation_dhcp_server_config_vlanEthertype      {create configVlanIfInner modify configVlanIfInner}       _none_}
    { ip_address                            Ipv4If                          Address             IPV4                                    8       _none_          _none_          true        _none_                  false       _none_                                                          {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { ip_step                               Ipv4If                          AddrStep            IPV4                                    9       _none_          _none_          true        _none_                  false       _none_                                                          {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { ip_prefix_step                        Ipv4If                          AddrStep            NUMERIC                                 10      _none_          _none_          true        _none_                  false       processEmulation_dhcp_server_config_ipPrefixstep                {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { ip_prefix_length                      Ipv4If                          PrefixLength        NUMERIC                                 11      _none_          0-32            true        _none_                  false       _none_                                                          {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { ip_repeat                             Ipv4If                          AddrRepeatCount     NUMERIC                                 12      1               _none_          true        _none_                  false       _none_                                                          {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { ip_gateway                            Ipv4If                          Gateway             IPV4                                    13      _none_          _none_          true        _none_                  false       _none_                                                          {create configIpv4Intf modify configIpv4Intf}                           _none_}
    { lease_time                            Dhcpv4ServerConfig              LeaseTime           NUMERIC                                 15      3600            1-4294967295    true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { assign_strategy                       Dhcpv4ServerConfig              AssignStrategy      ANY                                     15      GATEWAY         _none_          true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { decline_reserve_time                  Dhcpv4ServerConfig              DeclineReserveTime  NUMERIC                                 15      10              1-600           true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { offer_reserve_time                    Dhcpv4ServerConfig              OfferReserveTime    NUMERIC                                 15      10              1-600           true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { host_name                             Dhcpv4ServerConfig              HostName            ANY                                     15      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { enable_overlap_addr                   Dhcpv4ServerConfig              EnableOverlapAddress {CHOICES true false}                   15      false           _none_          true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { tos_value                             Dhcpv4ServerConfig              Ipv4Tos             ANY                                     15      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { rebinding_time_percent                Dhcpv4ServerConfig              RebindingTimePercent  ANY                                   15      87.5            1-200           true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { renewal_time_percent                  Dhcpv4ServerConfig              RenewalTimePercent  ANY                                     15      50              1-200           true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { min_allowed_lease_time                Dhcpv4ServerConfig              MinAllowedLeaseTime NUMERIC                                 15      10              1-4294967295    true        _none_                  false       _none_                                                          {create configDhcpServerConfig modify configDhcpServerConfig}           _none_}
    { ipaddress_pool                        Dhcpv4ServerDefaultPoolConfig   StartIpList         IPV4                                    16      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { ipaddress_count                       Dhcpv4ServerDefaultPoolConfig   HostAddrCount       NUMERIC                                 17      _none_          _none_          true        _none_                  false       processEmulation_dhcp_server_config_poolAddressCount            {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { ipaddress_increment                   Dhcpv4ServerDefaultPoolConfig   HostAddrStep        NUMERIC                                 18      _none_          _none_          true        _none_                  false       processEmulation_dhcp_server_config_poolAddressIncrement        {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { enable_custom_pool                    Dhcpv4ServerDefaultPoolConfig   EnablePoolAddrPrefix {CHOICES true false}                   17      false           _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { host_addr_prefix_length               Dhcpv4ServerDefaultPoolConfig   HostAddrPrefixLength  NUMERIC                               18      24              0-32            true    {{enable_custom_pool true}} false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { router_list                           Dhcpv4ServerDefaultPoolConfig   RouterList          ANY                                     17      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { domain_name                           Dhcpv4ServerDefaultPoolConfig   DomainName          ALPHANUM                                17      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { domain_name_server_list               Dhcpv4ServerDefaultPoolConfig   DomainNameServerList ANY                                    17      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { circuit_id                            Dhcpv4ServerDefaultPoolConfig   CircuitId           ANY                                     18      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { circuit_id_count                      Dhcpv4ServerDefaultPoolConfig   CircuitIdCount      NUMERIC                                 18      1               1-4294967295    true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { remote_id                             Dhcpv4ServerDefaultPoolConfig   RemoteId            ANY                                     18      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { remote_id_count                       Dhcpv4ServerDefaultPoolConfig   RemoteIdCount       NUMERIC                                 18      1               1-20            true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id                                Dhcpv4ServerDefaultPoolConfig   VPNId               ANY                                     18      _none_          _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id_count                          Dhcpv4ServerDefaultPoolConfig   VPNIdCount          NUMERIC                                 18      1               1-4294967295    true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id_type                           Dhcpv4ServerDefaultPoolConfig   VPNType             {CHOICES nvt_ascii rfc_2685}            18      nvt_ascii       _none_          true        _none_                  false       _none_                                                          {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}    
    { dhcp_ack_options                      Dhcpv4ServerMsgOption           MsgType             {CHOICES 0 1}                           19      _none_          _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_ack_time_offset                  Dhcpv4ServerMsgOption           _none_              NUMERIC                                 21      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_router_adddress              Dhcpv4ServerMsgOption           _none_              IPV4                                    22      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_router_address               Dhcpv4ServerMsgOption           _none_              IPV4                                    22      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_time_server_address          Dhcpv4ServerMsgOption           _none_              IPV4                                    23      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_circuit_id                   Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}               24      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_remote_id                    Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}               25      _none_          _none_          true        {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_link_selection               Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_cisco_server_id_override     Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_ack_server_id_override           Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_ack_options}      false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_options                    Dhcpv4ServerMsgOption           MsgType             {CHOICES 0 1}                           29      _none_          _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_offer_time_offset                Dhcpv4ServerMsgOption           _none_              NUMERIC                                 31      _none_          _none_          true        {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_router_address             Dhcpv4ServerMsgOption           _none_              IPV4                                    32      _none_          _none_          true        {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_time_server_address        Dhcpv4ServerMsgOption           _none_              IPV4                                    33      _none_          _none_          true        {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_circuit_id                 Dhcpv4ServerMsgOption           _none_              HEX                                     34      _none_          _none_          true        {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_remote_id                  Dhcpv4ServerMsgOption           _none_              HEX                                     35      _none_          _none_          true        {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_link_selection             Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_cisco_server_id_override   Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}
    { dhcp_offer_server_id_override         Dhcpv4ServerMsgOption           _none_              IPV4                                    99      _none_          _none_          false       {dhcp_offer_options}    false       processEmulation_dhcp_server_config_dhcpAckOfferOptions         {create configDhcpServerMsgOption modify configDhcpServerMsgOption}     _none_}  
    { ipv6_gateway                          Ipv6If                          Gateway             IPV6                                    99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { encapsulation                         _none_    _none_     {CHOICES ETHERNET_II ETHERNET_II_QINQ ETHERNET_II_VLAN ATM_LLC_SNAP_ETHERNET_II ATM_VC_MUX_ETHERNET_II}  58  ETHERNET_II _none_ true   _none_      false       _none_                                                          _none_                                                                  _none_}
    { ip_count                              _none_                          _none_              NUMERIC                                 99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { spfc_mac_mask_pool                    _none_                          _none_              MAC                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { spfc_mac_pattern_pool                 _none_                          _none_              HEX                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { spfc_mac_ipaddress_pool               _none_                          _none_              IP                                      99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { spfc_mac_ipaddress_count              _none_                          _none_              NUMERIC                                 99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { spfc_mac_ipaddress_increment          _none_                          _none_              NUMERIC                                 99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_ignore_mac                       _none_                          _none_              MAC                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_ignore_mac_mask                  _none_                          _none_              MAC                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_mac_nak                          _none_                          _none_              MAC                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_mac_nak_mask                     _none_                          _none_              MAC                                     99      _none_          _none_          false       _none_                  false       _none_                                                          _none_                                                                  _none_}
    { dhcp_ack_subnet_mask                  Dhcpv4ServerMsgOption           _none_              IPV4                                    20      _none_          _none_          false       {dhcp_ack_options}      false       _none_                                                          _none_                                                                  _none_}
    { dhcp_offer_subnet_mask                Dhcpv4ServerMsgOption           _none_              IPV4                                    30      _none_          _none_          false       {dhcp_offer_options}    false       _none_                                                          _none_                                                                  _none_}
    { vlan_outer_id                         VlanIf_Outer                          VlanId              NUMERIC                                 50      _none_          0-4095          true        {{encapsulation ETHERNET_II_QINQ}}  false       processEmulation_dhcp_server_config_vlanStep                   {create configVlanIfOuter modify configVlanIfOuter}                      _none_}
    { vlan_outer_id_mode                    _none_                          _none_              {CHOICES fixed increment}               50      _none_          _none_          true        {{encapsulation ETHERNET_II_QINQ}}  false       _none_                                                          _none_                                                                  _none_}
    { vlan_outer_id_step                    VlanIf_Outer                          IdStep              NUMERIC                                 50      _none_          0-4095          true        {{encapsulation ETHERNET_II_QINQ}}  false       _none_                                                          _none_                                                                  _none_}
    { vlan_outer_id_count                   VlanIf_Outer                          _none_              NUMERIC                                 50      _none_          1-4096          true        {{encapsulation ETHERNET_II_QINQ}}  false       processEmulation_dhcp_server_config_vlanIdCount                 {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { vlan_outer_user_priority              VlanIf_Outer                          Priority            NUMERIC                                 50      _none_          0-7             true        {{encapsulation ETHERNET_II_QINQ}}  false       _none_                                                          {create configVlanIfOuter modify configVlanIfOuter}                     _none_}        
    { vlan_outer_ethertype                  VlanIf_Outer                          Tpid                {CHOICES 0x8100 0x88A8 0x9100 0x9200}   50      _none_          _none_          true        {{encapsulation ETHERNET_II_QINQ}}  false       processEmulation_dhcp_server_config_vlanEthertype               {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
    { qinq_incr_mode                        _none_                          _none_              {CHOICES inner outer both}              50      _none_          inner           true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { vci                                   Aal5If                          Vci                 NUMERIC                                 51      _none_          0-65535         true        _none_                  false       processEmulation_dhcp_server_config_atmSettings                 {create configAtmIf modify configAtmIf}                                 _none_}
    { vci_step                              Aal5If                          VciStep             NUMERIC                                 52      _none_          0-65535         true        _none_                  false       _none_                                                          _none_                                                                  _none_} 
    { vci_count                             Aal5If                          VciRecycleCount              NUMERIC                                 53      _none_          1-65536         true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { vpi                                   Aal5If                          Vpi                 NUMERIC                                 54      _none_          0-255           true        _none_                  false       processEmulation_dhcp_server_config_atmSettings                 {create configAtmIf modify configAtmIf}                                 _none_}
    { vpi_step                              Aal5If                          VpiStep             NUMERIC                                 55      _none_          0-255           true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { vpi_count                             Aal5If                          IfRecycleCount              NUMERIC                                 56      _none_          1-256           true        _none_                  false       _none_                                                          _none_                                                                  _none_}
    { pvc_incr_mode                         _none_                          _none_              {CHOICES vci vpi both}                  57      _none_          _none_          true        _none_                  false       _none_                                                          _none_                                                                  _none_}
 }
 { emulation_dhcp_server_relay_agent_config
    { hname                                 stcobj                         stcattr              type                    priority    default         range         supported   dependency              mandatory         procfunc                                                    mode            constants}
    { handle                                _none_                          _none_              ALPHANUM                    1       _none_          _none_          true        _none_                  true            _none_                                                      _none_          _none_}
    { mode                                  _none_                          _none_         {CHOICES create modify delete}   2       _none_          _none_          true        _none_                  true            _none_                                                      _none_          _none_}
    { relay_agent_pool_count                _none_                          _none_              NUMERIC                     3       1               _none_          true        _none_                  false           _none_                                                      _none_          _none_}
    { relay_agent_pool_step                 _none_                          _none_              IPV4                        4       1.0.0.0         _none_          true        _none_                  false           _none_                                                      _none_          _none_}
    { relay_agent_ipaddress_pool            Dhcpv4ServerPoolConfig          StartIpList         IPV4                        5       192.0.1.0       _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_} 
    { relay_agent_ipaddress_count           Dhcpv4ServerPoolConfig          HostAddrCount       NUMERIC                     6       254             _none_          true        _none_                  false           process_dhcp_server_relay_agent_poolAddressCount            {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_} 
    { relay_agent_ipaddress_step            Dhcpv4ServerPoolConfig          HostAddrStep        IPV4                        7       0.0.0.1         _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_} 
    { prefix_length                         Dhcpv4ServerPoolConfig          PrefixLength        NUMERIC                     7       24              _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { router_list                           Dhcpv4ServerPoolConfig          RouterList          ANY                         7       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { domain_name                           Dhcpv4ServerPoolConfig          DomainName          ALPHANUM                    7       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { domain_name_server_list               Dhcpv4ServerPoolConfig          DomainNameServerList ANY                        7       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { circuit_id                            Dhcpv4ServerPoolConfig          CircuitId           ANY                         8       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { circuit_id_count                      Dhcpv4ServerPoolConfig          CircuitIdCount      NUMERIC                     8       1               1-4294967295    true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { remote_id                             Dhcpv4ServerPoolConfig          RemoteId            ANY                         8       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { remote_id_count                       Dhcpv4ServerPoolConfig          RemoteIdCount       NUMERIC                     8       1               1-20            true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id                                Dhcpv4ServerPoolConfig          VPNId               ANY                         8       _none_          _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id_count                          Dhcpv4ServerPoolConfig          VPNIdCount          NUMERIC                     8       1               1-4294967295    true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}
    { vpn_id_type                           Dhcpv4ServerPoolConfig          VPNType             {CHOICES nvt_ascii rfc_2685} 8      nvt_ascii       _none_          true        _none_                  false           _none_                                                      {create configDhcpServerPoolConfig modify configDhcpServerPoolConfig}   _none_}    
    { dhcp_ack_options                      Dhcpv4ServerMsgOption           MsgType             {CHOICES 0 1}               8       _none_          _none_          true        _none_                  false           _none_                                                      _none_              _none_}
    { dhcp_ack_time_offset                  Dhcpv4ServerMsgOption           _none_              NUMERIC                     9       _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_ack_router_adddress              Dhcpv4ServerMsgOption           _none_              IPV4                        10      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_ack_router_address               Dhcpv4ServerMsgOption           _none_              IPV4                        10      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_ack_time_server_address          Dhcpv4ServerMsgOption           _none_              IPV4                        11      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_ack_circuit_id                   Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}   12      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_ack_remote_id                    Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}   13      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_offer_options                    Dhcpv4ServerMsgOption           MsgType             {CHOICES 0 1}               14      _none_          _none_          true        _none_                  false           _none_                                                      _none_           _none_}
    { dhcp_offer_time_offset                Dhcpv4ServerMsgOption           _none_              NUMERIC                     15      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_offer_router_address             Dhcpv4ServerMsgOption           _none_              IPV4                        16      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_offer_time_server_address        Dhcpv4ServerMsgOption           _none_              IPV4                        17      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_offer_circuit_id                 Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}   18      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
    { dhcp_offer_remote_id                  Dhcpv4ServerMsgOption           _none_              {REGEXP ^[a-fA-F0-9]{8}$}   19      _none_          _none_          true        _none_                  false           processEmulation_dhcp_server_config_dhcpAckOfferOptions     {create configDhcpServerMsgOption modify configDhcpServerMsgOption}   _none_}
 }
 { emulation_dhcp_server_control
    { hname                                 stcobj                          stcattr           type                                   priority   default          range        supported   dependency          mandatory    procfunc                            mode                                constants}
    { port_handle                           _none_                          _none_          ALPHANUM                                     1       _none_          _none_          true        _none_             false       _none_                             _none_                                _none_}
    { ip_version                            _none_                          _none_          {CHOICES 4 6}                                2        4              _none_          true        _none_             false       _none_                             _none_                                _none_}
    { dhcp_handle                           _none_                          _none_          ALPHANUM                                     2       _none_          _none_          true        _none_             false       _none_                             _none_                                _none_}
    { action                                _none_                          _none_          {CHOICES connect renew reset}                3       _none_          _none_          true        _none_             true        _none_                             _none_                                _none_}
 }
 { emulation_dhcp_server_stats
    { hname                                 stcobj                          stcattr            type                                   priority   default         range         supported   dependency       mandatory      procfunc                            mode                                constants}
    { ip_version                            _none_                          _none_           {CHOICES 4 6}                                2        4             _none_          true        _none_             false       _none_                             _none_                                _none_}
    { port_handle                           _none_                          _none_           ALPHANUM                                     1       _none_         _none_          true        _none_             false       _none_                             _none_                                _none_}
    { dhcp_handle                           _none_                          _none_           ALPHANUM                                     2       _none_         _none_          true        _none_             false       _none_                             _none_                                _none_}
    { action                                _none_                          _none_           {CHOICES CLEAR COLLECT}                      3       _none_         _none_          true        _none_             true        _none_                             _none_                                _none_}
 }
 { dhcp_server_stats_rx_results
    { hname                                 stcobj                          stcattr             type                                   priority   default         range         supported   dependency       mandatory      procfunc                            mode                                constants}
    { discover                              Dhcpv4ServerResults             RxDiscoverCount     _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { offer                                 _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { request                               Dhcpv4ServerResults             RxRequestCount      _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { decline                               Dhcpv4ServerResults             RxDeclineCount      _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { ack                                   _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { nak                                   _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { release                               Dhcpv4ServerResults             RxReleaseCount      _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { inform                                Dhcpv4ServerResults             RxInformCount       _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { force_renew                           _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { relay_agent                           _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
 }
 { dhcp_server_stats_tx_results
    { hname                                 stcobj                          stcattr             type                                   priority   default         range         supported   dependency       mandatory      procfunc                            mode                                constants}
    { discover                              _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { offer                                 Dhcpv4ServerResults             TxOfferCount        _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { request                               _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { decline                               _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { ack                                   Dhcpv4ServerResults             TxAckCount          _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { nak                                   Dhcpv4ServerResults             TxNakCount          _none_                                  _none_    _none_          _none_         true         _none_            false       _none_                              _none_                               _none_}
    { release                               _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { inform                                _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { force_renew                           _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
    { allocated.ip                          _none_                          _none_              _none_                                  _none_    _none_          _none_         false        _none_            false       _none_                              _none_                               _none_}
 }
}