# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Dhcp:: {
}

set ::sth::Dhcp::dhcpTable {
 ::sth::Dhcp::
 { emulation_dhcp_config
    {hname                          stcobj              stcattr                     type                            priority    default     range           supported   dependency                  mandatory   procfunc                                    mode                                                                                                constants}
    {port_handle                    _none_              _none_                      ALPHANUM                        1           _none_      0-MAX_INT       true        _none_                      false       _none_                                      {reset processDeleteCmd}                                                                            _none_}
    {mode                           _none_              _none_                      {CHOICES enable create modify reset}   2    _none_      _none_          true        _none_                      true        _none_                                      _none_                                                                                              _none_} 
    {handle                         _none_              _none_                      ALPHANUM                        3           _none_      _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {ip_version                     _none_              _none_                      {CHOICES 4 6}                   2           4           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {lease_time                     Dhcpv4PortConfig    LeaseTime                   NUMERIC                         4           _none_      10-2147483647   true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {max_dhcp_msg_size              Dhcpv4PortConfig    MaxMsgSize                  NUMERIC                         5           _none_      264-1500        true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {msg_timeout                    Dhcpv4PortConfig    MsgTimeout                  NUMERIC                         6           _none_      1000-99999000   true        _none_                      false       emulation_dhcp_config_msg_timeout           {create emulation_dhcp_config_msg_timeout modify emulation_dhcp_config_msg_timeout}                 _none_}
    {outstanding_session_count      Dhcpv4PortConfig    OutstandingSessionCount     NUMERIC                         8           _none_      1-2048          true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {release_rate                   Dhcpv4PortConfig    ReleaseRate                 NUMERIC                         9           _none_      1-10000         true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {request_rate                   Dhcpv4PortConfig    RequestRate                 NUMERIC                         10          _none_      1-10000       true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {retry_count                    Dhcpv4PortConfig    RetryCount                  NUMERIC                         11          4           0-65535            true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {retry_timer                    _none_              _none_                      NUMERIC                         15          0           _none_          false       _none_                      false       _none_                                      _none_                                                                                              _none_}
    {response_wait                  _none_              _none_                      NUMERIC                         18          _none_      _none_          false       _none_                      false       _none_                                      _none_                                                                                              _none_}
    {active                         Dhcpv4PortConfig    _none_                      FLAG                            20          _none_      _none_          false       _none_                      false       _none_                                      _none_                                                                                              _none_}
    {name                           Dhcpv4PortConfig    _none_                      ALPHANUM                        21          _none_      _none_          false       _none_                      false       _none_                                      _none_                                                                                              _none_}
    {starting_xid                   Dhcpv4PortConfig    StartingXid                 NUMERIC                         22          0           0-4294967295    true        _none_                      false       processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}
    {sequencetype                   Dhcpv4PortConfig    SeqType                     {CHOICES PARALLEL SEQUENTIAL}   3           SEQUENTIAL  _none_          true        _none_                     false        processDhcpConfigCmd                        {create processDhcpConfigCmd modify processDhcpConfigCmd}                                           _none_}               
    {broadcast_bit_flag             Dhcpv4BlockConfig   UseBroadcastFlag            {CHOICES 0 1}                   30          1           _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {relay_agent_flag               Dhcpv4BlockConfig   EnableRelayAgent            {CHOICES 0 1}                   31          _none_      _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {relay_agent_ip_addr            Dhcpv4BlockConfig   RelayAgentIpv4Addr          IPV4                            32          192.1.1.0   _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {server_ip_addr                 Dhcpv4BlockConfig   RelayServerIpv4Addr         IPV4                            33          192.1.1.2   _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {circuit_id                     Dhcpv4BlockConfig   CircuitId                   ANY                             34          0           _none_          true        _none_                      false       emulation_dhcp_config_wildcard            {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                   _none_}
    {circuit_id_suffix              Dhcpv4BlockConfig   _none_                      NUMERIC                         35          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_step         Dhcpv4BlockConfig   _none_                      NUMERIC                         37          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_repeat       Dhcpv4BlockConfig   _none_                      NUMERIC                         38          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id                      Dhcpv4BlockConfig   RemoteId                    ANY                             39          0           _none_          true        _none_                      false       emulation_dhcp_config_wildcard             {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                     _none_}
    {remote_id_suffix               Dhcpv4BlockConfig   _none_                      NUMERIC                         40          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id_suffix_step          Dhcpv4BlockConfig   _none_                      NUMERIC                         42          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id_suffix_repeat        Dhcpv4BlockConfig   _none_                      NUMERIC                         43          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {relay_pool_ip_addr             Dhcpv4BlockConfig   RelayPoolIpv4Addr           IPV4                            44          0.0.0.0     _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {remote_id_suffix_count         Dhcpv4BlockConfig   _none_                      NUMERIC                         41          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_count        Dhcpv4BlockConfig   _none_                      NUMERIC                         36          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_type                 Dhcpv4MsgOption     _none_                      NUMERIC                         45          0           0-255           true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id                      Dhcpv4MsgOption     _none_                      HEX                             46          _none_      _none_          true        _none_                      false       emulation_dhcp_config_wildcard             {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                     _none_}
    {client_id_suffix               Dhcpv4MsgOption     _none_                      NUMERIC                         47          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_count         Dhcpv4MsgOption     _none_                      NUMERIC                         48          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_step          Dhcpv4MsgOption     _none_                      NUMERIC                         49          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_repeat        Dhcpv4MsgOption     _none_                      NUMERIC                         50          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
 }
 { emulation_dhcp_group_config
    {hname                      stcobj              stcattr                 type                                                                    priority    default     range           supported   dependency                                  mandatory   procfunc                                            mode                                                            constants}
    {handle                     _none_              _none_                  ALPHANUM                                                                1           _none_      _none_          true        _none_                                      true        _none_                                              {reset processDeleteCmd}                                            _none_}
    {mode                       _none_              _none_                  {CHOICES enable create modify reset}                                    2           _none_      _none_          true        _none_                                      true        _none_                                              _none_                                                              _none_}
    {num_sessions            EmulatedDevice         DeviceCount             NUMERIC                                                                 100         _none_      1-65536         true        _none_                                      false       emulation_dhcp_group_config_num_sessions            _none_                                                              _none_}
    {encap                      _none_              _none_                  {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq ethernet_ii_mvlan ethernet_ii_mvlan vc_mux llcsnap}  3           _none_      _none_          true        _none_                                      false       _none_                                              _none_                                            _none_}
    {protocol                   _none_              _none_                  {CHOICES dhcpoe dhcpoeoa}                                               4           dhcpoe      _none_          true        _none_                                      false       _none_                                              _none_                                                              _none_}
    {mac_addr                   EthIIIf              SourceMac               MAC                                                                    5           00:10:94:00:00:02      _none_          true        _none_                                      false       emulation_dhcp_group_config_mac_addr                _none_                                                   _none_}
    {mac_addr_step              EthIIIf              SrcMacStep              MAC                                                                    6           _none_      00.00.00.00.00.01-00.00.7f.ff.ff.ff       true        _none_            false       emulation_dhcp_group_config_mac_addr                _none_                                                              _none_}
    {dhcp_range_ip_type         _none_              _none_                  {CHOICES 4 6}                                                           2            4          _none_          true        _none_                                      false       _none_                                              _none_                                                              _none_}
    {vlan_id                    VlanIf              VlanId                  NUMERIC                                                                 10          100          0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id                 _none_                                                              _none_}
    {vlan_id_outer              VlanIf_Outer        VlanId                  NUMERIC                                                                 13          100          0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_outer           _none_                                                              _none_}
    {vlan_id_step               VlanIf              IdStep                  NUMERIC                                                                 11          1            0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_step            _none_                                                              _none_}
    {vlan_id_outer_step         VlanIf_Outer        IdStep                  NUMERIC                                                                 18          1            0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_outer_step      _none_                                                              _none_}
    {vlan_id_count              VlanIf              IfRecycleCount          NUMERIC                                                                 12          0            0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_count           _none_                                                              _none_}
    {vlan_id_outer_count        VlanIf_Outer        IfRecycleCount          NUMERIC                                                                 20          0            0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_outer_count     _none_                                                              _none_}
    {vlan_id_repeat_count       _none_              _none_                  NUMERIC                                                                 12          _none_      0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_repeat_count           _none_                                                         _none_}
    {vlan_id_outer_repeat_count _none_              _none_                  NUMERIC                                                                 20          _none_      0-4095          true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_id_outer_repeat_count      _none_                                                       _none_}
    {vlan_user_priority         VlanIf              Priority                NUMERIC                                                                 5           7           0-7             true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_priority           _none_                                                              _none_}
    {vlan_outer_user_priority   VlanIf_Outer        Priority                NUMERIC                                                                 5           7           0-7             true        {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}   false       emulation_dhcp_group_config_vlan_outer_priority     _none_                                                              _none_}
    {vlan_ether_type            VlanIf              Tpid                    NUMERIC                                        							5          33024        0-65535         TRUE      {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}  FALSE        _none_   _none_                                                  _none_}
    {vlan_outer_ether_type      VlanIf_Outer        Tpid                    NUMERIC                                          						5          33024        0-65535         TRUE         {encap ethernet_ii_vlan|ethernet_ii_qinq|ethernet_ii_mvlan}  FALSE        _none_    _none_                                        _none_}
    {vlan_id_list               VlanIf_List         VlanId                  NUMERIC                                                                 10          _none_      0-4095          true        {encap ethernet_ii_mvlan|ethernet_ii_qinq}   false       _none_                                            _none_                                                              _none_}
    {vlan_id_count_list         VlanIf_List         IfRecycleCount          NUMERIC                                                                 12          0           0-4095          true       {encap ethernet_ii_mvlan}                       false       _none_                                               _none_                                                          _none_}
    {vlan_id_repeat_count_list  VlanIf_List         IdRepeatCount           NUMERIC                                                                 12          0           0-4095          true        {encap ethernet_ii_mvlan}                       false       _none_                                               _none_                                                         _none_}
    {vlan_id_step_list          VlanIf_List         IdStep                  NUMERIC                                                                 11          1           0-4095          true        {encap ethernet_ii_mvlan}                      false      _none_                                               _none_                                                          _none_}
    {vlan_user_priority_list    VlanIf_List         Priority                NUMERIC                                                                 5           7           0-7             true        {encap ethernet_ii_mvlan}                       false       _none_                                              _none_                                                              _none_}
    {vlan_ether_type_list       VlanIf_List         Tpid                    NUMERIC                                         						5          33024       0-65535          TRUE      {encap ethernet_ii_mvlan}                       FALSE          _none_                                           _none_                                                               _none_}
    {qinq_incr_mode             _none_              _none_                  {CHOICES inner outer}                                                   9           _none_      _none_          true        {encap ethernet_ii_vlan|ethernet_ii_qinq}   false       emulation_dhcp_group_config_qinq_incr_mode          _none_                                                              { inner TRUE outer FALSE}}
    {qinq_oneblock              _none_              _none_                  {CHOICES 1 0 true false}                                                38          _none_      _none_          true        {encap ethernet_ii_qinq}                    false       _none_                                              _none_                                                              _none_}
    {host_name                  Dhcpv4BlockConfig   HostName                ANY                                                                     36          client_@p-@b-@s     _none_          true        _none_                                      false       processDhcpConfigCmd                                {create processDhcpConfigCmd modify processDhcpConfigCmd}   _none_}
    {opt_list                   Dhcpv4BlockConfig   OptionList              ALPHANUM                                                                37          1          _none_          true        _none_                                      false       emulation_dhcp_group_config_opt_list                {create processDhcpConfigCmd modify processDhcpConfigCmd}           _none_}
    {gateway_addresses          _none_              _none_                  {CHOICES 0 1}                                                           70          _none_     _none_          true        _none_                                      false       _none_                                              _none_                                                              _none_}
    {gateway_ipv4_addr_step     Ipv4If              GatewayStep              IPV4                                                                   72          0.0.0.0     _none_         true    _none_                                          false       emulation_dhcp_group_config_gateway_ipv4_addr_step                 _none_         												         _none_}
    {ipv4_gateway_address       Ipv4If              Gateway                  IPV4                                                                   71          192.85.1.1  _none_          true        {gateway_addresses 1}                      false       emulation_dhcp_group_config_gateway                 _none_                                                              _none_}
    {release_rate               Dhcpv4PortConfig    _none_                  NUMERIC                                                                 22          100         1-10000          false       _none_                                      false       emulation_dhcp_group_config_release_rate            _none_                                                              _none_}
    {request_rate               Dhcpv4PortConfig    _none_                  NUMERIC                                                                 23          100         1-10000          false       _none_                                      false       emulation_dhcp_group_config_request_rate            _none_                                                              _none_}
    {vci                        Aal5If              Vci                     NUMERIC                                                                 8           32          _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {vpi                        Aal5If              Vpi                     NUMERIC                                                                 9           0           _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {vci_count                  Aal5If              VciRecycleCount         NUMERIC                                                                 25          0           _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {vci_step                   Aal5If              VciStep                 NUMERIC                                                                 26          1           _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {vpi_count                  Aal5If              IfRecycleCount          NUMERIC                                                                 27          0           _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {vpi_step                   Aal5If              VpiStep                 NUMERIC                                                                 28          1           _none_          true        _none_                                      false       emulation_dhcp_group_config_atm_settings            _none_                                                              _none_}
    {sessions_per_vc            _none_              _none_                  NUMERIC                                                                 24          _none_      _none_          false        _none_                                     false       _none_                                              _none_                                                              _none_}
    {pvc_incr_mode              _none_              _none_                  {CHOICES vci vpi both}                                                  29          _none_      _none_          true         _none_                                     false       _none_                                              _none_                                                              _none_}
    {broadcast_bit_flag             Dhcpv4BlockConfig   UseBroadcastFlag            {CHOICES 0 1}                   30          1           _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {relay_agent_flag               Dhcpv4BlockConfig   EnableRelayAgent            {CHOICES 0 1}                   31          0           _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {relay_agent_ip_addr            Dhcpv4BlockConfig   RelayAgentIpv4Addr          IPV4                            32          192.1.1.0   _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {server_ip_addr                 Dhcpv4BlockConfig   RelayServerIpv4Addr         IPV4                            33          192.1.1.2   _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {relay_agent_ipv4_subnet_mask   Dhcpv4BlockConfig   RelayAgentIpv4AddrMask      IPV4                            32          255.255.0.0 _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {enable_relay_link_selection    Dhcpv4BlockConfig   EnableRelayLinkSelection    {CHOICES 0 1}                   31          0           _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {enable_relay_vpn_id            Dhcpv4BlockConfig   EnableRelayVPNID            {CHOICES 0 1}                   31          0           _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                       {0 FALSE 1 TRUE}}
    {vpn_id                         Dhcpv4BlockConfig   VPNId                       ANY                             32          spirent_@p  _none_          true        {enable_relay_vpn_id 1}     false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {vpn_type                       Dhcpv4BlockConfig   VPNType                     {CHOICES nvt_ascii rfc_2685}    32          nvt_ascii   _none_          true        {enable_relay_vpn_id 1}     false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {relay_link_selection           Dhcpv4BlockConfig   RelayLinkSelection          IPV4                            32          192.85.1.1  _none_          true        {enable_relay_link_selection 1} false   processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {circuit_id                     Dhcpv4BlockConfig   CircuitId                   ANY                             34          0           _none_          true        _none_                      false       emulation_dhcp_config_wildcard            {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                   _none_}
    {circuit_id_suffix              Dhcpv4BlockConfig   _none_                      NUMERIC                         35          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_step         Dhcpv4BlockConfig   _none_                      NUMERIC                         37          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_repeat       Dhcpv4BlockConfig   _none_                      NUMERIC                         38          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id                      Dhcpv4BlockConfig   RemoteId                    ANY                             39          0           _none_          true        _none_                      false       emulation_dhcp_config_wildcard             {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                     _none_}
    {remote_id_suffix               Dhcpv4BlockConfig   _none_                      NUMERIC                         40          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id_suffix_step          Dhcpv4BlockConfig   _none_                      NUMERIC                         42          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remote_id_suffix_repeat        Dhcpv4BlockConfig   _none_                      NUMERIC                         43          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {relay_pool_ip_addr             Dhcpv4BlockConfig   RelayPoolIpv4Addr           IPV4                            44          0.0.0.0     _none_          true        {relay_agent_flag 1}        false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {remote_id_suffix_count         Dhcpv4BlockConfig   _none_                      NUMERIC                         41          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {circuit_id_suffix_count        Dhcpv4BlockConfig   _none_                      NUMERIC                         36          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_type                 Dhcpv4MsgOption     _none_                      NUMERIC                         45          0           0-255           true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id                      Dhcpv4MsgOption     _none_                      ANY                             46          _none_      _none_          true        _none_                      false       emulation_dhcp_config_wildcard             {create emulation_dhcp_config_wildcard modify emulation_dhcp_config_wildcard}                     _none_}
    {client_id_suffix               Dhcpv4MsgOption     _none_                      NUMERIC                         47          0           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_count         Dhcpv4MsgOption     _none_                      NUMERIC                         48          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_step          Dhcpv4MsgOption     _none_                      NUMERIC                         49          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {client_id_suffix_repeat        Dhcpv4MsgOption     _none_                      NUMERIC                         50          1           _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {enable_auto_retry              Dhcpv4BlockConfig   EnableAutoRetry             {CHOICES true false}            51          false       _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {enable_arp_server_id           Dhcpv4BlockConfig   EnableArpServerId           {CHOICES true false}            52          false       _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {enable_router_option           Dhcpv4BlockConfig   EnableRouterOption          {CHOICES true false}            53          false       _none_          true        _none_                      false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {retry_attempts                 Dhcpv4BlockConfig   RetryAttempts               NUMERIC                         54          4           _none_          true        {enable_auto_retry true}    false       processDhcpBlockInputArgs                   {create processDhcpBlockInputArgs modify processDhcpBlockInputArgs}                                 _none_}
    {option_value                   Dhcpv4MsgOption     OptionType                  NUMERIC                         6           0           0-255           true        _none_                      false       emulation_dhcp_config_msgoption             {create emulation_dhcp_config_msgoption modify emulation_dhcp_config_msgoption}                     _none_}
    {dhcpv4_custom                  Dhcpv4MsgOption     _none_                      {CHOICES 0 1}                   46          _none_      _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {option_payload                 Dhcpv4MsgOption     Payload                     ANY                             6           _none_      _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {remove_option                  Dhcpv4MsgOption     Remove                      {CHOICES true false}            6           false       _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {enable_wildcards               Dhcpv4MsgOption     EnableWildcards             {CHOICES true false}            6           false       _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {string_as_hex_value            Dhcpv4MsgOption     HexValue                    {CHOICES true false}            6           false       _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_}
    {include_in_message             Dhcpv4MsgOption     MsgTypeList                 {CHOICES discover request both} 6           both        _none_          true        _none_                      false       _none_                                      _none_                                                                                              _none_} 
}
 { emulation_dhcp_control
    {hname              stcobj              stcattr     type                            priority    default     range       supported   dependency      mandatory   procfunc    mode        constants}
    {port_handle         _none_             _none_      ALPHANUM                        1           _none_      0-MAX_INT   true        _none_          false       _none_      _none_      _none_}
    {handle              _none_             _none_      ALPHANUM                        2           _none_      _none_      true        _none_          false       _none_      _none_      _none_}
    {ip_version          _none_             _none_      {CHOICES 4 6}                   2           4           _none_      true        _none_          false       _none_      _none_      _none_}
    {action             Dhcpv4PortConfig    _none_      {CHOICES bind release renew rebind abort}    5           _none_      _none_      true        _none_          true        _none_      _none_      _none_}
    {apply              _none_              _none_      FLAG                            26          _none_      _none_      true        _none_          false       _none_      _none_      {TRUE _none_ FALSE _none_}}
 }
 { emulation_dhcp_stats
    {hname                              stcobj                  stcattr             type                            priority    default     range   supported   dependency  mandatory   procfunc                                mode        constants}
    {action                             _none_                  _none_              {CHOICES clear collect }        2           collect     _none_  true        _none_      false       _none_                                  _none_      _none_}
    {handle                             _none_                  _none_              ALPHANUM                        25          _none_      _none_  true        _none_      false       _none_                                  _none_      _none_}
    {mode                               _none_                  _none_              {CHOICES aggregate session detailed_session}     3           session     _none_  true        _none_      false       _none_                                  _none_      _none_}
    {port_handle                        _none_                  _none_              ALPHANUM                        26          _none_      _none_  true        _none_      false       _none_                                  _none_      _none_}
    {ip_version                         _none_                  _none_              {CHOICES 4 6}                   2           4           _none_  true        _none_      false       _none_                                  _none_      _none_}
    {aggregate.elapsed_time             Dhcpv4PortResults       _none_              ANY                             30          _none_      _none_  true        _none_      false       processDHCPGetElapsedTime               _none_      _none_}
    {aggregate.currently_attempting     Dhcpv4PortResults       _none_              ANY                             31          _none_      _none_  true        _none_      false       processDHCPGetCurrentlyAttempting       _none_      _none_}
    {aggregate.currently_idle           Dhcpv4PortResults       CurrentIdleCount    ANY                             32          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.currently_bound          Dhcpv4PortResults       CurrentBoundCount   ANY                             33          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.total_attempted          Dhcpv4PortResults       TotalAttemptCount   ANY                             34          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.total_retried            Dhcpv4PortResults       TotalRetriedCount   ANY                             35          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.total_bound              Dhcpv4PortResults       TotalBoundCount     ANY                             36          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.bound_renewed            Dhcpv4PortResults       TotalRenewedCount   ANY                             62          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.total_failed             Dhcpv4PortResults       TotalFailedCount    ANY                             37          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.bind_rate                Dhcpv4PortResults       BindRate            ANY                             38          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.attempted_rate           Dhcpv4PortResults       AttemptRate         ANY                             39          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.success_percentage       Dhcpv4PortResults       SuccessPercent      ANY                             40          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.minimum_setup_time       Dhcpv4PortResults       MinSetupTime        ANY                             41          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.maximum_setup_time       Dhcpv4PortResults       MaxSetupTime        ANY                             42          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.average_setup_time       Dhcpv4PortResults       AvgSetupTime        ANY                             43          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.discover_tx_count        Dhcpv4PortResults       TxDiscoverCount     ANY                             44          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.request_tx_count         Dhcpv4PortResults       TxRequestCount      ANY                             45          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.release_tx_count         Dhcpv4PortResults       TxReleaseCount      ANY                             46          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.ack_rx_count             Dhcpv4PortResults       RxAckCount          ANY                             47          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.nak_rx_count             Dhcpv4PortResults       RxNakCount          ANY                             48          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {aggregate.offer_rx_count           Dhcpv4PortResults       RxOfferCount        ANY                             49          _none_      _none_  true        _none_      false       processDHCPGetCmd                       _none_      _none_}
    {elapsed_time                       Dhcpv4BlockResults      ElapsedTime         ANY                             1           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {currently_attempting               Dhcpv4BlockResults      CurrentAttemptCount    ANY                             2           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {currently_idle                     Dhcpv4BlockResults      CurrentIdleCount       ANY                             3           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {currently_bound                    Dhcpv4BlockResults      CurrentBoundCount      ANY                             4           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {total_attempted                    Dhcpv4BlockResults      TotalAttemptCount   ANY                             5           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {total_retried                      Dhcpv4BlockResults      TotalRetriedCount   ANY                             6           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {bound_renewed                      Dhcpv4BlockResults      TotalRenewedCount   ANY                             7           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {total_bound                        Dhcpv4BlockResults      TotalBoundCount     ANY                             8           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {total_failed                       Dhcpv4BlockResults      TotalFailedCount    ANY                             9           _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {bind_rate                          Dhcpv4BlockResults      BindRate            ANY                             10          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {attempt_rate                       Dhcpv4BlockResults      AttemptRate         ANY                             11          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {request_rate                       Dhcpv4BlockResults      _none_              ANY                             12          _none_      _none_  true        _none_      false       processUnsprtDHCPGroupGetCmd            _none_      _none_}
    {release_rate                       Dhcpv4BlockResults      _none_              ANY                             13          _none_      _none_  true        _none_      false       processUnsprtDHCPGroupGetCmd            _none_      _none_}
    {discover_tx_count                  Dhcpv4BlockResults      TxDiscoverCount     ANY                             14          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {request_tx_count                   Dhcpv4BlockResults      TxRequestCount      ANY                             15          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {release_tx_count                   Dhcpv4BlockResults      TxReleaseCount      ANY                             16          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {ack_rx_count                       Dhcpv4BlockResults      RxAckCount          ANY                             17          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {nak_rx_count                       Dhcpv4BlockResults      RxNakCount          ANY                             18          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {offer_rx_count                     Dhcpv4BlockResults      RxOfferCount        ANY                             19          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {discover_resp_time                 Dhcpv4SessionResults      DiscRespTime     ANY                             14          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {error_status                       Dhcpv4SessionResults      ErrorStatus      ANY                             15          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {ipv4_addr                          Dhcpv4SessionResults      Ipv4Addr         ANY                             16          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {lease_left                         Dhcpv4SessionResults      LeaseLeft        ANY                             17          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {lease_rx                           Dhcpv4SessionResults      LeaseRx          ANY                             18          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {mac_addr                           Dhcpv4SessionResults      MacAddr          ANY                             19          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {request_resp_time                  Dhcpv4SessionResults      RequestRespTime  ANY                             15          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {session_state                      Dhcpv4SessionResults      SessionState     ANY                             16          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {vci                                Dhcpv4SessionResults      Vci              ANY                             17          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {vlan_id                            Dhcpv4SessionResults      VlanId           ANY                             18          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
    {vpi                                Dhcpv4SessionResults      Vpi              ANY                             19          _none_      _none_  true        _none_      false       processDHCPGroupGetCmd                  _none_      _none_}
 }
}
