# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::fcoetraffic:: {
}

set ::sth::fcoetraffic::fcoetrafficTable {
   ::sth::fcoetraffic::
   {fcoe_traffic_config
      {hname              stcobj           stcattr          type              priority     default     range     supported          dependency     mandatory         mode     procfunc    constants}
      {handle      _none_         _none_      ALPHANUM        1          _none_          _none_          TRUE            _none_            TRUE         {create "" modify "" reset ""}       _none_    _none_}
      {mode      _none_         _none_      {CHOICES create modify reset}         1          _none_          _none_          TRUE            _none_   TRUE         {create "" modify "" reset ""}       _none_    _none_}
      {version      fc:fcoe        version      NUMERIC         2          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved1      fc:fcoe         reserved1      ANY         3          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved2      fc:fcoe         reserved2      ANY         4          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved3      fc:fcoe         reserved3      ANY         5         _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved4      fc:fcoe         reserved4      ANY         6          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {sof      fc:fcoe         sof      {CHOICES soff sofi2 sofn2 sofi3 sofn3 sofi4 sofn4 sofc4}         7          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {soff 28 sofi2 2D sofn2 35 sofi3 2E sofn3 36 sofi4 29 sofn4 31 sofc4 39}}
      {eof      fc:fcoe         eof      {CHOICES eofn eoft eofni eofa eofdt eofdti eofrt eofrti}         8          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {eofn 41 eoft 42 eofni 49 eofa 50 eofdt 46 eofdti 4E eofrt 44 eofrti 4F}}
      {reserved5      fc:fcoe         reserved5      ANY         9          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {h_rctl      fcheader         rCtl      ANY         10          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {efpacc 03 efpreq 02 diaacc 02 diareq 02 escacc 03 escreq 02  lsurequest 02 lsarequest 02 hlorequest 02 ganxtaccetp 02}}
      {h_type      fcheader         type      ANY       11          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {efpacc 00  efpreq 22 diaacc 22 diareq 22 escacc 22 escreq 22 lsurequest 22 lsarequest 22 hlorequest 22 ganxtaccetp 22}}
      {h_csctl    fcheader         csCtl    ANY         12          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_did       fcheader         dId      ANY         13          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_sid       fcheader         sId       ANY         14          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_framecontrol      fcheader         frameControl      ANY         15          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_seqid      fcheader         seqId      ANY         16          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_dfctl      fcheader         dfCtl      ANY         17          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_seqcnt      fcheader         seqCnt      ANY         18          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_origexchangeid     fcheader         origExchangeID      ANY         19          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_responseexchangeid      fcheader         responseExchangeId      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_parameter      fcheader         parameter      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {pl_id      _none_         _none_      {CHOICES custom plogireq plogiacc plogirjt flogireq flogiacc flogirjt fdiscreq fdiscacc fdiscrjt  logoreq  logoacc logorjt fcpcmnd efpreq efpacc diareq diaacc escreq escacc hloreq lsureq lsareq ganxtacc gpnidacc gnnidacc gcsidacc gftidacc gptidacc gfpnidacc gspnidacc gffidacc gidpnacc gidnnacc gsnnnnacc gidftacc gpnftacc gnnftacc rsnnnn rffid rspnid rptid rftid rcsid rnnid rpnid daid mergereq mergereqacc}         1          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {custom customPayload plogireq plogirequest plogiacc plogiaccept plogirjt plogireject flogireq flogirequest flogiacc flogiaccept flogirjt flogireject fdiscreq fdiscrequest fdiscacc fdiscaccept fdiscrjt fdiscreject logoreq logorequest logoacc logoaccept logorjt logoreject fcpcmnd fcpcmnd-fcpcdb efpreq efprequest efpacc efpaccept diareq diarequest diaacc diaaccept escreq escrequest escacc escaccept hloreq hlorequest lsureq lsurequest lsareq lsarequest ganxtacc ganxtaccept gpnidacc gpnidaccept gpnidacc gpnidaccept gnnidacc gnnidaccept gcsidacc gcsidaccept gftidacc gftidaccept gptidacc gptidaccept gffidacc gffidaccept gfpnidacc gfpnidaccept gidpnacc gidpnaccept gidnnacc gidnnaccept gsnnnnacc gsnnnnaccept  gspnidacc gspnidaccept gidftacc gidftaccept gpnftacc gpnftaccept gnnftacc gnnftaccept rsnnnn rsnnnn rffid rffid rspnid rspnid rptid rptid rftid rftid rcsid rcsid rnnid rnnid rpnid rpnid daid daid mergereq mergerequest mergereqacc  mergerequestacc}}
      {pl_command      _none_         _none_      ANY      22          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {efpacc 02}}
      {pl_payload      payload      Payload       ANY         22          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_reserved1     plogirequest/plogiaccept/plogireject/flogirequest/flogiaccept/flogireject/fdiscrequest/fdiscaccept/fdiscreject/logorequest/logoaccept/logoreject/hlorequest/rffid      reserved1     ANY         24          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nportname     plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept      nportname     ANY         25          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nodename     plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept      nodename     ANY         26          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_vendorversionlevel     plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept      vendorversionlevel     ANY         27          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_reasoncode     plogireject/flogireject/fdiscreject/logoreject     reasonCode     ANY         28          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_explanationcode     plogireject/flogireject/fdiscreject/logoreject     reasonExplanation     ANY         29          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_vendorunique     plogireject/flogireject/fdiscreject/logoreject     vendorUnique     ANY         30          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nportid  logorequest     nPortId     ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_portname  logorequest     PortName     ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_commonsvcparams  plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept/-commonsvcparams     _none_     ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class1svcparams  plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept/-class1svcparams     _none_     ANY         32          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class2svcparams  plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept/-class2svcparams      _none_     ANY         33          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class3svcparams  plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept/-class3svcparams     _none_     ANY         34          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class4svcparams  plogirequest/plogiaccept/flogirequest/flogiaccept/fdiscrequest/fdiscaccept/-class4svcparams     _none_     ANY         35          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {pl_cdbtype _none_  _none_ {CHOICES cdb6 cdb10 r_6 r_10 r_buff r_l10 r_capacity10 w_6 w_10 w_buff w_l10 w_verify10 xd_r10 xd_w10 ssu ms_6 ms_10 r_lun }         36          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {cdb6 cdb6 cdb10 cdb10 r_6 read6 r_10 read10 r_buff readBuffer r_l10 readLong10 r_capacity10 readCapacity10 w_6 write6 w_10 write10 w_buff writeBuffer w_l10 writeLong10 w_verify10 writeAndVerify10 xd_r10 xdRead10 xd_w10 xdWrite10 ssu startStopUnit ms_6 modeSense6 ms_10 modeSense10 r_lun reportLUNs}}
      {pl_fcplun  fcpcmnd     fcpLun     ANY         37          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cmndrefnum  fcpcmnd     cmndRefNum     ANY         38          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_reserved  fcpcmnd/efprequest/efpaccept/escaccept     reserved     ANY         39          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_priority  fcpcmnd     priority     ANY         40          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_taskattrib  fcpcmnd     taskAttrib     ANY         41          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_taskmgmtflags  fcpcmnd     taskMgmtFlags     ANY         42          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_addifcpcdblen  fcpcmnd     additionalFcpCdbLen     ANY         43          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_rdata   fcpcmnd     rdData      ANY         44          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_wdata   fcpcmnd     wrData      ANY         45          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_fcpdl   fcpcmnd     fcpDl      ANY         47          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_fcpbirddl   fcpcmnd     fcpBiDirReadDl      ANY         48          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {pl_cdb_miscinfo cdb6 miscinfo         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_miscinfo1 cdp10 miscinfo         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_lba cdb6/cdb10/read6/read10/readlong10/readcapacity10/write6/write10/writelong10/writeandverify10/xdread10 lba           ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_len cdb6/cdb10 length          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_control cdb6/cdb10/read6/read10/readbuffer/readlong10/readcapacity10/write6/write10/writebuffer/writelong10/writeandverify10/xdread10/xdwrite10/startstopunit/modesense6/modesense10/reportluns control          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_service cdb10  service          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_miscinfo2 cdb10 miscinfo2          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_reserved read6/readbuffer/write6/writebuffer/startstopunit reserved          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_transferlen read6/read10/readlong10/write6/write10/writelong10/writeandverify10/xdread10/xdwrite10 transferlength          ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_rdprotect	read10 rdprotect	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_dpo	read10/write10/writeandverify10/xdwrite10 dpo	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_fua	read10/write10/xdwrite10 fua	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_fua_nv 	read10/write10/xdwrite10 fua_nv	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_obsolete	read10/readlong10/readcapacity10/write10/writelong10/writeandverify10 obsolete	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_reserved2	read10/readlong10/readcapacity10/write10/writelong10/writeandverify10/xdwrite10/startstopunit/modesense6/modesense10/reportluns reserved2	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_groupnum	read10/write10/writeandverify10/xdread10/xdwrite10 groupnumber	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_mode	readbuffer/writebuffer mode	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_bufferid	readbuffer/writebuffer bufferid	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_bufferoffset	readbuffer/writebuffer bufferoffset	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_allolen	readbuffer/modesense6/modesense10/reportluns allocationlength	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pblock	readlong10 pblock	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_corrct	readlong10 corrct	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_reserved3	readcapacity10/startstopunit/modesense10/reportluns reserved3	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pmi	readcapacity10 pmi	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_wrprotect	write10/writeandverify10/xdwrite10 wrprotect	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_paramlistlen	writebuffer paramlistlength	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_wr_uncor	writelong10 wr_uncor	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_core_dis		writelong10 core_dis		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_xorpinfo	xdread10 xorpinfo	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_disablewr	xdwrite10 disablewrite	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_immed		startstopunit immed		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_reserved1	read10/readlong10/readcapacity10/write10/writelong10/writeandverify10/xdread10/xdread10/xdwrite10/startstopunit/modesense6/modesense10/reportluns reserved1	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pwrcondmod	startstopunit pwrcondmod	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pwrcond	startstopunit pwrcond	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_noflush		startstopunit noflush		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_loej		startstopunit loej		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_start		startstopunit start		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_dbd		modesense6/modesense10 dbd		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pc		modesense6/modesense10 pc		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_pagecode	modesense6/modesense10 pagecode	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_subpagecode	modesense6/modesense10 subpagecode	         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_llbaa		modesense10 llbaa		         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_cdb_selectreport	reportluns selectreport         ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {pl_recordlen  efprequest    recordlength  ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_principalswitchpriority efprequest/efpaccept    principalswitchpriority ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_principalswitchname    efprequest/efpaccept    principalswitchname    ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_domainid_lists    efprequest/-domainids-efpdomainidrecord      _none_      ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_multiid_lists    efprequest/-multicastids-efpmulticastidrecord      _none_      ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_pagelen    efpaccept pagelength    ANY  50  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_originswitchname diarequest originatingswitchname      ANY  51  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_notmeaningful    diarequest/diaaccept notmeaningful        ANY  51  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_respondswitchname diaaccept respondingswitchname            ANY  51  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_reserved lsurequest/lsarequest/escaccept/gidpnaccept/rspnid/rptid/rftid/rcsid/rnnid/rpnid/daid/mergerequestacc     reserved  ANY  52  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_flags escrequest/escaccept/lsurequest/lsarequest flags ANY  52  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_vendorescid escrequest/escaccept/-vendorescid _none_  ANY  52  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_lsr_lists lsurequest/-lsrs-linkstaterecord  _none_   ANY  53  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_fspfheader lsurequest/lsarequest/hlorequest/-fspfheader _none_  ANY  53  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_lsh_lists lsarequest/-lsrs-linkstateheader _none_  ANY  53  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_reserved2    hlorequest/rffid     reserved2  ANY  54  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_hellointerval hlorequest     hellointerval  ANY  54  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_deadinterval  hlorequest     deadinterval  ANY  54  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_rxdomainid   hlorequest     recipientdomainid  ANY  54  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_origiportindex   hlorequest     originatingportindex   ANY  54  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_ctiu    ganxtaccept/gpnidaccept/gnnidaccept/gcsidaccept/gftidaccept/gspnidaccept/gptidaccept/gfpnidaccept/gffidaccept/gidpnaccept/gidnnaccept/gsnnnnaccept/gidftaccept/gpnftaccept/gnnftaccept/rsnnnn/rffid/rspnid/rptid/rftid/rcsid/rnnid/rpnid/daid/-ctiupreamble    _none_    ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_porttype    ganxtaccept/gptidaccept/rptid        porttype        ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    {unidentified 00 nxport 7f nlport 02 nport 01 flport 82 fport 81 fnlport 03 eport 84 bport 85}}
      {pl_portid    ganxtaccept/gidpnaccept/rffid/rspnid/rptid/rftid/rcsid/rnnid/rpnid/daid      portidentifier       ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_portname    ganxtaccept/gpnidaccept/rpnid        portname         ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_nodename    ganxtaccept/gnnidaccept/rsnnnn/rnnid        nodename        ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_initprocessassociator    ganxtaccept       initialprocessassociator    ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_ipaddrnode    ganxtaccept   ipaddressnode       ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_classofservice    ganxtaccept/gcsidaccept/rcsid  classofservice         ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_fc4types    ganxtaccept/gftidaccept/rftid  fc4types        ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_ipaddrport    ganxtaccept  ipaddressport        ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_fabricportname    ganxtaccept/gfpnidaccept  fabricportname        ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_reserved3    ganxtaccept  reserved3             ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_hardaddr    ganxtaccept    hardaddress       ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_symbolicportname ganxtaccept/gspnidaccept/rspnid    symbolicportname       ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_fc4features gffidaccept   fc4features  ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_symbolicnodename ganxtaccept/gsnnnnaccept/rsnnnn    symbolicnodename       ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_portidentifier_list gidnnaccept/gidftacc/-portidentifiers-portidentifier _none_   ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_portname_list gpnftaccept/-portnames-portname _none_   ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_nodename_list gnnftaccept/-nodenames-nodename _none_   ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_fc4featurebits   rffid   fc4featurebits  ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_typecode   rffid   typecode  ANY  55  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      
      {pl_protocolver   mergerequest  protocolversion  ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_basiczoning_list mergerequest/-payload-mrpayloadchoice-basiczoning     _none_   ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_enhancezoning_list  mergerequest/-payload-mrpayloadchoice-enhancedzoning     _none_   ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_obsolete1  mergerequestacc   obsolete1   ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_obsolete2  mergerequestacc   obsolete2   ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
      {pl_obsolete3  mergerequestacc   obsolete3   ANY  56  _none_   _none_   TRUE  _none_   FALSE {create "" modify "" reset ""}   _none_    _none_}
   }
   {fip_traffic_config
      {hname                                    stcobj                                    stcattr                        type     priority     default         range        supported          dependency       mandatory         mode     procfunc    constants}
      {handle                                   _none_                                    _none_                        ALPHANUM    1          _none_          _none_          TRUE            _none_            TRUE         {create "" modify "" reset ""}       _none_    _none_}
      {mode                                     _none_                                    _none_                        {CHOICES create modify reset}  1  _none_   _none_      TRUE            _none_            TRUE         {create "" modify "" reset ""}       _none_    _none_}
      {version                                  fc:fip                                    version                       NUMERIC     2          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved1                                fc:fip                                    reserved1                     ANY         3          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {operationcode                            fc:fip                                    fipOperationCode              ANY         4          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved2                                fc:fip                                    reserved2                     ANY         5          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {subcode                                  fc:fip                                    fipSubCode                    ANY         6          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fp                                       fc:fip                                    fp                            ANY         7          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {sp                                       fc:fip                                    sp                            ANY         8          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {reserved3                                fc:fip                                    reserved3                     ANY         9          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {a                                        fc:fip                                    a                             ANY         10          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {s                                        fc:fip                                    s                             ANY         11          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {f                                        fc:fip                                    f                             ANY         12          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {padding                                  fc:fip                                    padding                       ANY         13          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {dl_id                                    _none_                                    _none_                        {CHOICES vlan priority macaddr fcmap nameid fabricname maxrcvsize flogireq flogiacc flogirjt fdiscreq fdiscacc fdiscrjt logoreq logoacc logorjt vxport fka_adv_period vendorid elpreq elpacc elprjt }         14          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    {vlan vlandescriptor priority priority macaddr macAddr fcmap fcMap nameid nameId fabricname fabricName maxrcvsize maxRcvSize flogireq flogirequest-flogi-fc flogiacc flogiaccept-flogiacc-fc  flogirjt flogireject-flogirjt-fc  fdiscreq npivfdiscrequest-fdisc-fc   fdiscacc npivfdiscaccept-fdiscacc-fc   fdiscrjt npivfdiscreject-fdiscrjt-fc   logoreq fabriclogorequest-logo-fc   logoacc fabriclogoaccept-logoacc-fc   logorjt fabriclogoreject-logorjt-fc  vxport vxportid fka_adv_period fkaadvperiod vendorid vendorid elpreq elprequest-elp elpacc elpaccept-elp elprjt elpreject-elprjt}}
      {vlanid                                   vlandescriptor                            vlanid                        ANY         15          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {priority_reserved                        priority                                  reserved                      ANY         15          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {priority                                 priority                                  priority                      ANY         15          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {macaddr                                  macaddr                                   macaddr                       ANY         16          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fcmap_reserved                           fcmap                                     reserved                      ANY         17          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fcmap                                    fcmap                                     fcmap                         ANY         17          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {nameid_reserved                          nameid                                    reserved                      ANY         18          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {nameid                                   nameid                                    nameid                        ANY         18          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fabricname_reserved                      fabricname                                reserved                      ANY         19          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fabricname                               fabricname                                fabricname                    ANY         19          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {maxrcvsize                               maxrcvsize                                maxreceivesize                ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vxport_macaddr                           vxportid                                  macaddr                       ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vxport_reserved                          vxportid                                  reserved                      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vxport_addrid                            vxportid                                  addressidentifier             ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vxport_portname                          vxportid                                  portname                      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fkaadvperiod                             fkaadvperiod                              fkaadvperiod                  ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fka_reserved                             fkaadvperiod                              reserved                      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vendorid                                 vendorid                                  vendorid                      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {vendorid_reserved                        vendorid                                  reserved                      ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {flogireq_reserved                        flogirequest                              reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {flogiacc_reserved                        flogiaccept                               reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {flogirjt_reserved                        flogireject                               reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fdiscreq_reserved                        npivfdiscrequest                          reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fdiscacc_reserved                        npivfdiscaccept                           reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {fdiscrjt_reserved                        npivfdiscreject                           reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {logoreq_reserved                         fabriclogorequest                         reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {logoacc_reserved                         fabriclogoaccept                          reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {logorjt_reserved                         fabriclogoreject                          reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {elpreq_reserved                          elprequest                                reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {elpacc_reserved                          elpaccept                                 reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {elprjt_reserved                          elpreject                                 reserved                      ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {h_rctl                                   fc                                        rCtl                          ANY         10          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_did                                    fc                                        dId                           ANY         11          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_csctl                                  fc                                        csCtl                         ANY         12          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_sid                                    fc                                        sId                           ANY         13          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_type                                   fc                                        type                          ANY         14          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_framecontrol                           fc                                        frameControl                  ANY         15          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_seqid                                  fc                                        seqId                         ANY         16          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_dfctl                                  fc                                        dfCtl                         ANY         17          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_seqcnt                                 fc                                        seqCnt                        ANY         18          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_origexchangeid                         fc                                        origExchangeID                ANY         19          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_responseexchangeid                     fc                                        responseExchangeId            ANY         20          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {h_parameter                              fc                                        parameter                     ANY         21          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      
      {pl_reserved1              flogi/flogiacc/flogirjt/fdisc/fdiscacc/fdiscrjt/logo/logoacc/logorjt/elprjt  reserved1 ANY         24          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nportname              flogi/flogiacc/fdisc/fdiscacc                            nportname                     ANY         25          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nodename               flogi/flogiacc/fdisc/fdiscacc                            nodename                      ANY         26          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_vendorversionlevel     flogi/flogiacc/fdisc/fdiscacc                            vendorversionlevel            ANY         27          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_reasoncode             flogirjt/fdiscrjt/logorjt/elprjt                         reasonCode                    ANY         28          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_explanationcode        flogirjt/fdiscrjt/logorjt/elprjt                         explanationcode               ANY         29          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_vendorunique           flogirjt/fdiscrjt/logorjt/elprjt                         vendorunique                  ANY         30          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_nportid                               logo                                      nPortId                       ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_portname                              logo                                      PortName                      ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_commonsvcparams        flogi/flogiacc/fdisc/fdiscacc/-commonsvcparams           _none_                        ANY         31          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class1svcparams        flogi/flogiacc/fdisc/fdiscacc/-class1svcparams           _none_                        ANY         32          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class2svcparams        flogi/flogiacc/fdisc/fdiscacc/-class2svcparams           _none_                        ANY         33          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class3svcparams        flogi/flogiacc/fdisc/fdiscacc/-class3svcparams           _none_                        ANY         34          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
      {pl_class4svcparams        flogi/flogiacc/fdisc/fdiscacc/-class4svcparams           _none_                        ANY         35          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
   
     {pl_code                                   elp                                       code                          ANY         36          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_revision                               elp                                       revision                      ANY         37          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_flags                                  elp                                       flags                         ANY         38          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_bbscn                                  elp                                       bbscn                         ANY         39          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_ratov                                  elp                                       ratov                         ANY         40          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_edtov                                  elp                                       edtov                         ANY         41          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_reqinterconnportname                   elp                                       reqinterconnportname          ANY         42          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_reqswitchname                          elp                                       reqswitchname                 ANY         43          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_reserved                               elp                                       reserved                      ANY         44          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_classfsvcparams                        elp/-classfsvcparams                      _none_                        ANY         45          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_class1interconnectportparams           elp/-class1interconnectportparams         _none_                        ANY         46          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_class2interconnectportparams           elp/-class2interconnectportparams         _none_                        ANY         47          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_class3interconnectportparams           elp/-class3interconnectportparams         _none_                        ANY         48          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_islflowcontrol                         elp-islflowcontrol-rrdy                   _none_                        ANY         49          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_commandcode                            elprjt                                    commandcode                   ANY         50          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
     {pl_reserved2                              logorjt/elprjt                            reserved2                     ANY         52          _none_          _none_          TRUE            _none_            FALSE         {create "" modify "" reset ""}       _none_    _none_}
   }
}
