# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Gre:: {
}

set ::sth::Gre::greTable {
 ::sth::Gre::
 { emulation_gre_config
    {hname                          stcobj              stcattr                     type                           priority    default      range           supported   dependency  mandatory   procfunc                            mode                                                 constants}
    {mode                           _none_              _none_                      {CHOICES create modify}         2          create      _none_           true        _none_       false        _none_                            _none_                                              _none_}
    {gre_count                      EmulatedDevice      DeviceCount                 NUMERIC                         4            1          1-100000        true        _none_      false       _none_                              _none_                                                 _none_}
    {gre_tnl_type                   _none_              _none_                     {CHOICES 4  6}                   1           _none_      _none_          true        _none_      true       _none_                               _none_                                                 _none_}
    {gre_tnl_addr                   Ipv4If              Gateway                     ANY                             2           _none_      _none_          true        _none_      false        _none_                             _none_                                                 _none_}
    {gre_tnl_addr_step              Ipv4If              GatewayStep                 ANY                            3           _none_      _none_          true        _none_      false       _none_                               _none_                                                 _none_}
    {gre_tnl_addr_count             _none_              _none_                      NUMERIC                         4           1           _none_          true        _none_      false       _none_                              _none_                                                 _none_}
    {gre_port_handle                _none_              _none_                     ALPHANUM                         1          _none_        _none_         true         _none_     false       _none_                              _none_                                                 _none_}
    {gre_src_mac_addr               Ethiiif             SourceMac                  ANY                              3          _none_       _none_          true        _none_      false       none                                _none_                                                 _none_}
    {gre_src_mac_addr_step          Ethiiif             SrcMacStep                 ANY                              3          _none_       _none_          true        _none_      false       _none_                              _none_                                                 _none_}   
    {gre_src_mode                   _none_              _none_                {CHOICES increment  fixed}            5           fixed       _none_          true        _none_      false      _none_                               _none_                                                _none_}
    {gre_src_addr                   Ipv4If              Address                     ANY                             6           _none_      _none_          true        _none_      false       _none_                              _none_                                                 _none_}
    {gre_src_addr_step              Ipv4If              AddrStep                      ANY                             8           _none_      _none_          true        _none_      false       _none_                              _none_                                                _none_}
    {gre_src_addr_count             _none_              _none_                      NUMERIC                         9           1           _none_          true        _none_      false       _none_                              _none_                                                _none_}
    {gre_dst_mode                   _none_              _none_                {CHOICES increment  fixed}            10          fixed       _none_          true        _none_      false      _none_                               _none_                                                _none_}
    {gre_dst_addr                   GreIf               RemoteTunnelEndPointV4      ANY                             11          _none_      _none_          true        _none_      false       _none_                              _none_                                                _none_}
    {gre_dst_addr_step	            GreIf	            RemoteTunnelEndPointV4Step  ANY 	                        12          _none_      _none_          true	    _none_      false         _none_                            _none_                                                _none_ }                                                                  
    {gre_prefix_len                 Ipv4If              PrefixLength                ANY                             11          24          _none_          true        _none_      false       _none_                              _none_                                                _none_}
    {gre_dst_addr_count	            _none_              _none_                      NUMERIC 	                    13	        1           _none_          true        _none_      false        _none_                             _none_                                                _none_ }                            
    {gre_checksum                   _none_              _none_			          {CHOICES  0  1}                   19          0           _none_          true        _none_      false        _none_                             _none_                                                  _none_ }    
    {gre_in_key                     GreIf               value                       NUMERIC                         20          _none_      _none_          true        _none_      false       _none_                              _none_                                                _none_}
    {gre_out_key                    GreIf               value                       NUMERIC                         21          _none_      _none_          true        _none_      false       _none_                               _none_                                               _none_} 
    {gre_qinq_incr_mode             _none_              _none_                     {CHOICES inner both}             4           outer       _none_          true        _none_                  false       _none_                                            _none_     _none_}
    {gre_encapsulation              _none_              _none_                     {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}  4           ethernet_ii     _none_          true        _none_                  false       _none_                                            _none_     _none_}
    {gre_vlan_id                    VlanIf              VlanId                       NUMERIC                        4               _none_      _none_      true        _none_       false       _none_                      {create configVlanIfInner modify configVlanIfInner}          _none_}
    {gre_vlan_id_step               VlanIf              IdStep                       NUMERIC                        4               _none_      _none_      true        _none_       false       _none_                      {create configVlanIfInner modify configVlanIfInner}          _none_}
    {gre_vlan_id_count              VlanIf              IfRecycleCount               NUMERIC                        4               1           _none_      true        _none_       false       _none_                      {create configVlanIfInner modify configVlanIfInner}          _none_}        
    {gre_vlan_user_priority              VlanIf              Priority                     NUMERIC                        4               _none_      0-7         true        _none_       false       _none_                      {create configVlanIfInner modify configVlanIfInner}          _none_}
    {gre_vlan_outer_id              VlanIf_Outer        VlanId                       NUMERIC                        4               _none_      _none_      true        _none_       false       _none_                      {create configVlanIfOuter modify configVlanIfOuter}          _none_}
    {gre_vlan_outer_id_step         VlanIf_Outer        IdStep                       NUMERIC                        4               _none_      _none_      true        _none_       false       _none_                      {create configVlanIfOuter modify configVlanIfOuter}          _none_}
    {gre_vlan_outer_id_count        VlanIf_Outer        IfRecycleCount               NUMERIC                        4               1           _none_      true        _none_       false       _none_                      {create configVlanIfOuter modify configVlanIfOuter}          _none_}        
    {gre_vlan_outer_user_priority        VlanIf_Outer        Priority                     NUMERIC                        4               _none_      0-7         true        _none_       false       _none_                      {create configVlanIfOuter modify configVlanIfOuter}          _none_}
    {gre_handle                     _none_              _none_			     ANY                            2               _none_      _none_      true        _none_       false        _none_                             _none_                                           _none_ }           
    }
}
