namespace eval ::sth::http:: {
}

set ::sth::http::httpTable {
    ::sth::http::
    {   emulation_http_profile_config
        {   hname                                   stcobj                      stcattr                             type                                priority    default             range           supported   dependency  mandatory   procfunc    mode                            constants   }
        {   body_content_type                       HttpServerResponseConfig    BodyContentType                     {CHOICES ascii binary}              1           ascii               _none_          true        _none_      false       _none_      {create server_response_config modify server_response_config}           {ascii ASCII binary BINARY}       }
        {   body_size_type                          HttpServerResponseConfig    BodySizeType                        {CHOICES fixed random}              1           fixed               _none_          true        _none_      false       _none_      {create server_response_config modify server_response_config}           {fixed FIXED random RANDOM}      }
        {   enable_delayed_ack                      ClientProfile|ServerProfile  EnableDelayedAck                    {CHOICES true false}                1           false               _none_          true        _none_      false       _none_      {create client_server_profile_config modify client_server_profile_config}           {true TRUE false FALSE}      }
        {   enable_keep_alive                       HttpClientProtocolProfile   EnableKeepAlive                     {CHOICES true false}                1           true                _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {true TRUE false FALSE}      }
        {   enable_pipeline                         HttpClientProtocolProfile   EnablePipelining                    {CHOICES true false}                1           ture                _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {true TRUE false FALSE}      }
        {   enable_video_client                     HttpClientProtocolProfile   EnableVideoClient                   {CHOICES true false}                1           false               _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {true TRUE false FALSE}      }
        {   enable_video_server                     HttpServerProtocolProfile   EnableVideoServer                   {CHOICES true false}                1           false               _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           {true TRUE false FALSE}      }
        {   fixed_body_size                         HttpServerResponseConfig    FixedBodySize                       NUMERIC                             1           64                  0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   fixed_response_latency                  HttpServerResponseConfig    FixedResponseLatency                NUMERIC                             1           0                   0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   http_version            HttpServerProtocolProfile|HttpClientProtocolProfile     HttpVersion                         {CHOICES version_1_0 version_1_1}   1           version_1_1         _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           _none_      }
        {   ipv4_tos                                ClientProfile|ServerProfile                      Ipv4Tos                             NUMERIC                             1           192                 0-255           true        _none_      false       _none_      {create client_server_profile_config modify client_server_profile_config}           _none_      }
        {   tos_type                           ClientProfile|ServerProfile                      TosType                             {CHOICES tos diffserv}                             1           tos                 _none_           true        _none_      false       _none_      {create client_server_profile_config modify client_server_profile_config}           _none_      }
        {   ipv6_traffic_class                      ClientProfile|ServerProfile                      Ipv6TrafficClass                    NUMERIC                             1           0                   0-255           true        _none_      false       _none_      {create client_server_profile_config modify client_server_profile_config}           _none_      }
        {   load_type                               ClientLoadProfile           LoadType                            {CHOICES connections connections_per_time_unit transactions transactions_per_time_unit bandwidth playlists} \
                                                                                                                                                        2           connections         _none_          true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           {connections CONNECTIONS connections_per_time_unit CONNECTIONS_PER_TIME_UNIT transactions TRANSACTIONS transactions_per_time_unit TRANSACTIONS_PER_TIME_UNIT bandwidth BANDWIDTH playlists PLAYLISTS}    }
        {   max_connections_attempted               ClientLoadProfile           MaxConnectionsAttempted             NUMERIC                             1           4294967295          0-4294967295    true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           _none_      }
        {   max_open_connections                    ClientLoadProfile           MaxOpenConnections                  NUMERIC                             1           4096                0-4294967295    true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           _none_      }
        {   max_pipeline_depth                      HttpClientProtocolProfile   MaxPipelineDepth                    NUMERIC                             1          8                   1-255           true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           _none_      }
        {   max_transactions_attempted              ClientLoadProfile           MaxTransactionsAttempted            NUMERIC                             1           4294967295          0-4294967295    true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           _none_      }
        {   mode                                    _none_                      _none_                              {CHOICES create modify delete}      1           _none_              _none_          true        _none_      true        _none_      _none_  _none_      }
        {   profile_handle                          _none_                      _none_                              ALPHANUM                            1           _none_              _none_          true        _none_      false       _none_      _none_  _none_      }
        {   profile_name                            ClientLoadProfile           ProfileName                         ANY                            1           _none_              _none_          true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           _none_      }
        {   profile_type                            _none_                      _none_                              {CHOICES load client server}        1           _none_              _none_          true        _none_      false       _none_      _none_   _none_      }
        {   randomization_seed                      ClientLoadProfile           RandomizationSeed                   NUMERIC                             1           123456              0-4294967295    true        _none_      false       _none_      {create load_profile_config modify load_profile_config}           _none_      }
        {   random_body_size_mean                   HttpServerResponseConfig    RandomBodySizeMean                  NUMERIC                             1           0                   0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   random_body_size_std_deviation          HttpServerResponseConfig    RandomBodySizeStdDeviation          NUMERIC                             1           0                   0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   random_latency_mean                     HttpServerResponseConfig    RandomResponseLatencyMean           NUMERIC                             1           0                   0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   random_latency_std_deviation            HttpServerResponseConfig    RandomResponseLatencyStdDeviation   NUMERIC                             1           0                   0-4294967295    true        _none_      false       _none_      {create server_response_config modify server_response_config}           _none_      }
        {   response_timing_type                    HttpServerResponseConfig    ResponseTimingType                  {CHOICES fixed random}              1           fixed               _none_          true        _none_      false       _none_      {create server_response_config modify server_response_config}          {fixed FIXED random RANDOM}      }
        {   rx_window_limit                         ClientProfile|ServerProfile RxWindowSizeLimit                   NUMERIC                             1           32768               0-4294967295    true        _none_      false       _none_      {create client_server_profile_config modify client_server_profile_config}           _none_      }
        {   server_media_seq_num                    HttpServerProtocolProfile   ServerMediaSeqNum                   NUMERIC                             1           1                   0-4294967295    true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           _none_      }
        {   server_port_num                         HttpServerProtocolProfile   ServerPortNum                       NUMERIC                             1           80                  0-65535         true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           _none_      }
        {   server_sliding_window_play_list_size    HttpServerProtocolProfile   ServerSlidingWindowPlaylistSize     NUMERIC                             1           8                   3-100           true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           _none_      }
        {   server_target_duration                  HttpServerProtocolProfile   ServerTargetDuration                NUMERIC                             1           10                  5-15            true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           _none_      }
        {   server_type                             HttpServerProtocolProfile   HttpServerTypes                     {CHOICES microsoft_iis apache}      1           microsoft_iis       _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}          {microsoft_iis MICROSOFT_IIS apache APACHE}      }
        {   server_video_length                     HttpServerProtocolProfile   ServerVideoLength                   NUMERIC                             1           60                  1-7200          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           _none_      }
        {   user_agent_header                             _none_                  _none_                            ANY                                1           _none_              _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           _none_      }
        {   use_dynamic_load                        ClientLoadProfile           UseDynamicLoad                      {CHOICES true false}                3           false               _none_          false        _none_      false       _none_      {create load_profile_config modify load_profile_config}           {true TRUE false FALSE}       }
        {   video_client_bitrate_alg                HttpClientProtocolProfile   VideoClientBitrateAlg               {CHOICES smart normal constant}     1           smart               _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {smart SMART normal NORMAL constant CONSTANT}      }
        {   video_client_predef_method              HttpClientProtocolProfile   VideoClientPredefineMethod          {CHOICES minimum median maximum}    1           minimum             _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {minimum MINIMUM median MEDIAN maximum MAXIMUM}      }
        {   video_client_start_bitrate              HttpClientProtocolProfile   VideoClientStartBitrate             {CHOICES predefine userdefine}      1           predefine           _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {predefine PREDEFINE userdefine USERDEFINE}      }
        {   video_client_type                       HttpClientProtocolProfile   VideoClientType                     {CHOICES spirent_hls}               1           spirent_hls         _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}         {spirent_hls SPIRENT_HLS}     }
        {   video_client_video_type                 HttpClientProtocolProfile   VideoClientVideoType                {CHOICES vod live}                  1           vod                 _none_          true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           {vod VOD live LIVE}      }
        {   video_client_user_def_value             HttpClientProtocolProfile   VideoClientUserDefineValue          NUMERIC                             1           128                 40-4096         true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           _none_      }
        {   video_client_view_time                  HttpClientProtocolProfile   VideoClientViewTime                 NUMERIC                             1           60                  0-4294967295    true        _none_      false       _none_      {create client_protocol_profile_config modify client_protocol_profile_config}           _none_      }
        {   video_server_bitrate_list               HttpServerProtocolProfile   VideoServerBitrateList              ANY \
                                                                                                                                                        1           br_64               _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}             _none_   }
        {   video_server_stream_type                HttpServerProtocolProfile   VideoServerStreamType               {CHOICES adaptive_bitrate progressive} \
                                                                                                                                                        1           adaptive_bitrate    _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           {adaptive_bitrate ADAPTIVE_BITRATE progressive PROGRESSIVE} }
        {   video_server_type                       HttpServerProtocolProfile   VideoServerType                     {CHOICES live_streaming}            1           live_streaming      _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           {live_streaming LIVE_STREAMING}  }
        {   video_server_version                    HttpServerProtocolProfile   VideoServerVersion                  {CHOICES version_1_0}               1           version_1_0         _none_          true        _none_      false       _none_      {create server_protocol_profile_config modify server_protocol_profile_config}           {version_1_0 VERSION_1_0}   }
    }
    {   emulation_http_config
        {   hname                           stcobj                      stcattr                     type                            priority    default         range           supported   dependency  mandatory   procfunc    mode                            constants   }
        {   client_profiles                 _none_                      _none_    ALPHANUM                  1           _none_          _none_          true        _none_      false       _none_      {create http_client_config modify http_client_config}           _none_      }
        {   connected_server                _none_                      _none_                      ALPHANUM                        1           _none_          _none_          true        _none_      false       _none_      _none_           _none_      }
        {   device_handle                   _none_                      _none_                      ALPHANUM                        1           _none_          _none_          true        _none_      false       _none_      _none_ _none_      }
        {   dynamic_load                    _none_                      _none_                      NUMERIC                         1           30               0-1000000      false      _none_      false       _none_      {create http_client_config modify http_client_config}           _none_      }
        {   endpoint_connection_pattern     HttpClientProtocolConfig    EndpointConnectionPattern   {CHOICES pair backbone_src_first backbone_dst_first backbone_interleaved}    1           pair            _none_          true        _none_      false       _none_      {create http_client_config modify http_client_config}           {pair PAIR backbone_src_first BACKBONE_SRC_FIRST backbone_dst_first BACKBONE_DST_FIRST backbone_interleaved BACKBONE_INTERLEAVED} }
        {   http_type                       _none_                      _none_                      {CHOICES client server}         1           client          _none_          true        _none_      true        _none_      _none_           _none_      }
        {   load_profiles                   _none_     _none_  ALPHANUM              1           _none_          _none_          true        _none_      false       _none_   {create http_client_config modify http_client_config}           _none_      }
        {   max_request_per_client          HttpServerProtocolConfig    MaxRequestsPerClient        NUMERIC                         1           10               1-4294967295   true        _none_      false       _none_      {create http_server_config modify http_server_config}           _none_      }
        {   max_simultaneous_clients        HttpServerProtocolConfig    MaxSimultaneousClients      NUMERIC                         1           4294967295       1-4294967295   true        _none_      false       _none_      {create http_server_config modify http_server_config}           _none_      }
        {   max_transactions_per_server     HttpClientProtocolConfig    MaxTransactionsPerServer    NUMERIC                         1           10               1-4294967295   true        _none_      false       _none_      {create http_client_config modify http_client_config}           _none_      }
        {   mode                            _none_                      _none_                      {CHOICES create modify delete}  1           _none_          _none_          true        _none_      true        _none_      _none_ _none_      }
        {   port_handle                     _none_                      _none_                      ALPHANUM                        1           _none_          _none_          true        _none_      false       _none_      _none_                     _none_      }
        {   server_profiles                 _none_    _none_   ALPHANUM                  1           _none_          _none_          true        _none_      false       _none_      {create http_server_config modify http_server_config}           _none_      }
    }
    {   emulation_http_control
        {   hname       stcobj              stcattr     type                                priority    default         range           supported   dependency  mandatory   procfunc    mode                                constants   }
        {   mode        _none_              _none_      {CHOICES start stop clear_stats}    1           _none_          _none_          true        _none_      true        _none_      _none_   _none_      }
        {   handle      _none_              _none_      ALPHANUM                            1           _none_          _none_          true        _none_      true        _none_      _none_   _none_      }
    }
    {   emulation_http_stats
        {   hname       stcobj              stcattr     type        priority    default         range           supported   dependency  mandatory   procfunc    mode                            constants   }
        {   handle      _none_              _none_      ALPHANUM    1           _none_          _none_          true        _none_      false       _none_      _none_                          _none_      }
    }
    {   emulation_http_stats_client_results
        {   hname                                   stcobj              stcattr                             type        priority    default         range           supported   dependency  mandatory   procfunc    mode        constants   }
        {   aborted_connections                     HttpClientResults   AbortedConnections                  _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   aborted_connections_per_second          HttpClientResults   AbortedConnectionsPerSecond         _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   aborted_transactions                    HttpClientResults   AbortedTransactions                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   aborted_transactions_per_second         HttpClientResults   AbortedTransactionsPerSecond        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   active_connections                      HttpClientResults   ActiveConnections                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   attempted_connections                   HttpClientResults   AttemptedConnections                _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   attempted_connections_per_second        HttpClientResults   AttemptedConnectionsPerSecond       _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   attempted_transactions                  HttpClientResults   AttemptedTransactions               _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   attempted_transactions_per_second       HttpClientResults   AttemptedTransactionsPerSecond      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   avg_response_time_per_url_msec          HttpClientResults   AvgResponseTimePerUrlMsec           _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   elapsed_seconds                         HttpClientResults   ElapsedSeconds                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_avg_rx_rate_bps                 HttpClientResults   GoodputAvgRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_avg_tx_rate_bps                 HttpClientResults   GoodputAvgTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_max_rx_rate_bps                 HttpClientResults   GoodputMaxRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_max_tx_rate_bps                 HttpClientResults   GoodputMaxTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_min_rx_rate_bps                 HttpClientResults   GoodputMinRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_min_tx_rate_bps                 HttpClientResults   GoodputMinTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_rx_bps                          HttpClientResults   GoodputRxBps                        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_rx_bytes                        HttpClientResults   GoodputRxBytes                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_tx_bps                          HttpClientResults   GoodputTxBps                        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_tx_bytes                        HttpClientResults   GoodputTxBytes                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   intended_load                           HttpClientResults   IntendedLoad                        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   max_response_time_per_url_msec          HttpClientResults   MaxResponseTimePerUrlMsec           _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   min_response_time_per_url_msec          HttpClientResults   MinResponseTimePerUrlMsec           _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   rx_response_code_200                    HttpClientResults   RxResponseCode200                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   rx_response_code_400                    HttpClientResults   RxResponseCode400                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   rx_response_code_404                    HttpClientResults   RxResponseCode404                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   rx_response_code_405                    HttpClientResults   RxResponseCode405                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_connections                  HttpClientResults   SuccessfulConnections               _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_connections_per_second       HttpClientResults   SuccessfulConnectionsPerSecond      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_transactions                 HttpClientResults   SuccessfulTransactions              _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_transactions_per_second      HttpClientResults   SuccessfulTransactionsPerSecond     _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   sum_response_time_per_url_msec          HttpClientResults   SumResponseTimePerUrlMsec           _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_connections                HttpClientResults   UnsuccessfulConnections             _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_connections_per_second     HttpClientResults   UnsuccessfulConnectionsPerSecond    _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_transactions               HttpClientResults   UnsuccessfulTransactions            _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_transactions_per_second    HttpClientResults   UnsuccessfulTransactionsPerSecond   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
    }
    {   emulation_http_stats_server_results
        {   hname                                   stcobj              stcattr                             type        priority    default         range           supported   dependency  mandatory   procfunc    mode        constants   }
        {   active_connections                      HttpServerResults   ActiveConnections                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   elapsed_seconds                         HttpServerResults   ElapsedSeconds                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_avg_rx_rate_bps                 HttpServerResults   GoodputAvgRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_avg_tx_rate_bps                 HttpServerResults   GoodputAvgTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_max_rx_rate_bps                 HttpServerResults   GoodputMaxRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_max_tx_rate_bps                 HttpServerResults   GoodputMaxTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_min_rx_rate_bps                 HttpServerResults   GoodputMinRxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_min_tx_rate_bps                 HttpServerResults   GoodputMinTxRateBps                 _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_rx_bps                          HttpServerResults   GoodputRxBps                        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_rx_bytes                        HttpServerResults   GoodputRxBytes                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_tx_bps                          HttpServerResults   GoodputTxBps                        _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   goodput_tx_bytes                        HttpServerResults   GoodputTxBytes                      _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_transactions                 HttpServerResults   SuccessfulTransactions              _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   successful_transactions_per_second      HttpServerResults   SuccessfulTransactionsPerSecond     _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   total_connections                       HttpServerResults   TotalConnections                    _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   total_connections_per_second            HttpServerResults   TotalConnectionsPerSecond           _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   tx_response_code_200                    HttpServerResults   TxResponseCode200                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   tx_response_code_400                    HttpServerResults   TxResponseCode400                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   tx_response_code_404                    HttpServerResults   TxResponseCode404                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   tx_response_code_405                    HttpServerResults   TxResponseCode405                   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_transactions               HttpServerResults   UnsuccessfulTransactions            _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
        {   unsuccessful_transactions_per_second    HttpServerResults   UnsuccessfulTransactionsPerSecond   _none_      _none_      _none_          _none_          true        _none_      false       _none_      _none_      _none_      }
    }
    {	emulation_http_phase_config
	{   hname                           stcobj                      stcattr                     type                            priority    default         range           supported   dependency  mandatory   procfunc    mode                            constants   }        
	{   mode                           _none_                      _none_              {CHOICES create modify delete}              1         create       _none_     true       _none_   true        _none_      _none_ _none_     }       
	{   load_pattern                 ClientLoadPhase             LoadPattern           {CHOICES stair flat burst sinusoid random sawtooth} \
                                                                                                                                       2           _none_                _none_          true        _none_      false       _none_      {create load_phase_config modify load_phase_config}           _none_      }
	{   duration_units               ClientLoadPhase             LoadPhaseDurationUnits {CHOICES milliseconds seconds minutes hours} \
                                                                                                                                       2           _none_             _none_          true        _none_      false       _none_      {create load_phase_config modify load_phase_config}           _none_      }
	{   phase_name                   ClientLoadPhase             PhaseName                     ALPHANUM                            2           _none_              _none_          true        _none_      false       _none_      {create load_phase_config modify load_phase_config}           _none_      }
	{   phase_num                    ClientLoadPhase             PhaseNum                      NUMERIC                             2           _none_           0-7          true        _none_      false       _none_            {create load_phase_config modify load_phase_config}           _none_      }
	{   profile_handle                 _none_                   _none_                       ALPHANUM                              1           _none_              _none_          true        _none_      false       _none_      _none_ 	   _none_      }
        {   phase_handle                   _none_                    _none_                         ALPHANUM                           1           _none_              _none_          true        _none_      false       _none_      _none_       _none_      }
        {   height          StairPatternDescriptor|FlatPatternDescriptor|BurstPatternDescriptor|SinusoidPatternDescriptor|SawToothPatternDescriptor  \
                                                                     Height                         NUMERIC                            2           30                 _none_     true        _none_      false       _none_      _none_           _none_      }
        {   ramp_time       StairPatternDescriptor|FlatPatternDescriptor     RampTime               NUMERIC                            2           20                 0-4294967295       true        _none_      false       _none_      _none_   _none_  }
        {   repetitions     StairPatternDescriptor|BurstPatternDescriptor|SinusoidPatternDescriptor|SawToothPatternDescriptor  \
                                                                     Repetitions                    NUMERIC                            2           1                0-4294967295           true        _none_      false       _none_      _none_           _none_      }
        {   steady_time     StairPatternDescriptor|FlatPatternDescriptor|SawToothPatternDescriptor   \
                                                                      SteadyTime                     NUMERIC                           2           40                  0-4294967295     true        _none_      false       _none_      _none_           _none_      } 
        {   burst_time      BurstPatternDescriptor                    BurstTime                      NUMERIC                           2           20                 0-4294967295      true        _none_      false       _none_      _none_          _none_      }   
        {   pause_time      BurstPatternDescriptor|SawToothPatternDescriptor             \
                                                                      PauseTime                      NUMERIC                           2           40                 0-4294967295      true        _none_      false       _none_      _none_          _none_      }
        {   period          SinusoidPatternDescriptor                 Period                         NUMERIC                           2           600           0-4294967295          true        _none_      false       _none_      _none_  _none_   }
        
    }             
	
}