namespace eval ::sth::igmp:: {
    
}

set ::sth::igmp::igmpQuerierTable {
    ::sth::igmp::
    {emulation_igmp_querier_config
        {hname                          stcobj              stcattr                         type                                priority        default                 range           supported   dependency      mandatory       procfunc                    mode        constants   }
        {mode                           _none_              _none_                  {CHOICES create modify delete enable}       10              _none_                  _none_          true        _none_          true            _none_                      _none_      _none_  }
        {port_handle                    _none_              _none_                          ALPHANUM                            10              _none_                  _none_          true        _none_          false           _none_                      _none_      _none_  }
        {handle                         _none_              _none_                          ALPHANUM                            10              _none_                  _none_          true        _none_          false           _none_                      _none_      _none_  }
        {count                          EmulatedDevice      count                           NUMERIC                             10              1                       1-65535         true        _none_          false           _none_                      _none_      _none_}
        {intf_ip_addr                   Ipv4If              Address                         IPV4                                10              0.0.0.0                 _none_          true        _none_          false           _none_                      {create configIpIntf modify configIpIntf}      _none_}
        {intf_ip_addr_step              Ipv4If              Address.step                    IPV4                                10              0.0.0.1                 _none_          true        _none_          false           _none_                      {create configIpIntf modify configIpIntf}      _none_}
        {intf_prefix_len                Ipv4If              PrefixLength                    NUMERIC                             10              24                      1-32            true        _none_          false           _none_                      {create configIpIntf modify configIpIntf}      _none_}
        {source_mac                     EthiiIf             SourceMac                       MAC                                 10              00:10:94:00:00:02       _none_          true        _none_          false           _none_                      {create configEthIIIntf modify configEthIIIntf}      _none_}
        {source_mac_step                EthiiIf             SourceMac.step                  MAC                                 10              00:00:00:00:00:01       _none_          true        _none_          false           _none_                      {create configEthIIIntf modify configEthIIIntf}      _none_}
        {neighbor_intf_ip_addr          Ipv4If              Gateway                         IPV4                                10              "192.85.1.1"            _none_          true        _none_          false           _none_                      {create configIpIntf modify configIpIntf}      _none_}
        {neighbor_intf_ip_addr_step     Ipv4If              Gateway.step                    IPV4                                10              0.0.0.0                 _none_          true        _none_          false           _none_                      {create configIpIntf modify configIpIntf}      _none_}
        {vlan_cfi                       VlanIf              cfi                         {CHOICES 0 1}                           10              0                       _none_          true        _none_          false           _none_                      {create configVlanIfInner modify configVlanIfInner}      _none_}
        {vlan_id                        VlanIf              VlanId                          NUMERIC                             10              100                     0-4095          true        _none_          false           processConfigCmd_vlanId     {create configVlanIfInner modify configVlanIfInner}      _none_}
        {vlan_id_mode                   VlanIf              vlanid.mode                 {CHOICES fixed increment}               10              fixed                   _none_          true        _none_          false           _none_                      _none_      {fixed FALSE increment TRUE}}
        {vlan_id_step                   VlanIf              vlanid.step                     NUMERIC                             10              1                       0-32767         true        _none_          false           _none_                      {create configVlanIfInner modify configVlanIfInner}      _none_}
        {vlan_id_count                  VlanIf              IfRecycleCount                  NUMERIC                             10              1                       1-4095          true        _none_          false           _none_                      {create configVlanIfInner modify configVlanIfInner}      _none_}
        {vlan_user_priority             VlanIf              Priority                        NUMERIC                             10              7                       0-7             true        _none_          false           _none_                      {create configVlanIfInner modify configVlanIfInner}      _none_}
        {vlan_outer_cfi                 VlanIf_Outer        cfi                         {CHOICES 0 1}                           10              0                       _none_          true        _none_          false           _none_                      {create configVlanIfOuter modify configVlanIfOuter}      _none_}
        {vlan_id_outer                  VlanIf_Outer        VlanId                          NUMERIC                             10              100                     0-4095          true        _none_          false           processConfigCmd_vlanId     {create configVlanIfOuter modify configVlanIfOuter}      _none_}
        {vlan_id_outer_mode             VlanIf_Outer        vlanid.mode                 {CHOICES fixed increment}               10              fixed                   _none_          true        _none_          false           _none_                      _none_      {fixed FALSE increment TRUE}}
        {vlan_id_outer_step             VlanIf_Outer        vlanid.step                     NUMERIC                             10              1                       0-32767         true        _none_          false           _none_                      {create configVlanIfOuter modify configVlanIfOuter}      _none_}
        {vlan_id_outer_count            VlanIf_Outer        IfRecycleCount                  NUMERIC                             10              1                       1-4095          true        _none_          false           _none_                      {create configVlanIfOuter modify configVlanIfOuter}      _none_}
        {qinq_incr_mode                 _none_              _none_                      {CHOICES inner outer both}              10              inner                   _none_          true        _none_          false       processConfigCmd_qinqIncrMode   {create configVlanIfOuter modify configVlanIfOuter}      {inner inner outer outer both both}}
        {vlan_outer_user_priority       VlanIf_Outer        Priority                        NUMERIC                             10              7                       0-7             true        _none_          false           _none_                      {create configVlanIfOuter modify configVlanIfOuter}      _none_}
        {igmp_version                   IgmpRouterConfig    Version                     {CHOICES v1 v2 v3}                      11              v2                      _none_          true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      {v1 igmp_v1 v2 igmp_v2 v3 igmp_v3}}
        {ignore_v1_reports              IgmpRouterConfig    IgnoreV1Reports             {CHOICES true false}                    11              false                   _none_          true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {ipv4_dont_fragment             IgmpRouterConfig    Ipv4DontFragment            {CHOICES true false}                    11              false                   _none_          true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {ipv4_tos                       IgmpRouterConfig    Ipv4Tos                         NUMERIC                             11              192                     0-255           true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {last_member_query_count        IgmpRouterConfig    LastMemberQueryCount            NUMERIC                             11              2                       0-255           true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {last_member_query_interval     IgmpRouterConfig    LastMemberQueryInterval         NUMERIC                             11              1000                    0-4294967295    true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {query_interval                 IgmpRouterConfig    QueryInterval                   NUMERIC                             11              125                     0-4294967295    true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {query_response_interval        IgmpRouterConfig    QueryResponseInterval           NUMERIC                             11              10000                   0-4294967295    true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {robustness_variable            IgmpRouterConfig    RobustnessVariable              NUMERIC                             11              2                       2-255           true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {startup_query_count            IgmpRouterConfig    StartupQueryCount               NUMERIC                             11              2                       2-255           true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {tos_type                       Ipv4If              TosType                     {CHOICES tos diffserv}                  11              tos                     _none_          true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
        {use_partial_block_state        IgmpRouterConfig    UsePartialBlockState        {CHOICES true false}                    11              false                   _none_          true        _none_          false           _none_                      {create configIgmpRouterConfig modify configIgmpRouterConfig}      _none_  }
    }
    {emulation_igmp_querier_control
        {hname                          stcobj              stcattr                         type                                priority        default                 range           supported   dependency      mandatory       procfunc                    mode        constants   }
        {mode                           _none_              _none_                      {CHOICES start stop}                    10              _none_                  _none_          true        _none_          true            _none_                      _none_      _none_  }
        {port_handle                    _none_              _none_                          ALPHANUM                            10              _none_                  _none_          true        _none_          false           _none_                      _none_      _none_  }
        {handle                         _none_              _none_                          ALPHANUM                            10              _none_                  _none_          true        _none_          false           _none_                      _none_      _none_  }
    }
    {emulation_igmp_querier_info
        {hname                          stcobj              stcattr                             type                            priority        default     range           supported   dependency      mandatory       procfunc                                mode    constants   }
        {port_handle                    _none_              _none_                              ALPHANUM                        100             _none_      _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {handle                         _none_              _none_                              ALPHANUM                        100             _none_      _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {host_state                     IgmpRouterResults   HostState                           ANY                             100             NON_MEMBER  _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {if_handle                      IgmpRouterResults   IfHandle                            ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {mcast_compatiblity_mode        IgmpRouterResults   McastCompatibilityMode              ANY                             100             V2          _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {router_state                   IgmpRouterResults   RouterState                         ANY                             100             NOT_STARTED _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {frame_count_rx                 IgmpRouterResults   RxFrameCount                        ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {igmp_check_sum_error_count_rx  IgmpRouterResults   RxIgmpCheckSumErrorCount            ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {igmp_length_error_count_rx     IgmpRouterResults   RxIgmpLengthErrorCount              ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {unknown_type_count_rx          IgmpRouterResults   RxUnknownTypeCount                  ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {time_stamp                     IgmpRouterResults   Timestamp                           ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
        {frame_count_tx                 IgmpRouterResults   TxFrameCount                        ANY                             100             0           _none_          true        _none_          false           _none_                                  _none_  _none_  }
    }
}

