#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl \
# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::iptv:: {
}

set ::sth::iptv::iptvTable {
    ::sth::iptv::
    {emulation_iptv_config
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory   mode                                            procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           TRUE        {modify "" enable ""}                  _none_         _none_}
        {mode                              _none_                    _none_                         {CHOICES modify enable disable} 1                _none_           _none_            TRUE               _none_           TRUE        {modify "" enable ""}                  _none_         _none_}
        {inter_client_start_delay_step    IptvStbBlockConfig         InterClientStartDelayStep      NUMERIC                         4                0                _none_            TRUE               _none_           FALSE       {modify "" enable configIptvStbBlock}                  _none_         _none_}
        {save_time_stamps_enable          IptvStbBlockConfig         SaveTimeStamps                 {CHOICES true false 0 1}        5                false            _none_            TRUE               _none_           FALSE       {modify "" enable configIptvStbBlock}                  _none_         _none_}
        {channel_viewing_profile          IptvStbBlockConfig         stbchannel-targets             ANY                             2                _none_           _none_            TRUE               _none_           FALSE       {modify "" enable configIptvStbBlock}                  _none_         _none_}
        {viewing_behavior_profile         IptvStbBlockConfig         iptvprofile-targets            ANY                             3                _none_           _none_            TRUE               _none_           FALSE       {modify "" enable configIptvStbBlock}                  _none_         _none_}
    }
    {emulation_iptv_channel_viewing_profile_config
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory   mode                                   procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {mode                              _none_                    _none_                         {CHOICES create modify delete}  1                _none_           _none_            TRUE               _none_           TRUE        {create "" modify ""}                  _none_         _none_}
        {channel_block                     IptvViewedChannels        ChannelBlock                    ANY                            5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {channel_range_start               IptvViewedChannels        ChannelRangeStart               NUMERIC                        5                1                1-31999           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {channel_range_end                 IptvViewedChannels        ChannelRangeEnd                 NUMERIC                        5                32               2-32000           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {channel_range_step                IptvViewedChannels        ChannelRangeStep                NUMERIC                        5                1                _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {initial_channel_start             IptvViewedChannels        InitialChannelStart             NUMERIC                        5                1                1-32000           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {initial_channel_step              IptvViewedChannels        InitialChannelStep              NUMERIC                        5                1                _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {name                              IptvViewedChannels        name                           ANY                             5               _none_             _none_           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
}
    {emulation_iptv_viewing_behavior_profile_config
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory   mode                                   procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {mode                              _none_                    _none_                         {CHOICES create modify delete}  1                _none_           _none_            TRUE               _none_           TRUE        {create "" modify ""}                  _none_         _none_}
        {change_before_view                IptvViewingProfileConfig  ChangesBeforeView              NUMERIC                         5                5                _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {zap_interval                      IptvViewingProfileConfig  Interval                       NUMERIC                         5                5000             _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {join_latency_threshold            IptvViewingProfileConfig  JoinLatencyThreshold           NUMERIC                         5                300              0-2000            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {leave_latency_threshold           IptvViewingProfileConfig  LeaveLatencyThreshold          NUMERIC                         5                3000             0-30000           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {set_top_leave_join_delay          IptvViewingProfileConfig  SetTopLeaveJoinDelay           NUMERIC                         5                0                _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {view_duration                     IptvViewingProfileConfig  ViewDuration                   NUMERIC                         5                60               0-429496729       TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {zap_behavior                      IptvViewingProfileConfig  ZapBehavior                    {CHOICES zap_only zap_and_view} 5                zap_only         _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {zap_direction                     IptvViewingProfileConfig  ZapDirection                   {CHOICES up down random}        5                up               _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {zap_interval_type                 IptvViewingProfileConfig  ZapIntervalType     {CHOICES leave_to_leave  multicast_pkt_to_leave} 5          leave_to_leave   _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {name                              IptvViewingProfileConfig  name                           ANY                             5               _none_             _none_           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
    }

    {emulation_iptv_channel_block_config
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory   mode                                   procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {mode                              _none_                    _none_                         {CHOICES create modify delete}  1                _none_           _none_            TRUE               _none_           TRUE        {create "" modify ""}                  _none_         _none_}
        {multicast_group_handle            IptvChannelBlock          MulticastParam-targets         ANY                             1                _none_           _none_            TRUE               _none_           FALSE        {create "" modify ""}                  _none_         _none_}
        {channel_name                      IptvChannelBlock          ChannelName                    ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {channel_start                     IptvChannelBlock          ChannelStart                   NUMERIC                         5                1                1-32000           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {filter_mode                       IptvChannelBlock          FilterMode                     {CHOICES include exclude}       5                include          _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {user_source_enable                IptvChannelBlock          UserDefinedSources             {CHOICES true false 0 1}        5                false            _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {subscribed_source                 IptvChannelBlock          TrafficSources-targets         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {source_pool_handle                 _none_                   _none_                         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {name                              IptvChannelBlock          name                           ANY                             5               _none_             _none_           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
    }

    {emulation_iptv_control
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory   mode                                   procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {port_handle                       _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {mode                              _none_                    _none_                         {CHOICES start stop wait}       1                _none_           _none_            TRUE               _none_           TRUE        {create "" modify ""}                  _none_         _none_}
        {db_name                           IptvStartTestCommand      DatabaseFileName               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {inter_block_start_delay           IptvStartTestCommand      InterStbStartDelayStep         NUMERIC                         5                0                _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {join_fail_percentage_threshold    IptvStartTestCommand      JoinFailPercentageThreshold    NUMERIC                         5                100              0-100             TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {test_env                          IptvStartTestCommand      TestEnv         {CHOICES testing_env real_world_env}           5                testing_env      _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {test_name                         IptvStartTestCommand      TestName                       ANY                             5                "IptvTest"       _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {test_duration                     IptvStartTestCommand      TestTime                       NUMERIC                         5                 300             0-429496729     TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {test_type                         IptvStartTestCommand      TypeOfTest {CHOICES channel_zapping_test  channel_verification_test} 5 channel_verification_test _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {udp_port                          IptvStartTestCommand      UdpPortNum                     NUMERIC                         5                3357             _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {udp_port_filter                   IptvStartTestCommand      UdpPortTypeFilter              {CHOICES "source" destination}    5              "source"           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        {vlan_sub_filter_type              IptvStartTestCommand      VlanSubFilter                  {CHOICES outer inner}          5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
    }
    {emulation_iptv_stats
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {handle                            _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {port_handle                       _none_                    _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {mode                              _none_                    _none_ {CHOICES set_top_box viewing_profile channel port test} 1                _none_           _none_            TRUE               _none_           TRUE        _none_                  _none_         _none_}
    }
    {emulation_iptv_stats_set_top_box
        {hname                             stcobj                    stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {profile_name                      IptvStbBlockResults       ProfileName                    ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {clients_num                       IptvStbBlockResults       NumClients                     ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {channel_changes_num               IptvStbBlockResults       NumOfChannelChanges            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {duplicate_joins                   IptvStbBlockResults       DuplicateJoins                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {errored_streams                   IptvStbBlockResults       ErroredStreams                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {flagged_joins                     IptvStbBlockResults       FlaggedJoins                   ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {flagged_leaves                    IptvStbBlockResults       FlaggedLeaves                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {join_failures                     IptvStbBlockResults       JoinFails                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {join_latency_threshold            IptvStbBlockResults       JoinLatencyThreshold           ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_change_latency                IptvStbBlockResults       MinChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_change_latency                IptvStbBlockResults       MaxChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_change_latency                IptvStbBlockResults       AvgChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_gap_latency                   IptvStbBlockResults       AvgGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_gap_latency                   IptvStbBlockResults       MaxGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_gap_latency                   IptvStbBlockResults       MinGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_overlap_latency               IptvStbBlockResults       MinOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_overlap_latency               IptvStbBlockResults       MaxOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_overlap_latency               IptvStbBlockResults       AvgOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_leave_latency                 IptvStbBlockResults       AvgLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_leave_latency                 IptvStbBlockResults       MinLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_leave_latency                 IptvStbBlockResults       MaxLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_join_latency                  IptvStbBlockResults       AvgJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_join_latency                  IptvStbBlockResults       MinJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_join_latency                  IptvStbBlockResults       MaxJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_leave_join_delay              IptvStbBlockResults       AvgLeaveJoinDelay              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_leave_join_delay              IptvStbBlockResults       MinLeaveJoinDelay              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_leave_join_delay              IptvStbBlockResults       MaxLeaveJoinDelay              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_leave_to_leave_interval       IptvStbBlockResults       AvgLeaveToLeaveInterval        ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_leave_to_leave_interval       IptvStbBlockResults       MinLeaveToLeaveInterval        ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_leave_to_leave_interval       IptvStbBlockResults       MaxLeaveToLeaveInterval        ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {avg_multicast_to_leave_interval   IptvStbBlockResults       AvgMulticastPktToLeaveInterval ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {min_multicast_to_leave_interval   IptvStbBlockResults       MinMulticastPktToLeaveInterval ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {max_multicast_to_leave_interval   IptvStbBlockResults       MaxMulticastPktToLeaveInterval ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {total_pkts                        IptvStbBlockResults       TotalPkts                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {total_pkt_rate                    IptvStbBlockResults       TotalPktRate                   ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {dropped_frame_count               IptvStbBlockResults       DroppedFrameCount              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {recorded_frame_count              IptvStbBlockResults       ReorderedFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {duplicate_frame_count             IptvStbBlockResults       DuplicateFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {late_frame_count                  IptvStbBlockResults       LateFrameCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
        {prbs_error_count                  IptvStbBlockResults       PrbsErrorCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {set_top_box ""}                  _none_         _none_}
   }
   {emulation_iptv_stats_viewing_profile
        {hname                             stcobj                           stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {handle                            _none_                           _none_                         ALPHANUM                        1                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {channel_changes_num               IptvViewingProfileResults        NumOfChannelChanges            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {duplicate_joins                   IptvViewingProfileResults        DuplicateJoins                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {errored_streams                   IptvViewingProfileResults        ErroredStreams                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {join_failures                     IptvViewingProfileResults        JoinFails                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_change_latency                IptvViewingProfileResults        MinChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_change_latency                IptvViewingProfileResults        MaxChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_change_latency                IptvViewingProfileResults        AvgChangeLatency               ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_gap_latency                   IptvViewingProfileResults        AvgGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_gap_latency                   IptvViewingProfileResults        MaxGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_gap_latency                   IptvViewingProfileResults        MinGapLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_overlap_latency               IptvViewingProfileResults        MinOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_overlap_latency               IptvViewingProfileResults        MaxOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_overlap_latency               IptvViewingProfileResults        AvgOverlapLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_leave_latency                 IptvViewingProfileResults        AvgLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_leave_latency                 IptvViewingProfileResults        MinLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_leave_latency                 IptvViewingProfileResults        MaxLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_join_latency                  IptvViewingProfileResults        AvgJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_join_latency                  IptvViewingProfileResults        MinJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_join_latency                  IptvViewingProfileResults        MaxJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkts                        IptvViewingProfileResults        TotalPkts                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkt_rate                    IptvViewingProfileResults        TotalPktRate                   ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {dropped_frame_count               IptvViewingProfileResults        DroppedFrameCount              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {recorded_frame_count              IptvViewingProfileResults        ReorderedFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {duplicate_frame_count             IptvViewingProfileResults        DuplicateFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {late_frame_count                  IptvViewingProfileResults        LateFrameCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {prbs_error_count                  IptvViewingProfileResults        PrbsErrorCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
   }

   {emulation_iptv_stats_channel
        {hname                             stcobj                     stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {channel_name                      IptvChannelResults         ChannelName                    ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {channel_num                       IptvChannelResults         NumOfChannels                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {channel_changes_num               IptvChannelResults         NumOfChannelChanges            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {duplicate_joins                   IptvChannelResults         DuplicateJoins                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {errored_streams                   IptvChannelResults         ErroredStreams                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {join_failures                     IptvChannelResults         JoinFails                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_leave_latency                 IptvChannelResults         AvgLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_leave_latency                 IptvChannelResults         MinLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_leave_latency                 IptvChannelResults         MaxLeaveLatency                ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {avg_join_latency                  IptvChannelResults         AvgJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {min_join_latency                  IptvChannelResults         MinJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {max_join_latency                  IptvChannelResults         MaxJoinLatency                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkts                        IptvChannelResults         TotalPkts                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkt_rate                    IptvChannelResults         TotalPktRate                   ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {dropped_frame_count               IptvChannelResults         DroppedFrameCount              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {recorded_frame_count              IptvChannelResults         ReorderedFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {duplicate_frame_count             IptvChannelResults         DuplicateFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {late_frame_count                  IptvChannelResults         LateFrameCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {prbs_error_count                  IptvChannelResults         PrbsErrorCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
   }
    {emulation_iptv_stats_port
        {hname                             stcobj                     stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {dropped_frame_count               IptvPortResults            DroppedFrameCount              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {recorded_frame_count              IptvPortResults            ReorderedFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {duplicate_frame_count             IptvPortResults            DuplicateFrameCount            ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {late_frame_count                  IptvPortResults            LateFrameCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {prbs_error_count                  IptvPortResults            PrbsErrorCount                 ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkts                        IptvPortResults            TotalPkts                      ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
        {total_pkt_rate                    IptvPortResults            TotalPktRate                   ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
    }

    {emulation_iptv_stats_test
        {hname                             stcobj                     stcattr                        type                            priority         default          range             supported          dependency       mandatory    mode                   procfunc       constants}
        {test_result                       IptvTestResults            TestResult                     ANY                             5                _none_           _none_            TRUE               _none_           FALSE       _none_                  _none_         _none_}
    }
}


        #{udp_port_filter                   IptvStbBlockResults       AvgRetransmissionLatency              ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastJoinLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastLeaveLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastMulticastPktGap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastMulticastPktOverlap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastPktRateNosb                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastPktRateSbit                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       AvgUnicastPktToLeaveInterval                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       DroppedUnicastFrameCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       DuplicateUnicastFrameCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       DuplicateUnicastJoins                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       ErroredUnicastStreams                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       ExtHdrErrors                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       FailedRetransmissionCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       FlaggedRetransmissionCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       FlaggedUnicastJoins                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       FlaggedUnicastLeaves                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       InvalidFirstPktCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       InvalidLastPktCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       LateUnicastFrameCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxRetransmissionLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastJoinLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastLeaveLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastMulticastPktGap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastMulticastPktOverlap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastPktRateNosb                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastPktRateSbit                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MaxUnicastPktToLeaveInterval                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinRetransmissionLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastJoinLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastLeaveLatency                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastMulticastPktGap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastMulticastPktOverlap                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastPktRateNosb                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastPktRateSbit                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       MinUnicastPktToLeaveInterval                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       ReorderedUnicastFrameCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       SbitFailures                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       Timestamp                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalMulticastPktRate                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalMulticastPkts                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPktRate                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPktRateNosb                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPktRateSbit                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPkts                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPktsNosb                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       TotalUnicastPktsSbit                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       UnicastJoinFails                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{vlan_sub_filter_type              IptvStbBlockResults       UnicastPrbsErrorCount                  ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #

        #{source_pool_handle                 IptvStartTestCommand           UnicastLeaveTrigger         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{multicast_group_handle            IptvStartTestCommand           AddToIterationResults         ANY                             1                _none_           _none_            TRUE               _none_           TRUE        {create "" modify ""}                  _none_         _none_}
        #{channel_start                     IptvStartTestCommand           ExtHdrCheckEnable                   NUMERIC                         5                1                1-32000           TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{filter_mode                       IptvStartTestCommand           ExtHdrCheckPatternPeriod                     {CHOICES include exclude}       5                include          _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{source_pool_handle                 IptvStartTestCommand           MaxSbitDelay         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{source_pool_handle                 IptvStartTestCommand           MinSbitDelay         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{source_pool_handle                 IptvStartTestCommand           MulticastJoinTrigger         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{source_pool_handle                 IptvStartTestCommand           RtpRetransmitThreshold         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
        #{source_pool_handle                 IptvStartTestCommand           StbBlockList         ANY                             5                _none_           _none_            TRUE               _none_           FALSE       {create "" modify ""}                  _none_         _none_}
