# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Ipv6AutoConfig:: {
}

set ::sth::Ipv6AutoConfig::ipv6AutoConfigTable {
 ::sth::Ipv6AutoConfig::

 { emulation_ipv6_autoconfig  
    { hname                                  stcobj              stcattr                          type                                                           priority                default                                 range         supported       dependency          mandatory   procfunc                                            mode                                       constants}
    { handle                                 _none_              _none_                           ALPHANUM                                                         1                      _none_                                 _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { port_handle                            _none_              _none_                           ALPHANUM                                                         1                      _none_                                 0-MAX_INT       true            _none_              false       _none_                        _none_                                                          _none_}
    { mode                                   _none_              _none_                           {CHOICES create modify reset enable disable}                     2                      _none_                                 _none_          true            _none_              true        _none_                        _none_                                                          _none_}
    { ip_version                             _none_              _none_                           {CHOICES 6 4_6}                                                  3                        6                                    _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { encap                                  _none_              _none_                           {CHOICES ethernet_ii ethernet_vlan ethernet_ii_qinq}                                      3                      ethernet_ii                            _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { count                                  EmulatedDevice      DeviceCount                      NUMERIC                                                          4                        1                                    1-65536          true            _none_              false       _none_                        _none_                                                          _none_} 
    { device_name                            _none_              _none_                           ANY                                                              6                      _none_                                 _none_          true            _none_              false       _none_                        _none_                                                          _none_}
    { mac_addr                               EthIIIf             SourceMac                        ANY                                                              6                      _none_                                 _none_          true            _none_              false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { mac_addr_step                          EthIIIf             SrcMacStep                       ANY                                                              7                      _none_                                 _none_          true            _none_              false       _none_                        {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { local_ip_addr                          Ipv4If              Address                          IPV4                                                             4                      _none_                                 _none_          true            _none_              false       _none_                        {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ip_addr_step                     Ipv4If              AddrStep                         IPV4                                                             4                      0.0.0.1                                _none_          true            _none_              false       _none_                        {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ip_prefix_len                    Ipv4If              PrefixLength                     NUMERIC                                                          4                       24                                    0-32            true            _none_              false       _none_                        {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { gateway_ip_addr                        Ipv4If              Gateway                          IPV4                                                             4                      _none_                                 _none_          true            _none_              false       _none_                        {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { gateway_ip_addr_step                   Ipv4If              GatewayStep                      IPV4                                                             4                      0.0.0.0                                _none_          true            _none_              false       _none_                        {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ipv6_addr                        Ipv6If              Address                          IPV6                                                             4                      _none_                                 _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_addr_step                   Ipv6If              AddrStep                         IPV6                                                             4                       ::1                                   _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_prefix_len                  Ipv6If              PrefixLength                     NUMERIC                                                          4                       64                                    0-128           true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr                      Ipv6If              Gateway                          IPV6                                                             4                      _none_                                 _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr_step                 Ipv6If              GatewayStep                      IPV6                                                             4                       ::                                    _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}    
	{ ipv6_enable_gateway_learning           Ipv6If              EnableGatewayLearning            _none_                                                             4                    false                                     _none_          true            _none_              false       _none_                        {create configIpv6Intf modify configIpv6Intf}                   _none_}    
	{ link_local_ipv6_addr           		 Ipv6If_Link_Local   Address                         IPV6                                               			   14            		   fe80::1     							 _none_          true            _none_              false       _none_                         _none_  _none_}
    { link_local_ipv6_addr_step      		 Ipv6If_Link_Local   AddrStep                        IPV6                                                			   15           		   ::1        							 _none_          true            _none_              false       _none_                         _none_  _none_}
    { link_local_ipv6_prefix_len     		 Ipv6If_Link_Local   PrefixLength                    NUMERIC                                             			   16            		   64         							 1-128           true            _none_              false       _none_                         _none_  _none_}
    { vlan_id                                VlanIf              VlanId                          NUMERIC                                                             4                     1                                0-4095              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_mode                           VlanIf              _none_                          {CHOICES fixed increment }                                          4                     fixed                                _none_              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_step                           VlanIf              IdStep                          NUMERIC                                                             4                     1                                0-4094              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_cfi                               VlanIf              Cfi                             NUMERIC                                                             4                       1                              0-1              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_priority                          VlanIf              Priority                        NUMERIC                                                             4                       0                              0-7              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_repeat_count                   VlanIf              IdRepeatCount                   NUMERIC                                                             4                     0                                _none_              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_recycle_count                  VlanIf              IfRecycleCount                  NUMERIC                                                             4                     0                                _none_              true        _none_              false       _none_                        {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_outer_id                          VlanIf_Outer        VlanId                          NUMERIC                                                             4                     1                                0-4095              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
    { vlan_outer_id_mode                     VlanIf_Outer        _none_                          {CHOICES fixed increment }                                          4                     fixed                                _none_              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
    { vlan_outer_id_step                     VlanIf_Outer        IdStep                          NUMERIC                                                             4                     1                                0-4094              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
    { vlan_outer_cfi                         VlanIf_Outer        Cfi                             NUMERIC                                                             4                       1                              0-1              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
    { vlan_outer_user_priority               VlanIf_Outer        Priority                        NUMERIC                                                             4                       0                              0-7              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
    { vlan_outer_id_repeat_count             VlanIf_Outer        IdRepeatCount                   NUMERIC                                                             4                     0                                _none_              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
	{ vlan_outer_id_recycle_count            VlanIf_Outer        IfRecycleCount                  NUMERIC                                                             4                     0                               _none_              true        _none_              false       _none_                        {create configVlanOuterIntf modify configVlanOuterIntf}                   _none_}
	{ dad_enable                             SaaDeviceConfig     DupAddrDetection                 {CHOICES true false }                                            4                      false                                  _none_          true            _none_              false       _none_                        {create configSaaDeviceConfig modify configSaaDeviceConfig}     _none_}
    { dad_transmit_count                     SaaDeviceConfig     DupAddrDetectTransmits           NUMERIC                                                          4                        1                                    1-255           true            {{dad_enable true}} false       _none_                        {create configSaaDeviceConfig modify configSaaDeviceConfig}     _none_}
    { dad_retransmit_delay                   SaaDeviceConfig     RetransTimer                     NUMERIC                                                          4                      1000                                   1000-4294967295 true            {{dad_enable true}} false       _none_                        {create configSaaDeviceConfig modify configSaaDeviceConfig}     _none_}
    { router_solicit_retransmit_delay        SaaDeviceConfig     RouterSolicitationRetransTimer   NUMERIC                                                          4                      3000                                   1000-4294967295 true            _none_              false       _none_                        {create configSaaDeviceConfig modify configSaaDeviceConfig}     _none_}
    { router_solicit_retry                   SaaDeviceConfig     RouterSolicitationRetries        NUMERIC                                                          4                        2                                    0-4294967295    true            _none_              false       _none_                        {create configSaaDeviceConfig modify configSaaDeviceConfig}     _none_}
 }

 { emulation_ipv6_autoconfig_control
    { hname              stcobj              stcattr    type                         priority      default      range       supported   dependency      mandatory   procfunc    mode        constants}
    { port_handle        _none_             _none_      ALPHANUM                        1           _none_      0-MAX_INT   true        _none_          false       _none_      _none_      _none_}
    { handle             _none_             _none_      ALPHANUM                        2           _none_      _none_      true        _none_          false       _none_      _none_      _none_}
    { action             _none_             _none_      {CHOICES start stop}            5           _none_      _none_      true        _none_          true        _none_      _none_      _none_}
 }
 
 { emulation_ipv6_autoconfig_stats
    { hname                              stcobj                  stcattr              type                            priority    default     range   supported   dependency  mandatory   procfunc             mode                    constants}
    { action                             _none_                  _none_               {CHOICES collect clear }        2           collect     _none_  true        _none_      false       _none_              _none_                    _none_}
    { handle                             _none_                  _none_               ALPHANUM                        25          _none_      _none_  true        _none_      false       _none_              _none_                    _none_}
    { port_handle                        _none_                  _none_               ALPHANUM                        1           _none_      0-MAX_INT  true     _none_      false       _none_              _none_                    _none_}
    { mode                               _none_                  _none_               {CHOICES aggregate session}     3           _none_      _none_  true        _none_      false       _none_              _none_                    _none_}
    { current_bound                      _none_                  CurrBound            NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { current_idle                       _none_                  CurrIdle             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { state                              _none_                  State                NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { total_attempt                      _none_                  TotAttempt           NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { total_bound                        _none_                  TotBound             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { total_dad_failures                 _none_                  TotDadFailures       NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { total_failed                       _none_                  TotFailed            NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { total_ra_timeout_failures          _none_                  TotRaTimeoutFailures NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" session ""}  _none_}
    { tx_nbr_sol                         _none_                  TxNbrSol             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { tx_rtr_sol                         _none_                  TxRtrSol             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { rx_nbr_adv                         _none_                  RxNbrAdv             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { rx_rtr_adv                         _none_                  RxRtrAdv             NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { success_percent                    _none_                  SuccessPercent       NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {aggregate "" }            _none_}
    { binding_state                      _none_                  BindingState         NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
    { current_attempt                    _none_                  CurrAttempt          NUMERIC                         5           _none_      _none_  true        _none_      false       _none_             {session ""}               _none_}
 }
}
