# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::l2tp:: {
}

set ::sth::l2tp::l2tpTable {
    ::sth::l2tp::
    {l2tp_config
        {hname                          stcobj                              stcattr                                 type                                    priority     default        range     supported dependency mandatory   mode        procfunc    constants}
        {port_handle                    _none_                              _none_                                  _none_                                      1       _none_          _none_      TRUE    _none_    TRUE    {creat ""}    _none_    _none_}
        {mode                           L2tpPortConfig                      L2tpNodeType                        {CHOICES lac lns }                              39      LAC             _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {attempt_rate                   L2tpPortConfig/PppoxPortConfig      TunnelConnectRate                       NUMERIC                                     2       100             1-1000      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_  _none_}
        {disconnect_rate                PppoxPortConfig                     DisconnectRate                          NUMERIC                                     2       _none_          1-1000      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_  _none_}
        {max_outstanding                PppoxPortConfig                     SessionOutstanding                      NUMERIC                                     37      _none_          2-2000      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {avp_framing_type               L2tpv2BlockConfig                    FrameType                        {CHOICES sync   async }                           5       sync            _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    {sync SYNC async ASYNC}}
        {avp_tx_connect_speed           L2tpv2BlockConfig                    TxConnectRate                          NUMERIC                                     9       56000           1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}    
        {avp_hide_list                  L2tpv2BlockConfig                    HiddenAvps                             NUMERIC                                     7       0               _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_  _none_}
        {avp_hide                       _none_                              _none_                              {CHOICES 1 0 TRUE FALSE}                        6       _none_          _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {avp_rx_connect_speed           _none_                              _none_                                  NUMERIC                                     8       _none_          _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {hello_interval                 L2tpv2BlockConfig                    HelloTimeout                           NUMERIC                                     20      60              1-1024      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {hello_req                      L2tpv2BlockConfig                    EnableHello                        {CHOICES 1 0 TRUE FALSE}                        21      FALSE           _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {hostname                       L2tpv2BlockConfig                    HostName                               REGEXP                                      22      "spirent"       _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {tunnel_id_start                L2tpv2BlockConfig                   TunnelStartingId                        NUMERIC                                     65      1               1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {num_tunnels                    L2tpv2BlockConfig                   TunnelCount                             NUMERIC                                     41      1               1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {tun_distribution               _none_                              _none_                      {CHOICES next_tunnel  fill_tunnel domain_group}         64      _none_          _none_      FALSE    _none_    FALSE    {creat ""}    _none_  _none_}
        {tun_auth                       L2tpv2BlockConfig                    EnableDutAuthentication            {CHOICES 1 0 TRUE FALSE}                        63      FALSE           _none_      TRUE    _none_    FALSE    {creat processConfigCmd_secret}    _none_    _none_}
        {session_id_start               L2tpv2BlockConfig                    SessionStartingId                      NUMERIC                                     60      1               1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {sessions_per_tunnel            L2tpv2BlockConfig                    SessionsPerTunnelCount                 NUMERIC                                     61      1               1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {sess_distribution              _none_                              _none_                                {CHOICES next fill}                           59      _none_          _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {rws                            L2tpv2BlockConfig                    RxWindowSize                           NUMERIC                                     55      4               1-2048      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}       
        {redial_max                     L2tpv2BlockConfig                    AutoRetryCount                         NUMERIC                                     53      1               1-20        TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {redial_timeout                 L2tpv2BlockConfig                    RetryTimeout                           NUMERIC                                     54      1               1-20        TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_} 
        {redial                         L2tpv2BlockConfig                    EnableAutoRetry                    {CHOICES 1 0 TRUE FALSE}                        52      _none_          _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}   
        {udp_src_port                   L2tpv2BlockConfig                    UdpSrcPort                             NUMERIC                                     67      1701            1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {force_lcp_renegotiation        L2tpv2BlockConfig                    ForceLcpRenegotiation              {CHOICES 1 0 TRUE FALSE}                        67      _none_          _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    _none_}
        {lcp_proxy_mode                 L2tpv2BlockConfig                    LcpProxyMode               {CHOICES none authentication lcponly }                  5       _none_          _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }        _none_    {none NONE authentication AUTHENTICATION lcponly LCPONLY}}
        {udp_dst_port                   _none_                              _none_                                  NUMERIC                                     66      _none_          1-65535     FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {pvc_incr_mode                  _none_                              _none_                              {CHOICES vpi vci both}                          51      both            _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}               
        {vci                            Aal5If                               Vci                                  NUMERIC                                     70      32              32-65535    TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vci_count                      Aal5If                               VciRecycleCount                        NUMERIC                                     71      1               1-16000     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vci_step                       Aal5If                               VciStep                                NUMERIC                                     72      1               _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vpi                            Aal5If                               Vpi                                    NUMERIC                                     73      32              _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vpi_count                      Aal5If                               IfRecycleCount                         NUMERIC                                     74      1               1-256       TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vpi_step                       Aal5If                               VpiStep                                NUMERIC                                     75      1               _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}     
        {l2_encap                       _none_                              _none_  {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq atm_snap atm_vc_mux} 26    ethernet_ii       _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {secret                         L2tpv2BlockConfig                   RxTunnelPassword                        REGEXP                                      56    "spirent"         _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_id                        VlanIf                              VlanId                                  NUMERIC                                    77       1               1-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_count                     VlanIf                              Count                                   NUMERIC                                    76       1               1-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_id_step                   VlanIf                              IdStep                                  NUMERIC                                    78       0               0-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_user_priority             VlanIf                              Priority                                NUMERIC                                    79       0               0-7         TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_user_priority_count       VlanIf                             _none_                                   NUMERIC                                    80       _none_          1-8         FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_user_priority_step        VlanIf                             _none_                                   NUMERIC                                    81       _none_          _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_id_outer                  VlanIf_Outer                        VlanId                                  NUMERIC                                    77       1               1-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_count_outer               VlanIf_Outer                        Count                                   NUMERIC                                    76       1               1-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_id_step_outer             VlanIf_Outer                        IdStep                                  NUMERIC                                    78       0               0-4095      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {vlan_user_priority_outer       VlanIf_Outer                        Priority                                NUMERIC                                    79       0               0-7         TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {qinq_incr_mode                 _none_                              _none_                          {CHOICES inner outer both}                          26      both             _none_      TRUE            {encap ethernet_ii_qinq}        FALSE  {creat "" }    _none_    _none_}
        {l2tp_mac_addr                  EthIIIf                             SourceMac                               _none_                                      27  "00:10:94:00:00:02" _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_mac_step                  EthIIIf                             SrcMacStep                              _none_                                      27  "00:00:00:00:00:01" _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}       
        {l2tp_dst_addr                  _none_                              Address                                 IP                                          27      "192.85.1.3"    _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_dst_count                 _none_                              DeviceCount                         NUMERIC                                     28      1               _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_dst_step                  _none_                              AddrStep                                _none_                                      29    0.0.0.1           _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_src_addr                  _none_                              Gateway                                 IP                                          30    "192.85.1.3"      _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_src_count                 _none_                              DeviceCount                      NUMERIC                                     31      1               _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {l2tp_src_step                  _none_                              AddrStep                                _none_                                      32    0.0.0.1           _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}      
        {ppp_client_ip                  PppoxServerIpv4PeerPool             StartIpList                             _none_                                      47    "192.0.1.0"       _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {ppp_client_step                PppoxServerIpv4PeerPool             AddrIncrement                           _none_                                      48    "0.0.0.1"         _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {ppp_server_ip                  _none_                              Address                                 _none_                                      49    "192.0.1.1"       _none_      TRUE   _none_    FALSE    {creat "" }    _none_    _none_}
        {ppp_server_step                _none_                              AddrStep                                _none_                                      50    "0.0.0.1"         _none_      TRUE    _none_    FALSE    {creat "" }    _none_    _none_}
        {enable_magic                   PppoL2tpBlockConfig                 EnableMagicNum                      {CHOICES 1 0 TRUE FALSE}                        19    TRUE              _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {ppp_auto_retry                 PppoL2tpv2ClientBlockConfig         EnableAutoRetry                     {CHOICES 1 0 TRUE FALSE}                        19    FALSE             _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {ppp_retry_count                PppoL2tpv2ClientBlockConfig         AutoRetryCount                          NUMERIC                                     38    65535             1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}       
        {auth_mode                      PppoL2tpBlockConfig                 Authentication              {CHOICES none pap chap pap_or_chap}                     3    _none_             _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting } _none_    {none NONE pap PAP chap CHAP_MD5 pap_or_chap AUTO}}
        {auth_req_timeout               PppoL2tpv2ClientBlockConfig         ChapAckTimeout                          NUMERIC                                     4    _none_             1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_PapChap}    _none_    _none_}
        {config_req_timeout             PppoL2tpBlockConfig                 LcpConfigRequestTimeout                 NUMERIC                                     10    3                 1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {echo_req                       PppoL2tpBlockConfig                 EnableEchoRequest                       {CHOICES 1 0 TRUE FALSE}                    16    _none_            _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {echo_req_interval              PppoL2tpBlockConfig                 EchoRequestGenFreq                      NUMERIC                                     17    10                1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_} 
        {max_echo_acks                  PppoL2tpBlockConfig                 MaxEchoRequestAttempts                  NUMERIC                                     17    10                0-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_} 
        {echo_rsp                       _none_                              _none_                                  {CHOICES 1 0 TRUE FALSE}                    18    TURE              _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {enable_magic                   PppoL2tpBlockConfig                 EnableMagicNum                          {CHOICES 1 0 TRUE FALSE}                    19    TRUE              _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {max_auth_req                   PppoL2tpBlockConfig                 _none_                                  NUMERIC                                     34    _none_            1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_PapChap}    _none_    _none_}
        {max_ipcp_req                   PppoL2tpBlockConfig                 NcpConfigRequestMaxAttempts             NUMERIC                                     36    10                1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {max_terminate_req              PppoL2tpBlockConfig                 LcpTermRequestMaxAttempts               NUMERIC                                     38    10                1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}       
        {ipcp_req_timeout               _none_                              _none_                                  NUMERIC                                     25    _none_            1-65535     FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {password                       PppoL2tpBlockConfig                 Password                                REGEXP                                      45    spirent           _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {terminate_req_timeout          PppoL2tpBlockConfig                 LcpTermRequestTimeout                   NUMERIC                                     62    3                 1-65535     TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {username                       PppoL2tpBlockConfig                 Username                                REGEXP                                      68    spirent           _none_      TRUE    _none_    FALSE    {creat processConfigCmd_usersetting }    _none_    _none_}
        {no_call_timeout                _none_                              _none_                                  NUMERIC                                     40    _none_            0-180       FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {domain_group_map               _none_                              _none_                                  KEYLIST                                     15    _none_            _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {secret_wc                      _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        57    _none_            _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {password_wc                    _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        46    _none_            _none_      TRUE    _none_    FALSE    {creat ""}      _none_    _none_}
        {username_wc                    _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        69    _none_            _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {hostname_wc                    _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        23    _none_            _none_      TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_bang_end              _none_                            _none_                                    NUMERIC                                    82    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_bang_start            _none_                            _none_                                    NUMERIC                                    83    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_dollar_end            _none_                            _none_                                    NUMERIC                                    84    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_dollar_start          _none_                            _none_                                    NUMERIC                                    85    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_pound_end             _none_                            _none_                                    NUMERIC                                    86    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_pound_start           _none_                            _none_                                    NUMERIC                                    87    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_question_end          _none_                            _none_                                    NUMERIC                                    88    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {wildcard_question_start        _none_                            _none_                                    NUMERIC                                    89    _none_             0-65535     TRUE    _none_    FALSE    {creat ""}    _none_    _none_}
        {length_bit                     _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        33    _none_            _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}  
        {offset_bit                     _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        42    _none_            _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {offset_byte                    _none_                            _none_                                    NUMERIC                                     43    _none_            0-255       FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {offset_len                     _none_                            _none_                                    NUMERIC                                     44    _none_            0-255       FALSE    _none_    FALSE    {creat ""}      _none_    _none_}        
        {sequence_bit                   _none_                            _none_                                {CHOICES 1 0 TRUE FALSE}                        58    1                 _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {ctrl_chksum                    _none_                              _none_                              {CHOICES 1 0 TRUE FALSE}                        11    _none_            _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {ctrl_retries                   _none_                              _none_                                  NUMERIC                                     12    _none_            1-100       FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {data_chksum                    _none_                              _none_                              {CHOICES 1 0 TRUE FALSE}                        13    _none_            _none_      FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {max_ctrl_timeout               _none_                            _none_                                    NUMERIC                                     35    _none_            1-65535     FALSE    _none_    FALSE    {creat ""}    _none_    _none_}
        {init_ctrl_timeout              _none_                            _none_                                    NUMERIC                                     24    _none_            1-20        FALSE    _none_    FALSE    {creat ""}    _none_    _none_}   
    }
    {l2tp_control
        {hname    stcobj     stcattr      type                                                            priority        default         range           supported       dependency      mandatory        mode        action        constants}
        {handle   _none_     _none_       ALPHANUM                                                        1               _none_          _none_          TRUE            _none_          TRUE             _none_          _none_        _none_}
        {action   _none_     _none_       {CHOICES connect disconnect reset clear pause resume retry abort}     2               _none_          _none_          TRUE            _none_          TRUE             {connect_l2tp L2tpConnect connect_pppox PppoxConnectCommand disconnect_l2tp L2tpDisconnect disconnect_pppox PppoxDisconnect reset_l2tp L2tpAbort reset_pppox PppoxAbort clear_l2tp L2tpClearStats clear_pppox PppoxClearStats pause_pppox PppoxPause resume_pppox PppoxResume retry_pppox PppoxRetry abort_l2tp L2tpAbort abort_pppox PppoxAbort }          _none_        _none_}    
    }
    {l2tp_stats
        {hname    stcobj     stcattr     type                           priority    default     range     supported       dependency      mandatory      procfunc      mode        constants}
        {handle   _none_     _none_      ALPHANUM                              1           _none_      _none_    TRUE            _none_          TRUE           _none_        _none_      _none_}
        {mode     _none_     _none_      {CHOICES aggregate session tunnel}    2           aggregate      _none_    TRUE            _none_          FALSE           _none_        _none_      _none_}
    }
    {l2tp_stats_aggregate
        {hname               stcobj                       stcattr                   type    priority   default  range supported dependency mandatory   procfunc  action  constants}
        {session_status  PppoL2tpv2SessionResults            BlockState                ANY         10        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxBlock   _none_    }     
        {idle                L2tpPortConfig             _none_                        ANY         1         _none_    _none_    TRUE    _none_        _none_    _none_    PortResult _none_}         
        {connecting          L2tpPortConfig             _none_                        ANY         2         _none_    _none_    TRUE    _none_        _none_    _none_    PortResult _none_}         
        {connected           L2tpPortConfig             _none_                        ANY         3         _none_    _none_    TRUE    _none_        _none_    _none_    PortResult _none_}    
        {disconnecting       L2tpPortConfig             _none_                        ANY         4         _none_    _none_    TRUE    _none_        _none_    _none_    PortResult _none_}        
        {atm_mode            L2tpv2BlockResults            _none_                        ANY         5         _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_    }     
        {num_sessions        L2tpv2BlockResults            _none_                        ANY         6         _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_    }     
        {connect_attempts    L2tpv2BlockResults            AttemptedCount                ANY         7         _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_    }     
        {connect_success     PppoL2tpv2SessionResults    ConnectedSuccessCount        ANY         8         _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {disconnect_success  PppoL2tpv2SessionResults    DisconnectedSuccessCount    ANY         9         _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {sessions_up         L2tpPortResults            SessionUpCount                ANY         10        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult    _none_    }     
        {sessions_down       L2tpPortResults            SessionDownCount        ANY         11        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult    _none_    }     
        {disconnect_failed   L2tpv2BlockResults            FailedDisconnectCount        ANY         12        _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_    }     
        {min_setup_time      L2tpPortResults        MinTunnelSetupTime          ANY         13        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult _none_    }     
        {max_setup_time      L2tpPortResults        MaxTunnelSetupTime          ANY         14        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult _none_    }     
        {avg_setup_time      L2tpPortResults             AvgTunnelSetupTime          ANY         15        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult _none_    }     
        {success_setup_rate  L2tpPortResults        TunnelSetupRate             ANY         16        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult  _none_    }
        {ipcp_rx      PppoL2tpv2SessionResults    RxIpcpCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }
        {chap_rx      PppoL2tpv2SessionResults    RxChapCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }
        {retry_count      PppoL2tpv2SessionResults    RetryCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxClientResult    _none_    }
        {echo_reply_rx      PppoL2tpv2SessionResults    RxLcpEchoReplyCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }
        {chap_tx      PppoL2tpv2SessionResults    TxChapCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }
        {ipcp_tx      PppoL2tpv2SessionResults    TxIpcpCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }
        {lcp_cfg_req_rx      PppoL2tpv2SessionResults    RxLcpConfigRequestCount        ANY         17        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {lcp_cfg_req_tx      PppoL2tpv2SessionResults    TxLcpConfigRequestCount        ANY         18        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {lcp_cfg_rej_rx      PppoL2tpv2SessionResults    RxLcpConfigRejectCount        ANY         19        _none_    _none_    TRUE    _none_        _none_     processL2TPGetCmd       PppoxResult    _none_    }     
        {lcp_cfg_rej_tx      PppoL2tpv2SessionResults    TxLcpConfigRejectCount        ANY         20        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }      
        {lcp_cfg_ack_rx      PppoL2tpv2SessionResults    RxLcpConfigAckCount        ANY         21        _none_    _none_    TRUE    _none_        _none_     processL2TPGetCmd       PppoxResult    _none_    }       
        {lcp_cfg_ack_tx      PppoL2tpv2SessionResults    TxLcpConfigAckCount        ANY         22        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {lcp_cfg_nak_rx      PppoL2tpv2SessionResults    RxLcpConfigNakCount        ANY         23        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {lcp_cfg_nak_tx      PppoL2tpv2SessionResults    TxLcpConfigNakCount        ANY         24        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {term_req_rx         PppoL2tpv2SessionResults    RxLcpTermRequestCount        ANY        25        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {term_req_tx         PppoL2tpv2SessionResults    TxLcpTermRequestCount        ANY         26        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }      
        {term_ack_rx         PppoL2tpv2SessionResults    RxLcpTermAckCount        ANY         27        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {term_ack_txv        PppoL2tpv2SessionResults    TxLcpTermAckCount        ANY         28        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PppoxResult    _none_    }     
        {echo_req_rx         PppoL2tpv2SessionResults    RxLcpEchoRequestCount        ANY         29        _none_    _none_    TRUE    _none_        _none_     processL2TPGetCmd       PppoxResult    _none_    }     
        {echo_req_tx         PppoL2tpv2SessionResults    TxLcpEchoRequestCount        ANY         30        _none_    _none_    TRUE    _none_        _none_     processL2TPGetCmd       PppoxResult    _none_    }     
        {zlb_tx              L2tpv2BlockResults         TxAckCount                  ANY         31        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sccrq_tx            L2tpv2BlockResults            TxStartCcRequestCount        ANY         32        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       L2tpResult   _none_    }     
        {scccn_tx            L2tpv2BlockResults            TxStartCcConnectCount        ANY         33        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sccrp_tx            L2tpv2BlockResults            TxStartCcReplyCount        ANY         34        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {stopccn_tx          L2tpv2BlockResults            TxStopCcNotifyCount        ANY         35        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {hello_tx            L2tpv2BlockResults            TxHelloCount                ANY         36        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {icrq_tx             L2tpv2BlockResults            TxIncomingCallRequestCount  ANY         37        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {icrp_tx             L2tpv2BlockResults            TxIncomingCallReplyCount    ANY         38        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {iccn_tx             L2tpv2BlockResults            TxIncomingCallConnectCount  ANY         39        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {cdn_tx              L2tpv2BlockResults            TxCallDisconnectNotifyCount ANY         40        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {wen_tx              L2tpv2BlockResults            TxWanErrorNotifyCount        ANY         41        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sli_tx              L2tpv2BlockResults            TxSetLinkInfoCount        ANY         42        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {zlb_rx              L2tpv2BlockResults         RxAckCount                 ANY         43        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sccrp_rx            L2tpv2BlockResults            RxStartCcReplyCount        ANY         44         _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {scccn_rx            L2tpv2BlockResults            RxStartCcConnectCount        ANY         45        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sccrq_rx            L2tpv2BlockResults            RxStartCcRequestCount        ANY         46        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {stopccn_rx          L2tpv2BlockResults            RxStopCcNotifyCount        ANY         47        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {hello_rx            L2tpv2BlockResults            RxHelloCount                ANY         48        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {icrq_rx             L2tpv2BlockResults            RxIncomingCallRequestCount  ANY         49        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {icrp_rx             L2tpv2BlockResults            RxIncomingCallReplyCount    ANY         50        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {iccn_rx             L2tpv2BlockResults            RxIncomingCallConnectCount  ANY         51        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {cdn_rx              L2tpv2BlockResults            RxCallDisconnectNotifyCount ANY         52        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {wen_rx              L2tpv2BlockResults            RxWanErrorNotifyCount        ANY         53        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {sli_rx              L2tpv2BlockResults            RxSetLinkInfoCount        ANY         54        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {out_of_order_rx     _none_                     _none_                    ANY         55        _none_    _none_    FALSE    _none_        _none_    _none_    _none_    _none_    }     
        {out_of_win_rx       _none_                   _none_                        ANY         56        _none_    _none_    FALSE    _none_        _none_    _none_    _none_    _none_    }     
        {duplicate_rx        _none_                  _none_                    ANY         57        _none_    _none_    FALSE    _none_        _none_    _none_    _none_    _none_    }     
        {in_order_rx         _none_                  _none_                    ANY         58        _none_    _none_    FALSE    _none_        _none_    _none_    _none_    _none_    } 
        {retransmits         _none_                     _none_                      ANY         59        _none_    _none_    FALSE   _none_        _none_    _none_  _none_  _none_    }     
        {tx_pkt_acked        L2tpv2BlockResults            RxAckCount                ANY         60        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd    L2tpResult    _none_    }     
        {tunnels_up          L2tpPortResults        TunnelUpCount                ANY         61        _none_    _none_    TRUE    _none_        _none_    processL2TPGetCmd       PortResult    _none_    }     
        {tunnels_neg         _none_                 _none_                    ANY         62        _none_    _none_    FALSE    _none_        _none_    _none_    _none_    _none_    }     
    }
    {l2tp_stats_session
        {hname                  stcobj              stcattr               type priority      default   range  supported dependency  mandatory procfunc  mode   constants}
        {chap_auth_chal_rx    _none_                _none_                    ANY    1    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_fail_rx    _none_                _none_                    ANY    2    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_rsp_tx    _none_                _none_                    ANY    3    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_succ_rx    _none_                _none_                    ANY    4    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {echo_req_rx            _none_                _none_                    ANY    5    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {echo_rsp_tx            _none_                _none_                    ANY    6    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_ack_rx    _none_                _none_                    ANY    7    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_ack_tx    _none_                _none_                    ANY    8    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_nak_rx    _none_                _none_                    ANY    9    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_nak_tx    _none_                _none_                    ANY    10    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_rej_rx    _none_                _none_                    ANY    11    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_rej_tx    _none_                _none_                    ANY    12    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_req_rx    _none_                _none_                    ANY    13    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_req_tx    _none_                _none_                    ANY    14    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_ack_rx            _none_                _none_                    ANY    15    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_ack_tx            _none_                _none_                    ANY    16    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_nak_rx            _none_                _none_                    ANY    17    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_nak_tx            _none_                _none_                    ANY    18    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_rej_rx            _none_                _none_                    ANY    19    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_rej_tx            _none_                _none_                    ANY    20    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_req_rx            _none_                _none_                    ANY    21    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_req_tx            _none_                _none_                    ANY    22    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_ack_rx    _none_                _none_                    ANY    23    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_nak_rx    _none_                _none_                    ANY    24    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_req_tx    _none_                _none_                    ANY    25    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_ack_rx            _none_                _none_                    ANY    26    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_ack_tx            _none_                _none_                    ANY    27    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_req_rx            _none_                _none_                    ANY    28    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_req_tx            _none_                _none_                    ANY    29    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {tx_pkt_acked            _none_                _none_                    ANY    30    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {cdn_rx            L2tpv2SessionResults      RxCallDisconnectNotifyCount   ANY    31    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {iccn_tx    L2tpv2SessionResults      TxIncomingCallConnectCount    ANY    32    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {icrp_rx    L2tpv2SessionResults      RxIncomingCallReplyCount      ANY    33    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {icrq_rx    L2tpv2SessionResults      RxIncomingCallRequestCount    ANY    34    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {cdn_tx            L2tpv2SessionResults      TxCallDisconnectNotifyCount   ANY    35    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {iccn_rx    L2tpv2SessionResults      RxIncomingCallConnectCount    ANY    36    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {icrp_tx    L2tpv2SessionResults      TxIncomingCallReplyCount      ANY    37    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
        {icrq_tx    L2tpv2SessionResults      TxIncomingCallRequestCount    ANY    38    _none_    _none_    TRUE    _none_        _none_    processL2TPSessionGetCmd    _none_    _none_}
    }
    {l2tp_stats_tunnel
        {hname          stcobj                  stcattr           type   priority    default  range   supported dependency mandatory  procfunc   mode   constants}
        {zlb_tx        _none_              _none_                  ANY    1    _none_    _none_    TRUE    _none_        _none_    _none_  _none_    _none_}
        {sccrp_tx    L2tpv2TunnelResults    TxStartCcReplyCount     ANY    2    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd            _none_    _none_}
        {scccn_tx    L2tpv2TunnelResults    TxStartCcConnectCount   ANY    3    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {stopccn_tx    L2tpv2TunnelResults    TxStopCcNotifyCount     ANY    4    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {hello_tx    L2tpv2TunnelResults    TxHelloCount            ANY    5    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {icrq_tx        _none_          _none_              ANY    6    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {icrp_tx        _none_          _none_              ANY    7    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {iccn_tx        _none_            _none_                  ANY    8    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {cdn_tx        _none_                    _none_                  ANY    9    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {wen_tx            L2tpv2TunnelResults    TxWanErrorNotifyCount   ANY    10    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {sli_tx            L2tpv2TunnelResults    TxStopCcNotifyCount     ANY    11    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {zlb_rx        _none_                    _none_                  ANY    12    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {sccrp_rx    L2tpv2TunnelResults     RxStartCcReplyCount     ANY    13    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {scccn_rx    L2tpv2TunnelResults     RxStartCcConnectCount   ANY    14    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {stopccn_rx    L2tpv2TunnelResults     RxStopCcNotifyCount     ANY    15    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {hello_rx    L2tpv2TunnelResults     RxHelloCount            ANY    16    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {icrq_rx        _none_            _none_                  ANY    17    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {icrp_rx        _none_            _none_                  ANY    18    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {iccn_rx        _none_            _none_                  ANY    19    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {cdn_rx        _none_                    _none_                  ANY    20    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {wen_rx            L2tpv2TunnelResults     RxWanErrorNotifyCount   ANY    21    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {sli_rx            L2tpv2TunnelResults     RxSetLinkInfoCount      ANY    22    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
        {out_of_order_rx    _none_        _none_                  ANY    23    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {out_of_win_rx            _none_        _none_                  ANY    24    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {duplicate_rx            _none_        _none_                  ANY    25    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {in_order_rx            _none_        _none_                  ANY    26    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {retransmits            _none_        _none_                  ANY    27    _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {tx_pkt_acked    L2tpv2TunnelResults     TxAckCount              ANY    28    _none_    _none_    TRUE    _none_        _none_    processL2TPTunnelGetCmd        _none_    _none_}
    }
}

