# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::l2tpv3:: {
}

set ::sth::l2tpv3::l2tpv3Table {
    ::sth::l2tpv3::
    {l2tpv3_config
        {hname                          stcobj                             stcattr                              type                                                                      priority              default                              range           supported      dependency       mandatory             mode                                                                                 procfunc    constants}
        {mode                           _none_                             _none_                              {CHOICES create  modify  delete}                                           0                      _none_                              _none_          TRUE           _none_           TRUE                 {creat "" modify "" delete ""}                                                        _none_      _none_}
        {port_handle                    _none_                             _none_                               ALPHANUM                                                                  2                      _none_                              _none_          TRUE           _none_           FALSE                {creat ""}                                                                            _none_      _none_}
        {handle                         _none_                             _none_                               ALPHANUM                                                                  1                      _none_                              _none_          TRUE          {mode modify}     FALSE                {modify "" delete ""}                                                                 _none_      _none_}
        {l2tp_node_type                 L2tpPortConfig                     L2tpNodeType                        {CHOICES lac lns }                                                         3                      lac                                 _none_          TRUE          {mode create}     FLSE                 {creat  processConfigCmd_usersetting  modify ""}                                                _none_      _none_}
        {connect_rate                   L2tpPortConfig                     ConnectRateV3                        NUMERIC                                                                   50                     100                                 1-1000          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {disconnect_rate                L2tpPortConfig                     DisconnectRateV3                     NUMERIC                                                                   50                     100                                 1-1000          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {seq_type                       L2tpPortConfig                     SeqType                             {CHOICES sequential parallel  }                                            51                     sequential                          _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {session_out_standing           L2tpPortConfig                     SessionOutstandingV3                 NUMERIC                                                                   52                     100                                 2-65535         TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {tunnel_connect_rate            L2tpPortConfig                     TunnelConnectRate                    NUMERIC                                                                   53                     100                                 1-1000          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {pseudo_wire_capabilities       l2tpv3BlockConfig                  PseudowireCapabilities               ANY                                                                       5                     ETHERNET                            _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {tx_connect_rate                l2tpv3BlockConfig                  TxConnectRate                        NUMERIC                                                                   9                      56000                               1-65535         TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}    
        {avp_hide                       l2tpv3BlockConfig                  HiddenAvps                           NUMERIC                                                                   70                      0                                   _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {ipv4_tos                       l2tpv3BlockConfig                  Ipv4Tos                              NUMERIC                                                                   70                      192                                 _none_          TRUE         {ip_encap  IPV4 } FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {use_gateway_as_remote_ipv4addr l2tpv3BlockConfig                 UseGatewayAsRemoteIpv4Addr            {CHOICES 1 0 TRUE FALSE}                                                   70                      1                                   _none_          TRUE         {ip_encap  IPV4 } FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {use_gateway_as_remote_ipv6addr l2tpv3BlockConfig                 UseGatewayAsRemoteIpv6Addr            {CHOICES 1 0 TRUE FALSE}                                                   70                      1                                   _none_          TRUE         {ip_encap  IPV6 } FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {hello_interval                 l2tpv3BlockConfig                  HelloTimeout                         NUMERIC                                                                   20                     60                                  1-1024          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {hello_req                      l2tpv3BlockConfig                  EnableHello                          {CHOICES 1 0 TRUE FALSE}                                                  21                     FALSE                               _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {hostname                       l2tpv3BlockConfig                  HostName                             REGEXP                                                                    22                     "server.spirent.com"                _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {secret                         l2tpv3BlockConfig                  TxTunnelPassword                     REGEXP                                                                    22                     "spirent"                           _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {ip_encap                       l2tpv3BlockConfig                  IpEncap                              {CHOICES IPV4 IPV6}                                                       65                      IPV4                                1-65535          TRUE          _none_          FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {num_tunnels                    l2tpv3BlockConfig                  TunnelCount                          NUMERIC                                                                   41                      1                                 1-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {tun_auth                       l2tpv3BlockConfig                  EnableDutAuthentication              {CHOICES 1 0 TRUE FALSE}                                                  63                      FALSE                              _none_          TRUE          _none_            FALSE                {creat  processConfigCmd_secret       modify processConfigCmd_secret}                 _none_      _none_}
        {session_id_start               l2tpv3BlockConfig                  SessionStartingId                    NUMERIC                                                                   60                      1                                 1-4294967295     TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {tunnel_id_start                l2tpv3BlockConfig                  TunnelStartingId                     NUMERIC                                                                   60                      1                                 1-4294967295     TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {sessions_per_tunnel            l2tpv3BlockConfig                  SessionsPerTunnelCount               NUMERIC                                                                   61                      1                                 1-4294967295     TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {rx_window_size                 l2tpv3BlockConfig                  RxWindowSize                         NUMERIC                                                                   55                      4                                 1-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}       
        {retry_max                      l2tpv3BlockConfig                  AutoRetryCount                       NUMERIC                                                                   53                      1                                 1-20             TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {retry_timeout                  l2tpv3BlockConfig                  RetryTimeout                         NUMERIC                                                                   54                      1                                 1-255            TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_} 
        {retry_enable                   l2tpv3BlockConfig                  EnableAutoRetry                      {CHOICES 1 0 TRUE FALSE}                                                  52                      _none_                            _none_           TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}   
        {udp_src_port                   l2tpv3BlockConfig                  UdpSrcPort                           NUMERIC                                                                   67                      1701                              0-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {force_lcp_renegotiation        l2tpv3BlockConfig                  ForceLcpRenegotiation                {CHOICES 1 0 TRUE FALSE}                                                  67                      _none_                            _none_           TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {lcp_proxy_mode                 l2tpv3BlockConfig                  LcpProxyMode                         {CHOICES none authentication lcponly }                                    5                       _none_                            _none_           TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_     {none NONE authentication AUTHENTICATION lcponly LCPONLY}}
        {pseudowire_type                L2tpv3SessionBlockParams           PseudowireType                        ANY                                                                      5                     ethernet                            _none_           TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {remote_end_id_start            L2tpv3SessionBlockParams           RemoteEndIdStart                      NUMERIC                                                                  67                      1                                 1-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {remote_end_id_step             L2tpv3SessionBlockParams           RemoteEndIdStep                       NUMERIC                                                                  67                      1                                 1-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {session_count                  L2tpv3SessionBlockParams           SessionCount                          NUMERIC                                                                  5                       1                                 1-65535          TRUE          _none_            FALSE                {creat  processConfigCmd_usersetting  modify processConfigCmd_usersetting}            _none_      _none_}
        {l2_encap                       _none_                             _none_                          {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}                        26                      ethernet_ii                       _none_           TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_id                        VlanIf                             VlanId                                NUMERIC                                                                  77                      1                                 1-4095           TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_count                     VlanIf                             Count                                  NUMERIC                                                                 76                      1                                 1-4095           TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_id_step                   VlanIf                             IdStep                                 NUMERIC                                                                 78                      0                                 0-4095           TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_user_priority             VlanIf                             Priority                               NUMERIC                                                                 79                      0                                 0-7              TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_user_priority_count       VlanIf                             _none_                                 NUMERIC                                                                 80                      _none_                            1-8              FALSE         _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_user_priority_step        VlanIf                             _none_                                 NUMERIC                                                                 81                      _none_                           _none_            FALSE         _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_id_outer                  VlanIf_Outer                       VlanId                                 NUMERIC                                                                 77                      1                                1-4095            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_count_outer               VlanIf_Outer                       Count                                  NUMERIC                                                                 76                      1                                1-4095            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_id_step_outer             VlanIf_Outer                       IdStep                                 NUMERIC                                                                 78                      0                                0-4095            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {vlan_user_priority_outer       VlanIf_Outer                       Priority                               NUMERIC                                                                 79                      0                                0-7               TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {qinq_incr_mode                 _none_                             _none_                                {CHOICES inner outer both}                                               26                      both                            _none_             TRUE {l2_encap ethernet_ii_qinq} FALSE               {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_mac_addr                EthIIIf                            SourceMac                              _none_                                                                  27                      "00:10:94:00:00:02"             _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_mac_step                EthIIIf                            SrcMacStep                             _none_                                                                  27                      "00:00:00:00:00:01"             _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}       
        {remote_ipv4addr                Ipv4NetworkBlock                   StartIpList                         IP                                                                      27                      "192.85.1.3"                    _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}       
        {remote_ipv6addr                Ipv6NetworkBlock                   StartIpList                         IP                                                                      27                      "2000::2"                       _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}       
        {l2tpv3_dst_addr                _none_                             Address                                IP                                                                      27                      "192.85.1.3"                    _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_dst_count               _none_                             DeviceCount                            NUMERIC                                                                 28                       1                              _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_dst_step                _none_                             AddrStep                               _none_                                                                  29                       0.0.0.1                        _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_src_addr                _none_                             Gateway                                IP                                                                      30                       "192.85.1.3"                   _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_src_count               _none_                             DeviceCount                            NUMERIC                                                                 31                       1                              _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {l2tpv3_src_step                _none_                             AddrStep                               _none_                                                                  32                       0.0.0.1                        _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}      
        {secret_wc                      _none_                             _none_                                {CHOICES 1 0 TRUE FALSE}                                                 57                       _none_                         _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {hostname_wc                    _none_                             _none_                                {CHOICES 1 0 TRUE FALSE}                                                 23                       _none_                         _none_             TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_bang_end              _none_                             _none_                                NUMERIC                                                                  82                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_bang_start            _none_                             _none_                                NUMERIC                                                                  83                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_dollar_end            _none_                             _none_                                NUMERIC                                                                  84                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_dollar_start          _none_                             _none_                                NUMERIC                                                                  85                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_pound_end             _none_                             _none_                                NUMERIC                                                                  86                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_pound_start           _none_                             _none_                                NUMERIC                                                                  87                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_question_end          _none_                             _none_                                NUMERIC                                                                  88                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        {wildcard_question_start        _none_                             _none_                                NUMERIC                                                                  89                       _none_                         0-65535            TRUE          _none_            FALSE                {creat "" modify ""}                                                                  _none_      _none_}
        
    }
    {l2tpv3_control
        {hname    stcobj     stcattr      type                                                                       priority        default         range           supported       dependency      mandatory        mode        action        constants}
        {handle   _none_     _none_       ALPHANUM                                                                   1               _none_          _none_          TRUE            _none_          TRUE             _none_      _none_         _none_}
        {action   _none_     _none_       {CHOICES connect disconnect retry terminate}                               2               _none_          _none_          TRUE            _none_          TRUE             _none_       _none_        _none_}    
    }
    {l2tpv3_stats
        {hname    stcobj     stcattr     type                                  priority    default     range     supported       dependency      mandatory      procfunc      mode        constants}
        {handle   _none_     _none_      ALPHANUM                              1           _none_      _none_    TRUE            _none_          TRUE           _none_        _none_      _none_}
        {mode     _none_     _none_      {CHOICES aggregate session tunnel}    2           aggregate   _none_    TRUE            _none_          FALSE          _none_        _none_      _none_}
    }
    {l2tpv3_stats_aggregate
        {hname                     stcobj                              stcattr                       type        priority  default   range   supported dependency    mandatory    procfunc                     action          constants}
        {idle                      l2tpv3PortConfig                    _none_                        ANY         1         _none_    _none_    TRUE    _none_        _none_       _none_                       PortResult      _none_}         
        {connecting                l2tpv3PortConfig                    _none_                        ANY         2         _none_    _none_    TRUE    _none_        _none_       _none_                       PortResult      _none_}         
        {connected                 l2tpv3PortConfig                    _none_                        ANY         3         _none_    _none_    TRUE    _none_        _none_       _none_                       PortResult      _none_}    
        {disconnecting             l2tpv3PortConfig                    _none_                        ANY         4         _none_    _none_    TRUE    _none_        _none_       _none_                       PortResult      _none_}        
        {atm_mode                  l2tpv3BlockResults                  _none_                        ANY         5         _none_    _none_    TRUE    _none_        _none_       _none_                       _none_          _none_}     
        {num_sessions              l2tpv3BlockResults                  _none_                        ANY         6         _none_    _none_    TRUE    _none_        _none_       _none_                       _none_          _none_}     
        {connect_attempts          l2tpv3BlockResults                  AttemptedCount                ANY         7         _none_    _none_    TRUE    _none_        _none_       _none_                       _none_          _none_}     
        {sessions_up               l2tpv3PortResults                   SessionUpCount                ANY         10        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}     
        {sessions_down             l2tpv3PortResults                   SessionDownCount              ANY         11        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}     
        {disconnect_failed         l2tpv3BlockResults                  FailedDisconnectCount         ANY         12        _none_    _none_    TRUE    _none_        _none_       _none_                      _none_           _none_}     
        {min_setup_time            l2tpv3PortResults                   MinTunnelSetupTime            ANY         13        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}     
        {max_setup_time            l2tpv3PortResults                   MaxTunnelSetupTime            ANY         14        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}     
        {avg_setup_time            l2tpv3PortResults                   AvgTunnelSetupTime            ANY         15        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}     
        {success_setup_rate        l2tpv3PortResults                   TunnelSetupRate               ANY         16        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         PortResult       _none_}
        {zlb_tx                    l2tpv3BlockResults                  TxAckCount                    ANY         31        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sccrq_tx                  l2tpv3BlockResults                  TxStartCcRequestCount         ANY         32        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {scccn_tx                  l2tpv3BlockResults                  TxStartCcConnectCount         ANY         33        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sccrp_tx                  l2tpv3BlockResults                  TxStartCcReplyCount           ANY         34        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {stopccn_tx                l2tpv3BlockResults                  TxStopCcNotifyCount           ANY         35        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {hello_tx                  l2tpv3BlockResults                  TxHelloCount                  ANY         36        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {icrq_tx                   l2tpv3BlockResults                  TxIncomingCallRequestCount    ANY         37        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {icrp_tx                   l2tpv3BlockResults                  TxIncomingCallReplyCount      ANY         38        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {iccn_tx                   l2tpv3BlockResults                  TxIncomingCallConnectCount    ANY         39        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {cdn_tx                    l2tpv3BlockResults                  TxCallDisconnectNotifyCount   ANY         40        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {wen_tx                    l2tpv3BlockResults                  TxWanErrorNotifyCount         ANY         41        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sli_tx                    l2tpv3BlockResults                  TxSetLinkInfoCount            ANY         42        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {zlb_rx                    l2tpv3BlockResults                  RxAckCount                    ANY         43        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sccrp_rx                  l2tpv3BlockResults                  RxStartCcReplyCount           ANY         44        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {scccn_rx                  l2tpv3BlockResults                  RxStartCcConnectCount         ANY         45        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sccrq_rx                  l2tpv3BlockResults                  RxStartCcRequestCount         ANY         46        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {stopccn_rx                l2tpv3BlockResults                  RxStopCcNotifyCount           ANY         47        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {hello_rx                  l2tpv3BlockResults                  RxHelloCount                  ANY         48        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {icrq_rx                   l2tpv3BlockResults                  RxIncomingCallRequestCount    ANY         49        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {icrp_rx                   l2tpv3BlockResults                  RxIncomingCallReplyCount      ANY         50        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {iccn_rx                   l2tpv3BlockResults                  RxIncomingCallConnectCount    ANY         51        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {cdn_rx                    l2tpv3BlockResults                  RxCallDisconnectNotifyCount   ANY         52        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {wen_rx                    l2tpv3BlockResults                  RxWanErrorNotifyCount         ANY         53        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {sli_rx                    l2tpv3BlockResults                  RxSetLinkInfoCount            ANY         54        _none_    _none_    TRUE    _none_        _none_       processl2tpv3GetCmd         l2tpv3Result     _none_}     
        {out_of_order_rx           _none_                              _none_                        ANY         55        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_}     
        {out_of_win_rx             _none_                              _none_                        ANY         56        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_}     
        {duplicate_rx              _none_                              _none_                        ANY         57        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_}     
        {in_order_rx               _none_                              _none_                        ANY         58        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_} 
        {retransmits               _none_                              _none_                        ANY         59        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_}     
        {tx_pkt_acked              l2tpv3BlockResults                  RxAckCount                    ANY         60        _none_    _none_    TRUE    _none_        _none_      processl2tpv3GetCmd          l2tpv3Result     _none_}     
        {tunnels_up                l2tpv3PortResults                   TunnelUpCount                 ANY         61        _none_    _none_    TRUE    _none_        _none_      processl2tpv3GetCmd          PortResult       _none_}     
        {tunnels_neg               _none_                              _none_                        ANY         62        _none_    _none_    FALSE   _none_        _none_      _none_                       _none_           _none_}     
    }
    {l2tpv3_stats_session
        {hname                        stcobj                            stcattr                   type   priority      default   range  supported dependency  mandatory     procfunc  mode   constants}
        {chap_auth_chal_rx            _none_                            _none_                    ANY    1             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_fail_rx            _none_                            _none_                    ANY    2             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_rsp_tx             _none_                            _none_                    ANY    3             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {chap_auth_succ_rx            _none_                            _none_                    ANY    4             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {echo_req_rx                  _none_                            _none_                    ANY    5             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {echo_rsp_tx                  _none_                            _none_                    ANY    6             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_ack_rx              _none_                            _none_                    ANY    7             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_ack_tx              _none_                            _none_                    ANY    8             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_nak_rx              _none_                            _none_                    ANY    9             _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_nak_tx              _none_                            _none_                    ANY    10            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_rej_rx              _none_                            _none_                    ANY    11            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_rej_tx              _none_                            _none_                    ANY    12            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_req_rx              _none_                            _none_                    ANY    13            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {ipcp_cfg_req_tx              _none_                            _none_                    ANY    14            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_ack_rx               _none_                            _none_                    ANY    15            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_ack_tx               _none_                            _none_                    ANY    16            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_nak_rx               _none_                            _none_                    ANY    17            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_nak_tx               _none_                            _none_                    ANY    18            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_rej_rx               _none_                            _none_                    ANY    19            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_rej_tx               _none_                            _none_                    ANY    20            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_req_rx               _none_                            _none_                    ANY    21            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {lcp_cfg_req_tx               _none_                            _none_                    ANY    22            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_ack_rx              _none_                            _none_                    ANY    23            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_nak_rx              _none_                            _none_                    ANY    24            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {pap_auth_req_tx              _none_                            _none_                    ANY    25            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_ack_rx                  _none_                            _none_                    ANY    26            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_ack_tx                  _none_                            _none_                    ANY    27            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_req_rx                  _none_                            _none_                    ANY    28            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {term_req_tx                  _none_                            _none_                    ANY    29            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {tx_pkt_acked                 _none_                            _none_                    ANY    30            _none_    _none_    TRUE    _none_        _none_    _none_    _none_    _none_}
        {cdn_rx                       l2tpv3SessionResults      RxCallDisconnectNotifyCount       ANY    31            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {iccn_tx                      l2tpv3SessionResults      TxIncomingCallConnectCount        ANY    32            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {icrp_rx                      l2tpv3SessionResults      RxIncomingCallReplyCount          ANY    33            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {icrq_rx                      l2tpv3SessionResults      RxIncomingCallRequestCount        ANY    34            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {cdn_tx                       l2tpv3SessionResults      TxCallDisconnectNotifyCount       ANY    35            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {iccn_rx                      l2tpv3SessionResults      RxIncomingCallConnectCount        ANY    36            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {icrp_tx                      l2tpv3SessionResults      TxIncomingCallReplyCount          ANY    37            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
        {icrq_tx                      l2tpv3SessionResults      TxIncomingCallRequestCount        ANY    38            _none_    _none_    TRUE    _none_        _none_    processl2tpv3SessionGetCmd    _none_    _none_}
    }
    {l2tpv3_stats_tunnel
        {hname               stcobj                       stcattr                 type   priority    default     range  supported dependency    mandatory      procfunc                         mode      constants}
        {zlb_tx              _none_                       _none_                  ANY    1            _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {sccrp_tx            l2tpv3TunnelResults          TxStartCcReplyCount     ANY    2            _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {scccn_tx            l2tpv3TunnelResults          TxStartCcConnectCount   ANY    3            _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {stopccn_tx          l2tpv3TunnelResults          TxStopCcNotifyCount     ANY    4            _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {hello_tx            l2tpv3TunnelResults          TxHelloCount            ANY    5            _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {icrq_tx             _none_                       _none_                  ANY    6            _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {icrp_tx             _none_                       _none_                  ANY    7            _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {iccn_tx             _none_                       _none_                  ANY    8            _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {cdn_tx              _none_                       _none_                  ANY    9            _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {wen_tx              l2tpv3TunnelResults          TxWanErrorNotifyCount   ANY    10           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {sli_tx              l2tpv3TunnelResults          TxStopCcNotifyCount     ANY    11           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {zlb_rx              _none_                       _none_                  ANY    12           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {sccrp_rx            l2tpv3TunnelResults          RxStartCcReplyCount     ANY    13           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {scccn_rx            l2tpv3TunnelResults          RxStartCcConnectCount   ANY    14           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {stopccn_rx          l2tpv3TunnelResults          RxStopCcNotifyCount     ANY    15           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {hello_rx            l2tpv3TunnelResults          RxHelloCount            ANY    16           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {icrq_rx             _none_                       _none_                  ANY    17           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {icrp_rx             _none_                       _none_                  ANY    18           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {iccn_rx             _none_                       _none_                  ANY    19           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {cdn_rx              _none_                       _none_                  ANY    20           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {wen_rx              l2tpv3TunnelResults          RxWanErrorNotifyCount   ANY    21           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {sli_rx              l2tpv3TunnelResults          RxSetLinkInfoCount      ANY    22           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
        {out_of_order_rx     _none_                       _none_                  ANY    23           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {out_of_win_rx       _none_                       _none_                  ANY    24           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {duplicate_rx        _none_                       _none_                  ANY    25           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {in_order_rx         _none_                       _none_                  ANY    26           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {retransmits         _none_                       _none_                  ANY    27           _none_    _none_    TRUE    _none_        _none_         _none_                           _none_    _none_}
        {tx_pkt_acked        l2tpv3TunnelResults          TxAckCount              ANY    28           _none_    _none_    TRUE    _none_        _none_         processl2tpv3TunnelGetCmd        _none_    _none_}
    }
    
}

