# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Ldp:: {
}

set ::sth::Ldp::LdpTable {
	::sth::Ldp::
	{	emulation_ldp_config
		{hname	                			stcobj	        	stcattr	        			type            					priority			default	range	supported	dependency	mandatory	procfunc	mode	constants}
		{count	                			_none_	        	_none_	        			NUMERIC         					15	          		1	_none_	true	_none_	false	_none_	_none_	_none_}
		{egress_label_mode				LdpRouterConfig		EgressLabel				{CHOICES nextlabel imnull exnull} 			16				_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{nextlabel LDP_EGRESS_NEXTAVAILABLE imnull LDP_EGRESS_IMPLICIT_NULL exnull LDP_EGRESS_EXPLICIT_NULL}}
		{handle	                			_none_	        	_none_	        			ALPHANUM						10	        		_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{affiliated_router_target 			Router			AffiliatedRouter-targets 		ALPHANUM 						10	        		_none_	_none_	true	_none_	false	_none_	{create processConfigCmd modify processConfigCmd}	_none_}
                {mac_address_init       			EthiiIf         	SourceMac       			ANY             					100             		_none_  _none_ true _none_ false processConfigCmd {create processConfigCmd modify processConfigCmd} _none_}
		{hello_interval	        			LdpRouterConfig		HelloInterval				NUMERIC         					70	       			5	1-65535	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{intf_ip_addr	        			Ipv4If	        	Address					IP	        					30	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{intf_ip_addr_step				Ipv4If	        	_none_	        			IP	        					35	        		0.0.0.1	_none_	true	_none_	false	_none_	_none_	_none_}
		{gateway_ip_addr				Ipv4If	        	Gateway	        			IP	        					30	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{gateway_ip_addr_step				Ipv4If	        	_none_	        			IP	        					35	        		0.0.0.1	_none_	true	_none_	false	_none_	_none_	_none_}
		{graceful_restart				LdpRouterConfig		EnableGracefulRestart			{CHOICES 0 1} 						16				0	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{graceful_recovery_timer 			LdpRouterConfig 	RecoveryTime				NUMERIC         					18	        		140	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{reconnect_time					LdpRouterConfig		ReconnectTime				NUMERIC         					17	        		60	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{recovery_time	        			LdpRouterConfig		RecoveryTime				NUMERIC         					18	        		140	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{intf_prefix_length				Ipv4If	        	PrefixLength				NUMERIC         					40	        		24	1-128	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{keepalive_interval				LdpRouterConfig		KeepAliveInterval 			NUMERIC       						75	        		45	1-21845		true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{targeted_hello_interval			LdpRouterConfig		TargetedHelloInterval 			NUMERIC       						75	        		5	1-21845		true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{label_adv	        			LdpRouterConfig		LabelAdvertisementMode			{CHOICES unsolicited on_demand}				20				unsolicited   _none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{unsolicited DOWNSTREAM_UNSOLICITED on_demand DOWNSTREAM_ON_DEMAND}}
		{label_start	        			LdpRouterConfig		LabelMin				NUMERIC         					80	        		_none_	0-1046400 true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{label_step					LdpRouterConfig	        _none_	        			NUMERIC         					15	        		1	_none_	true	_none_	false	_none_	_none_	_none_}
		{lsr_id		        			Router	        	RouterId        			IPV4            					45	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{lsr_id_step	        			Router	        	_none_	        			IPV4            					50	        		_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{mode	                			_none_	        	_none_	        		{CHOICES create modify delete disable enable active inactive activate}	1				_none_	_none_	true	_none_	true	_none_	_none_	_none_}	
		{peer_discovery					LdpRouterConfig		HelloType				{CHOICES link targeted link_and_targeted}	 	25				link	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{link LDP_DIRECTED_HELLO targeted LDP_TARGETED_HELLO link_and_targeted LDP_DIRECTED_AND_TARGETED_HELLO}}
		{port_handle	        			_none_	        	_none_	        			ALPHANUM						5	        		_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{remote_ip_addr					LdpRouterConfig		DutIp	        			IP	        					60	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{remote_ip_addr_step				LdpRouterConfig	        DutIpStep 	        			IP	        					65	        		0.0.0.1	_none_	true	_none_	false	_none_	_none_	_none_}
		{cfi    	        			VlanIf	        	Cfi					{CHOICES 0 1}   					90	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_cfi	        			VlanIf	        	Cfi					{CHOICES 0 1}   					90	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_id	        			VlanIf	        	VlanId	        			NUMERIC         					100	        		_none_	0-4095	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_id_mode	        			VlanIf	        	_none_	        			{CHOICES fixed increment} 				105				_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{vlan_id_step	        			VlanIf	        	IdStep	        			NUMERIC         					110				_none_	_none_	true	vlan_id_mode	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_user_priority				VlanIf	        	Priority				NUMERIC         					115	        		_none_	0-7	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}	
		{vlan_outer_id	        			VlanIf_Outer		VlanId	        			NUMERIC         					100	        		_none_	0-4095	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_outer_id_mode				VlanIf_Outer	        _none_	        			{CHOICES fixed increment} 				105				_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{vlan_outer_id_step				VlanIf_Outer		IdStep	        			NUMERIC         					110				_none_	_none_	true	vlan_id_mode	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vlan_outer_user_priority 			VlanIf_Outer		Priority				NUMERIC         					115	        		_none_	0-7	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}	
	        {tunnel_handle	        			_none_	        	_none_	        			ANY             					100	        		_none_	_none_	true	_none_	false	<procName>	_none_	_none_ }
                {bfd_registration       			LdpRouterConfig 	EnableBfd       			{CHOICES 1 0}   					200             		_none_  _none_  true    _none_  false       _none_     {create processConfigCmd modify processConfigCmd}   _none_}
		{vci	                			Aal5If	        	Vci	        			NUMERIC         					120	        		_none_	0-65535	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vci_step	        			Aal5If	        	VciStep	        			NUMERIC         					125	        		_none_	0-65535	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vpi	               		 		Aal5If	        	Vpi	        			NUMERIC         					130	        		_none_  0-4095	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vpi_step	        			Aal5If	        	VpiStep	        			NUMERIC         					135	        		_none_	0-4095	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
                {enable_l2vpn_vc_fecs   			_none_          	_none_          			{CHOICES 0 1}   					140             		_none_  _none_  false   _none_   false   _none_ _none_  _none_}
                {enable_vc_group_matching  			_none_       		_none_          			{CHOICES 0 1}   					140             		_none_  _none_  false   _none_   false   _none_ _none_  _none_}
		{loopback_ip_addr				Router	        	RouterId				IP	        					45	        		_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{loopback_ip_addr_step				_none_	        	_none_	        			IP              					50	        		0.0.0.1	_none_	true	_none_	false	_none_	_none_	_none_}                
		{ip_version	        			_none_	        	_none_					{CHOICES ipv4 ipv6 ipv46} 				30	        		ipv4			_none_	true	_none_	false	_none_	_none_	_none_}
		{intf_ipv6_addr	        			Ipv6If	        	Address					IP	        					30	        		_none_			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{intf_ipv6_addr_step				Ipv6If	        	_none_					IP	        					30	        		_none_			_none_	true	_none_	false	_none_	_none_	_none_}
		{intf_ipv6_prefix_length 			Ipv6If	        	PrefixLength				NUMERIC         					40	        		64			1-128	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{gateway_ipv6_addr				Ipv6If	        	Gateway					IP	        					30	        		_none_			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{gateway_ipv6_addr_step				Ipv6If	        	_none_					IP	        					30	        		_none_			_none_	true	_none_	false	_none_	_none_	_none_}
		{link_local_ipv6_addr				Ipv6If_Link_Local 	Address					IP	        					30	        		fe80::1			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{link_local_ipv6_addr_step 			Ipv6If_Link_Local	_none_					IP	        					30	        		_none_			_none_	true	_none_	false	_none_	_none_	_none_}
		{link_local_ipv6_prefix_length 			Ipv6If_Link_Local 	PrefixLength 				NUMERIC   						40	        		64			1-128	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{ipv6_router_id					Router	        	IPv6RouterId    			IPV6            					45	       			_none_			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{ipv6_router_id_step				Router	        	_none_ 					IPV6            					50	        		_none_			_none_	true	_none_	false	_none_	_none_	_none_}
		{adjacency_version				LdpRouterConfig		AdjacencyVersion 			{CHOICES ipv4 ipv6 ipv4_and_ipv6 first}			20				ipv4  			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{ipv4 LDP_IPV4_ADJACENCY ipv6 LDP_IPV6_ADJACENCY ipv4_and_ipv6 LDP_IPV6_ADJACENCY first LDP_FIRST_ADJACENCY}}
		{directed_hello_interval 			LdpRouterConfig 	DirectedHelloInterval			NUMERIC 						80				5			1-21845 true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{remote_ipv6_addr				LdpRouterConfig		DutIpv6	        			IP	        					60	        		_none_			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{remote_ipv6_addr_step				LdpRouterConfig		DutIpv6Step                               IP	        					65	        		::1			_none_	true	_none_	false	_none_	_none_	_none_}
		{enable_lsp_results				LdpRouterConfig		EnableLspResults			{CHOICES 0 1} 						16				1			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{enable_stateful_pseudowire_lsp_results		LdpRouterConfig		EnableStatefulPseudowireLspResults	{CHOICES 0 1} 						16				0			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{generalized_pwid_lsp_label_binding_mode 	LdpRouterConfig		GeneralizedPwidLspLabelBindingMode	{CHOICES tx_and_rx tx_only rx_only none} 		16				tx_and_rx		_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{hello_version 					LdpRouterConfig		HelloVersion				{CHOICES ipv4 ipv6 ipv4_and_ipv6} 			16				ipv4			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{ipv4 LDP_IPV4_HELLO ipv6 LDP_IPV6_HELLO ipv4_and_ipv6 LDP_IPV4_AND_IPV6_HELLO}}
		{label_request_retry_count 			LdpRouterConfig 	LabelRequestRetryCount			NUMERIC 						80				10			_none_ 	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{label_request_retry_interval 			LdpRouterConfig 	LabelRequestRetryInterval		NUMERIC 						80				30			_none_ 	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{ldp_version					LdpRouterConfig		LdpVersion				{CHOICES version_1 version_2} 				16				version_1		_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{liveness_time 					LdpRouterConfig 	LivenessTime				NUMERIC 						80				360			120-600 true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{prefix_lsp_label_binding_mode 			LdpRouterConfig		PrefixLspLabelBindingMode		{CHOICES tx_and_rx tx_only rx_only none} 		16				tx_and_rx		_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{pseudowire_redundancy_mode 			LdpRouterConfig		PseudowireRedundancyMode 		{CHOICES none independent master slave}			16				none			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{none PSEUDOWIRE_REDUNDANCY_MODE_NONE independent PSEUDOWIRE_REDUNDANCY_MODE_INDEPENDENT master PSEUDOWIRE_REDUNDANCY_MODE_MASTER slave PSEUDOWIRE_REDUNDANCY_MODE_SLAVE}}
		{transport_tlv_mode				LdpRouterConfig		TransportTlvMode 			{CHOICES none tester_ip router_id} 			16				tester_ip			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{none TRANSPORT_TLV_MODE_NONE tester_ip TRANSPORT_TLV_MODE_TESTER_IP router_id TRANSPORT_TLV_MODE_ROUTER_ID}}
		{use_static_flow_label				LdpRouterConfig		UseStaticFlowLabel			{CHOICES 0 1} 						16				0			_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{vc_lsp_label_binding_mode 			LdpRouterConfig		VcLspLabelBindingMode			{CHOICES tx_and_rx tx_only rx_only none} 		16				tx_and_rx		_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{hello_type 					LdpDeviceGenProtocolParams		HelloType		{CHOICES ldp_directed_hello ldp_targeted_hello ldp_directed_targeted_hello} 			16		ldp_directed_hello			_none_	true	_none_	false	_none_  _none_  _none_}
		{use_gateway_as_dut_ip_addr 			LdpDeviceGenProtocolParams		UseGatewayAsDutIpAddr 	 {CHOICES true false}                 16         false      _none_          true        _none_     			    false       _none_      _none_    _none_}
	    {use_gateway_as_dut_ipv6_addr     		LdpDeviceGenProtocolParams  	UseGatewayAsDutIpv6Addr          {CHOICES true false}                 16         false      _none_          true        _none_     			    false       _none_      _none_     _none_}
		{authentication_mode      LdpAuthenticationParams   Authentication          {CHOICES none simple md5}                       50          none        _none_          true        _none_      false       _none_      _none_    _none_}
		{password                 LdpAuthenticationParams   Password                ANY                                             51          _none_      _none_          true        _none_      false       _none_                                     _none_    _none_}
		{md5_key_id               LdpAuthenticationParams   Md5KeyId                NUMERIC                                         52          _none_      0-255           true        _none_      false       _none_                                     _none_    _none_}
		{expand                          _none_              _none_                 {CHOICES true false}                             3            true       _none_          true        _none_      false      _none_	_none_	 _none_    }
	}
	{	emulation_ldp_control
		{hname	         stcobj	stcattr	type   priority	default	range	supported   dependency	mandatory	procfunc	mode	constants}
		{advertise	_none_	_none_	ANY	15	_none_	_none_	false	_none_	false	processEmulation_ldp_control_advertise_lsp	{start processEmulation_ldp_control_advertise_lsp restart processEmulation_ldp_control_advertise_lsp}	_none_}
		{handle		_none_	_none_	ALPHANUM    10	_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{mode		_none_	_none_	{CHOICES start stop restart flap graceful_restart}	1	_none_	_none_	true	_none_	true	_none_	_none_	_none_}
		{port_handle	_none_	_none_	ALPHANUM  5	_none_	_none_	true	_none_	false	_none_	_none_	_none_}
		{withdraw	_none_	_none_	ANY	 20	_none_	_none_	false	_none_	false	processEmulation_ldp_control_withdraw_lsp	{start processEmulation_ldp_control_withdraw_lsp restart processEmulation_ldp_control_withdraw_lsp}	_none_}	
	}
	{	emulation_ldp_info
		{hname  	stcobj  	stcattr 	type    	priority 	default 	range   	supported   	dependency  	mandatory   	procfunc	mode	constants}
		{handle 	_none_		_none_		ALPHANUM	10		_none_		_none_		true		_none_		false		_none_		_none_	_none_}
		{mode		_none_	_none_	{CHOICES state stats settings lsp_labels}  1	_none_	 	_none_		true		_none_		false		_none_		_none_	_none_}
		{ip_address	Ipv4If		Address		ANY		20		_none_		_none_		true		_none_		false		_none_		{stats ""} _none_}
		{linked_hellos_tx	LdpRouterResults TxDirectHellosCount	ANY	20	_none_		_none_		true		_none_		false		_none_		{stats ""}	_none_}
		{linked_hellos_rx	LdpRouterResults RxDirectHellosCount	ANY	20	_none_		_none_		true		_none_		false		_none_		{stats ""}	_none_}
		{targeted_hellos_tx	LdpRouterResults TxTargetedHellosCount	ANY	20	_none_		_none_		true		_none_		false		_none_		{stats ""}	_none_}		
		{targeted_hellos_rx	LdpRouterResults RxTargetedHellosCount	ANY	20	_none_		_none_		true		_none_		false		_none_		{stats ""}  _none_}		
		{total_setup_time	LdpRouterResults SessionEstablishmentTime ANY 20	_none_		_none_		false		_none_		false		_none_		_none_	_none_}
		{req_rx	LdpRouterResults	RxLabelRequestsCount	ANY	20		_none_		_none_		true		_none_		false		_none_		{stats ""}	_none_}
		{req_tx	LdpRouterResults	TxLabelRequestsCount	ANY	20		_none_		_none_		true		_none_		false		_none_		{stats ""}	_none_}		
		{map_rx	LdpRouterResults	RxLabelMappingCount	ANY	20		_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}		
		{map_tx	LdpRouterResults	TxLabelMappingCount	ANY	20		_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}
		{release_rx	LdpRouterResults	RxLabelReleaseCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}
		{release_tx	LdpRouterResults	TxLabelReleaseCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}		
		{withdraw_rx	LdpRouterResults	RxLabelWithdrawCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}		
		{withdraw_tx	LdpRouterResults	TxLabelWithdrawCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}
		{abort_rx	LdpRouterResults	RxLabelAbortCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}
		{abort_tx	LdpRouterResults	TxLabelAbortCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}		
		{notif_rx	LdpRouterResults	RxNotificationCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}		
		{notif_tx	LdpRouterResults	TxNotificationCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{stats ""}	_none_}
		{intf_ip_addr	Ipv4If		Address		ANY		20		_none_		_none_		true		_none_		false		_none_	{settings ""}	_none_}
		{hello_interval	LdpRouterConfig		HelloInterval	ANY	20		_none_		_none_		true		_none_		false		_none_	{settings ""}	_none_}
		{hello_hold_time	LdpRouterConfig	 HelloInterval	ANY	20		_none_		_none_		true		_none_		false		_none_	{settings ""}	_none_}
		{keepalive_interval	LdpRouterConfig	 KeepAliveInterval	ANY	20	_none_		_none_		true		_none_		false		_none_	{settings ""}	_none_}		
		{label_space	LdpRouterConfig		LabelSpaceId		ANY	20	_none_		_none_		true		_none_		false		_none_	{settings ""}	_none_}
		{session_state	LdpRouterConfig	RouterState			ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	{LDP_SESSION_STATE_NO_STATE nonexist LDP_SESSION_STATE_DOWN init LDP_SESSION_STATE_UP operational LDP_SESSION_STATE_FAILED disabled LDP_SESSION_STATE_OPEN opensent LDP_SESSION_STATE_CONNECT openrec}}
		{lsp_pool_handle	LdpRouterConfig	children-ipv4prefixlsp	ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	_none_}
		{num_incoming_ingress_lsps	LdpRouterResults LspUpCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	_none_}
		{num_incoming_egress_lsps	LdpRouterResults LspUpCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	_none_}
		{num_opened_lsps	LdpRouterResults	LspUpCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	_none_}
		{num_opened_lsps	LdpRouterResults	LspUpCount	ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	_none_}
		{type			LdpLspResults		LspType		ANY	20	_none_		_none_		true		_none_		false		_none_	{state ""}	{LSP_TYPE_EGRESS egress LSP_TYPE_INGRESS ingress}}
		{fec_type		LdpLspResults		LspFecType	ANY	20	_none_		_none_		true		_none_		false		_none_	{lsp_labels ""}	{LDP_FEC_TYPE_PREFIX ipv4_prefix LDP_FEC_TYPE_HOST_ADDR host_addr LDP_FEC_TYPE_VC vc}}
		{label			LdpLspResults		LspLabel	ANY	20	_none_		_none_		true		_none_		false		_none_	{lsp_labels ""}		_none_}	
		{prefix			LdpLspResults		LspFecInfo	ANY	20	_none_		_none_		true		_none_		false		_none_	{lsp_labels ""}		_none_}	
		{prefix_length		LdpLspResults		LspFecInfo	ANY	20	_none_		_none_		true		_none_		false		_none_	{lsp_labels ""}		_none_}	
		{source			LdpRouterConfig	children-LdpLspResults	ANY	20	_none_		_none_		true		_none_		false		_none_	{lsp_labels ""}		_none_}	
		{label_adv		LdpLspResults		LspMode		ANY	20	_none_		_none_		true		_none_		false		_none_	{settings ""}	{LSP_MODE_DU unsolicited LSP_MODE_DOD on_demand}}	
	}
	{	emulation_ldp_route_config
		{hname	                  stcobj	                                                        stcattr				type    							priority       default	  	range	  	supported	dependency	mandatory	procfunc			mode						constants}
		{mode			_none_			                                                _none_			{CHOICES create modify delete}						1		_none_		_none_		true		_none_		true		_none_			_none_	_none_}
		{handle			_none_			                                                _none_				ALPHANUM							10		_none_		_none_		true		_none_		false		_none_			_none_		_none_}
		{lsp_type		_none_			                                                _none_	{CHOICES ipv4_egress ipv4_ingress ipv6_egress ipv6_ingress pwid generalized_pwid p2mp}	10 		ipv4_egress 	_none_		true 		_none_		false		_none_			_none_	_none_}
		{lsp_handle		_none_			                                                _none_				ALPHANUM							20		_none_		0-0xFFFFFFFFF	true		_none_		false		_none_			_none_	_none_}
		{fec_type		Ipv4PrefixLsp|Ipv4IngressPrefixLsp|Ipv6PrefixLsp|Ipv6IngressPrefixLsp	FecType			{CHOICES ipv4_prefix prefix host_addr vc} 				30  		prefix		_none_	  	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	{ipv4_prefix LDP_FEC_TYPE_PREFIX  prefix LDP_FEC_TYPE_PREFIX host_addr LDP_FEC_TYPE_HOST_ADDR vc LDP_FEC_TYPE_VC}}
		{fec_ip_prefix_length	ipv4networkblock|ipv6networkblock	                                PrefixLength			NUMERIC 							80		_none_		1-128	  	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{fec_ip_prefix_start	ipv4networkblock|ipv6networkblock	                                StartIpList			IP								70		_none_		_none_	  	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{fec_ip_prefix_step	ipv4networkblock|ipv6networkblock	                                AddrIncrement			NUMERIC 							90		_none_		_none_	  	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {num_routes     	ipv4networkblock|ipv6networkblock                                       NetworkCount    		NUMERIC 							42      	_none_   	 _none_  	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
		{fec_vc_group_id	VcLsp			GroupId				HEX								140		_none_		0-0xFFFFFFFFF	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{fec_vc_id_start	VcLsp			StartVcId			HEX								150		_none_		0-0xFFFFFFFFF	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{fec_vc_id_step		VcLsp			VcIdIncrement			HEX								150		_none_		0-0xFFFFFFFFF	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
		{fec_vc_intf_mtu	VcLsp			IfMtu				NUMERIC 							180		1500		0-65535		true		_none_		false		processConfigCmd    {create processConfigCmd modify processConfigCmd}	_none_}
		{fec_vc_type		VcLsp			Encap	{CHOICES none fr_dlci atm_aal5_sdu atm_cell eth_vlan eth hdlc ppp cem atm_vcc_n_1 atm_vpc_n_1 eth_vpls atm_vcc_1_1 atm_vpc_1_1 atm_aal5_pdu fr_port}	120	_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{none 0x0000 fr_dlci LDP_LSP_ENCAP_FRAME_RELAY_DLCI atm_aal5_sdu "" atm_cell "" eth_vlan LDP_LSP_ENCAP_ETHERNET_VLAN eth LDP_LSP_ENCAP_ETHERNET hdlc LDP_LSP_ENCAP_HDLC ppp LDP_LSP_ENCAP_PPP cem LDP_LSP_ENCAP_CEM atm_vcc_n_1 "" atm_vpc_n_1 "" eth_vpls LDP_LSP_ENCAP_ETHERNET_VPLS atm_vcc_1_1 "" atm_vpc_1_1 "" atm_aal5_pdu "" fr_port ""}}
		{fec_vc_id_count 	VcLsp 			VcIdCount 			NUMERIC  							201     	1       	1-65535 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_bfd_msg_format 	VcLsp 			BfdMessageFormat 		{CHOICES bfd_cc bfd_cv}  					201     	bfd_cc       	_none_ 		true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{bfd_cc BFD_CC bfd_cv BFD_CV}}
        {fec_vc_bfd_my_dis 	VcLsp 			BfdMyDiscriminator 		NUMERIC  							201     	_none_       	1-69151 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_ctrl_pre 	VcLsp 			ControlWordPreference 		{CHOICES not_preferred preferred}  				201     	not_preferred   _none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{not_preferred NOT_PREFERRED preferred PREFERRED}}
        {fec_vc_custom_status_en VcLsp 			UseCustomStatusCode 		{CHOICES true false} 						201     	false   	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_custom_status 	VcLsp 			CustomStatusCode 		NUMERIC 							201     	0   		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_dst_ipv4_addr 	VcLsp 			DstIpv4Address 			IP 								201     	127.0.0.1   	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_bfd_enable 	VcLsp 			EnableBfd 			{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_gal_enable 	VcLsp 			EnableGenericAssociatedLabel 	{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_label_sub_tlv_en VcLsp 			IncludeFlowLabelSubTlv 		{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_label_sub_tlv 	VcLsp 			FlowLabelSubTlvTRBit 		{CHOICES 0 1 2 3} 						201     	0  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{0 0 1 T_BIT 2 R_BIT 3 T_BIT\\|R_BIT}}
        {fec_vc_if_des 		VcLsp 			IfDescription 			ANY 								201     	_none_  	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_status_tlv_en 	VcLsp 			IncludeStatusTlv 		{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_redundant_set_role VcLsp 		RedundantSetRole 		{CHOICES none primary_pseudowire secondary_pseudowire} 		201     	none  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{none REDUNDANT_SET_ROLE_NONE primary_pseudowire REDUNDANT_SET_ROLE_PRIMARY_PSEUDOWIRE secondary_pseudowire REDUNDANT_SET_ROLE_SECONDARY_PSEUDOWIRE}}
        {fec_vc_req_vlan_id 	VcLsp 			RequestedVlanId 		NUMERIC 							201     	_none_  	0-4095	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_req_vlan_id_incr VcLsp 			RequestedVlanIdIncrement 	NUMERIC 							201     	1  	 	0-4095	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_signal_req_switchover_status_bit VcLsp 	SignalRequestSwitchoverStatusBit {CHOICES true false} 						201     	false  	 	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_vccv_connectivity_verification VcLsp 	VccvConnectivityVerification 	{CHOICES 0 icmp_ping lsp_ping bfd_ip_udp_pw_fault_detection_only  bfd_ip_udp_pw_fault_detection_with_status_signaling bfd_pw_ach_pw_fault_detection_only  bfd_pw_ach_pw_fault_detection_with_status_signaling} 		201     	_none_  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{icmp_ping ICMP_PING lsp_ping LSP_PING bfd_ip_udp_pw_fault_detection_only BFD_IP_UDP_PW_FAULT_DETECTION_ONLY bfd_ip_udp_pw_fault_detection_with_status_signaling BFD_IP_UDP_PW_FAULT_DETECTION_WITH_STATUS_SIGNALING bfd_pw_ach_pw_fault_detection_only  BFD_PW_ACH_PW_FAULT_DETECTION_ONLY bfd_pw_ach_pw_fault_detection_with_status_signaling BFD_PW_ACH_PW_FAULT_DETECTION_WITH_STATUS_SIGNALING}}
        {fec_vc_vccv_ctrl_channel VcLsp 		VccvControlChannel 		{CHOICES 0 mpls_pw_label_with_ttl mpls_router_alert_label pwe3_control_word_with_0001b_as_first_nibble} 		201     	_none_  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{mpls_pw_label_with_ttl MPLS_PW_LABEL_WITH_TTL mpls_router_alert_label MPLS_ROUTER_ALERT_LABEL pwe3_control_word_with_0001b_as_first_nibble PWE3_CONTROL_WORD_WITH_0001B_AS_FIRST_NIBBLE}}
        {fec_vc_count   	MacBlock  		NetworkCount  			NUMERIC 							41      	_none_  	_none_  	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_mac_start   	MacBlock  		StartMacList  			ANY 								190      	_none_  	_none_  	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_attachment_group_id 	GeneralizedPwidLsp 			AttachmentGroupId		ANY								140		100::1		_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_attachment_group_id_incr 	GeneralizedPwidLsp 			AttachmentGroupIdIncrement	ANY								140		0::1		_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_target_individual_id 	GeneralizedPwidLsp 			TargetAttachmentIndividualId	IP								140		192.0.0.1	_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_target_individual_id_incr GeneralizedPwidLsp 			TargetAttachmentIndividualIdIncrement	IP								140		0.0.0.1		_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_src_individual_id 	GeneralizedPwidLsp 			SrcAttachmentIndividualId	IP								140		192.0.0.1	_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_src_individual_id_incr 	GeneralizedPwidLsp 			SrcAttachmentIndividualIdIncrement	IP								140		0.0.0.1		_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_group_id			GeneralizedPwidLsp 			GroupId				HEX								140		_none_		0-0xFFFFFFFFF	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_intf_mtu			GeneralizedPwidLsp			IfMtu				NUMERIC 							180		1500		0-65535		true		_none_		false		processConfigCmd    {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_type			GeneralizedPwidLsp			Encap	{CHOICES none fr_dlci atm_aal5_sdu atm_cell eth_vlan eth hdlc ppp cem atm_vcc_n_1 atm_vpc_n_1 eth_vpls atm_vcc_1_1 atm_vpc_1_1 atm_aal5_pdu fr_port}	120	_none_	_none_	true	_none_	false	processConfigCmd	{create processConfigCmd modify processConfigCmd}	{none 0x0000 fr_dlci LDP_LSP_ENCAP_FRAME_RELAY_DLCI atm_aal5_sdu "" atm_cell "" eth_vlan LDP_LSP_ENCAP_ETHERNET_VLAN eth LDP_LSP_ENCAP_ETHERNET hdlc LDP_LSP_ENCAP_HDLC ppp LDP_LSP_ENCAP_PPP cem LDP_LSP_ENCAP_CEM atm_vcc_n_1 "" atm_vpc_n_1 "" eth_vpls LDP_LSP_ENCAP_ETHERNET_VPLS atm_vcc_1_1 "" atm_vpc_1_1 "" atm_aal5_pdu "" fr_port ""}}
        {fec_gen_pwid_id_count 			GeneralizedPwidLsp 			PwCount 			NUMERIC  							201     	1       	0-5000000 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_bfd_msg_format 		GeneralizedPwidLsp 			BfdMessageFormat 		{CHOICES bfd_cc bfd_cv}  					201     	bfd_cc       	_none_ 		true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{bfd_cc BFD_CC bfd_cv BFD_CV}}
        {fec_gen_pwid_bfd_my_dis 		GeneralizedPwidLsp 			BfdMyDiscriminator 		NUMERIC  							201     	_none_       	1-69151 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_ctrl_pre 			GeneralizedPwidLsp 			ControlWordPreference 		{CHOICES not_preferred preferred}  				201     	not_preferred   _none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{not_preferred NOT_PREFERRED preferred PREFERRED}}
        {fec_gen_pwid_custom_status_en 		GeneralizedPwidLsp 			UseCustomStatusCode 		{CHOICES true false} 						201     	false   	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_custom_status 		GeneralizedPwidLsp 			CustomStatusCode 		NUMERIC 							201     	0   		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_dst_ipv4_addr 		GeneralizedPwidLsp 			DstIpv4Address 			IP 								201     	127.0.0.1   	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_bfd_enable 		GeneralizedPwidLsp 			EnableBfd 			{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_gal_enable 		GeneralizedPwidLsp 			EnableGenericAssociatedLabel 	{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_label_sub_tlv_en 		GeneralizedPwidLsp 			IncludeFlowLabelSubTlv 		{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_label_sub_tlv 		GeneralizedPwidLsp 			FlowLabelSubTlvTRBit 		{CHOICES 0 1 2 3} 						201     	0  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{0 0 1 T_BIT 2 R_BIT 3 T_BIT\\|R_BIT}}
        {fec_gen_pwid_if_des 			GeneralizedPwidLsp 			IfDescription 			ANY 								201     	_none_  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_status_tlv_en 		GeneralizedPwidLsp 			IncludeStatusTlv 		{CHOICES true false} 						201     	false  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_redundant_set_role 	GeneralizedPwidLsp 			RedundantSetRole 		{CHOICES none primary_pseudowire secondary_pseudowire} 		201     	none  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{none REDUNDANT_SET_ROLE_NONE primary_pseudowire REDUNDANT_SET_ROLE_PRIMARY_PSEUDOWIRE secondary_pseudowire REDUNDANT_SET_ROLE_SECONDARY_PSEUDOWIRE}}
        {fec_gen_pwid_req_vlan_id 		GeneralizedPwidLsp 			RequestedVlanId 		NUMERIC 							201     	_none_  	0-4095	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_req_vlan_id_incr 		GeneralizedPwidLsp 			RequestedVlanIdIncrement 	NUMERIC 							201     	1  	 	0-4095	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_signal_req_switchover_status_bit GeneralizedPwidLsp 		SignalRequestSwitchoverStatusBit {CHOICES true false} 						201     	false  	 	_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_gen_pwid_vccv_connectivity_verification GeneralizedPwidLsp 		VccvConnectivityVerification 	{CHOICES 0 icmp_ping lsp_ping bfd_ip_udp_pw_fault_detection_only  bfd_ip_udp_pw_fault_detection_with_status_signaling bfd_pw_ach_pw_fault_detection_only  bfd_pw_ach_pw_fault_detection_with_status_signaling} 		201     	_none_  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{icmp_ping ICMP_PING lsp_ping LSP_PING bfd_ip_udp_pw_fault_detection_only BFD_IP_UDP_PW_FAULT_DETECTION_ONLY bfd_ip_udp_pw_fault_detection_with_status_signaling BFD_IP_UDP_PW_FAULT_DETECTION_WITH_STATUS_SIGNALING bfd_pw_ach_pw_fault_detection_only  BFD_PW_ACH_PW_FAULT_DETECTION_ONLY bfd_pw_ach_pw_fault_detection_with_status_signaling BFD_PW_ACH_PW_FAULT_DETECTION_WITH_STATUS_SIGNALING}}
        {fec_gen_pwid_vccv_ctrl_channel 	GeneralizedPwidLsp 			VccvControlChannel 	{CHOICES 0 mpls_pw_label_with_ttl mpls_router_alert_label pwe3_control_word_with_0001b_as_first_nibble} 		201     	_none_  		_none_	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	{mpls_pw_label_with_ttl MPLS_PW_LABEL_WITH_TTL mpls_router_alert_label MPLS_ROUTER_ALERT_LABEL pwe3_control_word_with_0001b_as_first_nibble PWE3_CONTROL_WORD_WITH_0001B_AS_FIRST_NIBBLE}}
        {fec_gen_pwid_pw_count 			    GeneralizedPwidLsp 			PwCount 			NUMERIC 							201     	1  	 	0-5000000	 	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
        {fec_vc_cbit				        _none_					_none_				{CHOICES 0 1}   						130 		_none_		_none_	  	false		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {label_msg_type				        _none_					_none_				{CHOICES mapping request} 				50		mapping		_none_		false		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	{mapping LDP_MAPPIN_MSG request LDP_REQ_MSG}}
        {address_family                     P2mpLsp                 AddressFamily        ANY                                    100     IPv4              _none_                          true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {root_node_address                  P2mpLsp                 RootNodeAddress      IPV4                                   100     _none_            _none_                          true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {opaque_type_selector               P2mpLsp                 OpaqueTypeSelector   {CHOICES type1_global_id type3_s_g type250_s_g_rd custom}   100  TYPE3_S_G  _none_    true    _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {global_id_reserved                 P2mpLsp                 GlobalIdReserved     NUMERIC                                100     0                 0-15       true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {global_id_table_id                 P2mpLsp                 GlobalIdTableId      NUMERIC                                100     0                 0-16383    true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {global_id_tree_id                  P2mpLsp                 GlobalIdTreeId       NUMERIC                                100     1                 _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {source_address                     P2mpLsp                 SourceAddress        IPV4                                   100     192.85.1.3        _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {route_distinguisher                P2mpLsp                 RouteDistinguisher   ANY                                    100     _none_            _none_     true     {opaque_type_selector type250_s_g_rd}   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {multicast_group_handle             _none_                  _none_               ANY                                    100     _none_            _none_     true     _none_   false    _none_   _none_   _none_}
        {custom_opaque_type                 LdpMldpCustomOpaque     CustomOpaqueType     NUMERIC                                100     _none_            _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {enable_extended_type               LdpMldpCustomOpaque     EnableExtendedType   {CHOICES true false}                   100     _none_            _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {extended_opaque_type               LdpMldpCustomOpaque     ExtendedOpaqueType   NUMERIC                                100     _none_            _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
        {custom_opaque_value                LdpMldpCustomOpaque     Value                NUMERIC                                100     _none_            _none_     true     _none_   false    processConfigCmd   {create processConfigCmd modify processConfigCmd}   _none_}
	}                                                                                                                     
    {	emulation_lsp_switching_point_tlvs_config
		{hname	                                        stcobj	                                   stcattr				                        type    							priority       default	  	range	  	supported	dependency	                        mandatory	procfunc			mode						constants}
		{mode			                                _none_			                            _none_			                {CHOICES create modify delete}						        1		_none_		_none_		true		_none_		                        true		_none_			        _none_	                                        _none_}
		{lsp_handle		                                _none_			                            _none_				                        ALPHANUM							20		_none_		_none_	        true		_none_		                        false		_none_			        _none_	                                        _none_}
        {tlv_handle		                                _none_			                            _none_				                        ALPHANUM							20		_none_		_none_	        true		_none_		                        false		_none_			        _none_	                                        _none_}
        {last_segment_traversed_subtlv_enable	        PseudoWireSwitchingPointTlv 		EnableLastSegmentTraversedSubTlv		        {CHOICES true false}						140		true		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {last_pseudowire_segment_fec_type	            PseudoWireSwitchingPointTlv 		LastPseudoWireSegmentFecType		                {CHOICES fec_128 fec_129}					140		_none_		_none_	        true	{last_segment_traversed_subtlv_enable	true}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	{fec_128 FEC_128 fec_129 FEC_129}}
        {start_vc_id	                                PseudoWireSwitchingPointTlv 		StartVcId		                                NUMERIC								140		1		_none_	        true	{last_pseudowire_segment_fec_type fec_128}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {vc_id_incr	                                    PseudoWireSwitchingPointTlv 		VcIdIncrement		                                NUMERIC								140		1		_none_	        true	{last_pseudowire_segment_fec_type fec_128}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {attachment_group_id	                        PseudoWireSwitchingPointTlv 		AttachmentGroupId		                        ANY								140		100:1		_none_	        true	{last_pseudowire_segment_fec_type fec_129}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {attachment_group_id_incr	                    PseudoWireSwitchingPointTlv 		AttachmentGroupIdIncrement		                ANY								140		0:1		_none_	        true	{last_pseudowire_segment_fec_type fec_129}      false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {src_attachment_individual_id	                PseudoWireSwitchingPointTlv 		SrcAttachmentIndividualId		                IP								140		192.0.0.1	_none_	        true	{last_pseudowire_segment_fec_type fec_129}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {src_attachment_individual_id_incr	            PseudoWireSwitchingPointTlv 		SrcAttachmentIndividualIdIncrement		        IP								140		0.0.0.1		_none_	        true	{last_pseudowire_segment_fec_type fec_129}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {target_attachment_individual_id	            PseudoWireSwitchingPointTlv 		TargetAttachmentIndividualId		                IP								140		192.0.0.1	_none_	        true	{last_pseudowire_segment_fec_type fec_129}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {target_attachment_individual_id_incr	        PseudoWireSwitchingPointTlv 		TargetAttachmentIndividualIdIncrement		        IP								140		0.0.0.0		_none_	        true	{last_pseudowire_segment_fec_type fec_129}	false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {local_ipv4_addr	                            PseudoWireSwitchingPointTlv 		LocalIpv4Addr		                                IPV4								140		_none_		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {remote_ipv4_addr	                            PseudoWireSwitchingPointTlv 		RemoteIpv4Addr		                                IPV4								140		_none_		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {remote_ipv4_addr_increment	                    PseudoWireSwitchingPointTlv 		RemoteIpv4AddrIncrement		                        IPV4								140		_none_		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {remote_ipv4_addr_repeat_count	                PseudoWireSwitchingPointTlv 		RemoteIpv4AddrRepeatCount		                NUMERIC								140		_none_		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {remote_ipv4_unique_addr_count	                PseudoWireSwitchingPointTlv 		RemoteIpv4UniqueAddrCount		                NUMERIC								140		_none_		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {pseudowire_addr_enable                         PseudoWireSwitchingPointTlv 		EnableSwitchingPointPseudoWireAddrSubTlv		{CHOICES true false}						140		false		_none_	        true		_none_		                        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {switching_point_description	                PseudoWireSwitchingPointTlv 		SwitchingPointDescription		                ANY								140		_none_		_none_	        true	{pseudowire_addr_enable true}		        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {pseudowire_addr_attachment_circuit_id	        PseudoWireSwitchingPointTlv 		SwitchingPointPseudoWireAddrAttachmentCircuitId		ANY								140		_none_		_none_	        true	{pseudowire_addr_enable true}		        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {pseudowire_addr_attachment_circuit_id_incr     PseudoWireSwitchingPointTlv 		SwitchingPointPseudoWireAddrAttachmentCircuitIdIncrement ANY								140		_none_		_none_	        true	{pseudowire_addr_enable true}		        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {pseudowire_addr_global_id	                    PseudoWireSwitchingPointTlv 		SwitchingPointPseudoWireAddrGlobalId		        ANY								140		_none_		_none_	        true	{pseudowire_addr_enable true}		        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        {pseudowire_addr_prefix	                        PseudoWireSwitchingPointTlv 		SwitchingPointPseudoWireAddrPrefix		        ANY								140		_none_		_none_	        true	{pseudowire_addr_enable true}		        false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
        }
        
    {	emulation_ldp_route_element_config
		{hname	                            stcobj	                stcattr				         type    					priority    default	  	range	 supported	dependency	    mandatory	procfunc			mode						                   constants}
		{mode			                    _none_			        _none_			     {CHOICES create modify delete}			1		_none_		_none_	   true		_none_		     true		_none_			  _none_	                                        _none_}
		{lsp_handle		                    _none_			        _none_				 ALPHANUM							    20		_none_		_none_	   true		_none_		     false		_none_			  _none_	                                        _none_}
        {element_handle		                _none_			        _none_				 ALPHANUM							    20		_none_		_none_	   true		_none_		     false		_none_			  _none_	                                        _none_}
		{element_type		                _none_			        _none_	             {CHOICES p2mp_custom_element generalized_pwid_switch_tlv}	10 _none_  _none_   true   _none_    false		_none_			  _none_	                                        _none_}
        {custom_opaque_type                 LdpMldpCustomOpaque     CustomOpaqueType     NUMERIC                                30        1         _none_     true     _none_           false    processConfigCmd   {create processConfigCmd modify processConfigCmd}  _none_}
        {enable_extended_type               LdpMldpCustomOpaque     EnableExtendedType   {CHOICES true false}                   30       false      _none_     true     _none_           false    processConfigCmd   {create processConfigCmd modify processConfigCmd}  _none_}
        {extended_opaque_type               LdpMldpCustomOpaque     ExtendedOpaqueType   NUMERIC                                30         0        _none_     true     _none_           false    processConfigCmd   {create processConfigCmd modify processConfigCmd}  _none_}
        {custom_opaque_value                LdpMldpCustomOpaque     Value                NUMERIC                                30         0        _none_     true     _none_           false    processConfigCmd   {create processConfigCmd modify processConfigCmd}  _none_}
    }                                                                                                                                                                        
}

# here ipv4_prefix is not recommend to use, should prefix instead of the ipv4_prefix

#delete these three args
#{fec_host_addr	        ipv4networkblock	StartIpList			IP								100	        _none_	  	_none_    	true		_none_	        false	        processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
#{fec_host_step	   	ipv4networkblock	AddrIncrement			NUMERIC 							110		_none_		_none_	  	true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}
#{fec_host_prefix_length ipv4networkblock  	PrefixLength    		NUMERIC 							200     	_none_      	1-128    	true    	_none_  	false   	processConfigCmd        {create processConfigCmd modify processConfigCmd}	_none_}
		
#fec_host_addr, fec_host_step, fec_host_prefix_length are not suggest to use,, will map these to fec_ip_prefix_start, fec_ip_prefix_step, fec_ip_prefix_length

#{num_lsps		ipv4networkblock|ipv6networkblock	NetworkCount			NUMERIC 							40		_none_		_none_		true		_none_		false		processConfigCmd	{create processConfigCmd modify processConfigCmd}	_none_}											
#num_lsps will be mapped to fec_vc_id_count when the lsp_type is pwid