
namespace eval ::sth::LinkOam {
    set LinkOamTable {
        ::sth::LinkOam::
        {emulation_efm_config
            {hname                              stcobj                             stcattr                                     type                              priority        default          range         supported    dependency                mandatory        procfunc                                   mode                                                                          constants}
            {mode                               _none_                              _none_                                  {CHOICES create modify destroy reset}   10          create          _none_          true        _none_                      true            _none_                                      _none_                                                                          _none_}
            {port_handle                        _none_                              _none_                                  ANY                                     11          _none_          _none_          true        {mandatory {mode create}}   false           _none_                                      _none_                                                                          _none_}
            {mac_local                          EthIIIf                             SourceMac                               ANY                                     12          _none_          _none_          true        _none_                      false           _none_                                      {create configEthIf modify configEthIf}                                         _none_}
            {oui_value                          LinkOamRouterConfig                 Oui                                     {REGEXP ^[a-fA-F0-9]{6}$}                13          000000          _none_          true        _none_                      false          processEmulation_efm_configOui              {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {vsi_value                          LinkOamRouterConfig                 VendorSpecificInfo                      {REGEXP ^[a-fA-F0-9]{8}$}               14          _none_          _none_          true        _none_                      false           processEmulation_efm_configVsi              {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {unidirectional                     LinkOamRouterConfig                 SupportsUnidirectionalMode              {CHOICES 0 1}                           15          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {error_symbol_period_window         LinkOamEventNotificationConfig      ErroredSymbolPeriodWindowSize           NUMERIC                                 16          500             1-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_symbol_period_threshold      LinkOamEventNotificationConfig      ErroredSymbolPeriodThreshold            NUMERIC                                 17          50              0-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_window                 LinkOamEventNotificationConfig      ErroredFrameWindowSize                  NUMERIC                                 18          400             10-600          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_threshold              LinkOamEventNotificationConfig      ErroredFrameThreshold                   NUMERIC                                 19          40              0-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_period_window          LinkOamEventNotificationConfig      ErroredFramePeriodWindowSize            NUMERIC                                 20          300             1-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_period_threshold       LinkOamEventNotificationConfig      ErroredFramePeriodThreshold             NUMERIC                                 21          30              0-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_summary_window         LinkOamEventNotificationConfig      ErroredFrameSecondsSummaryWindowSize    NUMERIC                                 22          200             100-9000        true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_summary_threshold      LinkOamEventNotificationConfig      ErroredFrameSecondsSummaryThreshold     NUMERIC                                 23          20              0-65535         true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {oam_mode                           LinkOamRouterConfig                 OperationMode                           {CHOICES active passive}                24          active          _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {remote_loopback                    LinkOamRouterConfig                 SupportsLoopback                        {CHOICES 0 1}                           25          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {link_events                        LinkOamRouterConfig                 InterpretsLinkEvents                    {CHOICES 0 1}                           26          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {variable_retrieval                 LinkOamRouterConfig                 SupportsVariableRetrieval               {CHOICES 0 1}                           27          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {critical_event                     LinkOamRouterConfig                 EnableCriticalEvent                     {CHOICES 0 1}                           28          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {dying_gasp                         LinkOamRouterConfig                 EnableDyingGasp                         {CHOICES 0 1}                           29          0               _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {link_fault                         LinkOamRouterConfig                 EnableLinkFault                         {CHOICES 0 1}                           30          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {vlan_id                            VlanIf                              VlanId                                  NUMERIC                                 31          _none_          0-4095          true        _none_                      false           processEmulation_efm_vlanIdInner            {create configVlanIfInner modify configVlanIfInner}                             _none_}
            {vlan_id_mode                       _none_                              _none_                                  {CHOICES fixed increment}               32          _none_          _none_          true        _none_                      false           _none_                                      _none_                                                                          _none_}
            {vlan_id_step                       VlanIf                              IdStep                                  NUMERIC                                 33          _none_          0-4095          true        {vlan_id_mode increment}    false           processEmulation_efm_vlanIdInner            {create configVlanIfInner modify configVlanIfInner}                             _none_}
            {vlan_user_priority                 VlanIf                              Priority                                NUMERIC                                 34          _none_          0-7             true        _none_                      false           processEmulation_efm_vlanIdInner            {create configVlanIfInner modify configVlanIfInner}                             _none_} 
            {vlan_outer_id                      VlanIf_Outer                              VlanId                                  NUMERIC                                 35          _none_          0-4095          true        _none_                      false           processEmulation_efm_vlanIdOuter            {create configVlanIfOuter modify configVlanIfOuter}                             _none_}
            {vlan_outer_id_mode                 _none_                              _none_                                  {CHOICES fixed increment}               36          _none_          _none_          true        _none_                      false           _none_                                      _none_                                                                          _none_}
            {vlan_outer_id_step                 VlanIf_Outer                              IdStep                                  NUMERIC                                 37          _none_          0-4095          true    {vlan_outer_id_mode increment}  false           processEmulation_efm_vlanIdOuter            {create configVlanIfOuter modify configVlanIfOuter}                             _none_}
            {vlan_outer_user_priority           VlanIf_Outer                              Priority                                NUMERIC                                 38          _none_          0-7             true        _none_                      false           processEmulation_efm_vlanIdOuter            {create configVlanIfOuter modify configVlanIfOuter}                             _none_}
            {size                               _none_                              _none_                                  NUMERIC                                 999         _none_          _none_          false       _none_                      false           _none_                                      _none_                                                                          _none_}
            {passive_peer_only                  _none_                              _none_                                  {CHOICES 0 1}                           999         _none_          _none_          false       _none_                      false           _none_                                      _none_                                                                          _none_}        
            {loopback_response_tx		LinkOamRouterConfig                 EnableLoopbackResponseTx                {CHOICES 0 1}	                    40            1	        _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {pdu_tx	                        LinkOamRouterConfig	            EnablePduTx                             {CHOICES 0 1} 	                    41            1		_none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {variable_response_tx	        LinkOamRouterConfig                 EnableVariableResponseTx	            {CHOICES 0 1}   	                    42            1             _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {max_pdu_size	                LinkOamRouterConfig	            MaxPduSize                               NUMERIC	                            43           1500           64-2047	        true        _none_	                false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {oam_version	                LinkOamRouterConfig	            OamVersion                               NUMERIC		                    44            1             _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {override_local_satisfied	        LinkOamRouterConfig	            OverrideLocalSatisfied                  {CHOICES false true default}	    45         default	        _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {override_remote_stable	        LinkOamRouterConfig	            OverrideRemoteStable                    {CHOICES false true default}	    46         default	        _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {override_revision	                LinkOamRouterConfig	            OverrideRevision	                    {CHOICES 0 1}                           47           0              _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {revision	                        LinkOamRouterConfig	            Revision	                              NUMERIC                               48           0              _none_          true        _none_                      false           _none_                                      {create configLinkOamRouter modify configLinkOamRouter}                         _none_}
            {error_frame_count	                LinkOamEventNotificationConfig      FrameErrors	                              NUMERIC                               49           1              _none_          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_period_count	        LinkOamEventNotificationConfig	    FramePeriodErrors	                      NUMERIC                               50           1              _none_          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_frame_summary_count	        LinkOamEventNotificationConfig	    FrameSecondsSummaryErrors	              NUMERIC                               51           1              _none_          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {error_symbol_period_count	        LinkOamEventNotificationConfig	    SymbolPeriodErrors	                      NUMERIC                               52           1              _none_          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {link_notification_events_per_interval  LinkOamEventNotificationConfig  MsgRepeatCount	                      NUMERIC                               53           2              1-10            true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {link_notifications_interval	LinkOamEventNotificationConfig	    InitialTimeBase	                      NUMERIC                               54           0              _none_          true        _none_                      false           _none_                                      {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {link_notifications_ose_oui	        LinkOamEventNotificationConfig	    Oui	                                      {REGEXP ^[a-fA-F0-9]{6}$}             55         001094           _none_          true        _none_                      false           processEmulation_efm_configOui              {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {link_notifications_ose_value	LinkOamEventNotificationConfig	    DataValue	                              ANY                                   56          00               _none_         true        _none_                      false           processEmulation_efm_datavalue              {create configLinkOamEventNotification modify configLinkOamEventNotification}   _none_}
            {loopback_response_timer	        LinkOamTimersConfig	            LoopbackResponseTimeout	              NUMERIC                               57          1                1-10           true        _none_                      false           _none_                                      {create configLinkOamTimers modify configLinkOamTimers}                         _none_}
            {lost_link_timer	                LinkOamTimersConfig	            LostLinkTimer	                      NUMERIC                               58          5                2-90           true        _none_                      false           _none_                                      {create configLinkOamTimers modify configLinkOamTimers}                         _none_}
            {pdu_timer	                        LinkOamTimersConfig	            PduTimer	                              NUMERIC                               59          1                1-10           true        _none_                      false           _none_                                      {create configLinkOamTimers modify configLinkOamTimers}                         _none_}
            {variable_response_timer	        LinkOamTimersConfig	            VariableResponseTimeout	              NUMERIC                               60          1                1-10           true        _none_                      false           _none_                                      {create configLinkOamTimers modify configLinkOamTimers}                         _none_}
            {variable_response_branch	        LinkOamVariableResponseConfig       Branch                                    ANY                                   62          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableResponse modify configLinkOamVariableResponse}     _none_}
            {variable_response_data	        LinkOamVariableResponseConfig       DataValue	                              ANY                                   63          _none_          _none_          true        _none_                      false           processEmulation_efm_datavalue              {create configLinkOamVariableResponse modify configLinkOamVariableResponse}     _none_}
            {variable_response_indication       LinkOamVariableResponseConfig	    Indication	                              {CHOICES 0 1}                         64          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableResponse modify configLinkOamVariableResponse}     _none_}
            {variable_response_leaf	        LinkOamVariableResponseConfig       Leaf	                              ANY                                   65          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableResponse modify configLinkOamVariableResponse}     _none_}
            {variable_response_width	        LinkOamVariableResponseConfig       Width	                              ANY                                   66          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableResponse modify configLinkOamVariableResponse}     _none_}
            {variable_request_branch	        LinkOamVariableRequestConfig        Branch	                              ANY                                   68          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableRequest  modify configLinkOamVariableRequest}      _none_}
            {variable_request_leaf	        LinkOamVariableRequestConfig        Leaf	                              ANY                                   69          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamVariableRequest  modify configLinkOamVariableRequest}      _none_}
            {osi_enable	                        LinkOamOrgSpecificInfoConfig	    ACTIVE	                              {CHOICES 0 1}                         70          _none_          _none_          true        _none_                      false           _none_                                      {create configLinkOamOrgSpecificInfo modify configLinkOamOrgSpecificInfo}       _none_}
            {osi_value	                        LinkOamOrgSpecificInfoConfig	    DataValue	                              ANY                                   71          _none_          _none_          true        _none_                      false           processEmulation_efm_datavalue              {create configLinkOamOrgSpecificInfo modify configLinkOamOrgSpecificInfo}       _none_}
            {osi_oui	                        LinkOamOrgSpecificInfoConfig	    Oui	                                      {REGEXP ^[a-fA-F0-9]{6}$}             72          _none_          _none_          true        _none_                      false           processEmulation_efm_configOui              {create configLinkOamOrgSpecificInfo modify configLinkOamOrgSpecificInfo}       _none_}
            {organization_specific_event_value	LinkOamOrgSpecificConfig	    DataValue	                              ANY                                   74          00              _none_          true        _none_                      false           processEmulation_efm_datavalue              {create configLinkOamOrgSpecific modify configLinkOamOrgSpecific}               _none_}
            {organization_specific_event_oui	LinkOamOrgSpecificConfig	    Oui	                                      {REGEXP ^[a-fA-F0-9]{6}$}             75          001094          _none_          true        _none_                      false           processEmulation_efm_configOui              {create configLinkOamOrgSpecific modify configLinkOamOrgSpecific}               _none_}
        }
        {emulation_efm_control
            {hname                                                      stcobj                             stcattr                                                      type                                                         priority       default          range       supported              dependency                 mandatory       procfunc       mode          constants}
            {port_handle                                                _none_                              _none_                                                      ANY                                                             10          _none_           _none_         true                    _none_                  false           _none_        _none_           _none_}
            {action                                                     _none_                              _none_  {CHOICES start stop start_loopback stop_loopback start_variable_request stop_variable_request start_organization_specific_event stop_organization_specific_event resume start_event_notification stop_event_notification}    20  _none_  _none_  true     _none_     true     _none_  _none_  _none_}
            {pdu_packing	                			_none_				PduPackingOption			                {CHOICES single_tlv batch_tlvs}	 		   			21          single_tlv	     _none_         true                    _none_                  false           _none_	  _none_           _none_}
            {period	                           			_none_                  	    Period					                NUMERIC								22	        1	      1-10	    true                    _none_                  false           _none_        _none_           _none_}
            {tx_type							_none_				    TxType				                {CHOICES single_mag periodic}						23	    single_mag	     _none_	    true		    _none_		    false	    _none_	  _none_	   _none_}
            {pause_at							_none_				    PauseAtState                    {CHOICES fault active_passive send_local_remote send_local_remote_ok send_any none}         23            none           _none_         true		    _none_		    false           _none_        _none_           _none_}
            {error_symbol_period_event_enable			LinkOamStartEventNotificationCommand	SendErroredSymbolPeriodEvent				{CHOICES 0 1}								23		0	     _none_	    true	 action start_event_notification    false	    _none_        _none_           _none_}
            {error_frame_event_enable      			LinkOamStartEventNotificationCommand	SendErroredFrameEvent					{CHOICES 0 1}								23		0	     _none_	    true	 action start_event_notification    false	    _none_        _none_           _none_}
            {error_frame_period_event_enable			LinkOamStartEventNotificationCommand	SendErroredFramePeriodEvent				{CHOICES 0 1}								23		0	     _none_	    true	 action start_event_notification    false	    _none_        _none_           _none_}
            {error_frame_seconds_summary_event_enable	        LinkOamStartEventNotificationCommand	SendErroredFrameSecondsSummaryEvent			{CHOICES 0 1}								23		0	     _none_	    true	 action start_event_notification    false	    _none_        _none_           _none_}
            {organization_specific_event_enable			LinkOamStartEventNotificationCommand	SendOrgSpecificEvent					{CHOICES 0 1}								23		0	     _none_	    true	 action start_event_notification    false	    _none_        _none_           _none_}
			
        }
        {emulation_efm_stat
            {hname                                  stcobj                          stcattr                               type                                                                              priority        default          range         supported   dependency              mandatory          procfunc          mode               constants}
            {port_handle                            _none_                          _none_                                 ANY                                                                                  10          _none_          _none_           true       _none_                      false           _none_           _none_                 _none_}
            {action                                 _none_                          _none_                                 {CHOICES get reset}                                                                  11          _none_          _none_           true       _none_                      true            _none_           _none_                 _none_}
            {oam_mode                               LinkOamRemoteInfoResults        RemoteOperationMode                    {CHOICES active passive}                                                             12          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {unidir_enabled                         LinkOamRemoteInfoResults        RemoteSupportsUnidirectionalMode       {CHOICES 0 1}                                                                        13          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {remote_loopback_enabled                LinkOamRemoteInfoResults        RemoteSupportsLoopback                 {CHOICES 0 1}                                                                        14          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {link_events_enabled                    LinkOamRemoteInfoResults        RemoteInterpretsLinkEvents             {CHOICES 0 1}                                                                        15          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {variable_retrieval_enabled             LinkOamRemoteInfoResults        RemoteSupportsVariableRetrieval        {CHOICES 0 1}                                                                        16          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {oampdu_count                           _none_                          _none_                                 NUMERIC                                                                              17          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {oui_value                              LinkOamRouterConfig             Oui                                    NUMERIC                                                                              18          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {vsi_value                              LinkOamRouterConfig             VendorSpecificInfo                     NUMERIC                                                                              19          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {remote_vsi_value                       LinkOamRemoteInfoResults        RemoteVendorSpecificInfo               NUMERIC                                                                              19          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {errored_symbol_period_events           LinkOamEventCounterResults      ErroredSymbolPeriodRxCount             NUMERIC                                                                              20          _none_          _none_           true       _none_                      false           _none_           {alarms ""}            _none_}
            {errored_frame_events                   LinkOamEventCounterResults      ErroredFrameRxCount                    NUMERIC                                                                              21          _none_          _none_           true       _none_                      false           _none_           {alarms ""}            _none_}
            {errored_frame_period_events            LinkOamEventCounterResults      ErroredFramePeriodRxCount              NUMERIC                                                                              22          _none_          _none_           true       _none_                      false           _none_           {alarms ""}            _none_}
            {errored_frame_seconds_summary_events   LinkOamEventCounterResults      ErroredFrameSecondsSummaryRxCount      NUMERIC                                                                              23          _none_          _none_           true       _none_                      false           _none_           {alarms ""}            _none_}
            {oampdu_size                            _none_                          _none_                                 NUMERIC                                                                              24          _none_          _none_           false      _none_                      false           _none_           {mac_remote  ""}       _none_}
            {tx_information_oam_pdu_count           LinkOamCounterResults           InfoPduTxCount                         NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {tx_link_event_notification_count       LinkOamCounterResults           EventPduTxCount                        NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {rx_information_oam_pdu_count           LinkOamCounterResults           InfoPduRxCount                         NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {rx_link_event_notification_count       LinkOamCounterResults           EventPduRxCount                        NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {rx_organization_specific_oam_pdu_count LinkOamCounterResults           OrgSpecificPduRxCount                  NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {mac_remote  ""}       _none_}
            {tx_errored_symbol_period_events        LinkOamEventCounterResults        ErroredSymbolPeriodTxCount             NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_errored_frame_events                LinkOamEventCounterResults        ErroredFrameTxCount                    NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_errored_frame_period_events         LinkOamEventCounterResults        ErroredFramePeriodTxCount              NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_errored_frame_seconds_summary_events LinkOamEventCounterResults       ErroredFrameSecondsSummaryTxCount      NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_organization_specific_events        LinkOamEventCounterResults        OrgSpecificTxCount                     NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {organization_specific_events           LinkOamEventCounterResults        OrgSpecificRxCount                     NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_critical_events                     LinkOamStateResults             CriticalEventTxCount                   NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_dying_gasp                          LinkOamStateResults             DyingGaspTxCount                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {tx_link_fault                          LinkOamStateResults             LinkFaultTxCount                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {rx_critical_events                     LinkOamStateResults             CriticalEventRxCount                   NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {rx_dying_gasp                          LinkOamStateResults             DyingGaspRxCount                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {rx_link_fault                          LinkOamStateResults             LinkFaultRxCount                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {alarms  ""}           _none_}
            {remote_dte_oam_version                 LinkOamRemoteInfoResults             RemoteOamVersion                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_revision                    LinkOamRemoteInfoResults             RemoteRevision                         NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_max_pdu_size                    LinkOamRemoteInfoResults             RemoteMaxPduSize                       NUMERIC                                                                              25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {current_discovery_state	            LinkOamStateResults             LocalState         {CHOICES UNSATISFIED NOT_COMPLETED COMPLETED RESERVED NONE}                                              25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {local_dte_tx_critical_event_bit        LinkOamStateResults             CriticalEvent                       {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {local_dte_tx_dying_gasp_bit            LinkOamStateResults             DyingGasp                           {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {local_dte_tx_link_fault_bit            LinkOamStateResults             LinkFault                           {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_rx_critical_event_bit       LinkOamStateResults             RemoteCriticalEvent                 {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_rx_dying_gasp_bit           LinkOamStateResults             RemoteDyingGasp                     {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_rx_link_fault_bit           LinkOamStateResults             RemoteLinkFault                     {CHOICES OFF ON}                                                                        25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_multiplexer_action_value    LinkOamStateResults             RemoteMultiplexerAction             {CHOICES FWD DISCARD}                                                                   25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {remote_dte_parser_action_value         LinkOamStateResults             RemoteParserAction                  {CHOICES FWD LB DISCARD RESERVED}                                                       25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {info_pdu_timesout                      LinkOamCounterResults           InfoPduTimeouts                       NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {rx_loopback_pdu_count                  LinkOamCounterResults           LoopbackPduRxCount                    NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {loopback_pdu_timesout                  LinkOamCounterResults           LoopbackPduTimeouts                   NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {tx_loopback_pdu_count                  LinkOamCounterResults           LoopbackPduTxCount                    NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {tx_org_specific_pdu_count              LinkOamCounterResults           OrgSpecificPduTxCount                 NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {rx_variable_request_pdu_count          LinkOamCounterResults           VariableRequestPduRxCount             NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {variable_request_pdu_timeouts          LinkOamCounterResults           VariableRequestPduTimeouts            NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {tx_variable_request_pdu_count          LinkOamCounterResults           VariableRequestPduTxCount             NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {rx_variable_response_pdu_count         LinkOamCounterResults           VariableResponsePduRxCount            NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {tx_variable_response_pdu_count         LinkOamCounterResults           VariableResponsePduTxCount            NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}       _none_}
            {local_dte_multiplexer_action_value     LinkOamStateResults             MultiplexerAction                   {CHOICES FWD DISCARD}                                                                   25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}          _none_}
            {local_dte_parser_action_value          LinkOamStateResults             ParserAction                        {CHOICES FWD LB DISCARD RESERVED}                                                       25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}          _none_}
            {remote_state                           LinkOamStateResults             RemoteState         {CHOICES UNSATISFIED NOT_COMPLETED COMPLETED RESERVED NONE}                                             25          _none_          _none_           true       _none_                      false           _none_           {statistics   ""}          _none_}
            {event_type                             LinkOamEventNotificationResults EventType   {CHOICES ERRORED_SYMBOL_PERIOD ERRORED_FRAME ERRORED_FRAME_PERIOD ERRORED_FRAME_SECONDS_SUMMARY ORG_SPECIFIC}   25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {time_stamp                             LinkOamEventNotificationResults Timestamp                             NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {window_size                            LinkOamEventNotificationResults WindowSize                            NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {threshold                              LinkOamEventNotificationResults Threshold                             NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {error_count                            LinkOamEventNotificationResults ErrorCount                            NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {error_running_total                    LinkOamEventNotificationResults ErrorRunningTotal                     NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {event_running_total                    LinkOamEventNotificationResults EventRunningTotal                     NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {oui                                    LinkOamEventNotificationResults Oui                                   NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
            {value                                  LinkOamEventNotificationResults DataValue                             NUMERIC                                                                               25          _none_          _none_           true       _none_                      false           _none_           {event_notification   ""}       _none_}
        }
    }
}