namespace eval ::sth::lspPing {
}
set ::sth::lspPing::lspPingTable {
    ::sth::lspPing::
    {     emulation_lsp_ping_config
        {hname                                     stcobj                      stcattr               type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                             constants}
        {handle                                    _none_                      _none_            ALPHANUM                         0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {mode                                      _none_                      _none_                {CHOICES enable disable config}     0             _none_         _none_      true           _none_                            true             _none_          _none_                           _none_}
        {gach_type           LspPingGlobalConfig         GenericAssociatedChannelType           NUMERIC    1             37             0-65535   true           _none_                            false            _none_          { config lspping_global_config }       _none_}
        {igp_adjacency_sr_sub_tlv_type             LspPingGlobalConfig         IgpAdjacencySrSubTlvType               NUMERIC    1             36             0-65535     true           _none_                            false            _none_          { config lspping_global_config }       _none_}
        {ipv4_igp_prefix_sr_sub_tlv_type           LspPingGlobalConfig         Ipv4IgpPrefixSrSubTlvType              NUMERIC    1             34             0-65535     true           _none_                            false            _none_          { config lspping_global_config }       _none_}
        {static_mpls_tp_lsp_sub_tlv_type           LspPingGlobalConfig         StaticMplsTpLspSubTlvType              NUMERIC    1             22             0-65535     true           _none_                            false            _none_          { config lspping_global_config }       _none_}
        {static_mpls_tp_pw_sub_tlv_type            LspPingGlobalConfig         StaticMplsTpPwSubTlvType               NUMERIC    1             23             0-65535     true           _none_                            false            _none_          { config lspping_global_config }       _none_}
    }
    {     emulation_lsp_ping_message_config
        {hname                                     stcobj                      stcattr               type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                             constants}
        {handle                                    _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {mode                                      _none_                      _none_                {CHOICES create delete modify}     0             _none_         _none_      true           _none_                            true             _none_          _none_                           _none_}
        {message_type                                _none_                      _none_           {CHOICES echo_request error_reply}        0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {operation_mode                            Ipv4EchoRequestConfig       OperationMode          ANY                        1             ping           _none_       true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {echo_reply_mode                           Ipv4EchoRequestConfig       EchoReplyMode          {CHOICES no_reply ip ip_with_route_alert control_channel} 1             ip           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {ping_interval                             Ipv4EchoRequestConfig       PingInterval           NUMERIC                    1             5              1-2147483647      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {ping_timeout                              Ipv4EchoRequestConfig       PingTimeout            NUMERIC                    1             2              1-65535      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {trace_route_interval                      Ipv4EchoRequestConfig       TraceRouteInterval     NUMERIC                    1             120            1-2147483647      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {trace_route_timeout                       Ipv4EchoRequestConfig       TraceRouteInterval     NUMERIC                    1             2              1-2147483647      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {ttl                                       Ipv4EchoRequestConfig       TimeToLive             NUMERIC                    1             null           1-255      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {exp_bits                                  Ipv4EchoRequestConfig       ExperimentalBits       NUMERIC                    1             0              0-7         true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {validate_fec_stack                        Ipv4EchoRequestConfig       ValidateFecStack       {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {enable_nil_fec_label                      Ipv4EchoRequestConfig       EnableNilFecLabel      {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {pad_mode                                  Ipv4EchoRequestConfig       PadMode                {CHOICES no_pad_tlv request_drop_pad_tlv request_copy_pad_tlv} 1             no_pad_tlv           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {pad_data                                  Ipv4EchoRequestConfig       PadData                NUMERIC                    1             0              _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {enable_nil_fec_label                      Ipv4EchoRequestConfig       EnableNilFecLabel      {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {enable_gach         Ipv4EchoRequestConfig       EnableGenericAssociatedChannel    {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {enable_gal           Ipv4EchoRequestConfig       EnableGenericAssociatedLabel      {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {enable_bfd_discr_sub_tlv          Ipv4EchoRequestConfig       EnableBfdDiscriminatorSubTlv      {CHOICES true false}       1             false           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {ipv4_dst_addr                             Ipv4EchoRequestConfig       DstAddr                IPV4                       1          127.0.0.1           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {encap                             Ipv4EchoRequestConfig       Encapsulation          {CHOICES udp raw} 1             udp           _none_      true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {bfd_my_discr                      Ipv4EchoRequestConfig       BfdMyDiscriminator      NUMERIC                    1             10      0-4294967295           true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {bfd_my_discr_step                 Ipv4EchoRequestConfig       BfdMyDiscriminatorStep  NUMERIC                    1             1       0-49151                true           _none_                            false            _none_          { create lspping_er_config modify lspping_er_config }              _none_}
        {error_scenario                            echoreplyerrorgeneration    ErrorScenario          {CHOICES no_reply no_mapping_for_fec mapping_mismatch no_label_entry} 1             no_reply           _none_      true           _none_                            false            _none_          { create lspping_error_config modify lspping_error_config }              _none_}
    }
    {     emulation_lsp_ping_fec_config
        {hname                                     stcobj                      stcattr               type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                             constants}
        {handle                                    _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {inner_fec_handle                          _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {middle_fec_handle                         _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {mode                                      _none_                      _none_                {CHOICES create delete modify}     0             _none_         _none_      true           _none_                            true             _none_          _none_                           _none_}
        {label_type                                _none_                      _none_             {CHOICES inner middle outer}        0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {fec_type                                  _none_                      _none_                ANY                          0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {rsvp_tunnel_count                         RsvpTunnelFecInfo       TunnelCount          NUMERIC                           1             1           1-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_start_tunnel_id                      RsvpTunnelFecInfo       StartTunnelId          NUMERIC                           1             1          0-65535      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_tunnel_id_increment                  RsvpTunnelFecInfo       TunnelIdIncrement      NUMERIC                           1             1           0-65535      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_lsp_count                            RsvpTunnelFecInfo       LspCount          NUMERIC                           1             1           1-20     true           _none_                                      false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_start_lsp_id                         RsvpTunnelFecInfo       StartLspId          NUMERIC                          1             1           1-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_lsp_id_increment                     RsvpTunnelFecInfo       LspIdIncrement          NUMERIC                   1             1           0-65535      true           _none_                                      false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_extended_tunnel_id                   RsvpTunnelFecInfo       ExtendedTunnelId          IPV4                   1             0.0.0.0           _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_tunnel_src_ip_addr                   RsvpTunnelFecInfo       TunnelSrcIpAddr           IPV4                    1            192.85.1.3           _none_      true           _none_                           false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {rsvp_tunnel_dst_ip_addr                   RsvpTunnelFecInfo       TunnelDstIpAddr          IPV4                    1             192.85.1.1           _none_      true           _none_                           false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {ipv4_prefix_addr_increment                Ipv4PrefixFecInfo       AddrIncrement          NUMERIC                           1             1          0-4294967295      true           _none_                           false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {ipv4_prefix_network_count                 Ipv4PrefixFecInfo       NetworkCount          NUMERIC                           1             1           0-4294967295      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {ipv4_prefix_start_ip_addr                 Ipv4PrefixFecInfo       StartIpAddr           IPV4                              1           192.0.1.0           _none_      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {ipv4_prefix_length                        Ipv4PrefixFecInfo       PrefixLength          NUMERIC                           1             24           1-32     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {ipv4_prefix_protocol                      Ipv4PrefixFecInfo       Protocol              {CHOICES bgp ldp}                  1         bgp                  _none_      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_id_count                               VcFecInfo               VcIdCount             NUMERIC                           1             1            1-65535      true           _none_                           false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {start_vc_id                               VcFecInfo               StartVcId             NUMERIC                           1             1           0-4294967295      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_id_increment                           VcFecInfo               VcIdIncrement         NUMERIC                            1           192.0.1.0    0-4294967295      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_encap_type                             VcFecInfo               Encap                 ANY                      1     LDP_L2VPN_ENCAP_ETHERNET_VLAN   _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_use_custom_encap                       VcFecInfo               UseCustomEncap              {CHOICES true false}         1   false    _none_                  true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_custom_encap                           VcFecInfo               CustomEncap         NUMERIC                           1             4           0-32767     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vc_vccv_control_channel                   VcFecInfo               VccvControlChannel              ANY                  1         0                  _none_      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {att_group_id                       GeneralizedPseudoWireFecInfo          AttachmentGroupId           ANY        1          100:1             _none_      true           _none_                           false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {att_group_id_step                  GeneralizedPseudoWireFecInfo          AttachmentGroupIdStep       ANY        1          0:1               _none_      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {pseudo_wire_count                  GeneralizedPseudoWireFecInfo          PseudoWireCount             NUMERIC    1          1                  1-65535      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {src_att_individual_id              GeneralizedPseudoWireFecInfo          SrcAttachmentIndividualId   ANY        1     192.168.1.1            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {src_att_individual_id_step         GeneralizedPseudoWireFecInfo          TargetAttachmentIndividualId  ANY      1     0.0.0.1                _none_     true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {target_att_individual_id           GeneralizedPseudoWireFecInfo          SrcAttachmentIndividualId   ANY        1     192.168.1.2            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {target_att_individual_id_step      GeneralizedPseudoWireFecInfo          TargetAttachmentIndividualIdStep  ANY  1     0.0.0.1                _none_     true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {generalized_pw_encap_type                 GeneralizedPseudoWireFecInfo        Encap        ANY                1     LDP_L2VPN_ENCAP_ETHERNET_VLAN   _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {generalized_pw_use_custom_encap           GeneralizedPseudoWireFecInfo        UseCustomEncap  {CHOICES true false}      1   false                   _none_     true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {generalized_pw_custom_encap               GeneralizedPseudoWireFecInfo        CustomEncap         NUMERIC               1      4                    0-32767     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {generalized_pw_vccv_control_channel       GeneralizedPseudoWireFecInfo        VccvControlChannel  ANY                   1      0                  _none_      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpls_block_count                          BgpVplsFecInfo          VplsBlockCount       NUMERIC                          1      1                 1-4294967295      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {far_end_ve_id                             BgpVplsFecInfo          FarEndVeId           NUMERIC                          1      0                 0-65535        true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {far_end_ve_id_increment                   BgpVplsFecInfo          FarEndVeIdIncrement  NUMERIC                          1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {near_end_ve_id                            BgpVplsFecInfo          NearEndVeId          NUMERIC                          1      0                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {near_end_ve_id_increment                  BgpVplsFecInfo          NearEndVeIdIncrement NUMERIC                          1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {bgp_vpls_rd                               BgpVplsFecInfo          RouteDistinguisher   ANY                              1      100:1                 _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {bgp_vpls_rd_increment                     BgpVplsFecInfo          RouteDistinguisherIncrement   ANY                     1      0:1                   _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpnv4_count                               BgpIpv4VpnFecInfo       NetworkCount             NUMERIC                      1      1                1-4294967295      true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpnv4_start_ip_addr                       BgpIpv4VpnFecInfo       StartIpAddr              IPV4                         1     192.0.1.0              _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpnv4_prefix_length                       BgpIpv4VpnFecInfo       PrefixLength             NUMERIC                      1     24                        1-32     true           _none_                            false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpnv4_addr_increment                      BgpIpv4VpnFecInfo       AddrIncrement            NUMERIC                      1     1                      _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {vpnv4_rd                                  BgpIpv4VpnFecInfo       RouteDistinguisher       ANY                           1      100:1                 _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_src_global_id                MplsTpStaticPseudoWireFecInfo      SrcGlobalId   ANY                           1      1                     _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_dst_global_id                MplsTpStaticPseudoWireFecInfo      DstGlobalId   ANY                           1      1                     _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_src_node_id                  MplsTpStaticPseudoWireFecInfo      SrcNodeId     ANY                           1      192.85.1.1            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_dst_node_id                  MplsTpStaticPseudoWireFecInfo      DstNodeId     ANY                           1      192.85.2.1            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_att_circuit_count            MplsTpStaticPseudoWireFecInfo      AttachmentCircuitCount      NUMERIC         1      1                1-4294967295      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_att_group_id                 MplsTpStaticPseudoWireFecInfo      AttachmentGroupId      ANY                  1      100:1                  _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_att_group_id_step            MplsTpStaticPseudoWireFecInfo      AttachmentGroupIdStep  ANY                  1      0:0                    _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_src_att_circuit_id           MplsTpStaticPseudoWireFecInfo      SrcAttachmentCircuitId      ANY             1      10.0.0.1               _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_src_att_circuit_id_step      MplsTpStaticPseudoWireFecInfo      SrcAttachmentCircuitIdStep  ANY             1      0.0.0.1                _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_dst_att_circuit_id           MplsTpStaticPseudoWireFecInfo      DstAttachmentCircuitId      ANY             1      10.0.0.2               _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_pw_dst_att_circuit_id_step      MplsTpStaticPseudoWireFecInfo      DstAttachmentCircuitIdStep  ANY             1      0.0.0.1                _none_     true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_src_global_id               MplsTpStaticLspFecInfo      SrcGlobalId   ANY                           1      1                     _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_dst_global_id               MplsTpStaticLspFecInfo      DstGlobalId   ANY                           1      1                     _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_src_node_id                 MplsTpStaticLspFecInfo      SrcNodeId     ANY                           1      192.85.1.1            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_dst_node_id                 MplsTpStaticLspFecInfo      DstNodeId     ANY                           1      192.85.2.1            _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_tunnel_count                MplsTpStaticLspFecInfo      TunnelCount      NUMERIC                    1      1                1-4294967295      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_src_tunnel_num              MplsTpStaticLspFecInfo      SrcTunnelNum           NUMERIC              1      1                 0-65535        true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_src_tunnel_num_step         MplsTpStaticLspFecInfo      SrcTunnelNumStep       NUMERIC              1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_dst_tunnel_num              MplsTpStaticLspFecInfo      DstTunnelNum          NUMERIC                1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {tp_static_lsp_dst_tunnel_num_step         MplsTpStaticLspFecInfo      DstTunnelNumStep      NUMERIC                1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {lsp_id                                    MplsTpStaticLspFecInfo      LspId          NUMERIC                1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {lsp_id_step                               MplsTpStaticLspFecInfo      LspIdStep      NUMERIC                1      1                 0-65535      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_protocol                               SrFecInfoList               Protocol      {CHOICES isis ospfv2}   1      isis              _none_       true            _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_node_type_list                         SrFecInfoList               NodeTypeList  {CHOICES prefix link neighbor}   1      prefix   _none_      true            _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_ipv4_prefix_list                       SrFecInfoList              Ipv4PrefixList     ANY                         1      192.0.1.0    _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_ipv4_prefix_length_list                SrFecInfoList              Ipv4PrefixLengthList     NUMERIC                1      24           1-32      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_addr_increment_list                    SrFecInfoList              AddrIncrementList        NUMERIC                1      1       0-4294967295      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_prefix_count_list                      SrFecInfoList              PrefixCountList     NUMERIC                     1      1       0-4294967295      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_system_id_list                         SrFecInfoList              SystemIdList        ANY                         1      00:00:94:00:00:01    _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_neighbor_id_list                       SrFecInfoList              NeighborIdList      ANY                         1      00:00:94:00:00:01    _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_local_ipv4_interface_id_list           SrFecInfoList              LocalIpv4InterfaceIdList     ANY               1      0.0.0.0    _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
        {sr_remote_ipv4_interface_id_list          SrFecInfoList              RemoteIpv4InterfaceIdList     ANY              1      0.0.0.0    _none_      true           _none_                                  false            _none_          { create lspping_fec_config modify lspping_fec_config }              _none_}
     } 
}