namespace eval ::sth::mplsIpVpn {
}

set ::sth::mplsIpVpn::mplsIpVpnTable {
    ::sth::mplsIpVpn::
    {    emulation_mpls_ip_vpn_provider_port_config
        {hname                                     stcobj                      stcattr               type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                             constants}
        {port_handle                               _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {handle                                    _none_                      _none_                ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                           _none_}
        {mode                                      _none_                      _none_                {CHOICES create delete}     0             _none_         _none_      true           _none_                            true             _none_          _none_                           _none_}
        {dut_interface_ipv4_addr                   VpnRfc2547GenCorePortParams     DutIpv4Addr           IPV4                        1             192.85.1.1     _none_      true           _none_                            false            _none_          { create coreport_config }       _none_}
        {dut_interface_ipv4_addr_step              VpnRfc2547GenCorePortParams     DutIpv4AddrStep       IPV4                        2             0.0.1.0        _none_      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {dut_interface_ipv4_prefix_length          VpnRfc2547GenCorePortParams     Ipv4PrefixLength      NUMERIC                     1             24             0-32        true           _none_                            false            _none_          { create coreport_config }       _none_}
        {sub_interface_enable                      VpnRfc2547GenCorePortParams     SubIfEnable           {CHOICES true false}        1             false          _none_      true           _none_                            false            _none_          { create coreport_config }       _none_}
        {sub_interface_count                       VpnRfc2547GenCorePortParams     SubIfCount            NUMERIC                     2             1              1-65535      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {vlan_id                                   VpnRfc2547GenCorePortParams     VlanId                NUMERIC                     2             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
        {vlan_id_step                              VpnRfc2547GenCorePortParams     VlanIdStep            NUMERIC                     0             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create coreport_config }       _none_}
    }
    {    emulation_mpls_ip_vpn_cust_port_config
        {hname                                     stcobj                       stcattr              type                        priority      default        range       supported      dependency                        mandatory        procfunc        mode                            constants}
        {port_handle                               _none_                       _none_               ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                          _none_}
        {handle                                    _none_                       _none_               ALPHANUM                    0             _none_         _none_      true           _none_                            false            _none_          _none_                          _none_}
        {mode                                      _none_                       _none_               {CHOICES create delete}     0             _none_         _none_      true           _none_                            true             _none_          _none_                          _none_}
        {dut_interface_ipv4_addr                   VpnRfc2547GenCustPortParams      DutIpv4Addr          IPV4                        1             192.85.1.1             _none_      true           _none_                            false            _none_          { create custport_config }      _none_}
        {dut_interface_ipv4_addr_step              VpnRfc2547GenCustPortParams      DutIpv4AddrStep      IPV4                        2             0.0.1.0      _none_      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {dut_interface_ipv4_prefix_length          VpnRfc2547GenCustPortParams      Ipv4PrefixLength     NUMERIC                     1             24             0-32       true           _none_                            false            _none_          { create custport_config }      _none_}
        {sub_interface_enable                      VpnRfc2547GenCustPortParams      SubIfEnable          {CHOICES true false}        1             false          _none_      true           _none_                            false            _none_          { create custport_config }      _none_}
        {sub_interface_count                       VpnRfc2547GenCustPortParams      SubIfCount           NUMERIC                     2             1              1-65535      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {vlan_id                                   VpnRfc2547GenCustPortParams      VlanId               NUMERIC                     2             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
        {vlan_id_step                              VpnRfc2547GenCustPortParams      VlanIdStep           NUMERIC                     0             1              0-4095      true           {sub_interface_enable true}       false            _none_          { create custport_config }      _none_}
    }
    {    emulation_mpls_ip_vpn_config
        {hname                                            stcobj                          stcattr                                           type                                                  priority             default                 range                 supported        dependency            mandatory       procfunc                  mode                                         constants}
        {handle                                           _none_                          _none_                                            ANY                                                   2                    _none_                  _none_                true             _none_                false           _none_                    _none_                                       _none_}
        {mode                                             _none_                          _none_                                            {CHOICES create delete}                               0                    _none_                  _none_                true             _none_                true            _none_                    _none_                                       _none_}
        {dut_router_id                                    VpnRfc2547GenParams                 DutLoopbackIpAddr                                 IPV4                                                  2                    "10.0.0.1"              _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {dut_as                                           VpnRfc2547GenParams                 DutAs                                             NUMERIC                                               2                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {dut_4byte_as_enable                              VpnRfc2547GenParams                 Enable4ByteDutAs                                  {CHOICES true false}                                  2                    0                       _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {dut_4byte_as                                     VpnRfc2547GenParams                 DutAs4Byte                                        ANY                                                   3                    "1:1"                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {use_provider_ports                               VpnRfc2547GenParams                 UseCorePortsEnable                                {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {use_cust_ports                                   VpnRfc2547GenParams                 UseCustPortsEnable                                {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {igp_protocol                                     VpnRfc2547GenParams                 CoreIgpProtocol                                   {CHOICES ospf isis rip none}                          2                    ospf                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {mpls_protocol                                    VpnRfc2547GenParams                 CoreMplsProtocol                                  {CHOICES none ldp rsvp ospf isis}                     2                    ldp                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                       _none_}
        {igp_ospf_area_id                                 VpnIgpOspfv2SessionParams       AreaId                                            IPV4                                                  3                    "0.0.0.0"               _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_network_type                            VpnIgpOspfv2SessionParams       NetworkType                                       {CHOICES native broadcast p2p}                        3                    native                  _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                {native "NATIVE" broadcast "BROADCAST" p2p "P2P"}}
        {igp_ospf_router_priority                         VpnIgpOspfv2SessionParams       RouterPriority                                    NUMERIC                                               3                    0                       0-255                 true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_interface_cost                          VpnIgpOspfv2SessionParams       IfCost                                            NUMERIC                                               3                    1                       1-65535               true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_options                                 VpnIgpOspfv2SessionParams       Options                                           HEX                                                   3                    0x02                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_auth_mode                               Ospfv2AuthenticationParams      Authentication                                    {CHOICES none simple md5}                             3                    none                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   {none "NONE" simple "SIMPLE" md5 "MD5"}}
        {igp_ospf_auth_password                           Ospfv2AuthenticationParams      Password                                          ANY                                                   4                    "spirent"               _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   _none_}
        {igp_ospf_auth_md5_key                            Ospfv2AuthenticationParams      Md5KeyId                                          NUMERIC                                               4                    1                       0-255                 true             {igp_protocol ospf}   false           _none_                    {create ospfv2auth_config}                   _none_}
        {igp_ospf_graceful_restart_enable                 VpnIgpOspfv2SessionParams       EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_ospf_graceful_restart_type                   VpnIgpOspfv2SessionParams       GracefulRestartType                               {CHOICES none rfc_standard ll_signalling}             3                    none                    _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                {none "NONE" rfc_standard "RFCSTANDARD" ll_signalling "LLSIGNALLING"}}
        {igp_ospf_bfd_enable                              VpnIgpOspfv2SessionParams       EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol ospf}   false           _none_                    {create ospfv2session_config}                _none_}
        {igp_isis_level                                   VpnIgpIsisSessionParams         Level                                             {CHOICES level1 level2 level1_and_2}                  3                    level2                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 {level1 "LEVEL1" level2 "LEVEL2" level1_and_2 "LEVEL1_AND_2"}}
        {igp_isis_network_type                            VpnIgpIsisSessionParams         NetworkType                                       {CHOICES broadcast p2p}                               3                    broadcast               _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 {broadcast "BROADCAST" p2p "P2P"}}
        {igp_isis_router_priority                         VpnIgpIsisSessionParams         RouterPriority                                    NUMERIC                                               3                    0                       0-127                 true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area1                                   VpnIgpIsisSessionParams         Area1                                             ANY                                                   3                    000001                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area2                                   VpnIgpIsisSessionParams         Area2                                             ANY                                                   3                    _none_                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_area3                                   VpnIgpIsisSessionParams         Area3                                             ANY                                                   3                    _none_                  _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_circuit_id                              VpnIgpIsisSessionParams         CircuitId                                         ANY                                                   3                    1                       0-255                 true             {igp_protocol isis}   false           _none_                    {create isissession_config}                 _none_}
        {igp_isis_auth_mode                               IsisAuthenticationParams        Authentication                                    {CHOICES none simple md5}                             3                    none                    _none_                true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   {none "NONE" simple "SIMPLE" md5 "MD5"}}
        {igp_isis_auth_password                           IsisAuthenticationParams        Password                                          ANY                                                   4                    "spirent"               _none_                true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   _none_}
        {igp_isis_auth_md5_key                            IsisAuthenticationParams        Md5KeyId                                          NUMERIC                                               4                    1                       0-255                 true             {igp_protocol isis}   false           _none_                    {create isisauth_config}                   _none_}
        {igp_isis_metric_mode                             VpnIgpIsisSessionParams         MetricMode                                        {CHOICES narrow wide narrow_and_wide}                 3                    narrow_and_wide         _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                {narrow "NARROW" wide "WIDE" narrow_and_wide "NARROW_AND_WIDE"}}
        {igp_isis_l1_metric                               VpnIgpIsisSessionParams         L1Metric                                          NUMERIC                                               3                    1                       1-63                  true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l1_wide_metric                          VpnIgpIsisSessionParams         L1WideMetric                                      NUMERIC                                               3                    1                       0-16777215            true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l2_metric                               VpnIgpIsisSessionParams         L2Metric                                          NUMERIC                                               3                    1                       1-63                  true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_l2_wide_metric                          VpnIgpIsisSessionParams         L2WideMetric                                      NUMERIC                                               3                    1                       0-16777215            true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_graceful_restart_enable                 VpnIgpIsisSessionParams         EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_hello_padding                           VpnIgpIsisSessionParams         HelloPadding                                      {CHOICES true false}                                  3                    1                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {igp_isis_bfd_enable                              VpnIgpIsisSessionParams         EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {igp_protocol isis}   false           _none_                    {create isissession_config}                _none_}
        {mpls_rsvp_bandwidth_per_link                     VpnRfc2547GenParams                 CorePRsvpBandwidthPerLink                         NUMERIC                                               4                    100000                  1-2147483647          true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {mpls_rsvp_bandwidth_per_tunnel                   VpnRfc2547GenParams                 CorePRsvpBandwidthPerTunnel                       NUMERIC                                               4                    0                       0-2147483647          true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {mpls_rsvp_egress_label                           VpnMplsRsvpSessionParams        EgressLabel                                       {CHOICES next_available implicit_null explicit_null}  3                    next_available          _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                {next_available "RSVP_EGRESS_NEXTAVAILABLE" implicit_null "RSVP_EGRESS_IMPLICIT_NULL" explicit_null "RSVP_EGRESS_EXPLICIT_NULL"}}
        {mpls_rsvp_transit                                VpnMplsRsvpSessionParams        Transit                                           {CHOICES  accept_all accept_configured}               3                    accept_configured       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                {accept_all "RSVP_TRANSIT_ACCEPT_ALL" accept_configured "RSVP_TRANSIT_ACCEPT_CONFIGURED"}}
        {mpls_rsvp_min_label                              VpnMplsRsvpSessionParams        LabelMin                                          NUMERIC                                               3                    16                      1-65535               true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_max_label                              VpnMplsRsvpSessionParams        LabelMax                                          NUMERIC                                               3                    65535                   1-65535               true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_graceful_restart_enable                VpnMplsRsvpSessionParams        EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_recover_time                           VpnMplsRsvpSessionParams        RecoveryTime                                      NUMERIC                                               3                    0                       0-4294967295          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_restart_time                           VpnMplsRsvpSessionParams        RestartTime                                       NUMERIC                                               3                    3000                    0-4294967295          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_bfd_enable                             VpnMplsRsvpSessionParams        EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_request_conf                           VpnMplsRsvpSessionParams        EnableResvRequestConfirmation                     {CHOICES true false}                                  3                    false                   _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_hello_interval                         VpnMplsRsvpSessionParams        HelloInterval                                     NUMERIC                                               3                    1000                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_} 
        {mpls_rsvp_bundle_interval                        VpnMplsRsvpSessionParams        RefreshReductionBundleInterval                    ALPHANUM                                              3                    null                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_summary_refresh_interval               VpnMplsRsvpSessionParams        RefreshReductionSummaryRefreshInterval            ALPHANUM                                              3                    null                    1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_inter_packet_delay                     VpnMplsRsvpSessionParams        InterPktDelay                                     NUMERIC                                               3                    30                      0-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_refresh_interval                       VpnMplsRsvpSessionParams        RefreshInterval                                   NUMERIC                                               3                    30000                   1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_refresh_delivery                       VpnMplsRsvpSessionParams        EnableReliableDelivery                            {CHOICES true false}                                  3                    false                   _none_                true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_interval                       VpnMplsRsvpSessionParams        RetransmitInterval                                NUMERIC                                               3                    500                     1-2147483647          true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_limit                          VpnMplsRsvpSessionParams        RetransmitLimit                                   NUMERIC                                               3                    3                       0-10                  true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_retrans_delta                          VpnMplsRsvpSessionParams        RetransmitDelta                                   NUMERIC                                               3                    1                       0-3                   true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_rsvp_hello_enable                           VpnMplsRsvpSessionParams        EnableHello                                       {CHOICES true false}                                  3                    1                       0-3                   true             {mpls_protocol rsvp}  false           _none_                    {create rsvpsession_config}                _none_}
        {mpls_ldp_hello_type                              VpnMplsLdpSessionParams         HelloType                                         {CHOICES direct targeted}                             3                    direct                  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {direct "LDP_DIRECTED_HELLO" targeted "LDP_TARGETED_HELLO"}}
        {mpls_ldp_transport_mode                          VpnMplsLdpSessionParams         TransportTlvMode                                  {CHOICES none tester_ip router_id}                    3                    tester_ip               _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {none "TRANSPORT_TLV_MODE_NONE" tester_ip "TRANSPORT_TLV_MODE_TESTER_IP" router_id "TRANSPORT_TLV_MODE_ROUTER_ID"}}
        {mpls_ldp_hello_interval                          VpnMplsLdpSessionParams         HelloInterval                                     NUMERIC                                               3                    5                       1-21845               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_keepalive_interval                      VpnMplsLdpSessionParams         KeepAliveInterval                                 NUMERIC                                               3                    60                      1-21845               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_egress_label                            VpnMplsLdpSessionParams         EgressLabel                                       {CHOICES next_available implicit_null explicit_null}  3                    next_available          _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 {next_available "LDP_EGRESS_NEXTAVAILABLE" implicit_null "LDP_EGRESS_IMPLICIT_NULL" explicit_null "LDP_EGRESS_EXPLICIT_NULL"}}
        {mpls_ldp_min_label                               VpnMplsLdpSessionParams         LabelMin                                          NUMERIC                                               3                    16                      1-65535               true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_graceful_restart_enable                 VpnMplsLdpSessionParams         EnableGracefulRestart                             {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_recover_time                            VpnMplsLdpSessionParams         RecoveryTime                                      NUMERIC                                               3                    140                     0-4294967295          true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_reconnect_time                          VpnMplsLdpSessionParams         ReconnectTime                                     NUMERIC                                               3                    60                      0-4294967295          true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_bfd_enable                              VpnMplsLdpSessionParams         EnableBfd                                         {CHOICES true false}                                  3                    0                       _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_label_adv_mode                          VpnMplsLdpSessionParams         LabelAdvertisementMode                            {CHOICES downstream_unsolicited downstream_on_demand} 3                    downstream_unsolicited  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpsession_config}                 _none_}
        {mpls_ldp_auth_mode                               LdpAuthenticationParams         Authentication                                    {CHOICES none md5}                                    3                    "none"                  _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpauth_config}                    _none_}
        {mpls_ldp_auth_password                           LdpAuthenticationParams         Password                                          ANY                                                   4                    "spirent"               _none_                true             {mpls_protocol ldp}   false           _none_                    {create ldpauth_config}                    _none_}
        {mpls_ospf_sr_algorithms                          VpnIgpOspfv2SessionParams       SrAlgorithmTlvAlgorithms                          ANY                                                   3                    0                       _none_                true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_sid_base                               VpnIgpOspfv2SessionParams       SidLabelRangeTlvSidBase                           NUMERIC                                               3                    100                     0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_sid_range                              VpnIgpOspfv2SessionParams       SidLabelRangeTlvSidRange                          NUMERIC                                               3                    100                     0-65535               true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_node_sid_index                         VpnIgpOspfv2SessionParams       PrefixSidSubTlvIndex                              NUMERIC                                               3                    0                       0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_ospf_node_sid_index_step                    VpnIgpOspfv2SessionParams       PrefixSidSubTlvIndexStep                          NUMERIC                                               3                    1                       0-4294967295          true             _none_                false           _none_                    {create ospfv2session_config}              _none_}
        {mpls_isis_sr_algorithm                           VpnIgpIsisSessionParams         SrAlgorithms                                      ANY                                                   3                    0                       _none_                true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_sid_base                               VpnIgpIsisSessionParams         SrCapSidBase                                      NUMERIC                                               3                    100                     0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_sid_range                              VpnIgpIsisSessionParams         SrCapSidRange                                     NUMERIC                                               3                    100                     0-65535               true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_node_sid_index                         VpnIgpIsisSessionParams         SrNodeSidIndex                                    NUMERIC                                               3                    0                       0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {mpls_isis_node_sid_index_step                    VpnIgpIsisSessionParams         SrNodeSidIndexStep                                NUMERIC                                               3                    1                       0-4294967295          true             _none_                false           _none_                    {create isissession_config}                _none_}
        {p_router_enable                                  VpnRfc2547GenParams                 CorePEnable                                       {CHOICES true false}                                  2                    1                       _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {p_router_num_per_subif                           VpnRfc2547GenParams                 CorePPerSubIf                                     NUMERIC                                               3                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {p_router_topology_type                           VpnRfc2547GenParams                 CorePTopologyType                                 {CHOICES tree grid}                                   3                    tree                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {tree "TREE" grid "GRID"}}
        {p_router_id_start                                VpnRfc2547GenParams                 CorePLoopbackIpAddr                               IPV4                                                  3                    "192.0.1.1"             _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {p_router_id_step                                 VpnRfc2547GenParams                 CorePLoopbackIpAddrStep                           IPV4                                                  3                    "0.0.1.0"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {p_router_ipv4_addr                               VpnRfc2547GenParams                 CorePIfIpAddr                                     IPV4                                                  3                    "1.0.0.1"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {p_router_ipv4_prefix_len                         VpnRfc2547GenParams                 CorePIfPrefixLength                               NUMERIC                                               3                    24                      1-30                  true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {pe_router_num_per_subif                          VpnRfc2547GenParams                 CorePePerSubIf                                    NUMERIC                                               3                    1                       1-10000               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {pe_router_id_start                               VpnRfc2547GenParams                 CorePeLoopbackIpAddr                              IPV4                                                  3                    "10.0.0.2"              _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {pe_router_id_step                                VpnRfc2547GenParams                 CorePeLoopbackIpAddrStep                          IPV4                                                  3                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_enable                       VpnRfc2547GenParams                 CoreRouteReflectorEnable                          {CHOICES true false}                                  2                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_per_subif                    VpnRfc2547GenParams                 CoreRouteReflectorPerSubIf                        NUMERIC                                               4                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_per_pe                       VpnRfc2547GenParams                 CoreRouteReflectorPerPe                           NUMERIC                                               4                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_id_start                     VpnRfc2547GenParams                 CoreRouteReflectorLoopbackIpAddr                  IPV4                                                  4                    "7.7.7.7"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_id_step                      VpnRfc2547GenParams                 CoreRouteReflectorLoopbackIpAddrStep              IPV4                                                  4                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_cluster_id                   VpnRfc2547GenParams                 CoreRouteReflectorClusterId                       IPV4                                                  4                    "0.0.0.0"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_cluster_id_step              VpnRfc2547GenParams                 CoreRouteReflectorClusterIdStep                   IPV4                                                  4                    "0.0.0.1"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_ids                          VpnRfc2547GenParams                 CoreRouteReflectorIds                             IPV4                                                  4                    "0.0.0.0"               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {bgp_route_reflector_mode                         VpnRfc2547GenParams                 CoreRouteReflectorMode                            {CHOICES stc_as_rr dut_as_rr}                         3                    stc_as_rr               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {stc_as_rr "STC_AS_RR" dut_as_rr "DUT_AS_RR"}}
        {bgp_bfd_enable                                   VpnRfc2547GenParams                 CoreEnableBfdForBgp                               {CHOICES true false}                                  3                    0                       _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {vrf_count                                        VpnRfc2547GenParams                 VpnCount                                          NUMERIC                                               3                    10                      1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {vrf_rd_assignment                                VpnRfc2547GenParams                 VpnRouteDistinguisherAssignment                   {CHOICES use_rt manual}                               3                    use_rt                  _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {use_rt "USE_RT" manual "MANUAL"}}
        {vrf_route_target_start                           VpnRfc2547GenParams                 VpnRouteTarget                                    ANY                                                   3                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {vrf_route_target_step                            VpnRfc2547GenParams                 VpnRouteTargetStep                                ANY                                                   3                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_vrf_assignment                           VpnRfc2547GenParams                 CustCeVpnAssignment                               {CHOICES round_robin sequential}                      3                    round_robin             _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {round_robin "ROUND_ROBIN" sequential "SEQUENTIAL"}}
        {cust_ce_routing_protocol                         VpnRfc2547GenParams                 CustCeRoutingProtocol                             {CHOICES bgp ospf rip isis mixed}                    3                    bgp                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {bgp "BGP" ospf "OSPF" rip "RIP" isis "ISIS" static_route "STATIC_ROUTES" mixed "MIXED"}}
        {cust_ce_bgp_percent                              VpnRfc2547GenParams                 CustCeBgpPercent                                  NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_rip_percent                              VpnRfc2547GenParams                 CustCeRipPercent                                  NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_ospf_percent                             VpnRfc2547GenParams                 CustCeOspfPercent                                 NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_isis_percent                             VpnRfc2547GenParams                 CustCeIsisPercent                                 NUMERIC                                               4                    0                       0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_as                                   VpnRfc2547GenParams                 CustCeBgpAs                                       NUMERIC                                               5                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_as_step_per_ce_enable                VpnRfc2547GenParams                 CustCeBgpAsStepPerCeEnable                        {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_as_step_per_ce                       VpnRfc2547GenParams                 CustCeBgpAsStepPerCe                              NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_as_step_per_vrf_enable               VpnRfc2547GenParams                 CustCeBgpAsStepPerVpnEnable                       {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_as_step_per_vrf                      VpnRfc2547GenParams                 CustCeBgpAsStepPerVpn                             NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as_enable                      VpnRfc2547GenParams                 CustCeBgp4ByteAsEnable                            {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as                             VpnRfc2547GenParams                 CustCeBgp4ByteAs                                  ANY                                                   6                    1:1                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_ce_enable          VpnRfc2547GenParams                 CustCeBgp4ByteAsStepPerCeEnable                   {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_ce                 VpnRfc2547GenParams                 CustCeBgp4ByteAsStepPerCe                         NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_vrf_enable         VpnRfc2547GenParams                 CustCeBgp4ByteAsStepPerVpnEnable                  {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_bgp_4byte_as_step_per_vrf                VpnRfc2547GenParams                 CustCeBgp4ByteAsStepPerVpn                        NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {customer_ce_static_route_percent                 VpnRfc2547GenParams                 CustCeStaticRoutePercent                          NUMERIC                                               6                    0                       0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_rd_start                                    VpnRfc2547GenParams                 CustRouteDistinguisher                            ANY                                                   5                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_rd_step_per_vrf_enable                      VpnRfc2547GenParams                 CustRouteDistinguisherStepPerVpnEnable            {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_rd_step_per_vrf                             VpnRfc2547GenParams                 CustRouteDistinguisherStepPerVpn                  ANY                                                   6                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_rd_step_per_ce_enable                       VpnRfc2547GenParams                 CustRouteDistinguisherStepPerCeEnable             {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_rd_step_per_ce                              VpnRfc2547GenParams                 CustRouteDistinguisherStepPerCe                   ANY                                                   6                    0:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_pe_vrf_assignment                       VpnRfc2547GenParams                 ProviderPeVpnAssignment                           {CHOICES vpn_per_pe pe_per_vpn}                       5                    vpn_per_pe              _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {vpn_per_pe "VPNS_PER_PE" pe_per_vpn "PES_PER_VPN"}}
        {provider_pe_vrf_count                            VpnRfc2547GenParams                 ProviderPeLspCount                                NUMERIC                                               6                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_pe_vrf_all_assign                       VpnRfc2547GenParams                 CorePeVpnAll                                      {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as_enable                        VpnRfc2547GenParams                 CoreCeBgpAsEnable                                 {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as                               VpnRfc2547GenParams                 CoreCeBgpAs                                       NUMERIC                                               6                    1                       1-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as_step_per_ce_enable            VpnRfc2547GenParams                 CoreCeBgpAsStepPerCeEnable                        {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as_step_per_ce                   VpnRfc2547GenParams                 CoreCeBgpAsStepPerCe                              NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as_step_per_vrf_enable           VpnRfc2547GenParams                 CoreCeBgpAsStepPerVpnEnable                       {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_as_step_per_vrf                  VpnRfc2547GenParams                 CoreCeBgpAsStepPerVpn                             NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as_enable                  VpnRfc2547GenParams                 CoreCeBgp4ByteAsEnable                            {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as                         VpnRfc2547GenParams                 CoreCeBgp4ByteAs                                  ANY                                                   6                    1:1                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_ce_enable      VpnRfc2547GenParams                 CoreCeBgp4ByteAsStepPerCeEnable                   {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_ce             VpnRfc2547GenParams                 CoreCeBgp4ByteAsStepPerCe                         NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_vrf_enable     VpnRfc2547GenParams                 CoreCeBgp4ByteAsStepPerVpnEnable                  {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_ce_bgp_4byte_as_step_per_vrf            VpnRfc2547GenParams                 CoreCeBgp4ByteAsStepPerVpn                        NUMERIC                                               6                    1                       0-65535               true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_rd_start                                VpnRfc2547GenParams                 CoreRouteDistinguisher                            ANY                                                   5                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_rd_step_per_vrf_enable                  VpnRfc2547GenParams                 CoreRouteDistinguisherStepPerVpnEnable            {CHOICES true false}                                  5                    true                    _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_rd_step_per_vrf                         VpnRfc2547GenParams                 CoreRouteDistinguisherStepPerVpn                  ANY                                                   6                    1:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_rd_step_per_ce_enable                   VpnRfc2547GenParams                 CoreRouteDistinguisherStepPerCeEnable             {CHOICES true false}                                  5                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_rd_step_per_ce                          VpnRfc2547GenParams                 CoreRouteDistinguisherStepPerCe                   ANY                                                   6                    0:0                     _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_vpn_route_start                             VpnRfc2547GenParams                 VpnCustRouteStart                                 IPV4                                                  7                    10.1.1.0                _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_vpn_route_overlap                           VpnRfc2547GenParams                 VpnCustRouteOverlap                               {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_vpn_route_prefix_len                        VpnRfc2547GenParams                 VpnCustRoutePrefixLength                          NUMERIC                                               7                    24                      1-32                  true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_vpn_route_step                              VpnRfc2547GenParams                 VpnCustRouteStep                                  NUMERIC                                               7                    1                       0-4294967295          true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {cust_ce_route_type                               VpnRfc2547GenParams                 CustCeRouteType                                   {CHOICES internal external}                           7                    internal                _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {internal "INTERNAL" external "EXTERNAL"}}
        {cust_route_count_per_ce                          VpnRfc2547GenParams                 CustRoutesPerCe                                   NUMERIC                                               7                     1                      1-2147483647          true             _none_                false           _none_                    {create mpls_ip_vpn_config }                    _none_}
        {provider_vpn_route_start                         VpnRfc2547GenParams                 VpnCoreRouteStart                                 IPV4                                                  7                    110.1.1.0               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_vpn_route_overlap                       VpnRfc2547GenParams                 VpnCoreRouteOverlap                               {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_vpn_route_prefix_len                    VpnRfc2547GenParams                 VpnCoreRoutePrefixLength                          NUMERIC                                               7                    24                      1-32                  true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_vpn_route_step                          VpnRfc2547GenParams                 VpnCoreRouteStep                                  NUMERIC                                               7                    1                       0-4294967295          true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {provider_route_count_per_ce                      VpnRfc2547GenParams                 CoreRoutesPerCe                                   NUMERIC                                               7                    1                       1-2147483647          true             _none_                false           _none_                    {create mpls_ip_vpn_config }                    _none_}
        {vrf_route_mpls_label_type                        VpnRfc2547GenParams                 VpnRouteMplsLabelType                             {CHOICES label_per_site label_per_route}              7                    label_per_site          _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {label_per_site "SITE" label_per_route "ROUTE"}}
        {vrf_route_mpls_label_start                       VpnRfc2547GenParams                 VpnRouteMplsLabelStart                            NUMERIC                                               7                    16                      1-1048575             true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {traffic_flow_direction                           VpnRfc2547GenParams                 TrafficFlow                                       {CHOICES cust_to_core core_to_cust bidirectional fully_meshed none }  7    bidirectional           _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {cust_to_core "customer_to_core" core_to_cust "core_to_customer" bidirectional "bidirectional" fully_meshed "fully_meshed"}}
        {traffic_pattern                                  VpnRfc2547GenParams                 TrafficPattern                                    {CHOICES one_to_one one_to_many}                      8                    one_to_many             _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {one_to_one "ONE_TO_ONE" one_to_many "ONE_TO_MANY"}}
        {traffic_stream_group_method                      VpnRfc2547GenParams                 StreamBlockGroupMethod                            {CHOICES aggregate vpn}                               7                    aggregate               _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     {aggregate "AGGREGATE" vpn "VPN"}}
        {traffic_use_single_stream_per_endpoint_pair      VpnRfc2547GenParams                 StreamBlockUseSingleStreamNumberPerEndpointPair   {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {traffic_load_percent_provider                    VpnRfc2547GenParams                 TrafficLoadPercentFromCorePorts                   NUMERIC                                               7                    10                      0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {traffic_load_percent_cust                        VpnRfc2547GenParams                 TrafficLoadPercentFromCustomerPorts               NUMERIC                                               7                    10                      0-100                 true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {enable_core_tunnel_lsp_ping                      VpnRfc2547GenParams                 EnableCoreTunnelLspPing                           {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {enable_vpn_tunnel_lsp_ping                       VpnRfc2547GenParams                 EnableVpnTunnelLspPing                            {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {enable_vpn_to_dut_tunnel_lsp_ping                VpnRfc2547GenParams                 EnableVpnToDutTunnelLspPing                       {CHOICES true false}                                  7                    false                   _none_                true             _none_                false           _none_                    {create mpls_ip_vpn_config}                     _none_}
        {lsp_ping_core_dst_addr                VpnLspPingGenIpv4CoreParams     DstAddr             IPV4        0       127.0.0.1   _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_interval           VpnLspPingGenIpv4CoreParams     PingInterval        NUMERIC     0           5       0-2147483647    TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_timeout            VpnLspPingGenIpv4CoreParams     PingTimeout         NUMERIC     0           2       1-65535            TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_ttl            VpnLspPingGenIpv4CoreParams     TimeToLive          NUMERIC     0         _none_    1-255           TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_exp_bits       VpnLspPingGenIpv4CoreParams     ExperimentalBits    NUMERIC     0           0       0-7             TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_validate_fec_stack      VpnLspPingGenIpv4CoreParams     ValidateFecStack    {CHOICES false true} 0         false       _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_enable_nil_fec_label    VpnLspPingGenIpv4CoreParams     EnableNilFecLabel   {CHOICES false true} 0         false       _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_pad_mode                VpnLspPingGenIpv4CoreParams     PadMode             {CHOICES request_copy_pad_tlv  request_drop_pad_tlv  no_pad_tlv}  0   no_pad_tlv  _none_  TRUE    _none_  FALSE   _none_   {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_core_pad_data                VpnLspPingGenIpv4CoreParams     PadData             ANY         0        _none_      _none_         TRUE       _none_       FALSE      _none_     {create lsp_ping_core_tunnel_config}    _none_}
        {lsp_ping_vpn_dst_addr                VpnLspPingGenIpv4VpnParams     DstAddr             IPV4        0       127.0.0.1   _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_interval           VpnLspPingGenIpv4VpnParams     PingInterval        NUMERIC     0           5       0-2147483647    TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_timeout            VpnLspPingGenIpv4VpnParams     PingTimeout         NUMERIC     0           2       1-65535            TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_ttl            VpnLspPingGenIpv4VpnParams     TimeToLive          NUMERIC     0         _none_    1-255           TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_exp_bits       VpnLspPingGenIpv4VpnParams     ExperimentalBits    NUMERIC     0           0       0-7             TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_validate_fec_stack      VpnLspPingGenIpv4VpnParams     ValidateFecStack    {CHOICES false true} 0         false       _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_enable_nil_fec_label    VpnLspPingGenIpv4VpnParams     EnableNilFecLabel   {CHOICES false true} 0         false       _none_          TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_pad_mode                VpnLspPingGenIpv4VpnParams     PadMode             {CHOICES request_copy_pad_tlv  request_drop_pad_tlv  no_pad_tlv}  0   no_pad_tlv  _none_  TRUE    _none_  FALSE   _none_   {create lsp_ping_vpn_tunnel_config}    _none_}
        {lsp_ping_vpn_pad_data                VpnLspPingGenIpv4VpnParams     PadData             ANY         0        _none_      _none_         TRUE       _none_       FALSE      _none_     {create lsp_ping_vpn_tunnel_config}    _none_}
     }
    {    emulation_mpls_ip_vpn_control
        {hname                        stcobj     stcattr           type                      priority          default        range       supported        dependency       mandatory    procfunc       mode       constants}
        {handle                       _none_     _none_            ANY                       2                _none_          _none_      true             _none_           false        _none_         _none_        _none_}
        {port_handle                  _none_     _none_            ANY                       2                _none_          _none_      true             _none_           false        _none_         _none_        _none_}
        {action                       _none_     _none_            {CHOICES start stop}      0                _none_          _none_      true             _none_           true         _none_         _none_        _none_}
    }
    {    emulation_mpls_ip_vpn_info 
        {hname                       stcobj       stcattr          type                                                  priority        default         range           supported     dependency        mandatory    procfunc        mode               constants}
        {port_handle                 _none_       _none_           ANY                                                   2               _none_          _none_          true          _none_            false        _none_          _none_             _none_}
        {handle                      _none_       _none_           ANY                                                   2               _none_          _none_          true          _none_            false        _none_          _none_             _none_}
        {mode                        _none_       _none_           {CHOICES rsvp|ldp|isis|ospfv2|ospfv3|bgp|rip|bfd|summary} 0           _none_          _none_          true          _none_            true         _none_          _none_             _none_}
    }
}