# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::multicast_group {
   set multicast_groupTable {
      ::sth::multicast_group::
      {emulation_multicast_group_config
         {hname               stcobj            stcattr            type                priority          default            range         supported         dependency        mandatory            procfunc            mode            constants         }
         {handle              _none_            _none_            ALPHANUM                10            _none_             _none_            true            _none_            false            <procName>            _none_            _none_         }
         {ip_addr_start       Ipv4NetworkBlock  StartIpList       IP                      100            224.0.0.0         _none_            true            _none_            false            <procName>            _none_            _none_         }
         {ip_addr_step        Ipv4NetworkBlock  AddrIncrement     NUMERIC                 100            1                 _none_            true            _none_            false            _none_               _none_            _none_         }
         {ip_prefix_len       Ipv4NetworkBlock  PrefixLength      NUMERIC                 100            32                1-128             true            _none_            false            <procName>            _none_            _none_         }
         {mode                _none_            _none_      {CHOICES create modify delete}   10          _none_            _none_            true            _none_            true            <procName>            _none_            _none_         }
         {num_groups          Ipv4NetworkBlock  NetworkCount      NUMERIC                 100            1                 1-65535           true            _none_            false            <procName>            _none_            _none_         }
         {pool_name           Ipv4Group         Name              ALPHANUM                100            _none_            _none_            true            _none_            false            <procName>            _none_            _none_         }
      }
      {emulation_multicast_source_config
         {hname            stcobj               stcattr           type                 priority       default            range         supported         dependency        mandatory         procfunc                mode            constants         }
         {handle           _none_               _none_            ANY                  100            _none_            _none_            true            _none_            false            _none_                  _none_            _none_         }
         {ip_addr_start    _none_               StartIpList       IP                   100            224.0.0.0         _none_            true            _none_            false            <procName>              _none_            _none_         }
         {ip_addr_step     Ipv4NetworkBlock     AddrIncrement     NUMERIC              100            1                 _none_            true            _none_            false            _none_                  _none_            _none_         }
         {ip_prefix_len    Ipv4NetworkBlock     PrefixLength      NUMERIC              100            24                1-128             true            _none_            false            <procName>              _none_            _none_         }
         {mode            _none_                _none_      {CHOICES create modify delete} 100        _none_            _none_            true            _none_            true             <procName>              _none_            _none_         }
         {num_sources      Ipv4NetworkBlock     NetworkCount      NUMERIC              100            1                 1-65535           true            _none_            false            <procName>              _none_            _none_         }
         {pool_name        Ipv4Group            Name              ALPHANUM             100            _none_            _none_            true            _none_            false            <procName>              _none_            _none_         }
      }
	  {emulation_mcast_wizard_config
        {hname                                stcobj                           stcattr  		      type                        priority         default        range         supported   dependency     mandatory   procfunc         mode                                          constants}
        {port_handle_upstream                 _none_                           _none_   		      ALPHANUM                           2              _none_         _none_          true       _none_         false         _none_        _none_                               	       _none_}
		{port_handle_downstream               _none_                           _none_   		      ALPHANUM                           2              _none_         _none_          true       _none_         false         _none_        _none_                               	       _none_}
		{handle                               _none_                           _none_   		      ALPHANUM                           2              _none_         _none_          true       _none_         false        _none_         _none_                               	       _none_}
        {mode                                 _none_                           _none_   		      {CHOICES create delete}       3              "create"        _none_         true       _none_         false        _none_         _none_                               	       _none_}	    
		{as_num						         McastUpstreamPortParams	       AsNum				  NUMERIC						3			   1              1-65535	      false	     _none_	        false	     _none_		    {create McastUpstreamPortParams}	       	   _none_}
		{mcast_protocol_upstream	         McastUpstreamPortParams	       MulticastProtocol	  {CHOICES none sm ssm}		    3			   sm	          _none_		  true		 _none_	        false	     _none_		    {create McastUpstreamPortParams}	       	   _none_}
	    {sub_if_upstream		             McastUpstreamPortParams	       SubIfEnable			  {CHOICES false true}          3              false	       _none_         true    	 _none_    	    false	     _none_		    {create McastUpstreamPortParams}	       	   _none_}
		{vlan_id_upstream                    McastUpstreamPortParams           VlanId                 NUMERIC                       3              1              1-4095          true       _none_         false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{igp_protocol				         McastUpstreamPortParams	       IgpProtocol		      {CHOICES none ospf isis bgp}  3              ospf	          _none_          true       _none_         false        _none_         {create McastUpstreamPortParams}	       	   _none_}
		{ipv4_prefix_len_upstream            McastUpstreamPortParams           Ipv4PrefixLength       NUMERIC                       3              24             1-32            true       _none_         false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{enable_bsr                          McastUpstreamPortParams           EnableBSR              {CHOICES true false}          3              flase          _none_          true       _none_         false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{mcast_encap_upstream                McastUpstreamPortParams           Encap                  {CHOICES ipv4 ipv6 ipv4v6}    3              ipv4           _none_          false       _none_        false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{ipv6_prefix_len_upstream            McastUpstreamPortParams           Ipv6PrefixLength       NUMERIC                       3              64             1-128           true       _none_         false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{sub_if_count_upstream		         McastUpstreamPortParams	       SubIfCount  		      NUMERIC                       3              1		      1-65535         false      _none_  		false		 _none_  	    {create McastUpstreamPortParams}      	       _none_}
		{vlan_id_step_upstream               McastUpstreamPortParams           VlanIdStep             NUMERIC                       3              1              1-4095          false      _none_         false        _none_         {create McastUpstreamPortParams}      	       _none_}
		{router_id_upstream 			     McastUpstreamPortParams 	       RouterId			      ANY						    3              192.85.1.2     _none_          true       _none_     	false   	 _none_      	{create McastUpstreamPortParams}      	       _none_} 		
		{ipv4_router_upstream		         McastUpstreamIpv4PortParams       RouterIp         	  IPV4                          3              192.85.1.2	  _none_          true       _none_     	false        _none_         {create McastUpstreamIpv4PortParams}  	       _none_}
		{ipv4_gw_addr_upstream               McastUpstreamIpv4PortParams	   Gateway                IPV4						    3              192.85.1.1     _none_      	  true       _none_   		false        _none_  	    {create McastUpstreamIpv4PortParams}  	       _none_}
		{ipv4_rp_addr_upstream               McastUpstreamIpv4PortParams       RpAddr                 IPV4                          3              192.0.2.0      _none_          true       _none_         false        _none_         {create McastUpstreamIpv4PortParams}  	       _none_}		
		{ipv6_gw_addr_upstream               McastUpstreamIpv6PortParams       Gateway                IPV6                          3              2000::1        _none_          true       _none_         false        _none_         {create McastUpstreamIpv6PortParams}  	       _none_}
		{ipv6_router_upstream                McastUpstreamIpv6PortParams       RouterIp               IPV6                          3              2000::2        _none_          true       _none_         false        _none_         {create McastUpstreamIpv6PortParams}  	       _none_}
		{ipv6_rp_addr_upstream               McastUpstreamIpv6PortParams       RpAddr                 IPV6                          3              2001:db8::1    _none_          true       _none_         false        _none_         {create McastUpstreamIpv6PortParams}  	       _none_}		
		{mcast_encap_downstream              McastDownstreamPortParams         Encap				  {CHOICES ipv4 ipv6 ipv4v6}    3              ipv4           _none_  		  false  	 _none_         false        _none_         {create McastDownstreamPortParams}  	       _none_}
		{hosts_routers_per_port	             McastDownstreamPortParams         HostsRoutersPerPort    NUMERIC 					    3              1              1-2000		  true       _none_         false        _none_         {create McastDownstreamPortParams}   	       _none_}
		{hosts_routers_per_vlan              McastDownstreamPortParams         HostsRoutersPerVlan    NUMERIC                       3              1              1-2000          true       _none_         false        _none_         {create McastDownstreamPortParams}   	       _none_}
		{ipv4_prefix_len_downstream          McastDownstreamPortParams         Ipv4PrefixLength       NUMERIC                       3              24             1-32            true       _none_         false        _none_         {create McastDownstreamPortParams}   	       _none_}
		{ipv6_prefix_len_downstream          McastDownstreamPortParams         Ipv6PrefixLength       NUMERIC                       3              64             1-128           true       _none_         false        _none_         {create McastDownstreamPortParams}   	       _none_}
		{sub_if_count_downstream             McastDownstreamPortParams         SubIfCount		      NUMERIC                       3              1              1-65535         true       _none_         false        _none_         {create McastDownstreamPortParams}   	       _none_}
		{sub_if_downstream                   McastDownstreamPortParams         SubIfEnable            {CHOICES false true}          3              false          _none_		  true		 _none_	        false	     _none_         {create McastDownstreamPortParams}	           _none_}
		{vlan_id_downstream                  McastDownstreamPortParams         VlanId			      NUMERIC                       3              1              1-4095          true       _none_         false        _none_         {create McastDownstreamPortParams}             _none_}
		{vlan_id_step_downstream             McastDownstreamPortParams         VlanIdStep             NUMERIC                       3              1              1-4095          true       _none_         false        _none_         {create McastDownstreamPortParams}             _none_}		
		{ipv4_gw_addr_downstream             McastDownstreamIpv4PortParams	   Gateway                IPV4						    3              192.85.1.1     _none_          true       _none_         false        _none_  	    {create McastDownstreamIpv4PortParams}     	   _none_}		
		{ipv4_mcast_protocol_downstream      McastDownstreamIpv4PortParams     MulticastProtocol  {CHOICES sm ssm igmp_v1 igmp_v2 igmp_v3} 3       igmp_v2        _none_          true       _none_         false        _none_         {create McastDownstreamIpv4PortParams}         _none_}		
		{ipv4_host_router_downstream         McastDownstreamIpv4PortParams     RouterIp               IPV4                          3              192.85.1.2     _none_          true       _none_         false        _none_         {create McastDownstreamIpv4PortParams}         _none_}		
		{ipv4_host_router_downstream_step    McastDownstreamIpv4PortParams     RouterStep             IPV4                          3              0.0.0.1        _none_          true       _none_         false        _none_         {create McastDownstreamIpv4PortParams}         _none_}		
		{ipv4_vlan_incr                      McastDownstreamIpv4PortParams     VlanIpIncr             IPV4                          3              0.0.1.0        _none_          true       _none_         false        _none_         {create McastDownstreamIpv4PortParams}         _none_}		
		{ipv6_gw_addr_downstream             McastDownstreamIpv6PortParams     Gateway                IPV6                          3              2000::1        _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}		
		{ipv6_mcast_protocol_downstream      McastDownstreamIpv6PortParams     MulticastProtocol  {CHOICES sm ssm mld_v1 mld_v2}    3              mld_v1         _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}
		{router_id_downstream                McastDownstreamIpv6PortParams     RouterId  			  ANY						    3              192.85.1.2     _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}		
		{ipv6_host_router_downstream         McastDownstreamIpv6PortParams     RouterIp  		      IPV6						    3              2000::2        _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}		
		{ipv6_host_router_downstream_step    McastDownstreamIpv6PortParams     RouterStep 			  IPV6						    3              ::1            _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}
		{ipv6_vlan_incr                      McastDownstreamIpv6PortParams     VlanIpIncr 			  IPV6						    3              ::0            _none_          true       _none_         false        _none_         {create McastDownstreamIpv6PortParams}         _none_}		
		{ipv4_base_group_addr                McastIpv4GroupParams              BaseGroupAddr 		  IPV4						    3       	   232.0.0.1      _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}
  		{ipv4_base_src_addr                  McastIpv4GroupParams              BaseSrcAddr 		      IPV4						    3       	   10.1.1.2       _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}		
  		{ipv4_base_group_addr_step           McastIpv4GroupParams              GroupAddrStep 		  IPV4						    3       	   0.0.0.1        _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}
  		{ipv4_base_src_addr_step              McastIpv4GroupParams             SrcAddrStep 		      IPV4						    3       	   0.0.1.0        _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}		
  		{ipv4_group_port_step                McastIpv4GroupParams              GroupPortStep		  IPV4						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}
  		{ipv4_group_vlan_step                McastIpv4GroupParams              GroupVlanStep		  IPV4						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}
  		{ipv4_src_port_step                  McastIpv4GroupParams              SrcPortStep 		      IPV4						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}
  		{ipv4_src_vlan_step                  McastIpv4GroupParams              SrcVlanStep  		  IPV4						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv4GroupParams}                  _none_}	
		{ipv6_base_group_addr                McastIpv6GroupParams              BaseGroupAddr 		  IPV6						    3       	   ff1e::1        _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
  		{ipv6_base_src_addr                  McastIpv6GroupParams              BaseSrcAddr 		      IPV6						    3       	   2000::1        _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}		
  		{ipv6_base_group_addr_step           McastIpv6GroupParams              GroupAddrStep 		  IPV6						    3       	   ::0:1          _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
  		{ipv6_base_src_addr_step             McastIpv6GroupParams              SrcAddrStep 		      IPV6						    3       	   ::0:1          _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
  		{ipv6_group_port_step                McastIpv6GroupParams              GroupPortStep		  IPV6						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
  		{ipv6_group_vlan_step                McastIpv6GroupParams              GroupVlanStep		  IPV6						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
 		{ipv6_src_port_step                  McastIpv6GroupParams              SrcPortStep 		      IPV6						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}
  		{ipv6_src_vlan_step                  McastIpv6GroupParams              SrcVlanStep 		      IPV6						    3       	   _none_         _none_          true       _none_         false        _none_         {create McastIpv6GroupParams}                  _none_}  		
		{create_traffic                      McastGenParams                    CreateTraffic 	      {CHOICES false true}          3              true           _none_		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}		
  		{filter_mode                         McastGenParams                    FilterMode 	          {CHOICES include exclude}     3              include        _none_		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}		
  		{traffic_frame_size                  McastGenParams                    FrameSize 	          NUMERIC                       3              1280           12-16383   	  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}
  		{groups_per_host                     McastGenParams                    GroupsPerHost 	      NUMERIC                       3              1              1-2000	      true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}		
  		{hosts_rx_same_groups                McastGenParams                    HostsRxSameGroups 	  {CHOICES false true}          3              true           _none_		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}
  		{ip_version			                 McastGenParams                    IpVersion	          {CHOICES v4 v6}               3              v4             _none_		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}
  		{traffic_load                        McastGenParams                    Load		              NUMERIC                       3              10             0-100		      true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}		
  		{ports_rx_same_groups                McastGenParams                    PortsRxSameGroups	  {CHOICES false true}          3              true           _none_		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}		
  		{src_addr_count_per_host             McastGenParams                    SrcAddrCount	          NUMERIC                       3              1              1-2000		  true		 _none_	        false	     _none_         {create McastGenParams}	                       _none_}
	  }
   }
}
