namespace eval ::sth::openflow:: {
}
set ::sth::openflow::openflowTable {
    ::sth::openflow::
    {emulation_openflow_config
        {hname                          stcobj                  				stcattr                         type                                                priority        default       range           supported   dependency              mandatory   procfunc           mode            							 			constants}
        {handle                         _none_                  				_none_                          ALPHANUM                                            2               _none_        _none_          true        _none_                  false       _none_             _none_           											_none_}
        {mode                           _none_                  				_none_                      {CHOICES enable modify add delete}                             3               _none_        _none_          true        _none_                  true        _none_             _none_           											_none_}
        {count                          EmulatedDevice          				devicecount                     NUMERIC                                             3               10000         _none_          true        _none_                  false       _none_             _none_           											_none_}
        {barrier_request_timeout        OpenflowControllerProtocolConfig        BarrierRequestTimeout   		NUMERIC                                             3              _none_        _none_          true        _none_                  false       _none_    {enable controller_config modify controller_modify}           _none_}
        {connection_type                OpenflowControllerProtocolConfig        ConnectionType              {CHOICES passive_Tcp passive_Tcp_Tls}                   3              passive_Tcp    _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {enable_barrier                 OpenflowControllerProtocolConfig        EnableBarrierFlowUpdate          {CHOICES 0 1}                                      3               0            _none_          true        _none_                  false       _none_    {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
        {add_default_discovery          OpenflowControllerProtocolConfig        AddDefaultDiscoveryFlows         {CHOICES 0 1}                              		4                1            _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
        {add_flows_on_connect           OpenflowControllerProtocolConfig        AddFlowsOnConnect                {CHOICES 0 1}                                      4               _none_        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
        {add_meters_on_connect          OpenflowControllerProtocolConfig        AddMetersOnConnect            	 {CHOICES 0 1}                                      4               _none_        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
        {clear_flows_on_connect         OpenflowControllerProtocolConfig        ClearExistingFlowsOnConnect      {CHOICES 0 1}                                      4               _none_        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
		{clear_meters_on_connect        OpenflowControllerProtocolConfig        ClearExistingMetersOnConnect     {CHOICES 0 1}                                      4               _none_        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE}}
        {discovery_dstmacaddr           OpenflowControllerProtocolConfig        DiscoveryDstMacAddr               ANY                                               4               _none_        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {discovery_msg_interval         OpenflowControllerProtocolConfig        DiscoveryMsgTxInterval           NUMERIC                                            4               30            _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {desired_role                   OpenflowControllerProtocolConfig        DesiredRole                      {CHOICES equal master salve}                       4               equal         _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {desired_generation_id          OpenflowControllerProtocolConfig        DesiredGenerationId              NUMERIC                                            4               0             _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {openflow_version           	OpenflowControllerProtocolConfig        OpenflowVersion                  ANY                                                4              VERSION_1_0   _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {send_role_connect              OpenflowControllerProtocolConfig        SendRoleRequestOnConnect         {CHOICES 0 1}                                      4               0             _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}          {1 TRUE 0 FALSE}}
        {max_flow_rate                  OpenflowControllerProtocolConfig        MaxFlowRate                       NUMERIC                                           4               0             _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}          _none_}
        {tcp_port                       OpenflowControllerProtocolConfig        TcpPort                           NUMERIC                                           4              6633           _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
		{switch_dpid   	                 OpenflowSwitchConfig                   Dpid							  HEX                                               6               0             _none_          true        _none_                  false       calc_num  {enable switch_config modify switch_modify}         		    _none_}
		{switch_link_list                _none_                 				_none_                            ANY                                               5              _none_        _none_          true        _none_                  false       _none_    {enable switch_config modify switch_modify}       	        _none_}
		{flow_cmd_type                   OpenflowFlowBlock						CmdType							  ANY                                               7               add           _none_          true        _none_                  false       calc_num   {enable flowblock_config modify flowblock_modify}      		_none_}
		{flow_block_type				 OpenflowFlowBlock                      FlowBlockType                  {CHOICES bound custom flow_table_text}               7               bound         _none_          true        _none_                  false       calc_num   {enable flowblock_config modify flowblock_modify} 			_none_}
		{flow_switch_handle			     OpenflowFlowBlock                 AffiliatedOpenflowSwitch-targets	      ANY                                               8               _none_        _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify} 	     	_none_}
		{flow_table_text				 OpenflowFlowBlock                      FlowTableText                    ANY                                                8               _none_        _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify} 			_none_}
		{stream_ids				 		 OpenflowFlowBlock                   OpenflowTraffic-targets             ANY                							    8               _none_        _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify} 					_none_}
		{match_fields					 OpenflowFlowBlock                      MatchFields                	     ANY            								    8               _none_        _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify}   			_none_}
		{hard_timeout 					 OpenflowFlowBlock                      HardTimeout	                     NUMERIC                                            8               0             _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify} 				_none_}
		{idle_timeout  				     OpenflowFlowBlock                      IdleTimeout	                     NUMERIC                                            8               0             _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify} 					_none_}
        {custom_match_field              OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_match_config modify custom_flowblock_match_modify}            _none_}
        {custom_action_field             OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_action_config modify custom_flowblock_action_modify}            _none_}
        {custom_goto_table_field         OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_goto_table_config modify custom_flowblock_goto_table_modify}            _none_}
        {custom_metadata_field           OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_metadata_config modify custom_flowblock_metadata_modify}            _none_}
        {custom_write_action_field       OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_write_action_config modify custom_flowblock_write_action_modify}            _none_}
        {custom_clear_action_field       OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_clear_action_config modify custom_flowblock_clear_action_modify}            _none_}
        {custom_meter_field              OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_meter_config modify custom_flowblock_meter_modify}            _none_}
        {custom_exp_field                OpenflowFlowBlock                      FrameConfig                      ANY                                                8              _none_         _none_          true        _none_                  false       calc_num   {enable custom_flowblock_exp_config modify custom_flowblock_exp_modify}            _none_}
        {transport_type				 	 OpenflowSwitchTransportConfig          TransportType					 ANY                      							8           Flow_Forward       _none_          true        _none_                 false       calc_num   {enable switch_transport_config modify switch_transport_modify} 					_none_}
		{first_vlan_id			 	     OpenflowSwitchTransportConfig          FirstVlanId				         NUMERIC                           	                8       		11             _none_          true        _none_                  false       _none_     {enable switch_transport_config modify switch_transport_modify} 					_none_}
		{action_type				 	 OpenflowFlowBoundTrafficAction         ActionType						ANY                          						8          forward_to_port    _none_          true        _none_                  false       calc_num   {enable bound_traffic_config modify bound_traffic_modify} 					_none_}		
		{modify_dst_device	             OpenflowFlowBoundTrafficAction         ModifyforDstDevice  			ANY                          						8              IPV4_ADDR      _none_          true        _none_                  false       _none_     {enable bound_traffic_config modify bound_traffic_modify} 					_none_}
		{meter_id                        OpenflowMeterConfig         			MeterId	  			    		NUMERIC                   						    7              1              _none_          true        _none_                  false       calc_num   {enable meter_config modify meter_modify} 					_none_}
		{enable_burst_size               OpenflowMeterConfig         			EnableBurstSize	  			    ALPHANUM                   						    7              0              _none_          true        _none_                  false       _none_     {enable meter_config modify meter_modify} 					_none_}
		{rate_type                       OpenflowMeterConfig         			RateType	  			    	{CHOICES pktps kbps}                   				7              pktps          _none_          true        _none_                  false       _none_     {enable meter_config modify meter_modify} 					_none_}
		{meter_switch_handle			 OpenflowMeterConfig                 AffiliatedOpenflowSwitch-targets	ANY                                                 8               _none_        _none_          true        _none_                  false       _none_     {enable meter_config modify meter_modify} 	     			_none_}
		{band_type 					     OpenflowMeterBandConfig               Type			                   {CHOICES Dscp_Remark Experimenter Drop}               9              Drop           _none_          true        _none_                  false       calc_num   {enable meter_band_config modify meter_band_modify} 					_none_}
		{burst_size 					 OpenflowMeterBandConfig               BurstSize			            NUMERIC                   						    9              0              _none_          true        _none_                  false       _none_     {enable meter_band_config modify meter_band_modify} 					_none_}
		{rate 					         OpenflowMeterBandConfig               Rate			            		NUMERIC                   						    9              100              _none_          true        _none_                  false       _none_     {enable meter_band_config modify meter_band_modify} 					_none_}
		{experimenter 					 OpenflowMeterBandConfig               Experimenter			            NUMERIC                   						    9              0              _none_          true        _none_                  false       _none_     {enable meter_band_config modify meter_band_modify} 					_none_}
		{precedence_level				 OpenflowMeterBandConfig               PrecLevel		                NUMERIC                   						    9              0              _none_          true        _none_                  false       _none_     {enable meter_band_config modify meter_band_modify} 					_none_}
        
        {add_group_entries_on_connect                 OpenflowControllerProtocolConfig        AddGroupEntriesOnConnect                           {CHOICES 0 1 true false TRUE FALSE}               4              true           _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE true TRUE false FALSE TRUE TRUE FALSE FALSE}}
        {clear_existing_group_entries_on_connect      OpenflowControllerProtocolConfig        ClearExistingGroupEntriesOnConnect                 {CHOICES 0 1 true false TRUE FALSE}               4              true           _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE true TRUE false FALSE TRUE TRUE FALSE FALSE}}
        {controller_certificate                       OpenflowControllerProtocolConfig        ControllerCertificate                              ANY                                               4              _none_         _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {controller_private_key                       OpenflowControllerProtocolConfig        ControllerPrivateKey                               ANY                                               4              _none_         _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {dynamic_load                                 OpenflowControllerProtocolConfig        DynamicLoad                                        NUMERIC                                           4              30             1-1000000       true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {enable_reactive_mode                         OpenflowControllerProtocolConfig        EnableReactiveMode                                 {CHOICES 0 1 true false TRUE FALSE}               4              false          _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE true TRUE false FALSE TRUE TRUE FALSE FALSE}}
        {endpoint_connection_pattern                  OpenflowControllerProtocolConfig        EndpointConnectionPattern                          {CHOICES pair backbone_src_first backbone_dst_first backbone_interleaved}       4               pair        _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        {send_set_async_on_connect                    OpenflowControllerProtocolConfig        SendSetAsyncOnConnect                              {CHOICES 0 1 true false TRUE FALSE}               4              false         _none_          true        _none_                   false       _none_   {enable controller_config modify controller_modify}           {1 TRUE 0 FALSE true TRUE false FALSE TRUE TRUE FALSE FALSE}}
        {switch_ca_certificates                       OpenflowControllerProtocolConfig        SwitchCaCertificates                               ANY                                               4              _none_         _none_          true        _none_                  false       _none_   {enable controller_config modify controller_modify}           _none_}
        
        {cookie                               OpenflowFlowBlock                      Cookie                         NUMERIC                                           8              0            _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify}             _none_}
        {cookie_mask                          OpenflowFlowBlock                      CookieMask                     NUMERIC                                           8              0            _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify}             _none_}
        {flags                                OpenflowFlowBlock                      Flags                          HEX                                               8              1            _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify}             _none_}
        {strict_match                         OpenflowFlowBlock                      StrictMatch                    {CHOICES 0 1 true false TRUE FALSE}               8             true          _none_          true        _none_                  false       _none_     {enable flowblock_config modify flowblock_modify}             {1 TRUE 0 FALSE true TRUE false FALSE TRUE TRUE FALSE FALSE}}

        {flow_removed_mask_master_equal              OpenflowSetAsyncMessageConfig                      FlowRemovedMaskMasterEqual            HEX                8              "0xF"          _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}
        {flow_removed_mask_slave                     OpenflowSetAsyncMessageConfig                      FlowRemovedMaskSlave                  HEX                8              0              _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}
        {packet_in_mask_master_equal                 OpenflowSetAsyncMessageConfig                      PacketInMaskMasterEqual               HEX                8              3              _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}
        {packet_in_mask_slave                        OpenflowSetAsyncMessageConfig                      PacketInMaskSlave                     HEX                8              0              _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}
        {port_status_mask_master_equal               OpenflowSetAsyncMessageConfig                      PortStatusMaskMasterEqual             HEX                8              7              _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}
        {port_status_mask_slave                      OpenflowSetAsyncMessageConfig                      PortStatusMaskSlave                   HEX                8              7              _none_          true        _none_                  false       _none_     {enable async_msg_config modify async_msg_config}             _none_}

        {group_id                 OpenflowGroupEntryConfig                      GroupId             NUMERIC                8              1          _none_          true        _none_                  false       calc_num     {enable group_entry_config modify group_entry_modify}             _none_}
        {group_type               OpenflowGroupEntryConfig                      GroupType           {CHOICES all indirect select fast_failover}      8              all          _none_          true        _none_                  false       calc_num     {enable group_entry_config modify group_entry_modify}             _none_}
		{group_switch_handle      OpenflowGroupEntryConfig                 AffiliatedOpenflowSwitch-targets	ANY            8               _none_        _none_          true        _none_                  false       _none_     {enable group_entry_config modify group_entry_modify} 	     			_none_}

        {watch_group               OpenflowGroupActionBucketConfig                      WatchGroup       HEX          8              "0xFFFFFFFF"          _none_          true        _none_                  false       calc_num     {enable group_action_bucket_config modify group_action_bucket_modify}             _none_}
        {watch_port                OpenflowGroupActionBucketConfig                      WatchPort        HEX          8              "0xFFFFFFFF"          _none_          true        _none_                  false       calc_num     {enable group_action_bucket_config modify group_action_bucket_modify}             _none_}
        {weight                    OpenflowGroupActionBucketConfig                      Weight           NUMERIC      8                0                   _none_          true        _none_                  false       calc_num     {enable group_action_bucket_config modify group_action_bucket_modify}             _none_}

        {controller_max_length            OpenflowGroupActionSetConfig              ControllerMaxLength                     NUMERIC                10   65535   _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {decrement_ttl_type               OpenflowGroupActionSetConfig              DecrementTtlType                        ANY                    10         decrement_ip_ttl _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {group_action_type                OpenflowGroupActionSetConfig              GroupActionType                         ANY                     10       output _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {output_group_id                  OpenflowGroupActionSetConfig              OutputGroupId                           NUMERIC                 10       1 _none_          true        _none_                  false       calc_num     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {output_port_action_type          OpenflowGroupActionSetConfig              OutputPortActionType                    {CHOICES port_num all controller table in_port any local normal flood}      10         port_num _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {output_port_number               OpenflowGroupActionSetConfig              OutputPortNumber                        NUMERIC              10    1 _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {pop_mpls_tag_data_ethertype      OpenflowGroupActionSetConfig              PopMplsTagDataEthertype                 HEX               10       0x8847 _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {pop_tag                          OpenflowGroupActionSetConfig              PopTag                                  ANY               10       pop_vlan_header  _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {push_mpls_tag_data_ethertype     OpenflowGroupActionSetConfig              PushMplsTagDataEthertype                HEX               10      0x8847                _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {push_pbb_tag_data_ethertype      OpenflowGroupActionSetConfig              PushPbbTagDataEthertype                 HEX               10      0x88e7                _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {push_vlan_tag_data_ethertype     OpenflowGroupActionSetConfig              PushVlanTagDataEthertype                HEX               10      0x8100                _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_arp_dst_hw_addr              OpenflowGroupActionSetConfig              SetArpDstHwAddr                         MAC               10      "00:10:01:00:00:01"     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_arp_dst_ipv4_addr            OpenflowGroupActionSetConfig              SetArpDstIpv4Addr                       IPV4              10      20.0.0.1              _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_arp_opcode                   OpenflowGroupActionSetConfig              SetArpOpcode                            NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_arp_src_hw_addr              OpenflowGroupActionSetConfig              SetArpSrcHwAddr                         MAC               10      "00:20:01:00:00:01"     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_arp_src_ipv4_addr            OpenflowGroupActionSetConfig              SetArpSrcIpv4Addr                       IPV4              10      10.0.0.1              _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_eth_dst                      OpenflowGroupActionSetConfig              SetEthDst                               MAC               10      "00:10:01:00:00:01"     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_eth_src                      OpenflowGroupActionSetConfig              SetEthSrc                               MAC               10      "00:20:01:00:00:01"     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_eth_type                     OpenflowGroupActionSetConfig              SetEthType                              HEX               10      0x8100                _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_icmpv4_code                  OpenflowGroupActionSetConfig              SetIcmpv4Code                           NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_icmpv4_type                  OpenflowGroupActionSetConfig              SetIcmpv4Type                           NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_icmpv6_code                  OpenflowGroupActionSetConfig              SetIcmpv6Code                           NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_icmpv6_type                  OpenflowGroupActionSetConfig              SetIcmpv6Type                           NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ip_dscp                      OpenflowGroupActionSetConfig              SetIpDscp                               NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ip_ecn                       OpenflowGroupActionSetConfig              SetIpEcn                                NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ip_proto                     OpenflowGroupActionSetConfig              SetIpProto                              NUMERIC           10      6                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv4_dst                     OpenflowGroupActionSetConfig              SetIpv4Dst                              IPV4              10      10.0.0.2              _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv4_fields                  OpenflowGroupActionSetConfig              SetIpv4Fields                           ANY               10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv4_src                     OpenflowGroupActionSetConfig              SetIpv4Src                              IPV4              10      10.0.0.1              _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_dst                     OpenflowGroupActionSetConfig              SetIpv6Dst                              IPV6              10      2000::1               _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_fields                  OpenflowGroupActionSetConfig              SetIpv6Fields                           ANY               10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_flabel                  OpenflowGroupActionSetConfig              SetIpv6Flabel                           NUMERIC           10      0                     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_nd_sll                  OpenflowGroupActionSetConfig              SetIpv6NdSll                            MAC               10      "00:00:01:00:00:01"   _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_nd_target               OpenflowGroupActionSetConfig              SetIpv6NdTarget                         IPV6              10      2000::1               _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_nd_tll                  OpenflowGroupActionSetConfig              SetIpv6NdTll                            MAC               10      "00:00:01:00:00:01"   _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_ipv6_src                     OpenflowGroupActionSetConfig              SetIpv6Src                              IPV6              10      2000::10              _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_l2_fields                    OpenflowGroupActionSetConfig              SetL2Fields                             ANY               10       0                    _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_mpls_bos_bit                 OpenflowGroupActionSetConfig              SetMplsBosBit                           {CHOICES 0 1 true false}    10           false  _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_mpls_label                   OpenflowGroupActionSetConfig              SetMplsLabel                            NUMERIC          10       0x8100   _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_mpls_tc                      OpenflowGroupActionSetConfig              SetMplsTc                               NUMERIC          10       0        _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_pbb_isid                     OpenflowGroupActionSetConfig              SetPbbIsid                              NUMERIC          10       0        _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_queue_id                     OpenflowGroupActionSetConfig              SetQueueId                              NUMERIC          10       1        _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_sctp_dst                     OpenflowGroupActionSetConfig              SetSctpDst                              NUMERIC          10       100      _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_sctp_src                     OpenflowGroupActionSetConfig              SetSctpSrc                              NUMERIC          10       100      _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_tcp_dst                      OpenflowGroupActionSetConfig              SetTcpDst                               NUMERIC          10       0000     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_tcp_src                      OpenflowGroupActionSetConfig              SetTcpSrc                               NUMERIC          10       0000     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_tunnel_id                    OpenflowGroupActionSetConfig              SetTunnelId                             NUMERIC          10       0        _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_udp_dst                      OpenflowGroupActionSetConfig              SetUdpDst                               NUMERIC          10       0000     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_udp_src                      OpenflowGroupActionSetConfig              SetUdpSrc                               NUMERIC          10       0000     _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_vlan_id                      OpenflowGroupActionSetConfig              SetVlanId                               NUMERIC          10       100      _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        {set_vlan_priority                OpenflowGroupActionSetConfig              SetVlanPriority                         NUMERIC          10       0        _none_          true        _none_                  false       _none_     {enable group_action_set_config modify group_action_set_modify}             _none_}
        
        {rm_switch_handle_list            OpenflowReactiveModeRuleConfig            AffiliatedOpenflowSwitch-targets        ANY          4       _none_        _none_          true        _none_                  false       _none_     {enable rm_config modify rm_modify}               _none_}
        {rm_action_field                  OpenflowReactivePacketOutActions          FrameConfig                             ANY          4       _none_        _none_          true        _none_                  false       _none_     {enable rm_action_config modify rm_action_modify} _none_}
        {rm_match_field                   OpenflowReactiveMatchFields               FrameConfig                             ANY          4       _none_        _none_          true        _none_                  false       _none_     {enable rm_match_config modify rm_match_modify}   _none_}
    }
    {   emulation_openflow_control
        {hname                          stcobj                 				 stcattr                          type                                                               priority          default      range           supported   dependency              mandatory   procfunc                       mode                  constants}
        {port_handle                    _none_                  			  _none_                          ALPHANUM                                                             2               _none_        _none_          true        _none_                  false       _none_                         _none_                 _none_}
        {handle                         _none_                  			  _none_                          ALPHANUM                                                             2               _none_        _none_          true        _none_                  false       _none_                         _none_                 _none_}
        {switch_handles                 _none_                  			  _none_                          ALPHANUM                                                             3               _none_        _none_          true        _none_                  false       _none_                         _none_                 _none_}
        {file_path                      _none_                                _none_                          ANY                                                                  3               _none_        _none_          true        _none_                  false       _none_                         _none_                 _none_}
        {action                         _none_                  			  _none_   {CHOICES start_controller stop_controller start_discovery stop_discovery update_switch add_flows remove_flows add_meters remove_meters \
        add_group_entries verify_discovery modify_flows modify_group_entries modify_meters remove_group_entries send_barrier_req send_controller_req send_feature_req send_get_async_req send_set_async_req manage_tls_files \
        view_meter_features view_table_stats view_table_features view_port_stats view_port_description view_switch_description view_individual_flow view_aggregate_flow view_group_stats}     3          start_controller   _none_          true        _none_                  true        _none_                         _none_                 _none_}
        {gen_id_list                    OpenflowRoleRequestCommand            GenerationIdList                NUMERIC                                     4         _none_         _none_          true        _none_                  false        _none_                         {enable control_req}   _none_}
        {role                           OpenflowRoleRequestCommand            RoleList                        {CHOICES nochange equal master slave}       4         _none_         _none_          true        _none_                  false        _none_                         {enable control_req}   _none_}
        {flow_remove_mask_master_list   OpenflowSetAsyncMessageCommand        FlowRemovedMaskMasterEqualList  ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {flow_remove_mask_slave_list    OpenflowSetAsyncMessageCommand        FlowRemovedMaskSlaveList        ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {packet_in_mask_master_list     OpenflowSetAsyncMessageCommand        PacketInMaskMasterEqualList     ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {packet_in_mask_slave_list      OpenflowSetAsyncMessageCommand        PacketInMaskSlaveList           ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {port_status_mask_master_list   OpenflowSetAsyncMessageCommand        PortStatusMaskMasterEqualList   ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {port_status_mask_slave_list    OpenflowSetAsyncMessageCommand        PortStatusMaskSlaveList         ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable async_set_req} _none_}
        {tls_file_action                _none_                                _none_                          {CHOICES upload delete}                     4         _none_         _none_          true        _none_                  false        _none_                         {enable manage_tls_files} _none_}
        {tls_file_name_list             _none_                                FileNameList                    ANY                                         4         _none_         _none_          true        _none_                  false       _none_                          {enable manage_tls_files} _none_}
        {tls_file_type                  _none_                                FileType                        {CHOICES private_key certificate ca_certificate}  4   certificate    _none_          true        _none_                  false        _none_                         {enable manage_tls_files} _none_}
        {all_groups                     OpenflowViewGroupStatisticsCommand    AllGroups                       {CHOICES true false}                                                  3             true         _none_             true        _none_                  false       _none_          {enable group_stats_set}                 _none_}
        {export_stats                   OpenflowExportStats                   ExportStatistics                {CHOICES true false}                                                  3             false        _none_             true        _none_                  false       _none_          {enable export_file_set}                 _none_}
        {file_prefix                    OpenflowExportStats                   ExportFilePrefix                ANY                                                                   3             _none_       _none_             true        _none_                  false       _none_          {enable export_file_set}                 _none_}
        {group_id                       OpenflowViewGroupStatisticsCommand    GroupId                         NUMERIC                                                               3             0            0-4294967295       true        _none_                  false       _none_          {enable group_stats_set}                 _none_}
        {save_archive                   OpenflowExportStats                   SaveAsArchive                   {CHOICES true false}                                                  3             false        _none_             true        _none_                  false       _none_          {enable export_file_set}                 _none_}
        {save_single_file               OpenflowExportStats                   SaveStatisticsToSingleFile      {CHOICES true false}                                                  3             false        _none_             true        _none_                  false       _none_          {enable export_file_set}                 _none_}
        {max_entries                    OpenflowExportStats                   MaxEntries                      NUMERIC                                                               3             5000         1-4294967295       true        _none_                  false       _none_          {enable export_file_set}                 _none_}
        {all_tables                     OpenflowViewstatsCommand              AllTables                       {CHOICES true false}                                                  3             true         _none_             true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {all_output_ports               OpenflowViewstatsCommand              AllOutPorts                     {CHOICES true false}                                                  3             true         _none_             true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {all_output_groups              OpenflowViewstatsCommand              AllOutGroups                    {CHOICES true false}                                                  3             true         _none_             true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {table_id                       OpenflowViewstatsCommand              TableId                         NUMERIC                                                               3             0            0-255              true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {output_port                    OpenflowViewstatsCommand              OutPort                         NUMERIC                                                               3             0            0-4294967295       true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {output_group                   OpenflowViewstatsCommand              OutGroup                        NUMERIC                                                               3             0            0-4294967295       true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {cookie                         OpenflowViewstatsCommand              Cookie                          NUMERIC                                                               3             0            0-4294967295       true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {cookie_mask                    OpenflowViewstatsCommand              CookieMask                      NUMERIC                                                               3             0            0-4294967295       true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
        {timeout                        OpenflowExportStats                   StatisticsRetrievalTimeout      NUMERIC                                                               3             30           1-65535            true        _none_                  false       _none_          {enable flow_stats_set}                  _none_}
    }                                                        
    {   emulation_openflow_stats
        {hname                          stcobj                  stcattr                          type                                                priority          default       range           supported   dependency              mandatory   procfunc             mode                                         constants}
        {port_handle                    _none_                  _none_                          ALPHANUM                                                2               _none_       _none_          true        _none_                  false       _none_              _none_                                          _none_}
        {handle                         _none_                  _none_                          ALPHANUM                                                2               _none_       _none_          true        _none_                  false       _none_              _none_                                          _none_}
        {mode                           _none_                  _none_                      {CHOICES controller switch_result switchport_result async_result reactive_mode_result all}    3    controller   _none_     true    _none_    false       _none_              _none_                                          _none_}
    }
    {emulation_openflow_switch_config
        {hname                           stcobj                  stcattr                          type                                                priority          default             range           supported   dependency                                                 mandatory   procfunc             mode                                                         constants}
        {handle                          _none_                  _none_                           ALPHANUM                                            2                 _none_              _none_          true        _none_                                                     true        _none_               _none_                                                       _none_}
        {mode                            _none_                  _none_                           {CHOICES enable modify disable}                     2                 _none_              _none_          true        _none_                                                     true        _none_               _none_                                                       _none_}
        {count                           EmulatedDevice          devicecount                      NUMERIC                                             3                 _none_              _none_          true        _none_                                                     false       _none_               _none_                                                       _none_}
        {openflow_version                OseSwitchConfig         OpenflowVersion                  ANY                                                 3                 version_1_3         _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {controller_ip_addr              OseSwitchConfig         ControllerIpAddrList             ANY                                                 3                 192.85.1.1          _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {tcp_port                        OseSwitchConfig         TcpPort                          NUMERIC                                             3                 6633                0-65535         true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {connection_type                 OseSwitchConfig         ConnectionType                   {CHOICES tcp tcp_tls }                              3                 tcp                 _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {switch_private_key              OseSwitchConfig         SwitchPrivateKey                 ANY                                                 4                 _none_              _none_          true        {connection_type tcp_tls}                                  false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {switch_certificate              OseSwitchConfig         SwitchCertificate                ANY                                                 4                 _none_              _none_          true        {connection_type tcp_tls}                                  false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {controller_ca_certificates      OseSwitchConfig         ControllerCaCertificates         ANY                                                 4                 _none_              _none_          true        {connection_type tcp_tls}                                  false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {switch_port_num                 OseSwitchConfig         BaseSwitchPortNum                NUMERIC                                             3                 4000                1-50000         true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {send_port_status_on_connect     OseSwitchConfig         SendPortStatusOnConnect          {CHOICES true false}                                3                 false               _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {dpid_start                      OseSwitchConfig         Dpid                             HEX                                                 3                 1                   _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {dpid_step                       OseSwitchConfig         DpidIncrement                    HEX                                                 3                 1                   _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {topo_type                       OseSwitchConfig         OseTopology                      {CHOICES linear ring grid spine_leaf full_mesh standalone}  5         linear              _none_          true        _none_                                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {switch_name                     OseSwitchConfig         SwitchName                       ANY                                                 6                 _none_              _none_          true        _none_                                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {topology_port_name              OseSwitchConfig         TopologyPortName                 ANY                                                 6                 topo_@b-@s-@x       _none_          true        _none_                                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {grid_row_count                  OseSwitchConfig         RowCount                         NUMERIC                                             6                 2                   2-255           true        {topo_type grid}                                           false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {edge_switches_count             OseSwitchConfig         NumEdgeSwitches                  NUMERIC                                             6                 2                   0-65535         true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {edge_switch_name                OseSwitchConfig         EdgeSwitchName                   ANY                                                 6                 _none_              _none_          true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {spine_switches_count            OseSwitchConfig         NumSpineSwitches                 NUMERIC                                             6                 2                   1-65535         true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {spine_switch_name               OseSwitchConfig         SpineSwitchName                  ANY                                                 6                 sp_@b-@s-@x         _none_          true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {leaf_switches_count             OseSwitchConfig         NumLeafSwitches                  NUMERIC                                             6                 4                   1-65535         true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {leaf_switch_name                OseSwitchConfig         LeafSwitchName                   ANY                                                 6                 lf_@b-@s-@x         _none_          true        {topo_type spine_leaf}                                     false       _none_               {enable osetopo_config modify osetopo_config}                _none_}
        {switch_port_mac_start           OseSwitchConfig         SwitchPortMacAddrStart           MAC                                                 6                 00:00:00:00:00:01   _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {configure_hosts                 OseSwitchConfig         ConfigureHosts                   {CHOICES true false}                                7                 false               _none_          true        _none_                                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {host_port_count                 OseSwitchConfig         HostCount                        NUMERIC                                             8                 1                   1-255           true        {configure_hosts true}                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {host_ip_start                   OseSwitchConfig         HostIpv4AddrStart                IPV4                                                8                 0.0.0.1             _none_          true        {configure_hosts true}                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {host_ip_step                    OseSwitchConfig         HostIpv4AddrIncr                 IPV4                                                8                 0.0.0.1             _none_          true        {configure_hosts true}                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {host_port_name                  OseSwitchConfig         HostPortName                     ANY                                                 8                 host_@b-@s-@x       _none_          true        {configure_hosts true}                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {use_switch_port_mac             OseSwitchConfig         UsePortMacAddr                   {CHOICES true false}                                8                 false               _none_          true        {configure_hosts true}                                     false       _none_               {enable osehost_config modify osehost_config}                _none_}
        {host_mac_start                  OseSwitchConfig         HostMacAddrStart                 MAC                                                 9                 00:10:00:00:00:01   _none_          true        {use_switch_port_mac false}                                false       _none_               {enable osehost_config modify osehost_config}                _none_}                           
        {configure_additional_switch_ports OseSwitchConfig       ConfigureAdditionalSwitchPorts   {CHOICES true false}                                6                 false               _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {addtional_switch_port_names     OseSwitchConfig         AdditionalSwitchPortNames        ANY                                                 6                 _none_              _none_          true        {configure_additional_switch_ports true}                   false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {traffic_enable                  OseSwitchConfig         trafficenable                    {CHOICES true false}                                11                false               _none_          true        _none_                                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {traffic_type                    OseSwitchConfig         TrafficTestType                  {CHOICES packet_in arp}                             11                packet_in           _none_          true        {traffic_enable true}                                      false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {defalute_table_miss_entry       OseSwitchConfig         OpenflowDefaultTableMissEntry    {CHOICES drop send_to_controller}                   11                send_to_controller  _none_          true        {traffic_enable false}                                     false       _none_               {enable oseswitch_config modify oseswitch_modify}            _none_}
        {customize_packet_in             OseTrafficConfig        CustomPacketInHostParams         {CHOICES true false}                                12                false               _none_          true        {traffic_type packet_in}                                   false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {dst_mac                         OseTrafficConfig        DestMacAddr                      MAC                                                 13                00:00:10:00:00:01   _none_          true        _none_                                                     false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {vlan_enable                     OseTrafficConfig        VlanTrafficEnable                {CHOICES true false}                                12                false               _none_          true        {traffic_type packet_in}                                   false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {vlan_id                         OseTrafficConfig        VlanId                           NUMERIC                                             3                 200                 0-4095          true        {vlan_enable true}                                         false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {ip_enable                       OseTrafficConfig        Ipv4TrafficEnable                {CHOICES true false}                                12                false               _none_          true        {traffic_type packet_in}                                   false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {dst_ip                          OseTrafficConfig        DestIpv4Addr                     IPV4                                                13                0.0.0.1             _none_          true        _none_                                                     false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {frame_mode                      OseTrafficConfig        TrafficMode                      {CHOICES continuous burst}                          12                continuous          _none_          true        _none_                                                     false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {frame_size                      OseTrafficConfig        TrafficFrameSize                 NUMERIC                                             13                1518                64-9014         true        {traffic_type packet_in}                                   false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {frame_per_second                OseTrafficConfig        TrafficFramesPerSecond           NUMERIC                                             13                1                   _none_          true        {traffic_type packet_in}                                   false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {frame_count                     OseTrafficConfig        FrameCount                       NUMERIC                                             13                1                   _none_          true        {traffic_frame_mode burst}                                 false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {configure_packet_in_param       OseTrafficConfig        UseSpirentPacketInParams         {CHOICES true false}                                12                false               _none_          true        {traffic_enable true}                                      false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {packet_in_reason                OseTrafficConfig        PacketInReason                   {CHOICES ofpr_no_match ofpr_action ofpr_invalid_ttl} 13               ofpr_no_match       _none_          true        {configure_packet_in_param true}                           false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {packat_in_table_id              OseTrafficConfig        TableId                          NUMERIC                                              13               0                   0-255           true        {configure_packet_in_param true}                           false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {end_point_map                   OseTrafficConfig        EndPointMapping                  {CHOICES one_to_many many_to_many many_to_one}      13                one_to_many         _none_          true        {traffic_type arp}                                         false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {arp_rate                        OseTrafficConfig        ArpRatePerSecond                 NUMERIC                                             13                1                   1-100           true        {traffic_type arp}                                         false       _none_               {enable osetraffic_config modify osetraffic_config}          _none_}
        {ose_flow_priority               OseGlobalParams         FlowPriority                     NUMERIC                                             13                65535               1-65535         true        _none_                                                     false       _none_               {enable oseglobalparams_config modify oseglobalparams_config}  _none_}
        {disable_echo_request            OseGlobalParams         DisableEchoRequest               {CHOICES true false}                                13                false               _none_          true        _none_                                                     false       _none_               {enable oseglobalparams_config modify oseglobalparams_config}  _none_}
        {echo_request_time               OseGlobalParams         EchoRequestTimer                 NUMERIC                                             13                5                   1-65000         true        _none_                                                     false       _none_               {enable oseglobalparams_config modify oseglobalparams_config}  _none_}
        {experimenter_support            OseGlobalParams         ExperimenterSupport              {CHOICES true false}                                13                false               _none_          true        _none_                                                     false       _none_               {enable oseglobalparams_config modify oseglobalparams_config}  _none_} 
    }
    {emulation_openflow_switch_control
        {hname                           stcobj                  stcattr                          type                                                priority          default            range           supported   dependency              mandatory   procfunc               mode                           constants}
        {port_handle                     _none_                  _none_                           ALPHANUM                                            2                 _none_             _none_          true        _none_                  false       _none_                _none_                          _none_}
        {handle                          _none_                  _none_                           ALPHANUM                                            2                 _none_             _none_          true        _none_                  false       _none_                _none_                          _none_}
        {file_path                       OseGetFlowsCommand      ExportFilePath                   ANY                                                 4                 _none_             _none_          true        _none_                  false       _none_                {enable get_flows}              _none_}
        {action                          _none_                  _none_                           {CHOICES start_ose stop_ose start_ose_traffic stop_ose_traffic break_link restore_link restore_all_links get_ose_flows manage_tls_files} 3 start_switch _none_ true _none_  true  _none_          _none_       _none_}
        {switch_number                   OseLinkCommand          SwitchIndex                      NUMERIC                                             4                 1                  1-65535         true        _none_                  false       _none_                {enable ose_link_command}       _none_} 
        {switch_type                     OseLinkCommand          SwitchType                       {CHOICES leaf_switch spine_switch edge_switch}      4                 leaf_switch        _none_          true        _none_                  false       _none_                {enable ose_link_command}       _none_}
        {port_type                       OseLinkCommand          PortType                         {CHOICES topology_port host_port}                   4                 topology_port      _none_          true        _none_                  false       _none_                {enable ose_link_command}       _none_}
        {port_number_list                OseLinkCommand          PortIndexList                    ANY                                                 4                 1                  _none_          true        _none_                  false       _none_                {enable ose_link_command}       _none_}
        {tls_file_action                _none_                   _none_                           {CHOICES upload delete}                             4                 _none_             _none_          true        _none_                  false       _none_                {enable manage_tls_files}       _none_}
        {tls_file_name_list             _none_                   FileNameList                     ANY                                                 4                 _none_             _none_          true        _none_                  false       _none_                {enable manage_tls_files}       _none_}
        {tls_file_type                  _none_                   FileType                         {CHOICES private_key certificate ca_certificate}    4                 certificate        _none_          true        _none_                  false       _none_                {enable manage_tls_files}       _none_}
	}
    {emulation_openflow_switch_stats
        {hname                          stcobj                  stcattr                          type                                                 priority          default              range           supported   dependency              mandatory   procfunc             mode                            constants}
        {port_handle                    _none_                  _none_                           ALPHANUM                                             2                 _none_               _none_          true        _none_                  false       _none_              _none_                           _none_}
        {handle                         _none_                  _none_                           ALPHANUM                                             2                 _none_               _none_          true        _none_                  false       _none_              _none_                           _none_}
        {mode                           _none_                  _none_                          {CHOICES controller_aggregate switch_results}         3                 controller_aggregate _none_          true        _none_                  false       _none_              _none_                           _none_}
    }
}
