# $Id: //TestCenter/4.81_rel/content/HltAPI/SourceCode/pppoxServerTable.tcl#1 $
# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

# Copyright (c) 2005 - 2007 Spirent Communications
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written consent of the copyright owner.
#

namespace eval ::sth::PppoxServer:: {
}

set ::sth::PppoxServer::pppoxServerTable {
   ::sth::PppoxServer::
   {pppox_server_config
      {hname                            stcobj                    stcattr                       type                                                  priority        default           range        supported   dependency                                    mandatory      procfunc                         mode                                                          constants}
      {port_handle                      _none_                    _none_                        ALPHANUM                                                 1              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {handle                           _none_                    _none_                        ALPHANUM                                                 1              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {mode                             _none_                    _none_                        {CHOICES create modify reset}                            1              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {attempt_rate                     PppoxPortConfig           ConnectRate                   NUMERIC                                                  3              _none_         1-1000        TRUE        _none_                                           FALSE          _none_                         {create configPortConfig modify configPortConfig}                  _none_}
      {disconnect_rate                  PppoxPortConfig           DisconnectRate                NUMERIC                                                  3              _none_         1-1000        TRUE        _none_                                           FALSE          _none_                         {create configPortConfig modify configPortConfig}                  _none_}
      {max_outstanding                  PppoxPortConfig           SessionOutstanding            NUMERIC                                                  3              _none_         2-65535       TRUE        _none_                                           FALSE          _none_                         {create configPortConfig modify configPortConfig}                  _none_}
      {encap                            _none_                    _none_      {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq vc_mux llcsnap}     2              ethernet_ii    _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {protocol                         _none_                    _none_                        {CHOICES pppoe pppoa pppoeoa}                            2              pppoe          _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {num_sessions                     EmulatedDevice|Host       DeviceCount                        NUMERIC                                             2              1              1-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {ip_cp                            PppoeServerBlockConfig    IpcpEncap                     {CHOICES ipv4_cp ipv6_cp}                                2              ipv4_cp        _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             { ipv4_cp ipv4 ipv6_cp ipv6 }}
      {intf_ip_addr                     Ipv4If                    Address                       IPV4                                                     4              _none_         _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {intf_ip_addr_step                Ipv4If                    AddrStep                      IPV4                                                     4              0.0.0.1        _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {intf_ip_prefix_length            Ipv4If                    PrefixLength                  NUMERIC                                                  4              24             0-32          TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {gateway_ip_addr                  Ipv4If                    Gateway                       IPV4                                                     4              _none_         _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {gateway_ip_step                  Ipv4If                    GatewayStep                   IPV4                                                     4              _none_         _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {intf_ipv6_addr                   Ipv6If                    Address                       IPV6                                                     4              _none_         _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {intf_ipv6_addr_step              Ipv6If                    AddrStep                      IPV6                                                     4              _none_         _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {intf_ipv6_prefix_length          Ipv6If                    PrefixLength                  NUMERIC                                                  4              64             0-128         TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {gateway_ipv6_addr                Ipv6If                    Gateway                       IPV6                                                     4              _none_         _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {gateway_ipv6_step                Ipv6If                    GatewayStep                   IPV6                                                     4              _none_         _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {mac_addr                         EthIIIf                   SourceMac                     ANY                                                      5              _none_         _none_        TRUE  {{protocol pppoe} {protocol pppoeoa}}                  FALSE          _none_                         {create configEthIIIntf modify configEthIIIntf}                    _none_}
      {mac_addr_step                    EthIIIf                   SrcMacStep                    ANY                                                      5              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         {create configEthIIIntf modify configEthIIIntf}                    _none_}
      {qinq_incr_mode                   _none_                    _none_                        {CHOICES inner outer both}                               6              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_id                          VlanIf                    VlanId                        NUMERIC                                                  6              100            0-4095        TRUE  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}}    FALSE          processConfigCmd_vlanId        {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_cfi                         VlanIf                    Cfi                           NUMERIC                                                  6              0              0-1           TRUE  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}}    FALSE          _none_                         {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_id_mode                     VlanIf                    IsRange                       {CHOICES fixed increment}                                6              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             {fixed FALSE increment TRUE}}
      {vlan_id_step                     VlanIf                    IdStep                        NUMERIC                                                  6              _none_         0-4095        TRUE  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}}    FALSE          _none_                         {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_id_count                    VlanIf                    IfRecycleCount                NUMERIC                                                  6              _none_         1-4096        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_user_priority               VlanIf                    Priority                      NUMERIC                                                  6              7              0-7           TRUE        _none_                                           FALSE          _none_                         {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_id_outer_count              VlanIf_Outer              IfRecycleCount                NUMERIC                                                  6              _none_         1-4096        TRUE  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}}    FALSE          _none_                          _none_                                                            _none_}
      {vlan_id_outer                    VlanIf_Outer              VlanId                        NUMERIC                                                  6              100            0-4095        TRUE        {{encap ethernet_ii_qinq}}                       FALSE          processConfigCmd_vlanId        {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {vlan_id_outer_mode               VlanIf_Outer              IsRange                        {CHOICES fixed increment}                                6              _none_          _none_       TRUE        _none_                                           FALSE          _none_                         _none_                                                             {fixed FALSE increment TRUE}}
      {vlan_outer_cfi                   VlanIf_Outer              Cfi                           NUMERIC                                                  6              0              0-1           TRUE        {{encap ethernet_ii_qinq}}                       FALSE          _none_                         {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {vlan_id_outer_step               VlanIf_Outer              IdStep                        NUMERIC                                                  6              _none_         0-4095        TRUE        {{encap ethernet_ii_qinq}}                       FALSE          _none_                         {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {vlan_outer_user_priority         VlanIf_Outer              Priority                      NUMERIC                                                  6              7              0-7           TRUE        {{encap ethernet_ii_qinq}}                       FALSE          _none_                         {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {pvc_incr_mode                    Aal5If                    _none_                        {CHOICES vci vpi both}                                   7              both           _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vci                              Aal5If                    Vci                           NUMERIC                                                  7              32             _none_        TRUE        {{encap vc_mux} {encap llcsnap}}                 FALSE          processConfigCmd_atmSettings   {create configAtmIntf modify configAtmIntf}                        _none_}
      {vci_count                        Aal5If                    VciRecycleCount               NUMERIC                                                  7              1              _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vci_step                         Aal5If                    VciStep                       NUMERIC                                                  7              0              _none_        TRUE        {{encap vc_mux} {encap llcsnap}}                 FALSE          _none_                         {create configAtmIntf modify configAtmIntf}                        _none_}
      {vpi                              Aal5If                    Vpi                           NUMERIC                                                  7              32             _none_        TRUE        {{encap vc_mux} {encap llcsnap}}                 FALSE          processConfigCmd_atmSettings   {create configAtmIntf modify configAtmIntf}                        _none_}
      {vpi_count                        Aal5If                    IfRecycleCount                NUMERIC                                                  7              1              _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vpi_step                         Aal5If                    VpiStep                       NUMERIC                                                  7              0              _none_        TRUE        {{encap vc_mux} {encap llcsnap}}                 FALSE          _none_                         {create configAtmIntf modify configAtmIntf}                        _none_}
      {wildcard_pound_end               _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_question_end            _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_pound_start             _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_question_start          _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_bang_start              _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_bang_end                _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_dollar_start            _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_dollar_end              _none_                    _none_                        NUMERIC                                                  10             _none_         0-65535       TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_pound_fill              _none_                    _none_                        NUMERIC                                                  10             _none_         0-9           TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_question_fill           _none_                    _none_                        NUMERIC                                                  10             _none_         0-9           TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_bang_fill               _none_                    _none_                        NUMERIC                                                  10             _none_         0-9           TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {wildcard_dollar_fill             _none_                    _none_                        NUMERIC                                                  10             _none_         0-9           TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {auth_mode                        PppoeServerBlockConfig    Authentication                {CHOICES none pap chap pap_or_chap}                      9              none           _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {none NONE pap PAP chap CHAP_MD5 pap_or_chap AUTO}}
      {username                         PppoeServerBlockConfig    Username                      REGEXP                                                   9              _none_         _none_        TRUE        _none_                                           FALSE          processConfigCmd_wildcard      {create configSessionBlock modify configSessionBlock}              _none_}
      {username_wildcard                PppoeServerBlockConfig    _none_                        {CHOICES 1 0 true false}                                 9              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {password                         PppoeServerBlockConfig    Password                      REGEXP                                                   9              _none_         _none_        TRUE        _none_                                           FALSE          processConfigCmd_wildcard      {create configSessionBlock modify configSessionBlock}              _none_}
      {password_wildcard                PppoeClientBlockConfig    _none_                        {CHOICES 1 0 true false}                                 9              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {echo_req                         PppoeServerBlockConfig    EnableEchoRequest             {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {echo_req_interval                PppoeServerBlockConfig    EchoRequestGenFreq            NUMERIC                                                  9              10             1-65535       TRUE        {{echo_req true} {echo_req 1}}                   FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {max_echo_acks                    PppoeServerBlockConfig    MaxEchoRequestAttempts        NUMERIC                                                  9              3              0-65535       TRUE        {{echo_req true} {echo_req 1}}                   FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {include_id                       PppoeServerBlockConfig    IncludeTxChapId               {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {service_name                     PppoeServerBlockConfig    ServiceName                   ALPHANUM                                                 9              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {local_magic                      PppoeServerBlockConfig    EnableMagicNum                {CHOICES 1 0 true false}                                 9              1              _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {mru_neg_enable                   PppoeServerBlockConfig    EnableMruNegotiation          {CHOICES 1 0 true false}                                 9              1              _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}    
      {lcp_mru                          PppoeServerBlockConfig    MruSize                       NUMERIC                                                  9              1492           128-65535     TRUE        {{mru_neg_enable true} {mru_neg_enable 1}}       FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {max_configure_req                PppoeServerBlockConfig    LcpConfigRequestMaxAttempts   NUMERIC                                                  9              5              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {config_req_timeout               PppoeServerBlockConfig    LcpConfigRequestTimeout       NUMERIC                                                  9              3              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {max_terminate_req                PppoeServerBlockConfig    LcpTermRequestMaxAttempts     NUMERIC                                                  9              10             1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {term_req_timeout                 PppoeServerBlockConfig    LcpTermRequestTimeout         NUMERIC                                                  9              10             1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {max_ipcp_req                     PppoeServerBlockConfig    NcpConfigRequestMaxAttempts   NUMERIC                                                  9              10             1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {ipcp_req_timeout                 PppoeServerBlockConfig    NcpConfigRequestTimeout       NUMERIC                                                  9              3              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {fsm_max_naks                     PppoeServerBlockConfig    MaxNaks                       NUMERIC                                                  9              5              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {max_payload_tag_enable           PppoeServerBlockConfig    EnableMaxPayloadTag           {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configSessionBlock modify configSessionBlock}              {0 FALSE 1 TRUE true TRUE false FALSE}}
      {max_payload_bytes                PppoeServerBlockConfig    MaxPayloadBytes               NUMERIC                                                  9              1500           1-65535       TRUE {{max_payload_tag_enable true} {max_payload_tag_enable 1}} FALSE       _none_                         {create configSessionBlock modify configSessionBlock}              _none_}
      {ipv4_pool_addr_start             PppoeServerIpv4PeerPool   Ipv4PeerPoolAddr              IPV4                                                     8              192.0.1.0      _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          processConfigAddrPool          {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv4_pool_addr_prefix_len        PppoeServerIpv4PeerPool   PrefixLength                  NUMERIC                                                  8              24             0-32          TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv4_pool_addr_count             PppoeServerIpv4PeerPool   NetworkCount                  NUMERIC                                                  8              1              _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv4_pool_addr_step              PppoeServerIpv4PeerPool   AddrIncrement                 NUMERIC                                                  8              1              _none_        TRUE        {{ip_cp ipv4_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_prefix_start           PppoxServerIpv6PeerPool   Ipv6PeerPoolPrefix            IPV6                                                     8              2001::         _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_prefix_step            PppoxServerIpv6PeerPool   Ipv6PeerPoolPrefixStep        IPV6                                                     8              0:0:0:1::      _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_intf_id_start          PppoxServerIpv6PeerPool   Ipv6IntfId                    IPV6                                                     8              ::1            _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_intf_id_step           PppoxServerIpv6PeerPool   Ipv6IntfIdStep                IPV6                                                     8              ::1            _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_prefix_len             PppoxServerIpv6PeerPool   PrefixLength                  NUMERIC                                                  8              64             1-128         TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {ipv6_pool_addr_count             PppoxServerIpv6PeerPool   NetworkCount                  NUMERIC                                                  8              1              _none_        TRUE        {{ip_cp ipv6_cp}}                                FALSE          _none_                         {create configIpAddressPool modify configIpAddressPool}            _none_}
      {echo_vendor_spec_tag_in_pado     PppoeServerBlockConfig    EchoVendorSpecificTagInPado   {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               {0 FALSE 1 TRUE true TRUE false FALSE}}
      {echo_vendor_spec_tag_in_pads     PppoeServerBlockConfig    EchoVendorSpecificTagInPads   {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               {0 FALSE 1 TRUE true TRUE false FALSE}}
      {force_server_connect_mode        PppoeServerBlockConfig    EnableForceServerConnectMode  {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               {0 FALSE 1 TRUE true TRUE false FALSE}}
      {unconnected_session_threshold    PppoeServerBlockConfig    UnconnectedSessionThreshold   NUMERIC                                                  9              0              0-65535       TRUE {{force_server_connect_mode true} {force_server_connect_mode 1}} FALSE _none_                         {create configSessionBlock modify configSessionBlock}               _none_}
      {server_inactivity_timer          PppoeServerBlockConfig    ServerInactivityTimer         NUMERIC                                                  9              30             1-65535       TRUE {{force_server_connect_mode true} {force_server_connect_mode 1}} FALSE _none_                         {create configSessionBlock modify configSessionBlock}               _none_}
      {enable_osi                       PppoeServerBlockConfig    EnableOsi                     {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               {0 FALSE 1 TRUE true TRUE false FALSE}}
      {enable_mpls                      PppoeServerBlockConfig    EnableMpls                    {CHOICES 1 0 true false}                                 9              0              _none_        TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               {0 FALSE 1 TRUE true TRUE false FALSE}}
      {chap_reply_timeout               PppoeServerBlockConfig    ChapReplyTimeout              NUMERIC                                                  9              3              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               _none_}
      {pap_req_timeout                  PppoeServerBlockConfig    PapPeerRequestTimeout         NUMERIC                                                  9              3              1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               _none_}
      {max_chap_req_attempt             PppoeServerBlockConfig    MaxChapRequestChallengeAttempts  NUMERIC                                               9              10             1-65535       TRUE        _none_                                           FALSE          _none_                         {create configSessionBlock modify configSessionBlock}               _none_}
   }
   {pppox_server_control
      {hname                            stcobj                     stcattr                        type                                                  priority        default         range       supported   dependency           mandatory      procfunc               mode                                                           constants}
      {port_handle                      _none_                     _none_                       ALPHANUM                                                  1             _none_          _none_       TRUE        _none_                FALSE          _none_                _none_                                                            _none_}
      {handle                           _none_                     _none_                       ALPHANUM                                                  2             _none_          _none_       TRUE        _none_                FALSE          _none_                _none_                                                            _none_}
      {action                           _none_                     _none_                    {CHOICES connect disconnect reset clear pause resume retry abort}  3       _none_          _none_       TRUE        _none_                TRUE           _none_                _none_   {connect PppoxConnect disconnect PppoxDisconnect reset PppoxAbort clear PppoxClearStats pause PppoxPause resume PppoxResume retry PppoxRetry abort PppoxAbort}}
   }
   {pppox_server_stats
      {hname                            stcobj                     stcattr                      type                             priority         default          range        supported  dependency            mandatory      procfunc           mode                          constants}
      {handle                           _none_                     _none_                       ALPHANUM                            1             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {port_handle                      _none_                     _none_                       ALPHANUM                            1             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {mode                             _none_                     _none_                       {CHOICES aggregate session}         2             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {retry                            _none_                     _none_                       {CHOICES 1 0 true false}            3             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {num_sessions                     PppoePortResult            sessions                        ANY                              35            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {idle                             PppoePortResults           _none_                          ANY                              37            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {connecting                       PppoePortResults           _none_                          ANY                              37            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {connected                        PppoePortResults           _none_                          ANY                              37            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {disconnecting                    PppoePortResults           _none_                          ANY                              37            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {abort                            PppoePortResults           _none_                          ANY                              37            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {connect_attempts                 PppoePortResults           AttemptedCount                  ANY                              7             _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {connect_success                  PppoePortResults           ConnectedSuccessCount           ANY                              38            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {disconnect_success               PppoePortResults           DisconnectedSuccessCount        ANY                              39            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {sessions_up                      PppoePortResults           sessionsUp                      ANY                              36            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {sessions_down                    PppoePortResults           failedConnectCount              ANY                              9             _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {disconnect_failed                PppoePortResults           FailedDisconnectCount           ANY                              10            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {avg_setup_time                   PppoePortResults           avgSetupTime                    ANY                              8             _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {max_setup_time                   PppoePortResults           maxSetupTime                    ANY                              11            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {min_setup_time                   PppoePortResults           minSetupTime                    ANY                              12            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {session_retried                  PppoePortResults           RetryCount                      ANY                              12            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {success_setup_rate               PppoePortResults           succSetupRate                   ANY                              40            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {lcp_cfg_req_rx                   PppoePortResults           RxLcpConfigRequestCount         ANY                              19            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_ack_rx                   PppoePortResults           RxLcpConfigAckCount             ANY                              16            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_nak_rx                   PppoePortResults           RxLcpConfigNakCount             ANY                              17            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_rej_rx                   PppoePortResults           RxLcpConfigRejectCount          ANY                              18            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_ack_tx                   PppoePortResults           TxLcpConfigAckCount             ANY                              42            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_nak_tx                   PppoePortResults           TxLcpConfigNakCount             ANY                              43            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_rej_tx                   PppoePortResults           TxLcpConfigRejectCount          ANY                              44            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {lcp_cfg_req_tx                   PppoePortResults           TxLcpConfigRequestCount         ANY                              45            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {term_ack_tx                      PppoePortResults           TxLcpTermAckCount               ANY                              56            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {term_req_tx                      PppoePortResults           TxLcpTermRequestCount           ANY                              57            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {term_ack_rx                      PppoePortResults           RxLcpTermAckCount               ANY                              33            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {term_req_rx                      PppoePortResults           RxLcpTermRequestCount           ANY                              34            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {echo_req_rx                      PppoePortResults           RxLcpEchoRequestCount           ANY                              20            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {echo_rsp_tx                      PppoePortResults           TxLcpEchoReplyCount             ANY                              46            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {echo_req_tx                      PppoePortResults           TxLcpEchoRequestCount           ANY                              46            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {echo_rsp_rx                      PppoePortResults           RxLcpEchoReplyCount             ANY                              46            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {padi_rx                          PppoePortResults           RxPadiCount                     ANY                              26            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {padr_rx                          PppoePortResults           RxPadrCount                     ANY                              28            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {padt_rx                          PppoePortResults           RxPadtCount                     ANY                              30            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {pads_tx                          PppoePortResults           TxPadsCount                     ANY                              53            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {padt_tx                          PppoePortResults           TxPadtCount                     ANY                              54            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {pado_tx                          PppoePortResults           TxPadoCount                     ANY                              54            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {pap_auth_tx                      PppoePortResults           TxPapCount                      ANY                              55            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {pap_auth_rx                      PppoePortResults           RxPapCount                      ANY                              31            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {chap_auth_tx                     PppoePortResults           TxChapCount                     ANY                              41            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_} 
      {chap_auth_rx                     PppoePortResults           RxChapCount                     ANY                              13            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {ipcp_rx                          PppoePortResults           RxIpcpCount                     ANY                              22            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {ipcp_tx                          PppoePortResults           TxIpcpCount                     ANY                              47            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {ipcpv6_rx                        PppoePortResults           RxIpv6cpCount                   ANY                              47            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {ipcpv6_tx                        PppoePortResults           TxIpv6cpCount                   ANY                              47            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate "" session ""}          _none_}
      {atm_mode                         PppoePortResults           _none_                          ANY                              58            _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_                             _none_}
      {padi_tx                          PppoePortResults           TxPadiCount                     ANY                              51            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {padr_tx                          PppoePortResults           TxPadrCount                     ANY                              52            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {pado_rx                          PppoePortResults           RxPadoCount                     ANY                              27            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
      {pads_rx                          PppoePortResults           RxPadsCount                     ANY                              29            _none_          _none_        TRUE       _none_                 FALSE         _none_             {aggregate ""}                     _none_}
   }
}
