namespace eval ::sth::ppp {
    set pppTable {
        ::sth::ppp::
        {ppp_config
            {hname                  stcobj                      stcattr                         type                         priority   default      range      supported  dependency                mandatory       procfunc                                               mode                                                                         constants}
            {action                 _none_                      _none_                      {CHOICES config up down}            1       _none_      _none_      true        _none_                      true            _none_                                                 _none_                                                                       _none_}
            {port_handle            _none_                      _none_                      ALPHANUM                            2       _none_      _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {handle                 _none_                      _none_                      ALPHANUM                            3       _none_      _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {local_auth_mode        PppProtocolConfig           Authentication              {CHOICES none pap chap}             4       none        _none_      true        _none_                      false           process_ppp_config_authentication                      {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {password               PppProtocolConfig           password                    ALPHANUM                            5       _none_      _none_      true        {local_auth_mode {pap|chap}}  false         process_ppp_config_authentication                      {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {username               PppProtocolConfig           username                    ALPHANUM                            6       _none_      _none_      true        {local_auth_mode {pap|chap}}  false         process_ppp_config_authentication                      {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {chap_req_timeout       PppProtocolConfig           ChapChalRequestTimeout      NUMERIC                             7       3           1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {pap_max_req            PppProtocolConfig           MaxPapRequestAttempts       NUMERIC                             8       10          1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {pap_req_timeout        PppProtocolConfig           MaxPapRequestAttempts       NUMERIC                             9       3           1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {fsm_max_conf_req       PppProtocolConfig           LcpConfigRequestMaxAttempts NUMERIC                             10      10          1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {fsm_max_naks           PppProtocolConfig           MaxNaks                     NUMERIC                             11      5           1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {fsm_max_term_req       PppProtocolConfig           LcpTermRequestMaxAttempts   NUMERIC                             12      10          1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {fsm_req_timeout        PppProtocolConfig           LcpConfigRequestTimeout     NUMERIC                             13      3           1-65535     true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {fcs_size               SonetConfig                 FCS                         {CHOICES 16 32}                     14      16          _none_      true        _none_                      false           process_ppp_config_fcsSize                             {create configSonetConfig modify configSonetConfig}                          _none_} 
            {ipv6_cp                PppProtocolConfig           IpcpEncap                   {CHOICES 0 1}                       15      0           _none_      true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_addr_given       _none_                      _none_                      {CHOICES 0 1}                       27      0           _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {local_addr_override    _none_                      _none_                      {CHOICES 0 1}                       28      0           _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {peer_addr_given        _none_                      _none_                      {CHOICES 0 1}                       29      0           _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {peer_addr_override     _none_                      _none_                      {CHOICES 0 1}                       30      0           _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {local_addr             Ipv4If                      Address                     IPV4                                16      _none_      _none_      true        _none_                      false           process_ppp_config_localAddrSetting                    {create configHostEncap modify configHostEncap}                              _none_}
            {peer_addr              PppProtocolConfig           Ipv4PeerAddr                IPV4                                17      _none_      _none_      true        _none_                      false           process_ppp_config_remoteAddrSetting                   {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_intf_id          Ipv6If                      Address       {REGEXP ^([0-9a-fA-F]{1,4}:){3}[0-9a-fA-F]{1,4}$}    18   _none_      _none_      true        _none_                      false           process_ppp_config_localAddrSetting                    {create configHostEncap modify configHostEncap}                              _none_}
            {peer_intf_id           PppProtocolConfig           Ipv6PeerAddr  {REGEXP ^([0-9a-fA-F]{1,4}:){3}[0-9a-fA-F]{1,4}$}    19   _none_      _none_      true        _none_                      false           process_ppp_config_remoteAddrSetting                   {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {lcp_echo_interval      PppProtocolConfig           EchoRequestGenFreq          NUMERIC                             20      0           0-65535     true        _none_                      false           process_ppp_config_lcpAchoInterval                     {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {lcp_local_mru          PppProtocolConfig           MruSize                     NUMERIC                             21      4096        128-65535   true        _none_                      false           process_ppp_config_mru                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_fcs              _none_                      _none_                      {CHOICES 0 1}                       22      0           _none_      true        _none_                      false           _none_                                                 _none_                                                                       _none_}
            {local_magic            PppProtocolConfig           EnableMagicNum              {CHOICES 0 1}                       23      0           _none_      true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_mpls_cp          PppProtocolConfig           EnableMpls                  {CHOICES 0 1}                       24      0           _none_      true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_mru              PppProtocolConfig           EnableMruNegotiation        {CHOICES 0 1}                       25      0           _none_      true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {local_osinl_cp         PppProtocolConfig           EnableOsi                   {CHOICES 0 1}                       26      0           _noen_      true        _none_                      false           _none_                                                 {create configPPPProtocolConfig modify configPPPProtocolConfig}              _none_}
            {peer_auth_mode         _none_                      _none_                      {CHOICES none pap chap}             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {chap_auth_interval     _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {chap_max_challenge     _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {pap_peer_req_timeout   _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {holdoff                _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {timeout                _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {lcp_fcs_size           _none_                      _none_                      {CHOICES no_fcs fcs16 fcs32}        99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {lcp_peer_max_tolerance _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {lcp_peer_mru           _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {lcp_accm               _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {local_accm             _none_                      _none_                      {CHOICES 0 1}                       99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {peer_accm              _none_                      _none_                      {CHOICES 0 1}                       99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {peer_fcs               _none_                      _none_                      {CHOICES 0 1}                       99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {peer_mru               _none_                      _none_                      {CHOICES 0 1}                       99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {vlan_outer_cfi         _none_                      _none_                      {CHOICES 0 1}                       99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {vlan_outer_tpid        _none_                      _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
            {vlan_outer_user_priority   _none_                  _none_                      NUMERIC                             99      _none_      _none_      false       _none_                      false           _none_                                                 _none_                                                                       _none_}
        }
        {ppp_stats
            {hname                          stcobj                 stcattr                  type                     priority   default      range      supported  dependency    mandatory    procfunc      mode        constants}
            {action                         _none_                  _none_                  {CHOICES collect clear}     1       _none_      _none_          true    _none_          true        _none_      _none_          _none_}
            {port_handle                    _none_                  _none_                  ALPHANUM                    2       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {pos_port_state                 PppProtocolResults      PosPortState            ANY                         3       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {lcp_or_ncp_state               PppProtocolResults      PosLcpOrNcpState        ANY                         4       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {pap_authentication_state       PppProtocolResults      PosPapAuthState         ANY                         5       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {chap_authentication_state      PppProtocolResults      PosChapAuthState        ANY                         6       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv4_cp_state                  PppProtocolResults      Ipv4CpState             ANY                         7       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv4_local_address             PppProtocolResults      Ipv4LocalAddr           IPV4                        8       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv4_peer_address              PppProtocolResults      Ipv4PeerAddr            IPV4                        9       _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv6_cp_state                  PppProtocolResults      Ipv6CpState             ANY                         10      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv6_local_address             PppProtocolResults      Ipv6LocalAddr           IPV6                        11      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {ipv6_peer_address              PppProtocolResults      Ipv6PeerAddr            IPV6                        12      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {pos_mpls_cp_state              PppProtocolResults      MplsCpState             ANY                         13      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {pos_osi_nlcp_state             PppProtocolResults      OsiNlcpState            ANY                         14      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {tx_mru_size                    PppProtocolResults      TxMruSize               NUMERIC                     15      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
            {rx_mru_size                    PppProtocolResults      RxMruSize               NUMERIC                     16      _none_      _none_          true    _none_          false       _none_      _none_          _none_}
        }
    }
}