# $Id: //TestCenter/4.81_rel/content/HltAPI/SourceCode/ptpTable.tcl#1 $
# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

# Copyright (c) 2005 - 2007 Spirent Communications
#
# All rights are reserved. Reproduction or transmission in whole or in part, in
# any form or by any means, electronic, mechanical or otherwise, is prohibited
# without the prior written consent of the copyright owner.
#

namespace eval ::sth::Ptp:: {
}

# sync_two_step_flag only support "on", ptp_session_mode only support "multicast"
# path_delay_mechanism do not support "peer-to-peer" now
set ::sth::Ptp::PtpTable {
   ::sth::Ptp::
   {emulation_ptp_config
      {hname                            stcobj                    stcattr                       type                                                  priority        default           range        supported   dependency                                    mandatory      procfunc                         mode                                                          constants}
      {port_handle                      _none_                    _none_                        ALPHANUM                                                 1              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {handle                           _none_                    _none_                        ALPHANUM                                                 2              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {mode                             _none_                    _none_       {CHOICES create modify delete enable disable enable_all disable_all}      3              _none_         _none_        TRUE        _none_                                           TRUE           _none_                         _none_                                                             _none_}
      {count                            Router	                    count                        NUMERIC                                                  4              1              _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {name                             _none_     _none_                          ALPHANUM                                                 7              _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {encapsulation                    _none_                    _none_      {CHOICES ETHERNETII LLC_SNAP VC_MUX ETHERNETII_LLC_SNAP ETHERNETII_VC_MUX} 8              ETHERNETII     _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {device_type                      Ieee1588v2ClockConfig     SlaveOnly                     {CHOICES ptpSlave ptpMaster}                             9              ptpMaster      _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configIeee1588v2Config modify configIeee1588v2Config}      {ptpSlave true ptpMaster false}}
      {transport_type                   Ieee1588v2ClockConfig     Encap                         {CHOICES ethernet_ii ipv4 ipv6}                          10             ipv4           _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configIeee1588v2Config modify configIeee1588v2Config}      {ethernet_ii ETHERNET ipv4 UDP_IPV4 ipv6 UDP_IPV6}}
      {vlan_id1                         VlanIf                    VlanId                        NUMERIC                                                  11             100            0-4095        TRUE        _none_                                           FALSE          processConfigCmd_vlanId        {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_ether_type1                 VlanIf                    Tpid                          {CHOICES 0x8100 0x88A8 0x9100 0x9200}                    11             0x8100         _none_        TRUE        _none_                                           FALSE          _none_                         {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_id_mode1                    _none_                    _none_                        {CHOICES fixed increment}                                11             increment      _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_id_step1                    VlanIf                    IdStep                        NUMERIC                                                  11             1              0-4095        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_id_repeat1                  VlanIf                    IdRepeatCount                 NUMERIC                                                  11             0              0-4095        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_priority1                   VlanIf                    Priority                      NUMERIC                                                  11             0              0-7           TRUE        _none_                                           FALSE          _none_                         {create configVlanIfInner modify configVlanIfInner}                _none_}
      {vlan_id2                         VlanIf_Outer                    VlanId                        NUMERIC                                                  12             100            0-4095        TRUE        _none_                                           FALSE          processConfigCmd_vlanId        {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {vlan_ether_type2                 VlanIf_Outer                    Tpid                          {CHOICES 0x8100 0x88A8 0x9100 0x9200}                    12             0x8100         _none_        TRUE        _none_                                           FALSE          _none_                         {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {vlan_id_mode2                    _none_                    _none_                        {CHOICES fixed increment}                                12             increment      _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_id_step2                    VlanIf_Outer                    IdStep                        NUMERIC                                                  12             1              0-4095        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_id_repeat2                  VlanIf_Outer                    IdRepeatCount                 NUMERIC                                                  12             0              0-4095        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {vlan_priority2                   VlanIf_Outer                    Priority                      NUMERIC                                                  12             0              0-7           TRUE        _none_                                           FALSE          _none_                         {create configVlanIfOuter modify configVlanIfOuter}                _none_}
      {local_mac_addr                   EthIIIf                   SourceMac                     ANY                                                      13             _none_         _none_        TRUE        _none_                                           FALSE          processConfigCmd_macAddr       {create configEthIIIntf modify configEthIIIntf}                    _none_}
      {local_mac_addr_step              EthIIIf                   SrcMacStep                    ANY                                                      13             _none_         _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {local_mac_addr_repeat            EthIIIf                   SrcMacRepeatCount             NUMERIC                                                  13             0              _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             _none_}
      {local_ip_addr                    Ipv4If                    Address                       IPV4                                                     14             _none_         _none_        TRUE        {{transport_type ipv4}}                          FALSE          processConfigCmd_ipSettings    {create configIpIntf modify configIpIntf}                          _none_}
      {local_ip_addr_step               Ipv4If                    AddrStep                      IPV4                                                     14             _none_         _none_        TRUE        {{transport_type ipv4}}                          FALSE          _none_                         _none_                                                             _none_}
      {local_ip_addr_repeat             Ipv4If                    AddrRepeatCount               NUMERIC                                                  14             0              _none_        TRUE        {{transport_type ipv4}}                          FALSE          _none_                         _none_                                                             _none_}
      {local_ip_prefix_len              Ipv4If                    PrefixLength                  NUMERIC                                                  14             24             0-32          TRUE        {{transport_type ipv4}}                          FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {local_ipv6_addr                  Ipv6If                    Address                       IPV6                                                     14             _none_         _none_        TRUE        {{transport_type ipv6}}                          FALSE          processConfigCmd_ipSettings    {create configIpIntf modify configIpIntf}                          _none_}
      {local_ipv6_addr_step             Ipv6If                    AddrStep                      IPV6                                                     14             _none_         _none_        TRUE        {{transport_type ipv6}}                          FALSE          _none_                         _none_                                                             _none_}
      {local_ipv6_addr_repeat           Ipv6If                    AddrRepeatCount               NUMERIC                                                  14             0              _none_        TRUE        {{transport_type ipv6}}                          FALSE          _none_                         _none_                                                             _none_}
      {local_ipv6_prefix_len            Ipv6If                    PrefixLength                  NUMERIC                                                  14             64             0-128         TRUE        {{transport_type ipv6}}                          FALSE          _none_                         {create configIpIntf modify configIpIntf}                          _none_}
      {remote_ip_addr                   Ipv4If                    Gateway                       IPV4                                                     15             _none_         _none_        TRUE        {{transport_type ipv4}}                          FALSE          processConfigCmd_ipSettings    {create configIpIntf modify configIpIntf}                          _none_}
      {remote_ip_addr_step              Ipv4If                    GatewayStep                   IPV4                                                     15             _none_         _none_        TRUE        {{transport_type ipv4}}                          FALSE          _none_                         _none_                                                             _none_}
      {remote_ipv6_addr                 Ipv6If                    Gateway                       IPV6                                                     15             _none_         _none_        TRUE        {{transport_type ipv6}}                          FALSE          processConfigCmd_ipSettings    {create configIpIntf modify configIpIntf}                          _none_}
      {remote_ipv6_addr_step            Ipv6If                    GatewayStep                   IPV6                                                     15             _none_         _none_        TRUE        {{transport_type ipv6}}                          FALSE          _none_                         _none_                                                             _none_}
      {mac_address_resolution           Ipv4If                    ResolveGatewayMac             {CHOICES user_defined arp_resolved}                      16             arp_resolved   _none_        TRUE        _none_                                           FALSE          _none_                         _none_                                                             {user_defined false arp_resolved true}}
      {ptp_session_mode                 Ieee1588v2ClockConfig     UnicastDiscovery              {CHOICES unicast multicast}                              17             multicast      _none_        TRUE        _none_                                           FALSE          processConfigFwdCmd            {create configIeee1588v2Config modify configIeee1588v2Config}      {unicast ENABLED multicast DISABLED}}
      {ipv4_priority                    Ipv4If                    TosType                       {CHOICES tos diff-serv}                                  18             tos            _none_        TRUE        {{transport_type ipv4}}                          FALSE          processConfigFwdCmd            {create configIpIntf modify configIpIntf}                          {tos TOS diff-serv DIFFSERV}}
      {ip_tos_field                     _none_                    _none_                        HEX                                                      18             _none_           0x0-0xFF      TRUE        _none_                                           FALSE          processConfigCmd_tos           {create configIpIntf modify configIpIntf}                          _none_}
      {tos_precedence                   _none_                    _none_                        {CHOICES routine priority immediate flash flash-override critic-ecp internet-control network-control}
                                                                                                                                                         18       internet-control     _none_      TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {routine 000 priority 001 immediate 010 flash 011 flash-override 100 critic-ecp 101 internet-control 110 network-control 111}}
      {tos_delay                        _none_                    _none_                        {CHOICES normal low}                                     18             normal         _none_      TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {normal 0 low 1}}
      {tos_throughput                   _none_                    _none_                        {CHOICES normal high}                                    18             normal         _none_      TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {normal 0 high 1}}
      {tos_reliability                  _none_                    _none_                        {CHOICES normal high}                                    18             normal         _none_      TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {normal 0 high 1}}
      {tos_monetary_cost                _none_                    _none_                        {CHOICES normal minimize}                                18             normal         _none_      TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {normal 0 minimize 1}}
      {tos_unused                       _none_                    _none_                        HEX                                                      18             0x0            0x0-0xF     TRUE           _none_                                           FALSE         processConfigCmd_tos           {create configIpIntf modify configIpIntf}                           {0x0 0 0x1 1}}
      {diff_default                     _none_                    _none_                        NUMERIC                                                  18             _none_         0-255       TRUE           _none_                                           FALSE         processConfigCmd_diffserv      {create configIpIntf modify configIpIntf}                            _none_}
      {diff_class                       _none_                    _none_                        NUMERIC                                                  18             _none_         0-7         TRUE           _none_                                           FALSE         processConfigCmd_diffserv      {create configIpIntf modify configIpIntf}                            _none_}
      {diff_assured_forwarding          _none_                    _none_                        {CHOICES class1-low-drop class1-medium-drop class1-high-drop class2-low-drop class2-medium-drop class2-high-drop class3-low-drop class3-medium-drop class3-high-drop class4-low-drop class4-medium-drop class4-high-drop}
                                                                                                                                                         18             _none_         _none_      TRUE           _none_                                           FALSE         processConfigCmd_diffserv      {create configIpIntf modify configIpIntf}
                                                                                                                                                         {class1-low-drop 001010 class1-medium-drop 001100 class1-high-drop 001110 class2-low-drop 010010 class2-medium-drop 010100 class2-high-drop 010110 class3-low-drop 011010 class3-medium-drop 011100 class3-high-drop 011110 class4-low-drop 100010 class4-medium-drop 100100 class4-high-drop 100110}}
      {diff_explicit_forwarding        _none_                     _none_                        NUMERIC                                                  18             _none_         0-63        TRUE           _none_                                           FALSE         processConfigCmd_diffserv      {create configIpIntf modify configIpIntf}                            _none_}
      {diff_ecn                        _none_                     _none_                        {CHOICES ecn-capable-transport1 ecn-capable-transport0 non-ecn-capable-transport congestion}
                                                                                                                                                         18             _none_         _none_      TRUE           _none_                                           FALSE          _none_                         _none_                                                             {ecn-capable-transport1 01 ecn-capable-transport0 10 non-ecn-capable-transport 00 congestion 11}}
      {ptp_domain_number               Ieee1588v2ClockConfig      DomainNum                     NUMERIC                                                  19             0              0-255       TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {ptp_port_number                 Ieee1588v2ClockConfig      PortNum                       NUMERIC                                                  20             1              0-65535     TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {ptp_clock_id                    Ieee1588v2ClockConfig      ClockIdentity                 HEX                                                      21             _none_         _none_      TRUE           _none_                                           FALSE          processConfigCmd_clockId       {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {ptp_clock_id_mode               _none_                     _none_                        {CHOICES list increment}                                 21             _none_         _none_      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {ptp_clock_id_step               _none_                     _none_                        HEX                                                      21             _none_         _none_      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {ptp_clock_id_repeat             _none_                     _none_                        NUMERIC                                                  21             _none_         _none_      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {master_clock_class              Ieee1588v2ClockConfig      ClockClass                    NUMERIC                                                  22             248            0-255       TRUE           {{device_type ptpMaster}}                        FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {master_clock_priority1          Ieee1588v2ClockConfig      Priority1                     NUMERIC                                                  23             0              0-255       TRUE           {{device_type ptpMaster}}                        FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {master_clock_priority2          Ieee1588v2ClockConfig      Priority2                     NUMERIC                                                  24             0              0-255       TRUE           {{device_type ptpMaster}}                        FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {time_source                     Ieee1588v2ClockConfig      TimeSrc                       {CHOICES atomic-clock gps terrestrial-radio ptp ntp handset other internal-oscillator ptp-profile reserved}
                                                                                                                                                         25             internal-oscillator  _none_   TRUE        {{device_type ptpMaster}}                        FALSE          processConfigFwdCmd            {create configIeee1588v2Config modify configIeee1588v2Config}
                                                                                                                                                                                                                                                                  {atomic-clock ATOMIC_CLOCK gps GPS terrestrial-radio TERRESTRIAL_RADIO ptp PTP ntp NTP handset HAND_SET other OTHER internal-oscillator INTERNAL_OSCILLATOR ptp-profile PTP_PROFILE240}}
      {announce_message_enable         _none_                     _none_                        {CHOICES 0 1 false true}                                 26             1              _none_      TRUE           {{device_type ptpMaster}}                        FALSE          _none_                         _none_                                                             _none_}
      {log_announce_message_interval   Ieee1588v2ClockConfig      LogAnnounceInterval           NUMERIC                                                  27             0              0-4         TRUE           {{announce_message_enable 1}}                    FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {announce_receipt_timeout        Ieee1588v2ClockConfig      AnnounceReceiptTimeout        NUMERIC                                                  28             3              3-20        TRUE           {{announce_message_enable 1}}                    FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {sync_enable                     _none_                     _none_                        {CHOICES 0 1 false true}                                 29             1              _none_      TRUE           {{device_type ptpMaster}}                        FALSE          _none_                         _none_                                                             _none_}
      {sync_two_step_flag              Ieee1588v2ClockConfig      StepMode                      {CHOICES on off}                                         30             on             _none_      TRUE           {{sync_enable 1}}                                FALSE          processConfigFwdCmd            {create configIeee1588v2Config modify configIeee1588v2Config}      {on TWO_STEP off ONE_STEP}}
      {log_sync_message_interval       Ieee1588v2ClockConfig      LogSyncInterval               {CHOICES -5 -4 -3 -2 -1 0 1 2 3 4 5}                     31             0              _none_      TRUE           {{sync_enable 1}}                                FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {path_delay_mechanism            Ieee1588v2ClockConfig      DelayMechanism                {CHOICES end-to-end peer-to-peer}                        32             end-to-end     _none_      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      {end-to-end REQUEST_RESPONSE peer-to-peer PEER_DELAY}}
      {delay_request_enable            _none_                     _none_                        {CHOICES 0 1 false true}                                 33             1              _none_      TRUE           {{path_delay_mechanism end-to-end}}              FALSE          _none_                         _none_                                                             _none_}
      {log_minimum_delay_request_interval  Ieee1588v2ClockConfig  LogMinDelayRequestInterval    {CHOICES -5 -4 -3 -2 -1 0 1 2 3 4 5}                     34             0              _none_      TRUE           {{delay_request_enable 1}}                       FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {vci                              Aal5If                    Vci                           NUMERIC                                                  35             32             _none_      TRUE           _none_                                           FALSE          processConfigCmd_atmSettings   {create configAtmIntf modify configAtmIntf}                        _none_}
      {vci_step                         Aal5If                    VciStep                       NUMERIC                                                  35             0              _none_      TRUE           _none_                                           FALSE          _none_                         {create configAtmIntf modify configAtmIntf}                        _none_}
      {vpi                              Aal5If                    Vpi                           NUMERIC                                                  35             32             _none_      TRUE           _none_                                           FALSE          processConfigCmd_atmSettings   {create configAtmIntf modify configAtmIntf}                        _none_}
      {vpi_step                         Aal5If                    VpiStep                       NUMERIC                                                  35             0              _none_      TRUE           _none_                                           FALSE          _none_                         {create configAtmIntf modify configAtmIntf}                        _none_}
      {tx_crc_error_perc           Ieee1588v2ClockConfig   TxFrameCRCErrorPercentage            NUMERIC                                                  66             0              0-100      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {tx_time_stamp_error_perc    Ieee1588v2ClockConfig   TxFrameTimeStampErrorPercentage      NUMERIC                                                  66             0              0-100      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {tx_delay_resp_dropped_perc  Ieee1588v2ClockConfig   TxDelayResponseFrameDroppedPercentage NUMERIC                                                 66             0              0-100      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {tx_followup_dropped_perc    Ieee1588v2ClockConfig   TxFollowUpFrameDroppedPercentage     NUMERIC                                                  66             0              0-100      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {enable_correction           Ieee1588v2ClockConfig   ConfigCorrectionField                {CHOICES 0 1}                                            66             0              _none_      TRUE           _none_                                           FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      {0 FALSE 1 TRUE}}
      {sync_correction             Ieee1588v2ClockConfig   SyncCorrectionField                  NUMERIC                                                  66             0              _none_     TRUE           {{enable_correction 1}}                          FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {followup_correction         Ieee1588v2ClockConfig   FollowUpCorrectionField              NUMERIC                                                  66             0              _none_      TRUE           {{enable_correction 1}}                          FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {delay_request_correction    Ieee1588v2ClockConfig   DelayRequestCorrectionField          NUMERIC                                                  66             0              _none_      TRUE           {{enable_correction 1}}                          FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {delay_response_correction   Ieee1588v2ClockConfig   DelayResponseCorrectionField         NUMERIC                                                  66             0              _none_     TRUE           {{enable_correction 1}}                          FALSE          _none_                         {create configIeee1588v2Config modify configIeee1588v2Config}      _none_}
      {num_sessions                _none_                  _none_                               NUMERIC                                                  5              1              _none_      FALSE          _none_                                           FALSE          _none_                         _none_                                                             _none_}
   }
   {emulation_ptp_control
      {hname                            stcobj                     stcattr                type                                   priority        default         range       supported   dependency           mandatory      procfunc               mode           constants}
      {port_handle                      _none_                     _none_                 ALPHANUM                                  1             _none_          _none_       TRUE        _none_                FALSE          _none_              _none_            _none_}
      {handle                           _none_                     _none_                 ALPHANUM                                  2             _none_          _none_       TRUE        _none_                FALSE          _none_              _none_            _none_}
      {action_control                   _none_                     _none_                 {CHOICES start stop}                      3             _none_          _none_       TRUE        _none_                TRUE           _none_              _none_            _none_}
      {interval                         _none_                     _none_                 NUMERIC                                   4             _none_          _none_       FALSE       _none_                FALSE          _none_              _none_            _none_}
      {interval_unit                    _none_                     _none_                 {CHOICES second millisecond microsecond}  5             _none_          _none_       FALSE       _none_                FALSE          _none_              _none_            _none_}
   }
   {emulation_ptp_stats
      {hname                            stcobj                     stcattr                      type                             priority         default          range        supported  dependency            mandatory      procfunc           mode            constants}
      {handle                           _none_                     _none_                       ALPHANUM                            1             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_             _none_}
      {port_handle                      _none_                     _none_                       ALPHANUM                            2             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_             _none_}
      {reset                            _none_                     _none_                       {CHOICES 0 1}                       3             _none_          _none_        TRUE       _none_                 FALSE         _none_             _none_             _none_}
      {mode                             _none_                     _none_                       {CHOICES device}                    4             device          _none_        TRUE       _none_                 FALSE         _none_             _none_             _none_}
      {device_instance                  _none_                     _none_                       NUMERIC                             5             _none_          _none_        FALSE      _none_                 FALSE         _none_             _none_             _none_}
      {total_rx_announce                Ieee1588v2ClockResult      RxAnnounceCount              NUMERIC                             6             _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_sync                    Ieee1588v2ClockResult      RxSyncCount                  NUMERIC                             7             _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_sync_followup           Ieee1588v2ClockResult      RxFollowUpCount              NUMERIC                             8             _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_delay_req               Ieee1588v2ClockResult      RxDelayRequestCount          NUMERIC                             9             _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_delay_resp              Ieee1588v2ClockResult      RxDelayResponseCount         NUMERIC                             10            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_announce                Ieee1588v2ClockResult      TxAnnounceCount              NUMERIC                             13            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_sync                    Ieee1588v2ClockResult      TxSyncCount                  NUMERIC                             14            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_sync_followup           Ieee1588v2ClockResult      TxFollowUpCount              NUMERIC                             15            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_delay_req               Ieee1588v2ClockResult      TxDelayRequestCount          NUMERIC                             16            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_delay_resp              Ieee1588v2ClockResult      TxDelayResponseCount         NUMERIC                             17            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {peer_mean_path_delay             ClockSynchronizationResult PeerMeanPathDelay            NUMERIC                             20            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {clock_domain                     Ieee1588v2ClockResult      ClockDomain                  NUMERIC                             20            _none_          _none_        TRUE       _none_                 FALSE         _none_             {device ""}        _none_}
      {bmc_grandmaster_clock_id         ParentClockInfoResult      GrandmasterIdentity          NUMERIC                             21            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_clock_class                  ParentClockInfoResult      GrandmasterClockClass        NUMERIC                             22            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_clock_accuracy               ParentClockInfoResult      GrandmasterClockAccuracy     NUMERIC                             23            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_offset_scaled_log_variance   ParentClockInfoResult      GrandmasterClockOffsetScaledLogVariance   NUMERIC                24            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_priority1                    ParentClockInfoResult      GrandmasterPriority1         NUMERIC                             25            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_priority2                    ParentClockInfoResult      GrandmasterPriority2         NUMERIC                             26            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_steps_removed                ClockSynchronizationResult StepRemoved                  NUMERIC                             27            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_time_source                  TimePropertiesResult       TimeSrc                      NUMERIC                             28            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {bmc_source_port_clock_id         Ieee1588v2ClockResult      ClockIdentity                NUMERIC                             29            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {offset_from_master               ClockSynchronizationResult CurrentOffset                NUMERIC                             30            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {mean_path_delay                  ClockSynchronizationResult CurrentMeanPathDelay         NUMERIC                             31            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {rx_log_min_delay_req_interval    ClockSynchronizationResult LogMinDelayRequestInterval   NUMERIC                             32            _none_          _none_        TRUE       slave                  FALSE         _none_             {device ""}        _none_}
      {total_tx_peerdelay_req           Ieee1588v2ClockResult      TxPeerDelayRequestCount      NUMERIC                             18            _none_          _none_        FALSE      _none_                 FALSE         _none_             {device ""}        _none_}
      {total_tx_peerdelay_resp          Ieee1588v2ClockResult      TxPeerDelayResponseCount     NUMERIC                             19            _none_          _none_        FALSE      _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_peerdelay_req           Ieee1588v2ClockResult      RxPeerDelayRequestCount      NUMERIC                             11            _none_          _none_        FALSE      _none_                 FALSE         _none_             {device ""}        _none_}
      {total_rx_peerdelay_resp          Ieee1588v2ClockResult      RxPeerDelayResponseCount     NUMERIC                             12            _none_          _none_        FALSE      _none_                 FALSE         _none_             {device ""}        _none_}
   }
}
