
namespace eval ::sth::rip {
   set ripTable {
      ::sth::rip::
         {emulation_rip_config
            {hname                         stcobj                                                      stcattr                       type                                                        priority                      default                                                     range                         supported                     dependency                                                  mandatory                     procfunc                      mode                          constants}
            {authentication_mode           RipRouterConfig.RipAuthenticationParams                     Authentication                {CHOICES null text md5}                                     100                            NONE                                                        _none_                       true                          _none_                                                      false                         _none_                        _none_                        {null None text Simple md5 MD5}}
            {count                         _none_                                                      count                        NUMERIC                                                     100                           _none_                                                      1-4294967295                  true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {expiration_interval           _none_                                                      _none_                        NUMERIC                                                     100                           180000                                                      1-16777215                    false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {garbage_interval              _none_                                                      _none_                        NUMERIC                                                     100                           120000                                                      1-16777215                    false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {handle                        _none_                                                      _none_                        ANY                                                         20                            _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {interface_metric              _none_                                                      _none_                        NUMERIC                                                     100                           0                                                           1-15                          false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {mac_address_start             EthiiIf                                                     SourceMac                     ANY                                                         100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {intf_ip_addr                  {ripv1 Ipv4If ripv2 Ipv4If ripng Ipv6If}                    Address                       IP                                                          100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {intf_ip_addr_step             {ripv1 Ipv4If ripv2 Ipv4If ripng Ipv6If}                    AddrStep                      IP                                                          100                           {ripv1 0.0.0.1 ripv2 0.0.0.1 ripng 0:0:0:0:0:0:0:1}         _none_                        true                          {stcobj {hname session_type} default {hname session_type}}  false                         _none_                        _none_                        _none_}
            {intf_prefix_length            {ripv1 Ipv4If ripv2 Ipv4If ripng Ipv6If}                    PrefixLength                  NUMERIC                                                     100                           {ripv1 24 ripv2 24 ripng 64}                                _none_                        true                          {stcobj {hname session_type} default {hname session_type}}  false                         _none_                        _none_                        _none_}
            {link_local_intf_ip_addr       {ripng Ipv6If}                                              Address                       IPV6                                                        100                           {ripng FE80::0}                                             _none_                        true                          {stcobj {hname session_type} default {hname session_type}}  false                         _none_                        _none_                        _none_}
            {link_local_intf_ip_addr_step  {ripng Ipv6If}                                              AddrStep                      IPV6                                                        100                           {ripng ::1}                                                 _none_                        true                          {stcobj {hname session_type} default {hname session_type}}  false                         _none_                        _none_                        _none_}
            {link_local_intf_prefix_len    {ripng Ipv6If}                                              PrefixLength                  NUMERIC                                                     100                           {ripng 128}                                                 1-128                         true                          {stcobj {hname session_type} default {hname session_type}}  false                         _none_                        _none_                        _none_}
            {md5_key                       RipRouterConfig.RipAuthenticationParams                     Password                      ALPHANUM                                                    100                           Spirent                                                     _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {md5_key_id                    RipRouterConfig.RipAuthenticationParams                     Md5KeyId                      NUMERIC                                                     100                           1                                                           0-255                         true                          {requirement {authentication_mode md5}}                     false                         _none_                        _none_                        _none_}
            {mode                          _none_                                                      _none_                        {CHOICES create modify delete enable disable active inactive} 10                          _none_                                                      _none_                        true                          _none_                                                      true                          _none_                        _none_                        _none_}
            {neighbor_intf_ip_addr         {ripv1 Ipv4If ripv2 Ipv4If ripng Ipv6If}                    DutIpv4Addr                   IP                                                          100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {neighbor_intf_ip_addr_step    _none_                                                      _none_                        IP                                                          100                           _none_                                                       _none_                        true                          {default {hname session_type}}                              false                         _none_                        _none_                        _none_}
            {gateway_ip_addr               {ripv1 Ipv4If ripv2 Ipv4If ripng Ipv6If}                    Gateway                       IP                                                          100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {gateway_ip_addr_step          _none_                                                      _none_                        IP                                                          100                           {ripv1 0.0.0.0 ripv2 0.0.0.0 ripng 0:0:0:0:0:0:0:0}         _none_                        true                          {default {hname session_type}}                              false                         _none_                        _none_                        _none_}
            {num_routes_per_period         RipRouterConfig                                             MaxRoutePerUpdate             NUMERIC                                                     100                           25                                                          1-70                          true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {password                      RipRouterConfig.RipAuthenticationParams                     Password                      ALPHANUM                                                    100                           Spirent                                                     _none_                        true                          {requirement {authentication_mode text}}                    false                         _none_                        _none_                        _none_}
            {port_handle                   _none_                                                      _none_                        ANY                                                         20                            _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {receive_type                  _none_                                                      _none_                        {CHOICES v1 v2 v1_v2}                                       100                           _none_                                                      _none_                        false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {router_id                     Router                                                      RouterId                      IPV4                                                        100                           _none_                                                      0.0.0.0-255.255.255.255       true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {router_id_step                _none_                                                      _none_                        IPV4                                                        100                           0.0.0.1                                                     0.0.0.1-255.255.255.255       true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {send_type                     RipRouterConfig                                             UpdateType                    {CHOICES multicast unicast broadcast}                       100                           {ripv1 broadcast ripv2 multicast ripng multicast}           _none_                        true                          {default {hname session_type}}                              false                         _none_                        _none_                        _none_}
            {session_type                  RipRouterConfig                                             RipVersion                    {CHOICES ripv1 ripv2 ripng}                                 90                            ripv2                                                       _none_                        true                          _none_                                                      false                         _none_                        _none_                        {ripv1 V1 ripv2 V2 ripng NG}}
            {time_period                   RipRouterConfig                                             InterUpdateDelay              NUMERIC                                                     100                           0                                                           0-5000                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {triggered_interval            _none_                                                      _none_                        NUMERIC                                                     100                           5000                                                        1-5000                        false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {update_interval               RipRouterConfig                                             UpdateInterval                NUMERIC                                                     100                           30                                                          1-10000                       true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {update_interval_offset        RipRouterConfig                                             UpdateJitter                  NUMERIC                                                     100                           0                                                           0-5                           true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {update_mode                   _none_                                                      _none_                        {CHOICES no_horizon split_horizon poison_reverse discard}   100                           no_horizon                                                  _none_                        false                         _none_                                                      false                         _none_                        _none_                        _none_}
            {vci                           Aal5If                                                      Vci                           NUMERIC                                                     100                           _none_                                                      0-65535                       true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vci_step                      Aal5If                                                      Vci.Step                      NUMERIC                                                     100                           _none_                                                      0-65535                       true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_cfi                      VlanIf                                                      Cfi                           NUMERIC                                                     100                           0                                                           0-1                           true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_id                       VlanIf                                                      VlanId                        NUMERIC                                                     100                           _none_                                                      0-4095                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_id_mode                  VlanIf                                                      _none_                       {CHOICES fixed increment}                                   100                           fixed                                                       _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_id_step                  VlanIf                                                      IdStep                        NUMERIC                                                     100                           1                                                           0-4095                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_user_priority            VlanIf                                                      Priority                      NUMERIC                                                     100                           7                                                           0-7                           true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vpi                           Aal5If                                                      Vpi                           NUMERIC                                                     100                           _none_                                                      0-255                         true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vpi_step                      Aal5If                                                      Vpi.Step                      NUMERIC                                                     100                           _none_                                                      0-255                         true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {bfd_registration              RipRouterConfig                                             EnableBfd                     {CHOICES 1 0}                                               100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {tunnel_handle                 _none_                                                      _none_                        ANY                                                         100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_outer_id                 VlanIf_Outer                                                VlanId                        NUMERIC                                                     100                           _none_                                                      0-4095                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_outer_id_mode            VlanIf_Outer                                                _none_                   {CHOICES fixed increment}                                       100                           fixed                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_outer_id_step            VlanIf_Outer                                                IdStep                        NUMERIC                                                     100                           1                                                           0-4095                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {vlan_outer_user_priority      VlanIf_Outer                                                Priority                      NUMERIC                                                     100                           7                                                           0-7                           true                          _none_                                                      false                         _none_                        _none_                        _none_}
         }

         {emulation_rip_control
            {hname                         stcobj                                                      stcattr                       type                                                        priority                      default                                                     range                         supported                     dependency                                                  mandatory                     procfunc                      mode                          constants}
            {advertise                     _none_                                                      _none_                        ANY                                                         100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {flap_count                    _none_                                                      _none_                        NUMERIC                                                     100                           1                                                           1-4294967295                  true                          {mandatory {mode flap}}                                     false                         _none_                        _none_                        _none_}
            {flap_down_time                _none_                                                      _none_                        NUMERIC                                                     100                           0                                                           0-4294967295                  true                          {mandatory {mode flap}}                                     false                         _none_                        _none_                        _none_}
            {flap_interval_time            _none_                                                      _none_                        NUMERIC                                                     100                           0                                                           0-4294967295                  true                          {mandatory {mode flap}}                                     false                         _none_                        _none_                        _none_}
            {flap_routes                   _none_                                                      _none_                        ANY                                                         100                           _none_                                                      _none_                        true                          {mandatory {mode flap}}                                     false                         _none_                        _none_                        _none_}
            {handle                        _none_                                                      _none_                        ANY                                                         20                            _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {mode                          _none_                                                      _none_                        {CHOICES start stop restart flap}                           10                            _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
            {port_handle                   _none_                                                      _none_                        ANY                                                         20                            _none_                                                      _none_                        true                          false                                                       _none_                        _none_                        _none_                        _none_}
            {withdraw                      _none_                                                      _none_                        ANY                                                         100                           _none_                                                      _none_                        true                          _none_                                                      false                         _none_                        _none_                        _none_}
         }

         {emulation_rip_route_config
            {hname                         stcobj                                                                                       stcattr                       type                                                        priority                      default                                                   range                         supported                     dependency                                                  mandatory                     procfunc                        mode                          constants}
            {handle                        _none_                                                                                       _none_                        ANY                                                         20                            _none_                                                    _none_                        true                          {mandatory {mode create}}                                    false                         _none_                        _none_                        _none_}
            {metric                        {ripv1 Ripv4RouteParams ripv2 Ripv4RouteParams ripng RipngRouteParams}                       Metric                        NUMERIC                                                     100                           1                                                         1-16                          true                          {stcobj {hname session_type}}                                false                         _none_                        _none_                        _none_}
            {mode                          _none_                                                                                       _none_                        {CHOICES create modify delete}                              10                            _none_                                                    _none_                        true                          _none_                                                       true                          _none_                        _none_                        _none_}
            {next_hop                      {ripv1 Ripv4RouteParams ripv2 Ripv4RouteParams ripng RipngRouteParams}                       NextHop                       IP                                                          100                           {ripv1 0.0.0.0 ripv2 0.0.0.0 ripng null}                  _none_                        true                          {stcobj {hname session_type} default {hname session_type}}   false                         _none_                        _none_                        _none_}
            {num_prefixes                  {ripv1 Ipv4NetworkBlock ripv2 Ipv4NetworkBlock ripng Ipv6NetworkBlock}                       NetworkCount                  NUMERIC                                                     100                           1                                                         1-1000000                     true                          {stcobj {hname session_type}}                                false                         _none_                        _none_                        _none_}
            {prefix_length                 {ripv1 Ipv4NetworkBlock ripv2 Ipv4NetworkBlock ripng Ipv6NetworkBlock}                       PrefixLength                  NUMERIC                                                     100                           {ripv1 24 ripv2 24 ripng 64}                              _none_                        true                          {stcobj {hname session_type} default {hname session_type}}   false                         _none_                        _none_                        _none_}
            {prefix_start                  {ripv1 Ipv4NetworkBlock ripv2 Ipv4NetworkBlock ripng Ipv6NetworkBlock}                       StartIpList                   IP                                                          100                           {ripv1 0.0.0.0 ripv2 0.0.0.0 ripng 0:0:0:0:0:0:0:0}       _none_                        true                          {stcobj {hname session_type} default {hname session_type}}   false                         _none_                        _none_                        _none_}
            {prefix_step                   {ripv1 Ipv4NetworkBlock ripv2 Ipv4NetworkBlock ripng Ipv6NetworkBlock}                       AddrIncrement                 NUMERIC                                                     100                           {ripv1 24 ripv2 24 ripng 64}                              1-128                         true                          {stcobj {hname session_type} default {hname session_type}}   false                         _none_                        _none_                        _none_}
            {route_handle                  _none_                                                                                       _none_                        ANY                                                         20                            _none_                                                    _none_                        true                          {mandatory {mode modify mode delete}}                        false                         _none_                        _none_                        _none_}
            {route_tag                     {ripv1 Ripv4RouteParams ripv2 Ripv4RouteParams ripng RipngRouteParams}                       RouteTag                      NUMERIC                                                     100                           0                                                         0-65535                       true                          {stcobj {hname session_type}}                                false                         _none_                        _none_                        _none_}
         }
   }
}
