namespace eval ::sth::sip {
    set sipTable {
        ::sth::sip::
        {emulation_sip_config
            {hname                          stcobj                  stcattr                                   type                                        priority       default         range      supported   dependency                  mandatory       procfunc                                        mode                                                                    constants}
            {mode                           _none_                  _none_       {CHOICES create modify delete enable disable enable_all disable_all}       10          _none_          _none_          true        _none_                      true        _none_                                          _none_                                                                  _none_}
            {handle                         _none_                  _none_                                  ALPHANUM                                        11          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}  
            {port_handle                    _none_                  _none_                                  ALPHANUM                                        12          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {count                          Emulateddevice          DeviceCount                             NUMERIC                                         14          1               _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {ip_version                     _none_                  _none_                                  {CHOICES 4 6 4_6}                               14          4               _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {router_id                       Emulateddevice          RouterId                                IPV4                                           14          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {name                           SipUaProtocolConfig     Name                                    ALPHANUM                                        15          _none_          _none_          true        _none_                      false       _none_                                          {create configSipUaProtocolConfig modify configSipUaProtocolConfig}                                                                  _none_}
            {vlan_id1                       VlanIf                  VlanId                                  NUMERIC                                         16          _none_          0-4095          true        _none_                      false       processEmulation_sip_config_vlanId              {create configVlanIfInner modify configVlanIfInner}                     _none_}
            {vlan_ether_type1               VlanIf                  Tpid                                    {CHOICES 0x8100 0x88A8 0x9100 0x9200}           17          _none_          _none_          true        _none_                      false       processEmulation_sip_config_vlanType            {create configVlanIfInner modify configVlanIfInner}                     _none_}
            {vlan_id_mode1                  VlanIf                  _none_                                 {CHOICES fixed increment}                       18          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  {fixed TRUE increment FALSE}}
            {vlan_id_step1                  VlanIf                  IdStep                                  NUMERIC                                         19          _none_          0-4095          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {vlan_id2                       VlanIf_Outer            VlanId                                  NUMERIC                                         20          _none_          0-4095          true        _none_                      false       processEmulation_sip_config_vlanId              {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
            {vlan_ether_type2               VlanIf_Outer            Tpid                                    {CHOICES 0x8100 0x88A8 0x9100 0x9200}           21          _none_          _none_          true        _none_                      false       processEmulation_sip_config_vlanType            {create configVlanIfOuter modify configVlanIfOuter}                     _none_}
            {vlan_id_mode2                  VlanIf_Outer            _none_                                 {CHOICES fixed increment}                       22          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  {fixed TRUE increment FALSE}}
            {vlan_id_step2                  VlanIf_Outer            IdStep                                  NUMERIC                                         23          _none_          0-4095          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {local_ip_addr                  Ipv4If                  Address                                 IPV4                                            24          _none_          _none_          true        _none_                      false       _none_                                          {create configIpInterface modify configIpInterface}                     _none_}
            {local_ip_addr_step             Ipv4If                  AddrStep                                NUMERIC                                         25          1               _none_          true        _none_                      false       processEmulation_sip_config_ip_addr_step        {create configIpInterface modify configIpInterface}                     _none_}
            {local_ip_addr_repeat           Ipv4If                  AddrRepeatCount                         NUMERIC                                         26          1               _none_          true        _none_                      false       processEmulation_sip_config_ip_addr_repeat      {create configIpInterface modify configIpInterface}                     _none_}
            {remote_ip_addr                 Ipv4If                  Gateway                                 IPV4                                            27          _none_          _none_          true        _none_                      false       _none_                                          {create configIpInterface modify configIpInterface}                     _none_}
            {remote_ip_addr_step            Ipv4If                  GatewayStep                             NUMERIC                                         28          0               _none_          true        _none_                      false       processEmulation_sip_config_ip_addr_step        {create configIpInterface modify configIpInterface}                     _none_}
            {remote_ip_addr_repeat          Ipv4If                  GatewayRepeatCount                      NUMERIC                                         29          1               _none_          true        _none_                      false       processEmulation_sip_config_ip_addr_repeat      {create configIpInterface modify configIpInterface}                     _none_}
            {intf_ipv6_addr		    Ipv6If		    Address				    IPV6					    29		_none_ 		_none_ 	        true        _none_ 		        false 	    _none_      				    {create configIpv6Interface modify configIpv6Interface}                 _none_}
            {intf_ipv6_addr_step	    Ipv6If		    AddrStep			            IPV6					    29		::1		_none_ 	        true 	    _none_ 		        false 	    _none_	 				    {create configIpv6Interface modify configIpv6Interface}                 _none_}
            {local_ipv6_addr	            Ipv6If_Link_Local	    Address                                 IPV6					    29		_none_		_none_ 	        true 	    _none_ 		        false 	    _none_	 				    _none_                                                                  _none_}
            {gateway_ipv6_addr		    Ipv6If		    Gateway			            IPV6					    29		_none_ 		_none_ 	        true 	    _none_ 		        false 	    _none_					    {create configIpv6Interface modify configIpv6Interface}                 _none_}
            {gateway_ipv6_addr_step	    Ipv6If 		    GatewayStep		                    IPV6 					    29          ::1		_none_ 	        true 	    _none_ 		        false 	    _none_				            {create configIpv6Interface modify configIpv6Interface}                 _none_}
            {gateway_enable                 _none_                  _none_                                  {CHOICES 0 1}                                   30          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {gateway_ipv4_address           _none_                  _none_                                  IPV4                                            31          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {local_username_prefix          SipUaProtocolConfig     UaNumFormat                             ALPHANUM                                        32          _none_          _none_          true        _none_                      false       processEmulation_sip_config_local_username      {create configSipUaProtocolConfig modify configSipUaProtocolConfig}     _none_}
            {local_username_suffix          SipUaProtocolConfig     UaNumStart                              NUMERIC                                         33          _none_   0-18446744073709551615  true       _none_                      false       _none_                                          {create configSipUaProtocolConfig modify configSipUaProtocolConfig}     _none_}
            {local_username_suffix_step     SipUaProtocolConfig     UaNumStep                               NUMERIC                                         34          _none_   0-18446744073709551615  true       _none_                      false       _none_                                          {create configSipUaProtocolConfig modify configSipUaProtocolConfig}     _none_}
            {user_agents_per_device          SipUaProtocolConfig     UaNumsPerDevice                         NUMERIC                                         34            1             1-32768         true        _none_                      false       _none_                                          {create configSipUaProtocolConfig modify configSipUaProtocolConfig}     _none_}
            {local_domain                   SipUaProtocolProfile    ProxyDomain                             ALPHANUM                                        35          _none_          _none_          true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {remote_username_prefix         SipUaProtocolProfile    _none_                                  ALPHANUM                                        36          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_username_suffix         SipUaProtocolProfile    _none_                                  NUMERIC                                         37          _none_  0-18446744073709551615  true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_username_suffix_step    SipUaProtocolProfile    _none_                                  NUMERIC                                         38          _none_  0-18446744073709551615  true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {call_using_aor                 SipUaProtocolProfile    _none_                                  {CHOICES 0 1}                                   39          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_domain                  SipUaProtocolProfile    _none_                                  ALPHANUM                                        40          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_host                    SipUaProtocolProfile    _none_                                  IP                                              41          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_host_repeat             SipUaProtocolProfile    _none_                                  NUMERIC                                         42          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {remote_host_step               SipUaProtocolProfile    _none_                                  ANY                                             43          _none_          _none_          true        _none_                      false       _none_                                          _none_                                                                  _none_}
            {registration_server_enable     SipUaProtocolProfile    UseUaToUaSignaling                      {CHOICES 0 1}                                   44          0               _none_          true        _none_                      false       processEmulation_sip_config_registration        {create configSipUaProtocolProfile modify configSipUaProtocolProfile}    {0 true 1 false}}
            {registrar_address              SipUaProtocolProfile    ProxyIpv4Addr                           IPV4                                            45          _none_          _none_          true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {desired_expiry_time            SipUaProtocolProfile    RegExpires                              NUMERIC                                         46          _none_          1-4294967295    true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {media_payload_type             SipUaProtocolProfile    AudioCodec                              {CHOICES SIP_MEDIA_ITU_G711_64K_240BYTE \
                                                                                                                SIP_MEDIA_ITU_G711_64K_160BYTE \
                                                                                                                SIP_MEDIA_ITU_G723_6K3_24BYTE \
                                                                                                                SIP_MEDIA_ITU_G723_5K3_20BYTE \
                                                                                                                SIP_MEDIA_ITU_G723_5K3_40BYTE \
                                                                                                                SIP_MEDIA_ITU_G729_8K_20BYTE  \
                                                                                                                SIP_MEDIA_ITU_G729_8K_40BYTE}               47          _none_          _none_          true        _none_                      false       processEmulation_sip_config_media_type          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   {SIP_MEDIA_ITU_G711_64K_240BYTE G_711\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G711_64K_160BYTE G_711\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G723_6K3_24BYTE G_723_1\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G723_5K3_20BYTE G_723_1\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G723_5K3_40BYTE G_723_1\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G729_8K_20BYTE  G_729\
                                                                                                                                                                                                                                                                                                                                                                                    SIP_MEDIA_ITU_G729_8K_40BYTE G_729}}
            {media_port_number              SipUaProtocolProfile    AudioSrcPort                            NUMERIC                                         48          50050           0-65535         true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {call_accept_delay_enable       _none_                  _none_                                  {CHOICES 0 1}                                   49          _none_          _none_          true       {call_accept_delay_enable 1} false       _none_                                          _none_                                                                  _none_}
            {response_delay_interval        SipUaProtocolProfile    RingTime                                NUMERIC                                         50          _none_          0-4294967295    true        _none_                      false       processEmulation_sip_config_ringTime            {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {call_duration                  SipUaProtocolProfile    CallTime                                NUMERIC                                         50          _none_          0-4294967295    true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {mac_address_start              EthIIIf                 SourceMac                               ANY                                             51          _none_          _none_          true        _none_                      false       _none_                                          {create configEthIIIntf modify configEthIIIntf}                         _none_}
            {local_port                     SipUaProtocolConfig     LocalPort                               NUMERIC                                         70          _none_          0-65535         true        _none_                      false       _none_                                          {create configSipUaProtocolConfig modify configSipUaProtocolConfig}     _none_}
            {proxy_server_port              SipUaProtocolProfile    ProxyPort                               NUMERIC                                         71          _none_          0-65535         true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {use_compact_headers            SipUaProtocolProfile    UseCompactHeaders                       {CHOICES 0 1}                                   72          _none_          _none_          true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {proxy_domain                   SipUaProtocolProfile    ProxyDomain                             ALPHANUM                                        73          _none_          _none_          false       _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {call_type                      SipUaProtocolProfile    CallType                {CHOICES SIGNALING_ONLY AUDIO_ONLY AUDIO_VIDEO TELEPRESENCE}    74          _none_          _none_          true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {video_type                     SipUaProtocolProfile    VideoCodec {CHOICES H_263 H_264 MP4V_ES H_264_720p H_264_1080p H_264_512_288 H_264_768_448} 75      _none_          _none_          true        _none_                      false       processEmulation_sip_config_vedio_type          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {video_port_number              SipUaProtocolProfile    VideoSrcPort                            NUMERIC                                         76          _none_          0-65535         true        _none_                      false       _none_                                          {create configSipUaProtocolProfile modify configSipUaProtocolProfile}   _none_}
            {device                         _none_                  _none_                                  {CHOICES sipIPv4Device \
                                                                                                                sipIPv4DhcpClientDevice \
                                                                                                                sipIPv4PppoeClientDevice}                   99          _none_          _none_          false       _none_                      false       _none_                                          _none_                                                                  _none_}
        }
        {emulation_sip_control
            {hname                          stcobj                  stcattr                 type                                        priority       default         range      supported  dependency   mandatory       procfunc                                mode                                    constants}
            {handle                         _none_                  _none_                  ALPHANUM                                        10          _none_          _none_          true    _none_          false       _none_                                  _none_                                      _none_}
            {action                         _none_                  _none_              {CHOICES register deregister establish terminate}   11          _none_          _none_          true    _none_          false       _none_                                  _none_                                      _none_}
            {action_control                 _none_                  _none_                  {CHOICES start stop}                            99          _none_          _none_          true    _none_          false       _none_                                  _none_                                      _none_}
            {batch_rate                     _none_                  _none_                  NUMERIC                                         99          _none_          _none_          true    _none_          false       _none_                                  _none_                                      _none_}
            {batch_rate_interval            _none_                  _none_                  NUMERIC                                         99          _none_          _none_          false   _none_          false       _none_                                  _none_                                      _none_}
            {job_handle                     _none_                  _none_                  NUMERIC                                         99          _none_          _none_          false   _none_          false       _none_                                  _none_                                      _none_}
        }
        {emulation_sip_stats
            {hname                          stcobj                  stcattr                 type                            priority       default         range        supported  dependency   mandatory       procfunc           mode               constants}
            {handle                         _none_                  _none_                  ALPHANUM                            10          _none_          _none_          true    _none_          false       _none_          _none_                  _none_}
            {action                         _none_                  _none_                  {CHOICES collect clear}             11          _none_          _none_          true    _none_          false       _none_          _none_                  _none_}
            {mode                           _none_                  _none_                  {CHOICES device}                    12          _none_          _none_          true    _none_          false       _none_          _none_                  _none_}
            {established_sessions           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {active_registrations           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {attempted_sessions             SipUaResults            CallAttemptCount        NUMERIC                             13          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {successful_sessions            SipUaResults            CallSuccessCount        NUMERIC                             14          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {unsuccessful_sessions          SipUaResults            CallFailureCount        NUMERIC                             15          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {attempted_termination          _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {successful_termination         _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {unsuccessful_termination       _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {avg_establishment_time         SipUaResults            CallAvgTime             NUMERIC                             16          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {min_establishment_time         SipUaResults            CallMinTime             NUMERIC                             17          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {max_establishment_time         SipUaResults            CallMaxTime             NUMERIC                             18          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {avg_termination_time           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {min_termination_time           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {max_termination_time           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {attempted_terminations         _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {attempted_registrations        SipUaResults            RegistrationAttemptCount    NUMERIC                         19          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {successful_registrations       SipUaResults            RegistrationSuccessCount    NUMERIC                         19          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {unsuccessful_registrations     SipUaResults            RegistrationFailureCount    NUMERIC                         20          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {attempted_deregistrations      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {successful_deregistrations     _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {unsuccessful_deregistrations   _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {avg_registration_time          SipUaResults            RegistrationAvgTime     NUMERIC                             21          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {min_registration_time          SipUaResults            RegistrationMinTime     NUMERIC                             22          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {max_registration_time          SipUaResults            RegistrationMaxTime     NUMERIC                             23          _none_          _none_          true    _none_          false       _none_          {device ""}             _none_}
            {avg_deregistration_time        _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {min_deregistration_time        _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {max_deregistration_time        _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_invite_requests             _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_register_requests           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_cancel_requests             _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_ack_requests                _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_bye_requests                _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_informational_requests      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_success_responses           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_client_error_responses      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {tx_server_error_responses      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_invite_requests             _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_register_requests           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_cancel_requests             _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_ack_requests                _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_bye_requests                _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_informational_responses     _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_success_responses           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_redirection_responses       _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_} 
            {rx_client_error_responses      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_server_error_responses      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {rx_global_error_responses      _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {retransmitted_requests         _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {retransmitted_responses        _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {transaction_timeouts           _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {to_no_session_transistions     _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {to_establishing_sessions       _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {to_established_transistions    _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {to_refreshing_transistions     _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
            {to_terminating_transistions    _none_                  _none_                  NUMERIC                             99          _none_          _none_          false   _none_          false       _none_          {device ""}             _none_}
        }
    }
}