# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::Stp:: {
}
set ::sth::Stp::stpTable {
    ::sth::Stp::                                                               
    {emulation_stp_config                                                          
        {   hname                           stcobj              stcattr                  type                                            priority           default             range        supported     dependency                               mandatory        procfunc                                          mode                                         constants}
        {   port_handle                     _none_              _none_                    ALPHANUM                                          1               _none_              _none_          true         _none_                                  false          _none_                                            _none_                                         _none_  }
        {   handle                          _none_              _none_                    ALPHANUM                                          1               _none_              _none_          true         _none_                                  false          _none_                                            _none_                                         _none_  }
        {   mode                            _none_              _none_                   {CHOICES create modify delete enable disable}      2               _none_              _none_          true         _none_                                  true           _none_                                            _none_                                         _none_  }
        {   count                           Router              count                    NUMERIC                                           3                  1                _none_          true         _none_                                  false          _none_                                            _none_                                         _none_  }
        {   ip_version                      _none_              _none_                   {CHOICES ipv4 ipv6 none}                           3                ipv4               _none_          true         _none_                                  false          _none_                                            _none_                                         _none_  }
        {   encap                           _none_              _none_          {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}     3              ethernet_ii          _none_          true         _none_                                  false          _none_                                            _none_                                         _none_  }
        {   mac_addr                        EthIIIf             SourceMac                 MAC                                               4               _none_              _none_          true         _none_                                  false          _none_                         {create configEthIIIntf modify configEthIIIntf}                   _none_  }
        {   mac_addr_step                   EthIIIf             SrcMacStep                MAC                                               4               _none_              _none_          true         _none_                                  false          _none_                         {create configEthIIIntf modify configEthIIIntf}                   _none_  }
        {   local_ip_addr                   Ipv4If              Address                   IPV4                                              4               _none_              _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   local_ip_addr_step              Ipv4If              AddrStep                  IPV4                                              4               0.0.0.1             _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   local_ip_prefix_len             Ipv4If              PrefixLength              NUMERIC                                           4                 24                0-32            true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   local_ipv6_addr                 Ipv6If              Address                   IPV6                                              4               _none_              _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   local_ipv6_addr_step            Ipv6If              AddrStep                  IPV6                                              4                 ::1               _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   local_ipv6_prefix_len           Ipv6If              PrefixLength              NUMERIC                                           4                 64                0-128           true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   gateway_ip_addr                 Ipv4If              Gateway                   IPV4                                              4               _none_              _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   gateway_ip_addr_step            Ipv4If              GatewayStep               IPV4                                              4              0.0.0.0              _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   gateway_ipv6_addr               Ipv6If              Gateway                   IPV6                                              4               _none_              _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   gateway_ipv6_addr_step          Ipv6If              GatewayStep               IPV6                                              4                ::                 _none_          true         _none_                                  false          _none_                         {create configIpIntf modify configIpIntf}                         _none_  }
        {   qinq_incr_mode                  _none_              _none_                   {CHOICES inner outer both}                         4               _none_              _none_          true         _none_                                  false          _none_                         _none_                                                            _none_  }
        {   vlan_id                         VlanIf              VlanId                    NUMERIC                                           5                100                0-4095          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     processConfigCmd_vlanId        {create configVlanIfInner modify configVlanIfInner}               _none_  }
        {   vlan_id_step                    VlanIf              IdStep                    NUMERIC                                           5                 1                 0-4095          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                         {create configVlanIfInner modify configVlanIfInner}               _none_  }
        {   vlan_id_count                   _none_              _none_                    NUMERIC                                           5                 1                 1-4096          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                                            _none_                                         _none_  }
        {   vlan_id_mode                    _none_              _none_                   {CHOICES fixed increment}                          5               _none_              _none_          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                                            _none_                                         _none_  }
        {   vlan_user_priority              VlanIf              Priority                  NUMERIC                                           5                 0                 0-7             true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false     _none_                         {create configVlanIfInner modify configVlanIfInner}               _none_  }
        {   vlan_cfi                        VlanIf              Cfi                      {CHOICES 0 1}                                      5                 1                 _none_          true  {{encap ethernet_ii_vlan} {encap ethernet_ii_qinq}} false    _none_                          {create configVlanIfInner modify configVlanIfInner}               _none_  }  
        {   vlan_id_outer                   VlanIf_Outer              VlanId                    NUMERIC                                           5                100                0-4095          true    {{encap ethernet_ii_qinq}}                   false          processConfigCmd_vlanId        {create configVlanIfOuter modify configVlanIfOuter}               _none_  }
        {   vlan_id_outer_step              VlanIf_Outer              IdStep                    NUMERIC                                           5                 1                 0-4095          true    {{encap ethernet_ii_qinq}}                   false          _none_                         {create configVlanIfOuter modify configVlanIfOuter}               _none_  }
        {   vlan_id_outer_count             VlanIf_Outer              _none_                    NUMERIC                                           5                 1                 1-4096          true    {{encap ethernet_ii_qinq}}                   false          _none_                                            _none_                                         _none_  }
        {   vlan_id_outer_mode              _none_              _none_                   {CHOICES fixed increment}                          5               _none_              _none_          true    {{encap ethernet_ii_qinq}}                   false          _none_                                            _none_                                         _none_  }
        {   vlan_outer_user_priority        VlanIf_Outer              Priority                  NUMERIC                                           5                 0                 0-7             true    {{encap ethernet_ii_qinq}}                   false          _none_                         {create configVlanIfOuter modify configVlanIfOuter}               _none_  }
        {   vlan_outer_cfi                  VlanIf              Cfi                      {CHOICES 0 1}                                      5                 1                 _none_          true    {{encap ethernet_ii_qinq}}                   false          _none_                         {create configVlanIfOuter modify configVlanIfOuter}               _none_  }
        {   stp_type                        StpPortConfig       StpType                  {CHOICES stp rstp pvst rpvst mstp}                 6               _none_              _none_          true         _none_                                  false          _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   port_type                       StpPortConfig       PortType                 {CHOICES trunk access}                             7               trunk               _none_          true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   ether_type                      StpPortConfig       EthernetType              ANY                                               7               8100                _none_          true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   native_vlan                     StpPortConfig       NativeVlan                NUMERIC                                           7               _none_              1-4094          true  {{stp_type pvst} {stp_type rpvst} {stp_type mstp}} false      _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   enable_pt2pt_link               StpPortConfig       EnablePt2PtLink          {CHOICES true false}                               7               false               _none_          true     {{stp_type rstp}}                           false          _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   enable_mac_addr_reduction       StpPortConfig       EnableMacAddrReduction   {CHOICES true false}                               7               false               _none_          true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configStpPortConfig modify configStpPortConfig}           _none_  }
        {   bridge_priority                 BridgePortConfig    BridgePriority            NUMERIC                                           8               32768               0-65535         true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   bridge_mac_address              BridgePortConfig    BridgeMacAddr             MAC                                               8          00:00:10:00:10:00        _none_          true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   port_priority                   BridgePortConfig    PortPriority              NUMERIC                                           8                128                0-255           true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   port_number                     BridgePortConfig    PortNum                   NUMERIC                                           8                 1                 1-255           true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   msg_age                         BridgePortConfig    MsgAgeTime                NUMERIC                                           11                1                 1-39            true   {{root_bridge_type custom}}                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   max_age_time                    BridgePortConfig    MaxAgeTime                NUMERIC                                           11                20                6-40            true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   hello_time                      BridgePortConfig    HelloTime                 NUMERIC                                           11                2                 1-10            true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   forward_delay                   BridgePortConfig    ForwardDelay              NUMERIC                                           11                15                4-30            true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   hold_count                      BridgePortConfig    HoldCount                 NUMERIC                                           11                3                 1-30            true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   root_bridge_type                BridgePortConfig    RootBridge               {CHOICES custom self}                              13              _none_              _none_          true        _none_                                   false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   root_priority                   BridgePortConfig    RootPriority              NUMERIC                                           10              32768               0-65535         true     {{root_bridge_type custom}}                 false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   root_mac_address                BridgePortConfig    RootMacAddr               MAC                                               10         00:00:10:00:10:00        _none_          true     {{root_bridge_type custom}}                 false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   root_path_cost                  BridgePortConfig    RootPortCost              NUMERIC                                           10                0                 0-200000000     true     {{root_bridge_type custom}}                 false          _none_                         {create configBridgePortConfig modify configBridgePortConfig}     _none_  }
        {   event_log_level                 BridgePortConfig    EventLogLevel            {CHOICES convergence_events debug}                 12              debug               _none_          true        _none_                                   false         processConfigFwdCmd             {create configBridgePortConfig modify configBridgePortConfig}  {convergence_events EVENT_LOG_LEVEL_CONVERGENCE_EVENTS debug EVENT_LOG_LEVEL_DEBUG}}
        {   vlan_start                      VlanBlock           StartVlanList             NUMERIC                                           13               100                0-4095          true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configVlanBlockConfig modify configVlanBlockConfig}       _none_  }
        {   vlan_count                      VlanBlock           NetworkCount              NUMERIC                                           13                1                 _none_          true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configVlanBlockConfig modify configVlanBlockConfig}       _none_  }
        {   vlan_priority                   VlanBlock           Priority                  NUMERIC                                           13                1                 0-7             true   {{stp_type pvst} {stp_type rpvst}}            false          _none_                         {create configVlanBlockConfig modify configVlanBlockConfig}       _none_  }
        {   region_root_bridge_type     MstpBridgePortConfig    RegionRootBridge         {CHOICES custom self}                              14              _none_              _none_          true     {{stp_type mstp}}                           false          _none_                   {create configMstpBridgePortConfig modify configMstpBridgePortConfig}   _none_  }
        {   region_root_priority        MstpBridgePortConfig    CistRegionalRootPriority  NUMERIC                                           15              32768               0-65535         true  {{stp_type mstp} {region_root_bridge_type custom}}  false     _none_                   {create configMstpBridgePortConfig modify configMstpBridgePortConfig}   _none_  }
        {   region_root_mac_address     MstpBridgePortConfig    CistRegionalRootMacAddr   MAC                                               15         00:00:10:00:10:00        _none_          true  {{stp_type mstp} {region_root_bridge_type custom}}  false     _none_                   {create configMstpBridgePortConfig modify configMstpBridgePortConfig}   _none_  }
        {   region_root_path_cost       MstpBridgePortConfig    CistInternalRootPathCost  NUMERIC                                           15                0                 0-200000000     true  {{stp_type mstp} {region_root_bridge_type custom}}  false     _none_                   {create configMstpBridgePortConfig modify configMstpBridgePortConfig}   _none_  }
        {   remaining_hops              MstpBridgePortConfig    RemainingHops             NUMERIC                                           15                16                1-255           true  {{stp_type mstp} {region_root_bridge_type custom}}  false     _none_                   {create configMstpBridgePortConfig modify configMstpBridgePortConfig}   _none_  }
    }
    {emulation_mstp_region_config
        {   hname                           stcobj              stcattr                  type                                            priority    default     range        supported    dependency      mandatory   procfunc                              mode                                     constants }
        {   port_handle                     _none_              _none_                   ALPHANUM                                           1        _none_      _none_          true        _none_          false       _none_                            _none_                                       _none_  }
        {   handle                          _none_              _none_                   ALPHANUM                                           1        _none_      _none_          true        _none_          false       _none_                            _none_                                       _none_  }
        {   mode                            _none_              _none_                   {CHOICES create modify delete}                     2        _none_      _none_          true        _none_          true        _none_                            _none_                                       _none_  }
        {   mstp_region_name                MstpRegionConfig    RegionName                ALPHANUM                                          12       _none_      _none_          true        _none_          false       _none_       {create configMstpRegionConfig modify configMstpRegionConfig}     _none_  }
        {   mstp_version_num                MstpRegionConfig    VersionNum                NUMERIC                                           13       1           0-65535         true        _none_          false       _none_       {create configMstpRegionConfig modify configMstpRegionConfig}     _none_  }
        {   mstp_instance_count             MstpRegionConfig    MstInstanceCount          NUMERIC                                           14       1            0-64           true        _none_          false       _none_       {create configMstpRegionConfig modify configMstpRegionConfig}     _none_  }
        {   mstp_instance_vlan_list         MstpRegionConfig    InstanceVlanList          ANY                                               14       1           _none_          true        _none_          false       _none_       {create configMstpRegionConfig modify configMstpRegionConfig}     _none_  }
        {   mstp_instance_num_list          MstpRegionConfig    InstanceNumList           NUMERIC                                           14       1           _none_          true        _none_          false       _none_       {create configMstpRegionConfig modify configMstpRegionConfig}     _none_  }
    }
    {emulation_msti_config
        {   hname                           stcobj              stcattr                   type                                           priority    default     range        supported    dependency                       mandatory    procfunc                 mode               constants}
        {   port_handle                     _none_              _none_                    ALPHANUM                                          1        _none_      _none_          true        _none_                           false       _none_                 _none_                 _none_ }
        {   handle                          _none_              _none_                    ALPHANUM                                          1        _none_      _none_          true        _none_                           false       _none_                 _none_                 _none_ }
        {   mstp_region_name                _none_              _none_                    ALPHANUM                                          12       _none_      _none_          true        _none_                           false       _none_                 _none_                 _none_ }
        {   msti_instance_num               MstiConfig          InstanceNum               NUMERIC                                           12       1           _none_          true        _none_                           false       _none_                 _none_                 _none_ }
        {   msti_bridge_priority            Msticonfig          BridgePriority            NUMERIC                                           15       32768       0-65535         true        _none_                           false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_port_priority              Msticonfig          PortPriority              NUMERIC                                           15       128         0-255           true        _none_                           false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_root_bridge_type           Msticonfig          RegionRootBridge         {CHOICES custom self}                              16       self        _none_          true        _none_                           false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_region_root_priority       Msticonfig          CistRegionalRootPriority  NUMERIC                                           17       32768       0-65535         true   {{msti_root_bridge_type custom}}      false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_region_root_mac_address    Msticonfig          CistRegionalRootMacAddr   MAC                                               17  00:00:10:00:10:00 _none_         true   {{msti_root_bridge_type custom}}      false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_region_root_path_cost      Msticonfig          CistInternalRootPathCost  NUMERIC                                           17       0           0-200000000     true   {{msti_root_bridge_type custom}}      false       _none_             {modify configMstiConfig}  _none_ }
        {   msti_remaining_hops             Msticonfig          RemainingHops             NUMERIC                                           18       16          1-255           true   {{msti_root_bridge_type custom}}      false       _none_             {modify configMstiConfig}  _none_ }
    }
    {emulation_stp_control                                                         
        {   hname               stcobj  stcattr             type                        priority        default          range         supported   dependency  mandatory   procfunc                       mode    constants}
        {   type                _none_  _none_     {CHOICES bridge_port cist msti}         1            bridge_port     _none_          true        _none_      false       _none_                        _none_  _none_  }
        {   handle              _none_  _none_      ALPHANUM                               1            _none_          _none_          true        _none_      false       _none_                        _none_  _none_  }
        {   action              _none_  _none_     {CHOICES start stop init_topo_change}   1            _none_          _none_          true        _none_      true        _none_                        _none_  _none_  }
        {   port_handle         _none_  _none_      ALPHANUM                               1            _none_          _none_          true        _none_      false       _none_                        _none_  _none_  }
    }                                                  
    {emulation_stp_stats
        {   hname                  stcobj                  stcattr            type                    priority    default     range           supported   dependency      mandatory   procfunc         mode                   constants}
        {   port_handle            _none_                   _none_           ALPHANUM                    1         _none_      _none_             TRUE       _none_          false      _none_        _none_                   _none_  }
        {   handle                 _none_                   _none_           ALPHANUM                    1         _none_      _none_             TRUE       _none_          false      _none_        _none_                   _none_  }
        {   mode                   _none_                   _none_       {CHOICES both stp msti}         1          both       _none_             TRUE       _none_          false      _none_        _none_                   _none_  }
        {   port_id                BridgePortResults        PortId             ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   bridge_id              BridgePortResults        BridgeId           ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   root_id                BridgePortResults        RootId             ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   regional_root_id       BridgePortResults        RegionalRootId     ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   designated_bridge_id   BridgePortResults        DesignatedId       ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_bpdus               BridgePortResults        TxBpdus            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_bpdus               BridgePortResults        RxBpdus            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_bpdu_flag           BridgePortResults        TxBpduFlag         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_bpdu_flag           BridgePortResults        RxBpduFlag         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_tc_bit_set          BridgePortResults        TxTcBitSet         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_tc_bit_set          BridgePortResults        RxTcBitSet         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_tc_ack              BridgePortResults        TxTcAck            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_tc_ack              BridgePortResults        RxTcAck            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_tcns                BridgePortResults        TxTcn              ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_tcns                BridgePortResults        RxTcn              ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_proposals           BridgePortResults        TxProposals        ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_proposals           BridgePortResults        RxProposals        ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_tc_agree            BridgePortResults        TxAgree            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_tc_agree            BridgePortResults        RxAgree            ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_port_role           BridgePortResults        TxPortRole         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_port_role           BridgePortResults        RxPortRole         ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   tx_port_state          BridgePortResults        TxPortState        ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   rx_port_state          BridgePortResults        RxPortState        ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp "" msti ""}  _none_  }
        {   vlan_id                BridgePortResults        VlanId             ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" stp ""}          _none_  }
        {   instance_num           BridgePortResults        InstanceNum        ANY                       1         _none_      _none_             TRUE       _none_          false      _none_        {both "" msti ""}         _none_  }
    }
}