# This file contains confidential and / or privileged information belonging to Spirent Communications plc,
# its affiliates and / or subsidiaries.

namespace eval ::sth::synce:: {
}

set ::sth::synce::synceTable {
 ::sth::synce::

 { emulation_synce_config  
    { hname                             stcobj                    stcattr                         type                                                   priority                default                 range         supported       dependency          mandatory   procfunc                          mode                                       constants}
    { handle                            _none_                    _none_                          ALPHANUM                                                 1                      _none_                 _none_          true            _none_              false       _none_      _none_                                                          _none_}
    { port_handle                       _none_                    _none_                          ALPHANUM                                                 1                      _none_                 0-MAX_INT       true            _none_              false       _none_      _none_                                                          _none_}
    { mode                              _none_                    _none_                          {CHOICES create modify reset}                            2                      _none_                 _none_          true            _none_              true        _none_      _none_                                                          _none_}
    { ip_version                        _none_                    _none_                          {CHOICES 4 6 4_6}                                        3                        6                    _none_          true            _none_              false       _none_      _none_                                                          _none_}
    { encap                             _none_                    _none_                          {CHOICES ethernet_ii ethernet_vlan ethernet_ii_qinq}     3                      ethernet_ii            _none_          true            _none_              false       _none_      _none_                                                          _none_}
    { count                             EmulatedDevice            DeviceCount                     NUMERIC                                                  4                        1                    1-65536          true            _none_              false       _none_      _none_                                                          _none_} 
    { device_name                       _none_                    _none_                          ANY                                                      6                      _none_                 _none_          true            _none_              false       _none_      _none_                                                          _none_}
    { mac_addr                          EthIIIf                   SourceMac                       ANY                                                      6                      _none_                 _none_          true            _none_              false       _none_      {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { mac_addr_step                     EthIIIf                   SrcMacStep                      ANY                                                      7                      _none_                 _none_          true            _none_              false       _none_      {create configEthIIIntf modify configEthIIIntf}                 _none_}
    { local_ipv4_addr                   Ipv4If                    Address                         IPV4                                                     4                      _none_                 _none_          true            _none_              false       _none_      {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ipv4_addr_step              Ipv4If                    AddrStep                        IPV4                                                     4                      0.0.0.1                _none_          true            _none_              false       _none_      {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ipv4_prefix_len             Ipv4If                    PrefixLength                    NUMERIC                                                  4                       24                    0-32            true            _none_              false       _none_      {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { gateway_ipv4_addr                 Ipv4If                    Gateway                         IPV4                                                     4                      _none_                 _none_          true            _none_              false       _none_      {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { gateway_ipv4_addr_step            Ipv4If                    GatewayStep                     IPV4                                                     4                      0.0.0.0                _none_          true            _none_              false       _none_      {create configIpv4Intf modify configIpv4Intf}                   _none_}
    { local_ipv6_addr                   Ipv6If                    Address                         IPV6                                                     4                      _none_                 _none_          true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_addr_step              Ipv6If                    AddrStep                        IPV6                                                     4                       ::1                   _none_          true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { local_ipv6_prefix_len             Ipv6If                    PrefixLength                    NUMERIC                                                  4                       64                    0-128           true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr                 Ipv6If                    Gateway                         IPV6                                                     4                      _none_                 _none_          true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}
    { gateway_ipv6_addr_step            Ipv6If                    GatewayStep                     IPV6                                                     4                       ::                    _none_          true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}    
	{ ipv6_enable_gateway_learning      Ipv6If                    EnableGatewayLearning           _none_                                                   4                      false                   _none_         true            _none_              false       _none_      {create configIpv6Intf modify configIpv6Intf}                   _none_}    
	{ link_local_ipv6_addr           	Ipv6If_Link_Local         Address                         IPV6                                               	   14            		  fe80::1     			 _none_          true            _none_              false       _none_       _none_  _none_}
    { link_local_ipv6_addr_step      	Ipv6If_Link_Local         AddrStep                        IPV6                                                	   15           		   ::1        			 _none_          true            _none_              false       _none_       _none_  _none_}
    { link_local_ipv6_prefix_len     	Ipv6If_Link_Local         PrefixLength                    NUMERIC                                             	   16            		   64         			 1-128           true            _none_              false       _none_       _none_  _none_}
    { vlan_id                           VlanIf                    VlanId                          NUMERIC                                                  4                       1                    0-4095          true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_mode                      VlanIf                    _none_                          {CHOICES fixed increment }                               4                       fixed                _none_          true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_step                      VlanIf                    IdStep                          NUMERIC                                                  4                       1                    0-4094          true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_cfi                          VlanIf                    Cfi                             NUMERIC                                                  4                       1                    0-1             true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_priority                     VlanIf                    Priority                        NUMERIC                                                  4                       0                    0-7             true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_repeat_count              VlanIf                    IdRepeatCount                   NUMERIC                                                  4                       0                    _none_          true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_id_recycle_count             VlanIf                    IfRecycleCount                  NUMERIC                                                  4                       0                    _none_          true            _none_              false       _none_      {create configVlanIntf modify configVlanIntf}                   _none_}
    { vlan_outer_id                     VlanIf_Outer              VlanId                          NUMERIC                                                  4                       1                    0-4095          true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
    { vlan_outer_id_mode                VlanIf_Outer              _none_                          {CHOICES fixed increment }                               4                     fixed                  _none_          true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
    { vlan_outer_id_step                VlanIf_Outer              IdStep                          NUMERIC                                                  4                       1                    0-4094          true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
    { vlan_outer_cfi                    VlanIf_Outer              Cfi                             NUMERIC                                                  4                       1                    0-1             true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
    { vlan_outer_user_priority          VlanIf_Outer              Priority                        NUMERIC                                                  4                       0                    0-7             true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
    { vlan_outer_id_repeat_count        VlanIf_Outer              IdRepeatCount                   NUMERIC                                                  4                       0                    _none_          true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
	{ vlan_outer_id_recycle_count       VlanIf_Outer              IfRecycleCount                  NUMERIC                                                  4                       0                    _none_          true            _none_              false       _none_      {create configVlanOuterIntf modify configVlanOuterIntf}         _none_}
	{ option_type                       SyncEthPortConfig         OptionType                      {CHOICES option1 option2 }                               4                     option2                _none_          true            _none_              false       _none_      {create configSyncEthPortConfig modify configSyncEthPortConfig}     _none_}
    { quality_level                     SyncEthDeviceConfig       QualityLevel                    ANY                                                      4                     _none_                 _none_          true            _none_              false       _none_      {create configSyncEthDeviceConfig modify configSyncEthDeviceConfig} _none_}
    { rate                              SyncEthDeviceConfig       Rate                            ANY                                                      4                     _none_                 _none_          true            _none_              false       _none_      {create configSyncEthDeviceConfig modify configSyncEthDeviceConfig} _none_}
    { use_partial_block_state           SyncEthDeviceConfig       UsePartialBlockState            {CHOICES true false }                                    4                     false                  _none_          true            _none_              false       _none_      {create configSyncEthDeviceConfig modify configSyncEthDeviceConfig} _none_}
 }
 { emulation_synce_control
    { hname              stcobj              stcattr    type                         priority      default      range       supported   dependency      mandatory   procfunc    mode        constants}
    { port_handle        _none_             _none_      ALPHANUM                        1           _none_      _none_      true        _none_          false       _none_      _none_      _none_}
    { handle             _none_             _none_      ALPHANUM                        2           _none_      _none_      true        _none_          false       _none_      _none_      _none_}
    { action             _none_             _none_      {CHOICES start stop delete}     5           _none_      _none_      true        _none_          true        _none_      _none_      _none_}
 }
 { emulation_synce_stats
	{hname                          stcobj                  stcattr         type                                    priority          default       range           supported   dependency    mandatory   procfunc             mode          constants}
	{port_handle                    _none_                  _none_         ALPHANUM                                    2               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{handle                         _none_                  _none_         ALPHANUM                                    2               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{mode                           _none_                  _none_         {CHOICES port device option1 option2 }      3               port         _none_          true        _none_        false       _none_              _none_           _none_}
 }
 { emulation_synce_stats_port
	{hname                          stcobj                  stcattr         type                                    priority          default       range           supported   dependency    mandatory   procfunc             mode          constants}
	{tx_info_msgs                SyncEthPortResults         TxInfoMsgs     NUMERIC                                     5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_events                   SyncEthPortResults         TxEvents       NUMERIC                                     5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_info_msgs                SyncEthPortResults         RxInfoMsgs     NUMERIC                                     5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_events                   SyncEthPortResults         RxEvents       NUMERIC                                     5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
 }
 { emulation_synce_stats_device
	{hname                                 stcobj                  stcattr                     type                priority          default       range           supported   dependency    mandatory   procfunc             mode          constants}
	{rx_avg_info_msg_inter_arrival_time    SyncEthDeviceResults    RxAvgInfoMsgInterarrivalTime   NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_events                             SyncEthDeviceResults    RxEvents                       NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_info_msgs                          SyncEthDeviceResults    RxInfoMsgs                     NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_max_info_msg_inter_arrival_time    SyncEthDeviceResults    RxMaxInfoMsgInterarrivalTime   NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_min_info_msg_inter_arrival_time    SyncEthDeviceResults    RxMinInfoMsgInterarrivalTime   NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql                                 SyncEthDeviceResults    RxQl                           NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_num                             SyncEthDeviceResults    RxQlNum                        NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_events                             SyncEthDeviceResults    TxEvents                       NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_info_msgs                          SyncEthDeviceResults    TxInfoMsgs                     NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql                                 SyncEthDeviceResults    TxQl                           NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_num                             SyncEthDeviceResults    TxQlNum                        NUMERIC              5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
 }
 { emulation_synce_stats_option1
	{hname                          stcobj               stcattr                   type                        priority          default       range           supported   dependency    mandatory   procfunc             mode          constants}
	{rx_ql_dnu_count        SyncEthOption1Results    RxQlDnuCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_prc_count        SyncEthOption1Results    RxQlPrcCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_sec_count        SyncEthOption1Results    RxQlSecCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_ssua_count       SyncEthOption1Results    RxQlSsuaCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_ssub_count       SyncEthOption1Results    RxQlSsubCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_unsup_count      SyncEthOption1Results    RxQlUnsupCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_dnu_count        SyncEthOption1Results    TxQlDnuCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_prc_count        SyncEthOption1Results    TxQlPrcCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_sec_count        SyncEthOption1Results    TxQlSecCount                 NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_ssua_count       SyncEthOption1Results    TxQlSsuaCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_ssub_count       SyncEthOption1Results    TxQlSsubCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_unsup_count      SyncEthOption1Results    TxQlUnsupCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
 }
 { emulation_synce_stats_option2
	{hname                          stcobj                  stcattr              type                        priority          default       range           supported   dependency    mandatory   procfunc             mode          constants}
	{rx_ql_dus_count        SyncEthOption2Results    RxQlDusCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_prov_count       SyncEthOption2Results    RxQlProvCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_prs_count        SyncEthOption2Results    RxQlPrsCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_smc_count        SyncEthOption2Results    RxQlSmcCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_st2_count        SyncEthOption2Results    RxQlSt2Count                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_st3_count        SyncEthOption2Results    RxQlSt3Count                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_st3e_count       SyncEthOption2Results    RxQlSt3eCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_stu_count        SyncEthOption2Results    RxQlStuCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_tnc_count        SyncEthOption2Results    RxQlTncCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{rx_ql_unsup_count      SyncEthOption2Results    RxQlUnsupCount              NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_dus_count        SyncEthOption2Results    TxQlDusCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_prov_count       SyncEthOption2Results    TxQlProvCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_prs_count        SyncEthOption2Results    TxQlPrsCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_smc_count        SyncEthOption2Results    TxQlSmcCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_st2_count        SyncEthOption2Results    TxQlSt2Count                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_st3_count        SyncEthOption2Results    TxQlSt3Count                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_st3e_count       SyncEthOption2Results    TxQlSt3eCount               NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_stu_count        SyncEthOption2Results    TxQlStuCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_tnc_count        SyncEthOption2Results    TxQlTncCount                NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
	{tx_ql_unsup_count      SyncEthOption2Results    TxQlUnsupCount              NUMERIC                         5               _none_       _none_          true        _none_        false       _none_              _none_           _none_}
 }
 
}
