#!/bin/sh
# -*- tcl -*-
# The next line is executed by /bin/sh, but not tcl
namespace eval ::sth::Vqa:: {
}

set ::sth::Vqa::vqaTable {
    ::sth::Vqa::
    {emulation_vqa_host_config
        {hname                                             stcobj                                  stcattr                                 type                 priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {handle                                            _none_                                  _none_                                  ANY                  10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {session_handle                                    _none_                                  _none_                                  ANY                  10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {mode                                              _none_                                  _none_                        {CHOICES enable modify }       10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_addr_select                                   VqDeviceChannelBlock                    DstAddrSelect            {CHOICES group_range device_addr}   10          group_range     _none_          true          _none_          false          _none_          _none_          _none_}
        {use_video_client_udp_port                         VqDeviceChannelBlock                    UseVideoClientUdpPort            {CHOICES true false}        10          false           _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_udp_max                                 VqDeviceChannelBlock                    MulticastUdpMax                         NUMERIC              10          5000            _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_udp_min                                 VqDeviceChannelBlock                    MulticastUdpMin                         NUMERIC              10          4000            _none_          true          _none_          false          _none_          _none_          _none_}
        {use_range                                         VqDeviceChannelBlock                    UseRange                         {CHOICES true false}        10          true            _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_config
        {hname                                             stcobj                                  stcattr                                 type                     priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {port_handle                                       _none_                                  _none_                                  ANY                      10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {handle                                            _none_                                  _none_                                  ANY                      10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {mode                                              _none_                                  _none_                        {CHOICES create modify }           10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {ip_version                                        VqProbeChannelBlock                     IpVersion                    {CHOICES ipv4 ipv6}                 10          ipv4            _none_          true          _none_          false          _none_          _none_          _none_}
        {filter_type                                       VqProbeChannelBlock                     FilterType           {CHOICES multicast_filter unicast_filter}   10      multicast_filter    _none_          true          _none_          false          _none_          _none_          _none_}
        {layer2_encap                                      VqProbeChannelBlock                     Layer2Encap          {CHOICES no_encap vlan pppoe pppoe_vlan}    10          no_encap        _none_          true          _none_          false          _none_          _none_          _none_}
        {pppoe_session_id                                  VqProbeChannelBlock                     PppoeSessionId                          NUMERIC                  10          1               1-65535         true          _none_          false          _none_          _none_          _none_}
        {vlan_count                                        VqProbeChannelBlock                     VlanCount                               NUMERIC                  10          1               1-3             true          _none_          false          _none_          _none_          _none_}
        {vlan1_id                                          VqProbeChannelBlock                     Vlan1Id                                 NUMERIC                  10          100             0-4095          true          _none_          false          _none_          _none_          _none_}
        {vlan2_id                                          VqProbeChannelBlock                     Vlan2Id                                 NUMERIC                  10          100             0-4095          true          _none_          false          _none_          _none_          _none_}
        {vlan3_id                                          VqProbeChannelBlock                     Vlan3Id                                 NUMERIC                  10          100             0-4095          true          _none_          false          _none_          _none_          _none_}
        {unicast_ipv4_min                                  VqProbeChannelBlock                     UnicastIpv4Min                          IPV4                     10          192.168.0.0     _none_          true          _none_          false          _none_          _none_          _none_}
        {unicast_ipv4_max                                  VqProbeChannelBlock                     UnicastIpv4Max                          IPV4                     10          192.168.255.255 _none_          true          _none_          false          _none_          _none_          _none_}
        {unicast_ipv6_min                                  VqProbeChannelBlock                     UnicastIpv6Min                          IPV6                     10          2001::1         _none_          true          _none_          false          _none_          _none_          _none_}
        {unicast_ipv6_max                                  VqProbeChannelBlock                     UnicastIpv6Max                          IPV6                     10          2001::FF        _none_          true          _none_          false          _none_          _none_          _none_}
        {unicast_udp_min                                   VqProbeChannelBlock                     UnicastUdpMin                           NUMERIC                  10          1000            _none_          true          _none_          false          _none_          _none_          _none_}
        {unicast_udp_max                                   VqProbeChannelBlock                     UnicastUdpMax                           NUMERIC                  10          2000            _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_ipv4_min                                VqProbeChannelBlock                     MulticastIpv4Min                        IPV4                     10          225.0.0.0       _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_ipv4_max                                VqProbeChannelBlock                     MulticastIpv4Max                        IPV4                     10          225.0.0.255     _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_ipv6_min                                VqProbeChannelBlock                     MulticastIpv6Min                        IPV6                     10          ff1e::1         _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_ipv6_max                                VqProbeChannelBlock                     MulticastIpv6Max                        IPV6                     10          ff1e::FF        _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_udp_min                                 VqProbeChannelBlock                     MulticastUdpMin                         NUMERIC                  10          4000            _none_          true          _none_          false          _none_          _none_          _none_}
        {multicast_udp_max                                 VqProbeChannelBlock                     MulticastUdpMax                         NUMERIC                  10          5000            _none_          true          _none_          false          _none_          _none_          _none_}

    }
    {emulation_vqa_port_config
        {hname                                             stcobj                                  stcattr                                 type                 priority    default         range               supported     dependency      mandatory       procfunc        mode           constants}
        {mode                                              _none_                                  _none_                         {CHOICES create modify}       10          _none_          _none_              true          _none_          false          _none_          _none_          _none_}
        {port_handle                                       _none_                                  _none_                                  ANY                  10          _none_          _none_              true          _none_          false          _none_          _none_          _none_}
        {handle                                            _none_                                  _none_                                  ANY                  10          _none_          _none_              true          _none_          false          _none_          _none_          _none_}
        {frame_loss_concealment_robustness                 VqAnalyzer                              FrameLossConcealmentRobustness          NUMERIC              10          4               0-65535             true          _none_          false          _none_          _none_          _none_}
        {slices_per_iframe                                 VqAnalyzer                              SlicesPerIframe                         NUMERIC              10          0               0-65535             true          _none_          false          _none_          _none_          _none_}
        {nominal_delay                                     VqAnalyzer                              NominalDelay                            DECIMAL              10          3.0             0.001-4294967.295   true          _none_          false          _none_          _none_          _none_}
        {max_pkt_count                                     VqAnalyzer                              MaxPktCount                             NUMERIC              10          65535          0-4294967295         true          _none_          false          _none_          _none_          _none_}
        {mos_v_threshold                                   VqAnalyzer                              MosVThreshold                           DECIMAL              10          1               1.00-5.00                true          _none_          false          _none_          _none_          _none_}
        {mos_v_normalized_threshold                        VqAnalyzer                              MosVNormalizedThreshold                 DECIMAL              10          1               1.00-5.00                true          _none_          false          _none_          _none_          _none_}
        {mos_av_threshold                                  VqAnalyzer                              MosAvThreshold                          DECIMAL              10          1               1.00-5.00                 true          _none_          false          _none_          _none_          _none_}
        {mos_a_threshold                                   VqAnalyzer                              MosAThreshold                           DECIMAL              10          1               1.00-5.00                 true          _none_          false          _none_          _none_          _none_}
        {pid_interval                                      VqAnalyzer                              PidInterval                             DECIMAL              10          1               0.001-4294967.295   true          _none_          false          _none_          _none_          _none_}
        {pat_repetition                                    VqAnalyzer                              PatRepetition                           DECIMAL              10          0.5             0.001-4294967.295   true          _none_          false          _none_          _none_          _none_}
        {pmt_repetition                                    VqAnalyzer                              PmtRepetition                           DECIMAL              10          0.5             0.001-4294967.295   true          _none_          false          _none_          _none_          _none_}
        {pcr_continuity                                    VqAnalyzer                              PcrContinuity                           DECIMAL              10          0.1             0.001-47721.858     true          _none_          false          _none_          _none_          _none_}
        {pcr_repetition                                    VqAnalyzer                              PcrRepetition                           DECIMAL              10          0.04            0.001-47721.858     true          _none_          false          _none_          _none_          _none_}
        {pts_repetition                                    VqAnalyzer                              PtsRepetition                           DECIMAL              10          0.7             0.001-4294967.295   true          _none_          false          _none_          _none_          _none_}
        {rtp_timestamp_threshold                           VqAnalyzer                              RtpTimestampThreshold                   DECIMAL              10          3               0.001-47721.858     true          _none_          false          _none_          _none_          _none_}
        {payload_type                                      VqDynamicPayloadConfig                  PayloadType                             NUMERIC              10          96              96-127              true          _none_          false          _none_          _none_          _none_}
        {codec                                             VqDynamicPayloadConfig                  Codec    {CHOICES MPEG_L1 MPEG_L2 MPEG_L3 MPEG2_AAC AC3 MPEG4_AAC MPEG4_LD_AAC MPEG4_HE_AAC JPEG MPEG1 MPEG2 H261 H263 H263_PLUS H264 MPEG4 VC1}                  10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_height                                      VqDynamicPayloadConfig                  FrameHeight                             NUMERIC              10          486             50-65535          true          _none_          false          _none_          _none_          _none_}
        {frame_width                                       VqDynamicPayloadConfig                  FrameWidth                              NUMERIC              10          720             50-65535          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_global_config
        {hname                                             stcobj                                  stcattr                                 type              priority       default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {sampling_period                                   VqAnalyzerOptions                       SamplingPeriod                          NUMERIC              10          10              5-600          true          _none_          false          _none_          _none_          _none_}
        {database_file_name                                VqAnalyzerOptions                       DatabaseFileName                        ANY                  10      vqAnalyzerTest.db   _none_          true          _none_          false          _none_          _none_          _none_}
        {append_date_time                                  VqAnalyzerOptions                       AppendDateTime                       {CHOICES true false}    10          true          _none_          true          _none_          false          _none_          _none_          _none_}
        {enable_eot_database                               VqAnalyzerOptions                       EnableEotDatabase                    {CHOICES true false}    10          true          _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_control
        {hname                                             stcobj                                  stcattr                                 type              priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {port_handle                                       _none_                                  _none_                                  ANY               10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {handle                                            _none_                                  _none_                                  ANY               10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {action                                            _none_                                  _none_                        {CHOICES start stop}        10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_stats
        {hname                                             stcobj                                  stcattr                                 type              priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {port_handle                                       _none_                                  _none_                                  ANY               10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {handle                                            _none_                                  _none_                                  ANY               10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {mode                                              _none_                                  _none_                        {CHOICES audio_program_information audio_interval_metric audio_continuous_metric video_program_information video_interval_metric video_continuous_metric etsi rtp}        10          _none_          _none_          true          _none_          true          _none_          _none_          _none_}
    }
    {emulation_vqa_stats_audio_program_information
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {audio_channel_count                               VqAudioStreamResults                    AudioChannelCount                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {ref_clock_rate                                    VqAudioStreamResults                    RefClockRate                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pid                                               VqAudioStreamResults                    Pid                                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_addr                                          VqAudioStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqAudioStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {src_addr                                          VqAudioStreamResults                    SrcAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {src_udp_port                                      VqAudioStreamResults                    SrcUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {codec_type                                        VqAudioStreamResults                    CodecType                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_ssrc                                          VqAudioStreamResults                    RtpSsrc                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_stats_audio_continuous_metric
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {dst_addr                                          VqAudioStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqAudioStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {min_abs_mos_a                                     VqAudioStreamResults                    MinAbsMosA                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_abs_mos_a                                     VqAudioStreamResults                    AvgAbsMosA                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {max_abs_mos_a                                     VqAudioStreamResults                    MaxAbsMosA                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {abs_mos_a_below_threshold_prop                    VqAudioStreamResults                    AbsMosABelowThresholdProp               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pkt_loss_degrad_sev                               VqAudioStreamResults                    PktLossDegradSev                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {codec_type_degrad_sev                             VqAudioStreamResults                    CodecTypeDegradSev                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_stream_audio_bw                               VqAudioStreamResults                    AvgStreamAudioBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {transport_pkt_count                               VqAudioStreamResults                    TransportPktCount                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {transport_pkt_lost_count                          VqAudioStreamResults                    TransportPktLostCount                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {uncorr_loss_prop                                  VqAudioStreamResults                    UncorrLossProp                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_count                                         VqAudioStreamResults                    GapCount                                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_loss_rate                                     VqAudioStreamResults                    GapLossRate                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_length                                        VqAudioStreamResults                    GapLength                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_loss_rate                                   VqAudioStreamResults                    BurstLossRate                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_length                                      VqAudioStreamResults                    BurstLength                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_count                                       VqAudioStreamResults                    BurstCount                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {ppdv                                              VqAudioStreamResults                    Ppdv                                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_stats_audio_interval_metric
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {dst_addr                                          VqAudioStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqAudioStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_abs_mos_a                                VqAudioStreamResults                    IntervalAbsMosA                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_abs_mos_a                            VqAudioStreamResults                    IntervalMinAbsMosA                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_abs_mos_a                            VqAudioStreamResults                    IntervalMaxAbsMosA                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_avg_stream_audio_bw                      VqAudioStreamResults                    IntervalAvgStreamAudioBw                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_count                      VqAudioStreamResults                    IntervalTransportPktCount               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_lost_count                 VqAudioStreamResults                    IntervalTransportPktLostCount           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_duplicated_count           VqAudioStreamResults                    IntervalTransportPktDuplicatedCount     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_loss_rate                  VqAudioStreamResults                    IntervalTransportGapLossRate            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_length                     VqAudioStreamResults                    IntervalTransportGapLength              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_count                      VqAudioStreamResults                    IntervalTransportGapCount               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_loss_rate                VqAudioStreamResults                    IntervalTransportBurstLossRate          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_length                   VqAudioStreamResults                    IntervalTransportBurstLength            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_count                    VqAudioStreamResults                    IntervalTransportBurstCount             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_eff_loss_rate              VqAudioStreamResults                    IntervalTransportPktEffLossRate         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }

    {emulation_vqa_stats_video_program_information
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {vid_scrambling                                    VqVideoStreamResults                    VidScrambling                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gop_structure                                     VqVideoStreamResults                    GopStructure                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_gop_length                                    VqVideoStreamResults                    AvgGopLength                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {max_gop_length                                    VqVideoStreamResults                    MaxGopLength                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {curr_gop_length                                   VqVideoStreamResults                    CurrGopLength                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {inter_iframe_gap                                  VqVideoStreamResults                    InterIframeGap                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_width                                       VqVideoStreamResults                    FrameWidth                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_height                                      VqVideoStreamResults                    FrameHeight                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_rate                                        VqVideoStreamResults                    FrameRate                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_interlacing                                 VqVideoStreamResults                    FrameInterlacing                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {slices_per_iframe                                 VqVideoStreamResults                    SlicesPerIframe                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {ref_clock_rate                                    VqVideoStreamResults                    RefClockRate                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pid                                               VqVideoStreamResults                    Pid                                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_addr                                          VqVideoStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqVideoStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {src_addr                                          VqVideoStreamResults                    SrcAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {src_udp_port                                      VqVideoStreamResults                    SrcUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {codec_type                                        VqVideoStreamResults                    CodecType                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_ssrc                                          VqVideoStreamResults                    RtpSsrc                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }

    {emulation_vqa_stats_video_continuous_metric
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {min_abs_mos_v                                     VqVideoStreamResults                    MinAbsMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_abs_mos_v                                     VqVideoStreamResults                    AvgAbsMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {max_abs_mos_v                                     VqVideoStreamResults                    MaxAbsMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {abs_mos_v_below_threshold_prop                    VqVideoStreamResults                    AbsMosVBelowThresholdProp               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {min_rel_mos_v                                     VqVideoStreamResults                    MinRelMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_rel_mos_v                                     VqVideoStreamResults                    AvgRelMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {max_rel_mos_v                                     VqVideoStreamResults                    MaxRelMosV                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rel_mos_v_below_threshold_prop                    VqVideoStreamResults                    RelMosVBelowThresholdProp               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {min_abs_mos_av                                    VqVideoStreamResults                    MinAbsMosAv                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_abs_mos_av                                    VqVideoStreamResults                    AvgAbsMosAv                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {max_abs_mos_av                                    VqVideoStreamResults                    MaxAbsMosAv                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {abs_mos_av_below_threshold_prop                   VqVideoStreamResults                    AbsMosAvBelowThresholdProp              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {vstq                                              VqVideoStreamResults                    Vstq                                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {est_peak_sig_noise_ratio                          VqVideoStreamResults                    EstPeakSigNoiseRatio                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pkt_loss_degrad_sev                               VqVideoStreamResults                    PktLossDegradSev                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {codec_quantization_degrad_sev                     VqVideoStreamResults                    CodecQuantizationDegradSev              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_resolution_degrad_sev                       VqVideoStreamResults                    FrameResolutionDegradSev                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {frame_rate_degrad_sev                             VqVideoStreamResults                    FrameRateDegradSev                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gop_length_degrad_sev                             VqVideoStreamResults                    GopLengthDegradSev                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {avg_stream_video_bw                               VqVideoStreamResults                    AvgStreamVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {iframe_interarrival_jitter                        VqVideoStreamResults                    IframeInterarrivalJitter                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_addr                                          VqVideoStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqVideoStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {transport_pkt_count                               VqVideoStreamResults                    TransportPktCount                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {transport_pkt_lost_count                          VqVideoStreamResults                    TransportPktLostCount                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {uncorr_loss_prop                                  VqVideoStreamResults                    UncorrLossProp                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_count                                         VqVideoStreamResults                    GapCount                                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_loss_rate                                     VqVideoStreamResults                    GapLossRate                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {gap_length                                        VqVideoStreamResults                    GapLength                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_loss_rate                                   VqVideoStreamResults                    BurstLossRate                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_length                                      VqVideoStreamResults                    BurstLength                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {burst_count                                       VqVideoStreamResults                    BurstCount                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {ppdv                                              VqVideoStreamResults                    Ppdv                                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {iframe_avg_video_bw                               VqVideoStreamResults                    IframeAvgVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {iframe_max_video_bw                               VqVideoStreamResults                    IframeMaxVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pframe_avg_video_bw                               VqVideoStreamResults                    PframeAvgVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pframe_max_video_bw                               VqVideoStreamResults                    PframeMaxVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {bframe_avg_video_bw                               VqVideoStreamResults                    BframeAvgVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {bframe_max_video_bw                               VqVideoStreamResults                    BframeMaxVideoBw                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {siframe_avg_video_bw                              VqVideoStreamResults                    SiframeAvgVideoBw                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {siframe_max_video_bw                              VqVideoStreamResults                    SiframeMaxVideoBw                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {spframe_avg_video_bw                              VqVideoStreamResults                    SpframeAvgVideoBw                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {spframe_max_video_bw                              VqVideoStreamResults                    SpframeMaxVideoBw                       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }

    {emulation_vqa_stats_video_interval_metric
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {dst_addr                                          VqVideoStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqVideoStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_iframe_count                             VqVideoStreamResults                    IntervalIframeCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_iframe_impaired_count                    VqVideoStreamResults                    IntervalIframeImpairedCount             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_iframe_impaired_prop                     VqVideoStreamResults                    IntervalIframeImpairedProp              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_pframe_count                             VqVideoStreamResults                    IntervalPframeCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_pframe_impaired_count                    VqVideoStreamResults                    IntervalPframeImpairedCount             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_pframe_impaired_prop                     VqVideoStreamResults                    IntervalPframeImpairedProp              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_pframe_err_ext_impaired_prop             VqVideoStreamResults                    IntervalPframeErrExtImpairedProp        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_bframe_count                             VqVideoStreamResults                    IntervalBframeCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_bframe_impaired_count                    VqVideoStreamResults                    IntervalBframeImpairedCount             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_bframe_impaired_prop                     VqVideoStreamResults                    IntervalBframeImpairedProp              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_bframe_err_ext_impaired_prop             VqVideoStreamResults                    IntervalBframeErrExtImpairedProp        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_siframe_count                            VqVideoStreamResults                    IntervalSiframeCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_siframe_impaired_count                   VqVideoStreamResults                    IntervalSiframeImpairedCount            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_siframe_impaired_prop                    VqVideoStreamResults                    IntervalSiframeImpairedProp             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_spframe_count                            VqVideoStreamResults                    IntervalSpframeCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_spframe_impaired_count                   VqVideoStreamResults                    IntervalSpframeImpairedCount            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_spframe_impaired_prop                    VqVideoStreamResults                    IntervalSpframeImpairedProp             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_spframe_err_ext_impaired_prop            VqVideoStreamResults                    IntervalSpframeErrExtImpairedProp       ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_abs_mos_v                                VqVideoStreamResults                    IntervalAbsMosV                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_abs_mos_v                            VqVideoStreamResults                    IntervalMinAbsMosV                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_abs_mos_v                            VqVideoStreamResults                    IntervalMaxAbsMosV                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_rel_mos_v                                VqVideoStreamResults                    IntervalRelMosV                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_rel_mos_v                            VqVideoStreamResults                    IntervalMinRelMosV                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_rel_mos_v                            VqVideoStreamResults                    IntervalMaxRelMosV                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_mos_av                                   VqVideoStreamResults                    IntervalMosAv                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_mos_av                               VqVideoStreamResults                    IntervalMinMosAv                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_mos_av                               VqVideoStreamResults                    IntervalMaxMosAv                        ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_vstq                                     VqVideoStreamResults                    IntervalVstq                            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_avg_stream_video_bw                      VqVideoStreamResults                    IntervalAvgStreamVideoBw                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_est_peak_sig_noise_ratio                 VqVideoStreamResults                    IntervalEstPeakSigNoiseRatio            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_static_image_prop                        VqVideoStreamResults                    IntervalStaticImageProp                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_high_detail_prop                         VqVideoStreamResults                    IntervalHighDetailProp                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_low_detail_prop                          VqVideoStreamResults                    IntervalLowDetailProp                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_high_panning_prop                        VqVideoStreamResults                    IntervalHighPanningProp                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_high_motion_prop                         VqVideoStreamResults                    IntervalHighMotionProp                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_low_motion_prop                          VqVideoStreamResults                    IntervalLowMotionProp                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_count                      VqVideoStreamResults                    IntervalTransportPktCount               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_lost_count                 VqVideoStreamResults                    IntervalTransportPktLostCount           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_duplicated_count           VqVideoStreamResults                    IntervalTransportPktDuplicatedCount     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_loss_rate                  VqVideoStreamResults                    IntervalTransportGapLossRate            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_length                     VqVideoStreamResults                    IntervalTransportGapLength              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_gap_count                      VqVideoStreamResults                    IntervalTransportGapCount               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_loss_rate                VqVideoStreamResults                    IntervalTransportBurstLossRate          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_length                   VqVideoStreamResults                    IntervalTransportBurstLength            ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_burst_count                    VqVideoStreamResults                    IntervalTransportBurstCount             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_transport_pkt_eff_loss_rate              VqVideoStreamResults                    IntervalTransportPktEffLossRate         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_avg_ppdv                                 VqVideoStreamResults                    IntervalAvgPpdv                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_delay_factor                         VqVideoStreamResults                    IntervalMinDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_delay_factor                         VqVideoStreamResults                    IntervalMaxDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_avg_delay_factor                         VqVideoStreamResults                    IntervalAvgDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_min_media_loss_rate                      VqVideoStreamResults                    IntervalMinMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_max_media_loss_rate                      VqVideoStreamResults                    IntervalMaxMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {interval_avg_media_loss_rate                      VqVideoStreamResults                    IntervalAvgMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }
    {emulation_vqa_stats_etsi
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {dst_addr                                          VqVideoStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqVideoStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {sync_loss_count                                   VqVideoStreamResults                    SyncLossCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {sync_byte_error_count                             VqVideoStreamResults                    SyncByteErrorCount                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pat_error_count                                   VqVideoStreamResults                    PatErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pat2_error_count                                  VqVideoStreamResults                    Pat2ErrorCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {continuity_error_count                            VqVideoStreamResults                    ContinuityErrorCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pmt_error_count                                   VqVideoStreamResults                    PmtErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pmt2_error_count                                  VqVideoStreamResults                    Pmt2ErrorCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pid_error_count                                   VqVideoStreamResults                    PidErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {transport_error_count                             VqVideoStreamResults                    TransportErrorCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {crc_error_count                                   VqVideoStreamResults                    CrcErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pcr_error_count                                   VqVideoStreamResults                    PcrErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pcr_repetition_error_count                        VqVideoStreamResults                    PcrRepetitionErrorCount                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pcr_discontinuity_error_count                     VqVideoStreamResults                    PcrDiscontinuityErrorCount              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pcr_accuracy_error_count                          VqVideoStreamResults                    PcrAccuracyErrorCount                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {pts_error_count                                   VqVideoStreamResults                    PtsErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }


    {emulation_vqa_stats_rtp
        {hname                                             stcobj                                  stcattr                                 type         priority    default         range           supported     dependency      mandatory       procfunc        mode           constants}
        {dst_addr                                          VqVideoStreamResults                    DstAddr                                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {dst_udp_port                                      VqVideoStreamResults                    DstUdpPort                              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_transport_pkt_count                           VqVideoStreamResults                    RtpTransportPktCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_pkt_lost_count                                VqVideoStreamResults                    RtpPktLostCount                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_pkt_discarded_count                           VqVideoStreamResults                    RtpPktDiscardedCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_pkt_oos_count                                 VqVideoStreamResults                    RtpPktOosCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_pkt_duplicate_count                           VqVideoStreamResults                    RtpPktDuplicateCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        {rtp_timestamp_error_count                         VqVideoStreamResults                    RtpTimestampErrorCount                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    }


}
######following are the results not displayed on the GUI , so did not return in HLTAPI
#{
        #{rtp_transport_pkt_count                           VqAudioStreamResults                    RtpTransportPktCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{rtp_pkt_lost_count                                VqAudioStreamResults                    RtpPktLostCount                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{rtp_pkt_discarded_count                           VqAudioStreamResults                    RtpPktDiscardedCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{rtp_pkt_oos_count                                 VqAudioStreamResults                    RtpPktOosCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{rtp_pkt_duplicate_count                           VqAudioStreamResults                    RtpPktDuplicateCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{rtp_timestamp_error_count                         VqAudioStreamResults                    RtpTimestampErrorCount                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{sync_loss_count                                   VqAudioStreamResults                    SyncLossCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{sync_byte_error_count                             VqAudioStreamResults                    SyncByteErrorCount                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pat_error_count                                   VqAudioStreamResults                    PatErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pat2_error_count                                  VqAudioStreamResults                    Pat2ErrorCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{continuity_error_count                            VqAudioStreamResults                    ContinuityErrorCount                    ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pmt_error_count                                   VqAudioStreamResults                    PmtErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pmt2_error_count                                  VqAudioStreamResults                    Pmt2ErrorCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pid_error_count                                   VqAudioStreamResults                    PidErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{transport_error_count                             VqAudioStreamResults                    TransportErrorCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{crc_error_count                                   VqAudioStreamResults                    CrcErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pcr_error_count                                   VqAudioStreamResults                    PcrErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pcr_repetition_error_count                        VqAudioStreamResults                    PcrRepetitionErrorCount                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pcr_discontinuity_error_count                     VqAudioStreamResults                    PcrDiscontinuityErrorCount              ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pcr_accuracy_error_count                          VqAudioStreamResults                    PcrAccuracyErrorCount                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pts_error_count                                   VqAudioStreamResults                    PtsErrorCount                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{timestamp                                         VqAudioStreamResults                    Timestamp                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{timestamp_string                                  VqAudioStreamResults                    TimestampString                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
       #{interval_avg_ppdv                                 VqAudioStreamResults                    IntervalAvgPpdv                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_min_delay_factor                         VqAudioStreamResults                    IntervalMinDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_max_delay_factor                         VqAudioStreamResults                    IntervalMaxDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_avg_delay_factor                         VqAudioStreamResults                    IntervalAvgDelayFactor                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_min_media_loss_rate                      VqAudioStreamResults                    IntervalMinMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_max_media_loss_rate                      VqAudioStreamResults                    IntervalMaxMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_avg_media_loss_rate                      VqAudioStreamResults                    IntervalAvgMediaLossRate                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{interval_transport_pkt_discarded_count            VqAudioStreamResults                    IntervalTransportPktDiscardedCount      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    #}
#{
        #{interval_transport_pkt_discarded_count            VqVideoStreamResults                    IntervalTransportPktDiscardedCount      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{static_image_prop                                 VqVideoStreamResults                    StaticImageProp                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{high_detail_prop                                  VqVideoStreamResults                    HighDetailProp                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{low_detail_prop                                   VqVideoStreamResults                    LowDetailProp                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{high_panning_prop                                 VqVideoStreamResults                    HighPanningProp                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{high_motion_prop                                  VqVideoStreamResults                    HighMotionProp                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{low_motion_prop                                   VqVideoStreamResults                    LowMotionProp                           ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_pkt_count                                  VqVideoStreamResults                    IframePktCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_pkt_lost_count                             VqVideoStreamResults                    IframePktLostCount                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_pkt_discarded_count                        VqVideoStreamResults                    IframePktDiscardedCount                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_typ_impaired_prop                          VqVideoStreamResults                    IframeTypImpairedProp                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_pkt_count                                  VqVideoStreamResults                    PframePktCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_pkt_lost_count                             VqVideoStreamResults                    PframePktLostCount                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_pkt_discarded_count                        VqVideoStreamResults                    PframePktDiscardedCount                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_typ_impaired_prop                          VqVideoStreamResults                    PframeTypImpairedProp                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_err_ext_impaired_prop                      VqVideoStreamResults                    PframeErrExtImpairedProp                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_pkt_count                                  VqVideoStreamResults                    BframePktCount                          ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_pkt_lost_count                             VqVideoStreamResults                    BframePktLostCount                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_pkt_discarded_count                        VqVideoStreamResults                    BframePktDiscardedCount                 ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_typ_impaired_prop                          VqVideoStreamResults                    BframeTypImpairedProp                   ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_err_ext_impaired_prop                      VqVideoStreamResults                    BframeErrExtImpairedProp                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{siframe_pkt_count                                 VqVideoStreamResults                    SiframePktCount                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{siframe_pkt_lost_count                            VqVideoStreamResults                    SiframePktLostCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{siframe_pkt_discarded_count                       VqVideoStreamResults                    SiframePktDiscardedCount                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{siframe_typ_impaired_prop                         VqVideoStreamResults                    SiframeTypImpairedProp                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{spframe_pkt_count                                 VqVideoStreamResults                    SpframePktCount                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{spframe_pkt_lost_count                            VqVideoStreamResults                    SpframePktLostCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{spframe_pkt_discarded_count                       VqVideoStreamResults                    SpframePktDiscardedCount                ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{spframe_typ_impaired_prop                         VqVideoStreamResults                    SpframeTypImpairedProp                  ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{spframe_err_ext_impaired_prop                     VqVideoStreamResults                    SpframeErrExtImpairedProp               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_count                                      VqVideoStreamResults                    IframeCount                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_impaired_count                             VqVideoStreamResults                    IframeImpairedCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{iframe_impaired_prop                              VqVideoStreamResults                    IframeImpairedProp                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_count                                      VqVideoStreamResults                    PframeCount                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_impaired_count                             VqVideoStreamResults                    PframeImpairedCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{pframe_impaired_prop                              VqVideoStreamResults                    PframeImpairedProp                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_count                                      VqVideoStreamResults                    BframeCount                             ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_impaired_count                             VqVideoStreamResults                    BframeImpairedCount                     ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{bframe_impaired_prop                              VqVideoStreamResults                    BframeImpairedProp                      ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{timestamp                                         VqVideoStreamResults                    Timestamp                               ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
        #{timestamp_string                                  VqVideoStreamResults                    TimestampString                         ANY          10          _none_          _none_          true          _none_          false          _none_          _none_          _none_}
    #}
