namespace eval ::sth::vxlan:: {
}

set ::sth::vxlan::vxlanTable {
    ::sth::vxlan::
    {   emulation_vxlan_config
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                                                                                            constants}
        {port_handle                    _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {handle                         _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {mode                           _none_                  _none_                      {CHOICES create modify delete}                                 3               _none_      _none_          true        _none_                  true        _none_                                              _none_                                                                                                          _none_}
        {count                          _none_                  count                           NUMERIC                                             3               1           _none_          false        _none_                  false       _none_                                              _none_                                                                       _none_}
        {router_id                      EmulatedDevice          RouterId                        IPV4                                                3               _none_      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {router_id_ipv6                 EmulatedDevice          Ipv6RouterId                    IPV6                                                3               _none_      _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       _none_}
        {enable_ping_response           EmulatedDevice          EnablePingResponse          {CHOICES 0 1}                                           3               0           _none_          true        _none_                  false       _none_                                              {create configDevice modify configDevice}                                                                       {1 TRUE 0 FALSE}}
        {ip_version                     _none_                  _none_                      {CHOICES ipv4 ipv6 ipv46}                               4               ipv4        _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {intf_ip_addr                   Ipv4If                  Address                         IPV4                                                4               192.85.1.3  _none_          true        _none_                  false       processEmulation_vxlan_configIp                     {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_ip_addr_step              Ipv4If                  AddrStep                        IPV4                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {gateway_ip_addr                Ipv4If                  Gateway                         IPV4                                                4               _none_      _none_          true        _none_                  false       processEmulation_vxlan_configIp                {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {gateway_ip_addr_step           Ipv4If                  GatewayStep                     IPV4                                                4               _none_      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_prefix_len                Ipv4If                  PrefixLength                    NUMERIC                                             4               _none_      _none_          true        _none_                  false       _none_                                              {create configIpv4Intf modify configIpv4Intf}                                                                   _none_}
        {intf_ipv6_addr                 Ipv6If                  Address                         IPV6                                                4               _none_      _none_          true        _none_                  false       processEmulation_vxlan_configIp                     {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {intf_ipv6_addr_step            Ipv6If                  AddrStep                        IPV6                                                4               _none_      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {intf_ipv6_prefix_len           Ipv6If                  PrefixLength                    NUMERIC                                             4               _none_      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {gateway_ipv6_addr              Ipv6If                  Gateway                         IPV6                                                4               _none_      _none_          true        _none_                  false       processEmulation_vxlan_configIp                {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {gateway_ipv6_addr_step         Ipv6If                  GatewayStep                     IPV6                                                4               _none_      _none_          true        _none_                  false       _none_                                              {create configIpv6Intf modify configIpv6Intf}                                                                   _none_}
        {link_local_ipv6_addr           Ipv6If                  Address                         IPV6                                                14              FE80::0     _none_          true        _none_                  false       processEmulation_vxlan_configIp                     {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {link_local_ipv6_addr_step      Ipv6If                  AddrStep                        IPV6                                                15              ::1         _none_          true        _none_                  false       _none_                                              {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {link_local_ipv6_prefix_len     Ipv6If                  PrefixLength                    NUMERIC                                             16              128         1-128           true        _none_                  false       _none_                                              {create configIpv6LinkLocalIntf modify configIpv6LinkLocalIntf}                                                  _none_}
        {mac_addr                       EthIIIf                 SourceMac                          ANY                                                 4               _none_      _none_          true        _none_               false       processEmulation_vxlan_configSrcMacAddr             {create configEthIIIntf modify configEthIIIntf}                                                                 _none_}
        {mac_addr_step                  EthIIIf                 SrcMacStep                      ANY                                                 4               _none_      _none_          true        _none_                  false       _none_                                              {create configEthIIIntf modify configEthIIIntf}                                                                 _none_}
        {qinq_incr_mode                 _none_                  _none_                     {CHOICES inner both outer}                               4               inner       _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {encapsulation                  _none_                  _none_                     {CHOICES ethernet_ii ethernet_ii_vlan ethernet_ii_qinq}  4           ethernet_ii     _none_          true        _none_                  false       _none_                                              _none_                                                                                                          _none_}
        {vlan_id                        VlanIf                  VlanId                          NUMERIC                                             4               _none_      _none_          true        _none_                  false       processEmulation_vxlan_configVlanId                 {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_id_step                   VlanIf                  IdStep                          NUMERIC                                             4               _none_      _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_id_count                  VlanIf                  IfRecycleCount                  NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_user_pri                  VlanIf                  Priority                        NUMERIC                                             4               _none_      0-7             true        _none_                  false       _none_                                              {create configVlanIfInner modify configVlanIfInner}                                                             _none_}
        {vlan_outer_id                  VlanIf_Outer            VlanId                          NUMERIC                                             4               _none_      _none_          true        _none_                  false       processEmulation_vxlan_configOuterVlanId            {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_id_step             VlanIf_Outer            IdStep                          NUMERIC                                             4               _none_      _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_id_count            VlanIf_Outer            IfRecycleCount                  NUMERIC                                             4               1           _none_          true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        {vlan_outer_user_pri            VlanIf_Outer            Priority                        NUMERIC                                             4               _none_      0-7             true        _none_                  false       _none_                                              {create configVlanIfOuter modify configVlanIfOuter}                                                             _none_}
        
        {udp_dst_port                   VxlanPortConfig         UdpDstPort                      NUMERIC                                             7               4789        _none_          true        _none_                  false       _none_                                              {create configVxlanPort modify configVxlanPort}                                                                 _none_}
        {auto_select_udp_src_port       VxlanVtepConfig         AutoSelectUdpSrcPort        {CHOICES true false}                                    7               true        _none_          true        _none_                  false       _none_                                              {create configVxlan modify configVxlan}                                                                         _none_}
        {udp_src_port                   VxlanVtepConfig         UdpSrcPort                      NUMERIC                                                 7               1025        _none_          true        _none_                  false       _none_                                          {create configVxlan modify configVxlan}                                                                         _none_}
        {multicast_type                 VxlanVtepConfig         MulticastType               {CHOICES MULTICAST_IGMP MULTICAST_PIM}                  7           MULTICAST_IGMP  _none_          true        _none_                  false       _none_                                          {create configVxlan modify configVxlan}                                                                         _none_}
        {udp_checksum_enabled           VxlanVtepConfig         UdpChecksumEnabled          {CHOICES true false}                                    7               false       _none_          true        _none_                  false       _none_                                              {create configVxlan modify configVxlan}                                                                         _none_}
        {vni                            VxlanSegmentConfig      Vni                              NUMERIC                                            7               1           _none_          true        _none_                  false       _none_                                              {create configVxlanSegment modify configVxlanSegment}                                                           _none_}
        {communication_type             VxlanSegmentConfig      CommunicationType           {CHOICES MULTICAST_LEARNING UNICAST_CONFIGURATION}      7        MULTICAST_LEARNING _none_          true        _none_                  false       _none_                                              {create configVxlanSegment modify configVxlanSegment}                                                           _none_}
        {multicast_group                VxlanSegmentConfig      -UsesIpv4MulticastGroupForOverlay-targets   ANY                                     7             _none_        _none_          true        _none_                  false       _none_                                              {create configVxlanSegment modify configVxlanSegment}   _none_  }
        {vm_hosts                       VxlanVmInfo             -UsesVxlanVmInfo-sources        ANY                                                 7             _none_        _none_          true        _none_                  false       _none_                                              {create configVxlanSegment modify configVxlanSegment}   _none_      }
        {vxlansegmenthandle             _none_                  _none_                          ANY                                                 7               _none_       _none_         true        _none_                  false       _none_                                              _none_                                                      _none_  }
    }
    {   emulation_vxlan_control
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                            constants}
        {port_handle                    _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {handle                         _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {action                         _none_                  _none_                          {CHOICES start stop}                                3               _none_      _none_          true        _none_                  true       _none_                                              _none_                                          _none_}
    }
    {   emulation_vxlan_stats
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                            constants}
        {port_handle                    _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {handle                         _none_                  _none_                          ALPHANUM                                            2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {state                          VxlanVtepConfig         State                           ANY                                                 3               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {learned_binding_count          VxlanVtepConfig         LearnedBindingsCount            ANY                                                 3               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {load_profile_run_state         VxlanVtepConfig         LoadProfileRunState             ANY                                                 3               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {resolved_vm_macs_count         VxlanVtepConfig         ResolvedVmMacsCount             ANY                                                 3               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {unresolved_vm_macs_count       VxlanVtepConfig         UnResolvedVmMacsCount           ANY                                                 3               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
    }
    {   emulation_vxlan_port_config
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                            constants}
        {port_handle                    _none_                  _none_                           ANY                                                2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {handle                         _none_                  _none_                           ANY                                                2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {mode                           _none_                  _none_                          {CHOICES create delete}                             3               "create"    _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {vlan_enable                    VxlanGenVtepPortParams  EnableVlan                      {CHOICES true false}                                4                false      _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ip_addr                VxlanGenVtepPortParams  GatewayIpAddress                 ANY                                                4             192.168.100.1 _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ip_addr_step           VxlanGenVtepPortParams  GatewayIpAddressStep             ANY                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {mac_addr                       VxlanGenVtepPortParams  MacAddress                       ANY                                                4            10:00:00:10:00:01 _none_       true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {mac_addr_step                  VxlanGenVtepPortParams  MacAddressStep                   ANY                                                4            00:00:00:00:00:01 _none_       true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {prefix_len                     VxlanGenVtepPortParams  PrefixLength                     ANY                                                4                 24        _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_count                     VxlanGenVtepPortParams  VlanCount                        ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_id                        VxlanGenVtepPortParams  VlanId                           ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_id_step                   VxlanGenVtepPortParams  VlanIdStep                       ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vtep_ip_addr                   VxlanGenVtepPortParams  VtepIpAddress                    ANY                                                4             192.168.100.2 _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vtep_ip_addr_step              VxlanGenVtepPortParams  VtepIpAddressStep                ANY                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}    
    }
    {   emulation_nonvxlan_port_config
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                            constants}
        {port_handle                    _none_                  _none_                           ANY                                                2               _none_      _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {handle                         _none_                  _none_                           ANY                                                2               _none_      _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {mode                           _none_                  _none_                          {CHOICES create delete}                             3               "create"    _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {device_count                   VxlanGenHostPortParams  DeviceCount                      ANY                                                4                  1        _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_enable                    VxlanGenHostPortParams  EnableVlan                      {CHOICES true false}                                4                false      _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ip_addr                VxlanGenHostPortParams  GatewayIpAddress                 ANY                                                4             192.168.100.1 _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ip_addr_step           VxlanGenHostPortParams  GatewayIpAddressStep             ANY                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ip_addr                        VxlanGenHostPortParams  IpAddress                        ANY                                                4             192.85.100.2  _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ip_addr_step                   VxlanGenHostPortParams  IpAddressStep                    ANY                                                4               0.0.0.1     _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ip_prefix                      VxlanGenHostPortParams  IpPrefix                         ANY                                                4                  24       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {mac_addr                       VxlanGenHostPortParams  MacAddress                       ANY                                                4            10:00:00:10:00:01 _none_       true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {mac_addr_step                  VxlanGenHostPortParams  MacAddressStep                   ANY                                                4            00:00:00:00:00:01 _none_       true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_id                        VxlanGenHostPortParams  VlanId                           ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vlan_id_step                   VxlanGenHostPortParams  VlanIdStep                       ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vni                            VxlanGenHostPortParams  Vni                              ANY                                                4                  100      _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {vni_step                       VxlanGenHostPortParams  VniStep                          ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}    
        {dut_vtep_ip_addr               VxlanGenHostPortParams  DutVtepIpAddress                 ANY                                                4            192.85.100.1   _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ipv6_addr              VxlanGenHostPortParams  GatewayIpv6Address               ANY                                                4                5001::1    _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {gateway_ipv6_addr_step         VxlanGenHostPortParams  GatewayIpv6AddressStep           ANY                                                4                0::1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {host_count                     VxlanGenHostPortParams  HostCount                        ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {host_ip_type                   VxlanGenHostPortParams  HostIpType      {CHOICES ipv4 ipv4andipv6 ipv6 mac}                                 4                ipv4       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}    
        {host_per_segment               VxlanGenHostPortParams  HostPerSegment                   ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {hosts_per_block                VxlanGenHostPortParams  HostsPerBlock                    ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ipv6_addr                      VxlanGenHostPortParams  Ipv6Address                      ANY                                                4                  5001::2  _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ipv6_addr_step                 VxlanGenHostPortParams  Ipv6AddressStep                  ANY                                                4                  0::1     _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}
        {ipv6_prefix                    VxlanGenHostPortParams  Ipv6Prefix                       ANY                                                4                  64       _none_          true        _none_                  false       _none_                                              {create processConfigCmd}                       _none_}    
    }
    {   emulation_vxlan_wizard_config
        {hname                          stcobj                  stcattr                          type                                             priority          default     range           supported   dependency              mandatory   procfunc                                            mode                                            constants}
        {handle                         _none_                  _none_                           ANY                                                2               _none_      _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {mode                           _none_                  _none_                          {CHOICES create delete}                             3               "create"    _none_          true        _none_                  false       _none_                                              _none_                                          _none_}
        {auto_select_udp_src_port       VxlanGenVtepParams      AutoSelectUdpSourcePort         {CHOICES true false}                                4                true       _none_          true        _none_                  false       _none_                                              {create VxlanGenVtepParams}                     _none_}
        {udp_checksum_enable            VxlanGenVtepParams      EnableUdpChecksum               {CHOICES true false}                                4                false      _none_          true        _none_                  false       _none_                                              {create VxlanGenVtepParams}                     _none_}
        {udp_src_port                   VxlanGenVtepParams      UdpSourcePort                    ANY                                                4                1025       _none_          true        _none_                  false       _none_                                              {create VxlanGenVtepParams}                     _none_}
        {udp_src_port_step              VxlanGenVtepParams      UdpSourcePortStep                ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenVtepParams}                     _none_}
        {vteps_per_sub_interf_count     VxlanGenVtepParams      VtepsPerSubInterfaceCount        ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenVtepParams}                     _none_}
        
        {vlan_enable                    VxlanGenHostParams  EnableVlan          {CHOICES true false}                                                4                 false     _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {host_ip_addr                   VxlanGenHostParams  HostIpAddress                        ANY                                                4                 100.0.0.2 _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ip_addr_step_per_Segment       VxlanGenHostParams  IpAddressStepPerSegment              ANY                                                4                 0.0.1.0   _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ip_prefix                      VxlanGenHostParams  IpPrefix                             ANY                                                4                  24       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ip_addr_incr_per_port          VxlanGenHostParams  IpaddressIncrementPerPort            ANY                                                4                 0.0.0.0   _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ip_addr_step                   VxlanGenHostParams  IpaddressStep                        ANY                                                4                0.0.0.1    _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {mac_addr                       VxlanGenHostParams  MacAddress                           ANY                                                4                 00:00:10:01:00:00  _none_    true     _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {mac_addr_step                  VxlanGenHostParams  MacAddressStep                       ANY                                                4                 00:00:00:00:00:01  _none_    true     _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {use_same_vnis_across_ports     VxlanGenHostParams  UseSameVnisAcrossPorts {CHOICES true false}                                             4                  true     _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {use_same_vnis_across_vteps     VxlanGenHostParams  UseSameVnisAcrossVteps {CHOICES true false}                                             4                  true     _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vlan_id                        VxlanGenHostParams  VlanId                               ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vlan_id_step                   VxlanGenHostParams  VlanIdStep                           ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vms_per_segment                VxlanGenHostParams  VmsPerSegment                        ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vni                            VxlanGenHostParams  Vni                                  ANY                                                4                 100       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vni_step                       VxlanGenHostParams  VniStep                              ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vxlan_segments_per_vtep        VxlanGenHostParams  VxlanSegmentsPerVtep                 ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {gateway_ip_addr                VxlanGenHostParams  GatewayIpAddress                     ANY                                                4                 100.0.0.1 _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {gateway_ip_addr_step           VxlanGenHostParams  GatewayIpAddressStep                 ANY                                                4                 0.0.0.1   _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {gateway_ipv6_addr              VxlanGenHostParams  GatewayIpv6Address                   ANY                                                4                 2001::1   _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {gateway_ipv6_addr_step         VxlanGenHostParams  GatewayIpv6AddressStep               ANY                                                4                 0::1      _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {host_ipv6_addr                 VxlanGenHostParams  HostIpv6Address                      ANY                                                4                 2001::2   _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ipv6_addr_incr_per_port        VxlanGenHostParams  Ipv6AddressIncrementPerPort          ANY                                                4                 0::0      _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ipv6_addr_step                 VxlanGenHostParams  Ipv6AddressStep                      ANY                                                4                 0::1      _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ipv6_addr_step_per_segment     VxlanGenHostParams  Ipv6AddressStepPerSegment            ANY                                                4                 0::1:0    _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {ipv6_prefix                    VxlanGenHostParams  Ipv6Prefix                           ANY                                                4                   64      _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {l3_vni                         VxlanGenHostParams  L3Vni                                ANY                                                4                  200      _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {l3_vni_for_evpn_learning       VxlanGenHostParams  L3VniForEvpnLearning       {CHOICES true false}                                         4                 false     _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {l3_vni_step                    VxlanGenHostParams  L3VniStep                            ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {segments_per_block             VxlanGenHostParams  SegmentsPerBlock                     ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vms_per_vtep                   VxlanGenHostParams  VmsPerVtep                           ANY                                                4                   0       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        {vxlan_ip_type                  VxlanGenHostParams  VxlanIpType                 {CHOICES ipv4 ipv4andipv6 ipv6 mac}                         4                ipv4       _none_          true        _none_                  false       _none_                                              {create VxlanGenHostParams}                     _none_}
        
        {dut_as                        VxlanConfigGenParams      DutAs                           ANY                                                4                 1001      _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_as_4byte                  VxlanConfigGenParams      DutAs4Byte                      ANY                                                4               1.1001      _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_ip_addr                   VxlanConfigGenParams      DutIpAddr                       ANY                                                4                 10.0.0.1  _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_ip_addr_step              VxlanConfigGenParams      DutIpAddrStep                   ANY                                                4                 0.0.0.1   _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {igmp_multicast_version        VxlanConfigGenParams      IgmpMulticastVersion  {CHOICES igmp_v2 igmp_v3}                                    4                 igmp_v2   _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {pim_mode_vxlan                VxlanConfigGenParams      PimModeVxlan          {CHOICES sm ssm}                                             4                 sm        _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {use_bi_dir                    VxlanConfigGenParams      UseBiDir                       {CHOICES true false}                                4                 false     _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {vxlan_multicast_ip_addr       VxlanConfigGenParams      VxlanMulticastIpAddress         ANY                                                4                 225.0.0.1 _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {vxlan_multicast_ip_addr_step  VxlanConfigGenParams      VxlanMulticastIpAddressStep     ANY                                                4                 0.0.0.1   _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {vxlan_multicast_rp_addr       VxlanConfigGenParams      VxlanMulticastRpAddress         ANY                                                4                 192.0.0.1 _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {vxlan_segment_multicast_type  VxlanConfigGenParams      VxlanSegmentMulticastType       {CHOICES igmp pim}                                 4                 igmp       _none_          true        _none_                  false       _none_                                             {create VxlanConfigGenParams}                   _none_}
        {vxlan_segment_type            VxlanConfigGenParams      VxlanSegmentType                {CHOICES evpn_learning multicast_learning unicast_and_multicast unicast_configuration}     4 unicast_configuration _none_   true   _none_      false _none_                                        {create VxlanConfigGenParams}                   _none_}
        {as_byte_mode                  VxlanConfigGenParams      AsByteMode                      {CHOICES as2byte as4byte}                          4                as2byte    _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num                        VxlanConfigGenParams      AsNum                           ANY                                                4                 1         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num_4byte                  VxlanConfigGenParams      AsNum4Byte                      ANY                                                4                 1.1       _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num_4byte_step             VxlanConfigGenParams      AsNum4ByteStep                  ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num_4byte_step_per_port    VxlanConfigGenParams      AsNum4ByteStepPerPort           ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num_step                   VxlanConfigGenParams      AsNumStep                       ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {as_num_step_per_port          VxlanConfigGenParams      AsNumStepPerPort                ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {bgp_mode                      VxlanConfigGenParams      BgpMode                         {CHOICES ebgp ibgp}                                4                ebgp       _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {config_l3_vni                 VxlanConfigGenParams      ConfigureL3Vni                  {CHOICES true false}                               4                 false     _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_as_num_4byte_step         VxlanConfigGenParams      DutAsNum4ByteStep               ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_as_num_4byte_step_per_port VxlanConfigGenParams     DutAsNum4ByteStepPerPort        ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_as_num_step_per_port      VxlanConfigGenParams      DutAsNumStepPerPort             ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {dut_as_step                   VxlanConfigGenParams      DutAsStep                       ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
        {use_vxlan_ports               VxlanConfigGenParams      UseVxlanPorts                   {CHOICES true false}                               4               true        _none_          true        _none_                  false       _none_                                              {create VxlanConfigGenParams}                   _none_}
         
        {active                         BgpEvpnRouteParams      Active                          {CHOICES true false}                               4                 true      _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {name                           BgpEvpnRouteParams      Name                            ANY                                                4               _none_      _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_active_standby_mode      BgpEvpnRouteParams      VxlanActiveStandbyMode          {CHOICES all_active single_active}                 4           single_active   _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_ether_segment_id         BgpEvpnRouteParams      VxlanEthernetSegmentId          ANY                                                4        00:00:00:00:00:00:00:00:00  _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_ether_segment_id_step    BgpEvpnRouteParams      VxlanEthernetSegmentIdStep      ANY                                                4        00:00:00:00:00:00:00:00:00 _none_  true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_ether_segment_value_type BgpEvpnRouteParams      VxlanEthernetSegmentValueType   {CHOICES type0 type1 type2 type3 type4 type5}      4                type0      _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_ether_tag_id             BgpEvpnRouteParams      VxlanEthernetTagId              ANY                                                4                 0         _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_evi_count                BgpEvpnRouteParams      VxlanEviCount                   ANY                                                4                 1         _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_evpn_ip_prefix_gateway_type BgpEvpnRouteParams   VxlanEvpnIPPrefixGatewayType    {CHOICES vaipaddress vtepipaddress}                4              vaipaddress  _none_          true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                      _none_}
        {vxlan_evpn_router_mac_addr     BgpEvpnRouteParams      VxlanEvpnRouterMacAddress           ANY                                                4       00:00:00:00:00:00  _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_evpn_router_mac_addr_step BgpEvpnRouteParams    VxlanEvpnRouterMacAddressStep       ANY                                                4       00:00:00:00:00:01  _none_ true         _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_evpn_router_mac_ext_community BgpEvpnRouteParams VxlanEvpnRouterMacExtCommunity     {CHOICES true false}                                4       false              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_evpn_topology_types      BgpEvpnRouteParams      VxlanEvpnTopologyTypes             {CHOICES custom multihome singlehome}               4       singlehome         _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_route_dist               BgpEvpnRouteParams      VxlanRouteDistinguisher             ANY                                                4       192.0.0.1:1        _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_route_dist_step          BgpEvpnRouteParams      VxlanRouteDistinguisherStep         ANY                                                4       0:1                _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_route_target             BgpEvpnRouteParams      VxlanRouteTarget                    ANY                                                4       100:1              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_route_target_step        BgpEvpnRouteParams      VxlanRouteTargetStep                ANY                                                4       0:1                _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_vaip_addr                BgpEvpnRouteParams      VxlanVAIPAddress                    ANY                                                4       0.0.0.0            _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_vaip_addr_step           BgpEvpnRouteParams      VxlanVAIPAddressStep                ANY                                                4       0.0.0.1            _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_wizard_ad_route          BgpEvpnRouteParams      VxlanWizardAdRoute                 {CHOICES true false}                                4       false              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_wizard_ad_route_esi      BgpEvpnRouteParams      VxlanWizardAdRouteEsi              {CHOICES true false}                                4       false              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_wizard_ad_route_evi      BgpEvpnRouteParams      VxlanWizardAdRouteEvi              {CHOICES true false}                                4       false              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_wizard_ad_route_type     BgpEvpnRouteParams      VxlanWizardADRouteType             {CHOICES per_esi per_evi}                           4       per_esi            _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                            _none_}
        {vxlan_wizard_ether_segment_route  BgpEvpnRouteParams VxlanWizardEthernetSegmentRoute      {CHOICES true false}                                4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_wizard_inclusive_multicast_route  BgpEvpnRouteParams VxlanWizardInclusiveMulticastRoute {CHOICES true false}                            4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_wizard_ip_prefix_route  BgpEvpnRouteParams      VxlanWizardIPPrefixRoute            {CHOICES true false}                                4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_wizard_mac_ip_route     BgpEvpnRouteParams      VxlanWizardMacIpRoute               {CHOICES true false}                                4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_va_ipv6_addr            BgpEvpnRouteParams      VxlanVaIpv6Address                   ANY                                                 4       2002::1           _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_va_ipv6_addr_step       BgpEvpnRouteParams      VxlanVaIpv6AddressStep               ANY                                                 4       0::1              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_wizard_mac_and_ip_route BgpEvpnRouteParams      VxlanWizardMacAndIpRoute             {CHOICES true false}                                4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        {vxlan_wizard_mac_only_route   BgpEvpnRouteParams      VxlanWizardMacOnlyRoute              {CHOICES true false}                                4       true              _none_ true        _none_                  false       _none_                                              {create BgpEvpnRouteParams}                             _none_}
        
        {create_traffic                      VxlanTrafficParams CreateTraffic                    {CHOICES true false}                                   4       false              _none_ true        _none_                  false       _none_                                             {create VxlanTrafficParams}                            _none_}
        {traffic_flow                        VxlanTrafficParams TrafficFlow                    {CHOICES bidirectional host_to_vxlan vxlan_to_host}      4       bidirectional      _none_ true        _none_                  false       _none_                                             {create VxlanTrafficParams}                            _none_}
        {traffic_frame_size                  VxlanTrafficParams TrafficFrameSize                    ANY                                                 4       1518              _none_ true        _none_                  false       _none_                                              {create VxlanTrafficParams}                            _none_}
        {traffic_load_percent_ports          VxlanTrafficParams TrafficLoadPercentPorts             ANY                                                 4       10.0              _none_ true        _none_                  false       _none_                                              {create VxlanTrafficParams}                            _none_}
        {traffic_type                        VxlanTrafficParams TrafficType                    {CHOICES ipv4 mac}                                       4       ipv4              _none_ true        _none_                  false       _none_                                              {create VxlanTrafficParams}                            _none_}
        
		{l3_vlan_enable                    VxlanL3VniParams  EnableVlan          {CHOICES true false}                                                4                 false     _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_host_ip_addr                   VxlanL3VniParams  HostIpAddress                        ANY                                                4                 200.0.0.2 _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ip_addr_step_per_Segment       VxlanL3VniParams  IpAddressStepPerSegment              ANY                                                4                 0.0.1.0   _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ip_prefix                      VxlanL3VniParams  IpPrefix                             ANY                                                4                  24       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ip_addr_incr_per_port          VxlanL3VniParams  IpaddressIncrementPerPort            ANY                                                4                 0.0.0.0   _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ip_addr_step                   VxlanL3VniParams  IpaddressStep                        ANY                                                4                0.0.0.1    _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_mac_addr                       VxlanL3VniParams  MacAddress                           ANY                                                4                 00:00:20:01:00:00  _none_    true     _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_mac_addr_step                  VxlanL3VniParams  MacAddressStep                       ANY                                                4                 00:00:00:00:00:01  _none_    true     _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_use_same_vnis_across_ports     VxlanL3VniParams  UseSameVnisAcrossPorts {CHOICES true false}                                             4                  true     _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_use_same_vnis_across_vteps     VxlanL3VniParams  UseSameVnisAcrossVteps {CHOICES true false}                                             4                  true     _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vlan_id                        VxlanL3VniParams  VlanId                               ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vlan_id_step                   VxlanL3VniParams  VlanIdStep                           ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vms_per_segment                VxlanL3VniParams  VmsPerSegment                        ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vni                            VxlanL3VniParams  Vni                                  ANY                                                4                 1000       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vni_step                       VxlanL3VniParams  VniStep                              ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vxlan_segments_per_vtep        VxlanL3VniParams  VxlanSegmentsPerVtep                 ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_gateway_ip_addr                VxlanL3VniParams  GatewayIpAddress                     ANY                                                4                 200.0.0.1 _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_gateway_ip_addr_step           VxlanL3VniParams  GatewayIpAddressStep                 ANY                                                4                 0.0.0.1   _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_gateway_ipv6_addr              VxlanL3VniParams  GatewayIpv6Address                   ANY                                                4                 4001::1   _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_gateway_ipv6_addr_step         VxlanL3VniParams  GatewayIpv6AddressStep               ANY                                                4                 0::1      _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_host_ipv6_addr                 VxlanL3VniParams  HostIpv6Address                      ANY                                                4                 4001::2   _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ipv6_addr_incr_per_port        VxlanL3VniParams  Ipv6AddressIncrementPerPort          ANY                                                4                 0::0      _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ipv6_addr_step                 VxlanL3VniParams  Ipv6AddressStep                      ANY                                                4                 0::1      _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ipv6_addr_step_per_segment     VxlanL3VniParams  Ipv6AddressStepPerSegment            ANY                                                4                 0::1:0    _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_ipv6_prefix                    VxlanL3VniParams  Ipv6Prefix                           ANY                                                4                   64      _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vni_params                     VxlanL3VniParams  L3Vni                                ANY                                                4                  2000      _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vni_step_params                VxlanL3VniParams  L3VniStep                            ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_segments_per_block             VxlanL3VniParams  SegmentsPerBlock                     ANY                                                4                   1       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        {l3_vxlan_ip_type                  VxlanL3VniParams  VxlanIpType                 {CHOICES ipv4 ipv4andipv6 ipv6 mac}                         4                ipv4       _none_          true        _none_                  false       _none_                                              {create VxlanL3VniParams}                     _none_}
        
    }
    
}
