
traffic_profile = {}
traffic_profile['multi_f1_profile'] = {
           "total_flows" : "flow1 flow2 flow3 flow4 flow5",
           "total_duration" : "160",
           "netesto_controller" : "mpoc-server01",
           "flow1" : {
               "test" : "TCP_RR",
               "clients" : "mpoc-server30,mpoc-server34",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "30",
               "delay"    : "0",
               "instances" : "1",
               "rr_size"   : "1M,1",
           },
           "flow2" : {
               "test" : "TCP_RR",
               "clients" : "mpoc-server30,mpoc-server34,mpoc-server45,mpoc-server47",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "30",
               "delay"    : "35",
               "instances" : "1",
               "rr_size"   : "1M,1",
           },
           "flow3" : {
               "test" : "TCP_RR",
               "clients" : "mpoc-server45",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "30",
               "delay"    : "65",
               "instances" : "1",
               "rr_size"   : "1M,1",
           },
          "flow4" : {
               "test" : "TCP_RR",
               "clients" : "mpoc-server30,mpoc-server34,mpoc-server45,mpoc-server47,mpoc-server40",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "30",
               "delay"    : "95",
               "instances" : "1",
               "rr_size"   : "1M,1",
           },
           "flow5" : {
               "test" : "TCP_RR",
               "clients" : "mpoc-server45,mpoc-server47",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "30",
               "delay"    : "125",
               "instances" : "1",
               "rr_size"   : "1M,1",
           }

        }
traffic_profile['workload_mix'] = {
           "total_flows" : "flow1 flow2 flow3",
           "total_duration" : "150",
           "netesto_controller" : "mpoc-server01",
           "flow1" : {
               "comment" : "Run 2 instances each stream at 5 Gbps. Total 10 Gbps",
               "test" : "TCP_STREAM",
               "clients" : "mpoc-server30",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "120",
               "delay"    : "0",
               "instances" : "2",
            },
           "flow2" : {
               "comment" : "Run 4 RR instances bursting at line rate for 2 seconds, periodicity 15 sec, inter-stream 1 sec",
               "test" : "TCP_RR",
               "clients" : "mpoc-server30",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "2",
               "delay"    : "5",
               "instances" : "4",
               "rr_size"   : "1M,1",
               "delay_between_instances" : "1",
               "repeat_flow" : "15",
               "repeat_max" : "4",
           },
           "flow3" : {
               "comment" : "Run 2 instances, each bursting at line rate, each running for 1 sec, periodicity 30 sec",
               "test" : "TCP_RR",
               "clients" : "mpoc-server30",
               "servers" : "mpoc-server44",
               "servers_t" : "mpoc-server44t",
               "duration" : "1",
               "delay"    : "45",
               "instances" : "2",
               "rr_size"   : "800B,1",
               "repeat_flow": "30",
               "repeat_max": "2",
           }
        }