# coding: utf-8

"""
    Fungible Storage Controller Intent API

    REST API for interfacing between the management/orchestration system and Fungible Storage Controller `(FSC)` `INTERNAL`: The API is for internal controller use only `DEBUG`: The API will not be available in production use   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: storage@fungible.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Request(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'method': 'str',
        'url': 'str',
        'params': 'dict(str, object)',
        'reqid': 'int'
    }

    attribute_map = {
        'method': 'method',
        'url': 'url',
        'params': 'params',
        'reqid': 'reqid'
    }

    def __init__(self, method=None, url=None, params=None, reqid=None):  # noqa: E501
        """Request - a model defined in Swagger"""  # noqa: E501

        self._method = None
        self._url = None
        self._params = None
        self._reqid = None
        self.discriminator = None

        if method is not None:
            self.method = method
        if url is not None:
            self.url = url
        if params is not None:
            self.params = params
        if reqid is not None:
            self.reqid = reqid

    @property
    def method(self):
        """Gets the method of this Request.  # noqa: E501


        :return: The method of this Request.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this Request.


        :param method: The method of this Request.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def url(self):
        """Gets the url of this Request.  # noqa: E501


        :return: The url of this Request.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Request.


        :param url: The url of this Request.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def params(self):
        """Gets the params of this Request.  # noqa: E501


        :return: The params of this Request.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this Request.


        :param params: The params of this Request.  # noqa: E501
        :type: dict(str, object)
        """

        self._params = params

    @property
    def reqid(self):
        """Gets the reqid of this Request.  # noqa: E501


        :return: The reqid of this Request.  # noqa: E501
        :rtype: int
        """
        return self._reqid

    @reqid.setter
    def reqid(self, reqid):
        """Sets the reqid of this Request.


        :param reqid: The reqid of this Request.  # noqa: E501
        :type: int
        """

        self._reqid = reqid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Request, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Request):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
