# coding: utf-8

"""
    Fungible Storage Controller Intent API

    REST API for interfacing between the management/orchestration system and Fungible Storage Controller `(FSC)` `INTERNAL`: The API is for internal controller use only `DEBUG`: The API will not be available in production use   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: storage@fungible.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VolumeStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'physical_usage': 'int',
        'physical_writes': 'int'
    }

    attribute_map = {
        'physical_usage': 'physical_usage',
        'physical_writes': 'physical_writes'
    }

    def __init__(self, physical_usage=None, physical_writes=None):  # noqa: E501
        """VolumeStats - a model defined in Swagger"""  # noqa: E501

        self._physical_usage = None
        self._physical_writes = None
        self.discriminator = None

        if physical_usage is not None:
            self.physical_usage = physical_usage
        if physical_writes is not None:
            self.physical_writes = physical_writes

    @property
    def physical_usage(self):
        """Gets the physical_usage of this VolumeStats.  # noqa: E501


        :return: The physical_usage of this VolumeStats.  # noqa: E501
        :rtype: int
        """
        return self._physical_usage

    @physical_usage.setter
    def physical_usage(self, physical_usage):
        """Sets the physical_usage of this VolumeStats.


        :param physical_usage: The physical_usage of this VolumeStats.  # noqa: E501
        :type: int
        """

        self._physical_usage = physical_usage

    @property
    def physical_writes(self):
        """Gets the physical_writes of this VolumeStats.  # noqa: E501


        :return: The physical_writes of this VolumeStats.  # noqa: E501
        :rtype: int
        """
        return self._physical_writes

    @physical_writes.setter
    def physical_writes(self, physical_writes):
        """Sets the physical_writes of this VolumeStats.


        :param physical_writes: The physical_writes of this VolumeStats.  # noqa: E501
        :type: int
        """

        self._physical_writes = physical_writes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
