"""
Scheduler states
"""


class SchedulerStates:
    SCHEDULER_STATE_UNKNOWN = "SCHEDULER_STATE_UNKNOWN"
    SCHEDULER_STATE_STARTING = "SCHEDULER_STATE_STARTING"
    SCHEDULER_STATE_RUNNING = "SCHEDULER_STATE_RUNNING"
    SCHEDULER_STATE_RESTART_REQUESTED = "SCHEDULER_STATE_RESTART_REQUESTED"
    SCHEDULER_STATE_RESTARTING = "SCHEDULER_STATET_RESTARTING"
    SCHEDULER_STATE_STOPPED = "SCHEDULER_STATE_STOPPED"
